### ISSUE TITLE
Image path preference for FBrowser

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#100]
It would be more convenient if `FBrowser` plugin can read in user preference on what root path to display, instead of starting out at `HOME` every time; Something like `imdir` in IRAF's `login.cl`.

**Comment by ejeschke** [comment]
@pllim, could you try out commit 8a524549eafabe5872175913ce8a2f59813dcbbf?

Before using, please examine the possible settings preferences in the file `examples/configs/plugin_FBrowser.cfg`.

**Comment by pllim** [comment]
I changed the config to point to my desired working directory, but `FBrowser` did not pick it up. It is not clear to me why it is not working by looking at your diff.

**Comment by ejeschke** [comment]
Did you copy the file to your $HOME/.ginga ?

**Comment by pllim** [comment]
Ah, okay. It turns out I need to do
```
home_path = '/my/local/path'
```
and not
```
home_path = /my/local/path
```
Okay. This works fine now. Thanks!
