### ISSUE TITLE
Rename ORIGIN branch name

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#1011]
Following the lead of many other projects, change the name of "master" branch to "main".

**Comment by ejeschke** [comment]
@pllim, you are more in touch with the CI integration than I am. I will need your help on this. Shall we take a stab at this for release 4.0 or wait for 4.1?

**Comment by pllim** [comment]
Should not be hard to do for v4.0. Two main things:

1. `grep` for mentions of `master` in this repo and change to `main`.
2. If you mention `master` in your `github.io` stuff, you need to change that too.
3. Go into RTD admin and change the default branch from `master` to `main` but only do this after GitHub change has happened.
