### ISSUE TITLE
RTD failed with 2 warnings

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#1020]
Example log: https://readthedocs.org/projects/ginga/builds/17910838/

```
WARNING: duplicated ToC entry found: api/ginga.util.wcs.ra_deg_to_str.xhtml
WARNING: duplicated ToC entry found: api/ginga.util.wcs.dec_deg_to_str.xhtml
```

**Comment by ejeschke** [comment]
Hmm.. I get a successful build when I do it manually with "make html".

**Comment by pllim** [comment]
The "xhtml" is weird. I wonder if it is from your other formats...

https://github.com/ejeschke/ginga/blob/fa9d412778d4c627a8d911cb9da86634bfa4ee47/.readthedocs.yml#L27-L30

**Comment by ejeschke** [comment]
Does the RTD build always start with a completely clean checkout?

**Comment by pllim** [comment]
Good question. Let me wipe and rebuild.

**Comment by pllim** [comment]
Actually, I cannot find the "wipe" button anymore. They might have moved their backend into the "cloud" so theoretically each build would be clean.

**Comment by ejeschke** [comment]
Do you get the error building manually?

**Comment by pllim** [comment]
I am about to log off but can check next week if time allows.

By the way, this is not an outright error. It would be a warning in your logs and you would still get a build. Only in RTD, we turn warnings into failures. So, if you pipe your local doc build into a log file, chances are you will see these warnings (e.g., using grep).

**Comment by ejeschke** [comment]
Ah, ok.  Because it looks from the terminal output like a fully successful build and reports no errors or warnings.  I'll dig around in the log files to see it I can find a message like that.

**Comment by ejeschke** [comment]
No message "duplicated ToC entry found" anywhere in the `doc` directory or any subdirectory.  I don't think I'm getting that error anywhere.

**Comment by pllim** [comment]
@ejeschke , from #1021 , looks like it is either the LaTeX or epub build... Do we really need those? I really don't wanna debug either of those.

**Comment by ejeschke** [comment]
> Do we really need those? I really don't wanna debug either of those.

I think we could take them out for now.  The LaTeX build would be nice to keep if it is not the source of the problem.
