### ISSUE TITLE
Window not redrawn correctly initially or on a resize

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#1027]
There is a bug in the StandardPipelineRenderer (the default one for the Ginga viewer), where the window may not be drawn correctly initially or on a window resize unless a pan or zoom operation has been performed.

This is reproducible in the Reference Viewer by turning off autozoom and autocenter on a channel, setting the pan position in the corner of an image so that some background is visible and then saving settings (under Preferences for that channel).  Then start up the viewer and drag that image to the channel.

**Comment by ejeschke** [comment]
This bug has been fixed in working dev branch, targeted for 4.0.

**Comment by ejeschke** [comment]
I have also made a backport of the fix for 3.4.0 (to become 3.4.1).  I'm also backporting one other fix for the Preferences plugin that has been made since then.

@pllim, is there anything else you want to backport to 3.4.1?

**Comment by pllim** [comment]
Re: backport -- How are you doing it? I don't see any 3.4.x branch here.

> is there anything else

No, I don't think so. Thanks for asking!

**Comment by ejeschke** [comment]
> How are you doing it? I don't see any 3.4.x branch here.

That's a question I was going to ask you! Actually, what I did was to checkout "v3.4.0", made a branch and applied the fixes.
I was planning to just tag the branch, push it here and make a release from it.  Is there some preferred method beside that?

**Comment by pllim** [comment]
Well... if you plan to do further 3.4.x series (e.g., v3.4.2 or more), maybe you can push that branch back out here and name it v3.4.x ? Then you can backport to that branch as needed and tag a new 3.4.x release from that branch as needed. That is what astropy does... YMMV

**Comment by ejeschke** [comment]
That sounds good. I'm not planning to make more releases from that, but you never know.

**Comment by ejeschke** [comment]
v3.4.1 released, fixing this issue. Also, fix is in dev branch.  Closing this issue as fixed.
