### ISSUE TITLE
TST: conda_linux_tests failed

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#1048]
Example log: https://github.com/ejeschke/ginga/actions/runs/4848985893/jobs/8640572843

It appears to be using astropy 5.1. Hopefully just bumping versions on that job would fix things up but I don't have time to investigate right away.

**Comment by ejeschke** [comment]
@pllim, I saw the same error. It appears something has changed in astropy 5.1 (possibly something that has been deprecated is no longer generating a DeprecationWarning, although I think that we should have seen that earlier).

**Comment by pllim** [comment]
astropy 5.1 was out a while ago, so I am guessing it is incompatible with some newer stuff that the conda job picked up but I haven't had the chance to compare logs. If you get to it first, find the last successful log and compare the version numbers. 🤞
