### ISSUE TITLE
Pillow v10.0 has deprecated many text size methods, including ImageDraw.textsize

### ISSUE THREAD

**Issue by StuartLittlefair** [ejeschke/ginga#1057]
See https://pillow.readthedocs.io/en/stable/deprecations.html#font-size-and-offset-methods

This means that  the following lines need changing to use an alternative method

https://github.com/ejeschke/ginga/blob/804ca99f8bde9f3bc75220b26b3020e9367bc5f9/ginga/pilw/PilHelp.py#L39

https://github.com/ejeschke/ginga/blob/804ca99f8bde9f3bc75220b26b3020e9367bc5f9/ginga/pilw/PilHelp.py#L134

**Comment by ejeschke** [comment]
@StuartLittlefair , thanks for the heads up. Did you see any clear workaround for the change? PR welcome!

**Comment by ejeschke** [comment]
Thanks for the pointers, @StuartLittlefair. First stab at fix in #1058

**Comment by ejeschke** [comment]
@StuartLittlefair, merged fix.  Please reopen if you find a problem with it.  Worked well with the versions of PIL I tried, including 10.0

**Comment by StuartLittlefair** [comment]
Thanks @ejeschke !
