### ISSUE TITLE
canvas/types/astro.py - bug in calculation of dec axis grid values?

### ISSUE THREAD

**Issue by pmaxted** [ejeschke/ginga#1087]
On line 1134, should 
```        dec_arr = np.arange(dec_min + d_dec, dec_max - d_ra * 0.5, d_dec)```

be replaced with
```        dec_arr = np.arange(dec_min + d_dec, dec_max - d_dec * 0.5, d_dec)```
?

**Comment by ejeschke** [comment]
@pmaxted , that sure looks like like a bug.  @pllim, I believe this is your code. Are you ok if I fix this as suggested?

**Comment by pllim** [comment]
Ooops, does look like a copy paste error. My bad! Yes, please fix. Thanks!

https://github.com/ejeschke/ginga/blob/bc2606d702bf55e8c3e8a1af3edfca14430642e0/ginga/canvas/types/astro.py#L1134

**Comment by ejeschke** [comment]
@pmaxted, this is fixed in the dev branch. Release v5.0 will contain this fix (Feb time frame)

**Comment by pllim** [comment]
Thanks!
