### ISSUE TITLE
TST: devdeps "unable to copy" error caused by numpy and astropy 

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#1093]
https://github.com/ejeschke/ginga/actions/runs/8149052451/job/22273047631

astropy is trying to patch it. You just have to wait it out. If you don't want devdeps to block other jobs, either move it to its own job or set fast-fail to false.

Thanks for your patience!

**Comment by ejeschke** [comment]
Ok, thanks. Not so urgent if I know someone is working on it.

**Comment by pllim** [comment]
I restarted your failed test and it is green now.

**Comment by ejeschke** [comment]
TY, @pllim!
