### ISSUE TITLE
distutils is completely deprecated in python 3.12

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#1095]
The `distutils` module is [to be removed in python 3.12](https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated). 

Ginga currently imports the module in:
- `ginga.rv.plugins.MultiDim` (using `spawn()`)
- `ginga.opengl.CanvasRenderGL` (using `LooseVersion`)

**Comment by pllim** [comment]
You can import it, but you might have seen a deprecation warning?
