### ISSUE TITLE
Drag and Drop onto viewer doesn't work under Windows.

### ISSUE THREAD

**Issue by Cadair** [ejeschke/ginga#110]
It appears to be pre-prending a `/` infront of the path.

ping @alex-ian-hamilton

**Comment by Alex-Ian-Hamilton** [comment]
Error code:
```
Failed to load file '/C:/Users/Alex/Dropbox/Alex and Stuart/HMI_ME_Data/hmi.ME_720s_fd10.20150531_224800_TAI.conv_flag.fits': [Errno 22] invalid mode ('rb') or filename: '/C:/Users/Alex/Dropbox/Alex and Stuart/HMI_ME_Data/hmi.ME_720s_fd10.20150531_224800_TAI.conv_flag.fits'
  File "C:\Users\Alex\Anaconda\lib\site-packages\ginga\Control.py", line 515, in load_image
    image.load_file(filepath, **kwdargs)

  File "C:\Users\Alex\Anaconda\lib\site-packages\ginga\AstroImage.py", line 118, in load_file
    phdr=self._primary_hdr)

  File "C:\Users\Alex\Anaconda\lib\site-packages\ginga\util\io_fits.py", line 131, in load_file
    fits_f = pyfits.open(filepath, 'readonly')

  File "C:\Users\Alex\Anaconda\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 129, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache, **kwargs)

  File "C:\Users\Alex\Anaconda\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 271, in fromfile
    save_backup=save_backup, cache=cache, **kwargs)

  File "C:\Users\Alex\Anaconda\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 792, in _readfrom
    ffo = _File(fileobj, mode=mode, memmap=memmap, cache=cache)

  File "C:\Users\Alex\Anaconda\lib\site-packages\astropy\io\fits\file.py", line 137, in __init__
    self._open_filename(fileobj, mode, clobber)

  File "C:\Users\Alex\Anaconda\lib\site-packages\astropy\io\fits\file.py", line 440, in _open_filename
    self._file = fileobj_open(self.name, PYFITS_MODES[mode])

  File "C:\Users\Alex\Anaconda\lib\site-packages\astropy\io\fits\util.py", line 419, in fileobj_open
    return open(filename, mode)
```

**Comment by ejeschke** [comment]
@Cadair, I might need some help with this one.  I don't have access to any Windows machines and the only people who have them here are the office staff, who don't have anaconda installed and probably would not appreciate me asking them to install stuff.

This would be easiest to debug with one of the example programs, such as [example2_qt.py](https://github.com/ejeschke/ginga/blob/master/examples/qt/example2_qt.py).  What we want to do is check the value of the path in the `drop_file()` method, and work backward from there into the widget's drag drop support.  If that example works fine, then it is a problem in the reference viewer--probably in `Control.py` having to do with parsing the drop string.

**Comment by Alex-Ian-Hamilton** [comment]
@ejeschke, if you tell me what to do I can send you back the results, just I'm a bit new when it comes to Python/GIT.
I ran that script, the viewer loaded and I could manually open files, but I couldn't use drag-and-drop, it just does nothing and doesn't show an error in the console. Is there any way I can get more info for you?

FYI I'm running Windows 10, but I doubt that's the issue, I could always fire up a Windows 7 VM if you want me to test on that.

**Comment by ejeschke** [comment]
Hi Alex, does drag and drop work if you run the sample program in .../examples/qt/example2_qt.py ?

**Comment by Alex-Ian-Hamilton** [comment]
Sorry, I wasn't clear, example2_qt.py is the script I ran and no it didn't work.
I could manually open files, but I couldn't use drag-and-drop, it just does nothing and doesn't show an error in the console. Is there any way I can get more info for you?

**Comment by ejeschke** [comment]
Ah, ok, good this is what we want to use to track this down, it will be a lot easier than debugging from the reference viewer, which generates a lot more log noise.  Could you run the program again, this time adding the following parameters:

```python
python examples/qt/example2_qt.py --loglevel=10 --log=ginga.log
```
Then drag your file into the window.  Afterward, search `ginga.log` for the string "dropped filename(s)".  Please post those lines here. Tnx.

**Comment by Alex-Ian-Hamilton** [comment]
Here's what I got:
```
2015-06-09 13:10:20,688 | D | ImageViewQt.py:771 (drop_event) | dropped filename(s): ['file:///C:/Users/Alex/Dropbox/Study/2014-2015/SoCiS/Coding/Python/Random/data/hmi.m_720s.2015.05.01_00-12-00_TAI.magnetogram.fits']
```
I can say that from C:/* the file address appears correct (it works in Windows Explorer), so I assume Stuart is right that it's adding an additional '/' in front?

**Comment by pllim** [comment]
If the extra separator is the issue, maybe this will fix it?
```
fileName = os.path.abspath(paths[0])
```

**Comment by ejeschke** [comment]
@Alex-Ian-Hamilton, can you test commit 01e97ad6943bd6d1e5531bddfc36e46fcaeeb3ec (just committed to master).  Does this fix the issue?

**Comment by Alex-Ian-Hamilton** [comment]
Yup... That does it, drag and drop works. :)
