### ISSUE TITLE
How to auto start local plugin?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#115]
Is there something I can add to the `Bunch` definition when I define a local plugin to command Ginga to automatically open it under `Dialogs` on start-up? There is no `start=True` option like with a global plugin.

```python
Bunch(module='MosaicAuto', tab='MosaicAuto', ws='dialogs')
```

**Comment by ejeschke** [comment]
@pllim, you can use the feature of `ginga_config.py` to achieve this.  It's slightly hacky, but basically, create a file called `ginga_config.py` in your $HOME/.ginga folder.  In this file, put the following functions:
```python
def pre_gui_config(ginga):
    pass

def post_gui_config(ginga):
    ginga.add_channel('Image')
    ginga.start_local_plugin('Image', 'Ruler', None)
```

Replace 'Ruler' with 'MosaicAuto' if this is the name of the desired local plugin. Let me know how this works for you.

**Comment by pllim** [comment]
This works. Thanks!
