### ISSUE TITLE
"Go to next image in channel" does not follow alphabetical order

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#119]
I have a bunch of images displayed. They are in alphabetical order in `Thumbs` and `Contents`. When I click the right arrow to go to the next image, it jumps from "image1.fits" to "image4.fits", not "image2.fits" as expected. I understand that Ginga uses many threads to open images and the internal list might not be ordered, but is there no way to have left/right arrows follow alphabetical order?

**Comment by ejeschke** [comment]
@pllim, the images in a channels `Datasrc` are not ordered alphabetically by default, but by time of last access.  The idea behind the buttons is that they are a bit like the back/forward buttons on a web browser: they follow your temporal visitations to the files.

So, this is a feature and not a bug, according to the original design.  If it is desirable to have the buttons work as you describe, it probably would not be too difficult to read a preference to make it follow this behavior.

**Comment by pllim** [comment]
@ejeschke , I see. That behavior makes sense if you open the image one by one. But I open up all of them at once using `ginga *.fits`, so "time of last access" does not apply in my case. A user preference for alphabetical ordering like you have with `Thumbs` will be desirable. Thanks!

**Comment by pllim** [comment]
Also related, I notice that back/forward has no "loop back to beginning" feature. That is, if I am on the last frame, and I press "right arrow" again, I will go back to the first frame. Currently, it just says, "No next image!"

**Comment by ejeschke** [comment]
@pllim, addressing the looping only at the moment, please try commit 97ff2c75ce171313932115a2f6b12e3ad98350eb, which gives this capability.

**Comment by pllim** [comment]
@ejeschke , it works *but* it only cycles through the images already in memory. For example, I have 6 images listed under `Contents` and `Thumbs`, and it has `numImages=4`. When I repeatedly click on the right arrow, it only cycles through images 1, 5, 3, 4, 1, 5, 3, 4, ... (i.e., It ignores two of the six images.)

**Comment by pllim** [comment]
This is resolved by #226.
