### ISSUE TITLE
Ginga and sphere

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#127]
As discussed in #89 . `sphere` is at https://github.com/spacetelescope/sphere . c/c: @mdboom , @bernie-simon

**Comment by ejeschke** [comment]
As @mdboom suggested in #89, I think we just need to define a reasonable projection to map a sphere to 2D.  @mdboom, do you have any suggestions on this?

What I am thinking is that it would be straightforward to define a `SpherePolygon` (perhaps a subclass of the ginga `Polygon` canvas object) in which the vertexes are specified in sphere-compatible coordinates.  There is a coordinate mapper inside every canvas object, we would just need to define one that maps the sphere coordinates to 2D data coordinates (and back, ideally).

@pllim, how are you envisioning this being used in the viewer?  To extract the data with non-containing pixels masked?

**Comment by pllim** [comment]
> how are you envisioning this being used in the viewer? To extract the data with non-containing pixels masked?

Pretty much, yes. But now that you have your own method to do this, I guess using `sphere` is optional?

Another thing that you might or might not find useful in `sphere` is that it has functions to compute intersections. Could be useful for `Mosaic`?

**Comment by ejeschke** [comment]
Closing for now.  If we find some interesting application, @pllim, we can reopen.

**Comment by pllim** [comment]
Okay, thanks, @ejeschke !
