### ISSUE TITLE
Feature Request: Annulus shape

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#128]
As discussed in #89 , I am trying to use `arr_masked = image.cutout_shape(shape_obj)` but to extract a region defined by an annulus. Since there is no direct support for this shape, I use two circles:
```python
icirc_masked = image.cutout_shape(obj.objects[0])  # inner circle
ocirc_masked = image.cutout_shape(obj.objects[1])  # outer circle
data = icirc_masked[~icirc_masked.mask & ~ocirc_masked.mask].data
```
But this doesn't work because they have bounding boxes with different shapes:
```
2015-06-25 11:51:56,856 | E | Callback.py:88 (make_callback) | Error making callback 'draw-event': operands could not be broadcast together with shapes (200,199) (220,219) 
```
I thought maybe I could write my own shape, but looking at `DrawingMixin.py` and `CanvasObject.py`, adding a new shape does not seem trivial.

**Comment by pllim** [comment]
Alternately, instead of a new shape object, if there is a way to just return the full-size mask for each of the circle, I can build the annulus mask myself.

**Comment by pllim** [comment]
Just so you know, I already have my own functions to extract annulus using your circle objects. So if you don't think such a support would benefit Ginga in general, feel free to close this issue.

**Comment by ejeschke** [comment]
@pllim, I think there is support for this via the `CompoundObject` canvas object.  You just need to define an annulus shape by combining the two circles:
```python
CompoundObject = viewer.getDrawClass('compoundobject')
annulus = CompoundObject([circ1, circ2])
# hack to change the default interpretation of containment from OR to AND
annulus._contains_reduce = numpy.logical_and
```
(you can also just import CompoundObject from `ginga.canvas.CanvasObject`).
```

This is largely uncharted waters.  Let me know how it goes!

**Comment by ejeschke** [comment]
Sorry, this won't work  because the AND containment test is not right.  So we have to write a custom containment test.  I'll work up an example.

**Comment by ejeschke** [comment]
Tested this a little bit, and I think it should work:
```python
import numpy
from ginga.canvas.CanvasObject import CompoundObject

class Annulus(CompoundObject):

    def contains(self, x, y):
        circ1, circ2 = self.objects
        return circ1.contains(x, y) and numpy.logical_not(circ2.contains(x, y))
```
You need to place the object on the canvas (using ``add()``) before the `contains()` method will work (because it will get initialized with a coordinate mapper).

**Comment by ejeschke** [comment]
BTW, this issue helped me uncover a bug in the containment method for circles (I found out it worked for coords in floating point (the usual case), but not for integers.  This is fixed in commit 97b34118ef2c8c82f8dd5dcc264ade6d992334f0.  You might want to merge that before proceeding with this.

**Comment by pllim** [comment]
@ejeschke , will this work if my canvas is done this way?
```python
obj1 = Rectangle(...)
obj2 = Annulus(Circle(...), Circle(...))
canvas.add(CompoundObject(obj1, obj2))
```
That is, the annulus itself is part of another `CompoundObject`.

**Comment by pllim** [comment]
I think I answered my own question. The answer is no. In the traceback below, `bg_obj` is the `Annulus` that is in `obj.objects[1]` as I illustrated above.
```
  File "~/.ginga/plugins/SurfBgRatio.py", line 351, in redo
    bg_masked = image.cutout_shape(bg_obj)

  File ".../ginga-2.4.20150626080455-py2.7.egg/ginga/BaseImage.py", line 324, in cutout_shape
    view, mask = self.get_shape_view(shape_obj)

  File ".../ginga-2.4.20150626080455-py2.7.egg/ginga/BaseImage.py", line 312, in get_shape_view
    contains = shape_obj.contains_arr(xi, yi)

  File ".../ginga-2.4.20150626080455-py2.7.egg/ginga/canvas/CompoundMixin.py", line 43, in contains_arr
    map(lambda obj: obj.contains_arr(x_arr, y_arr)))
```
Is there a solution for this? Thanks!

**Comment by ejeschke** [comment]
I think that *should* work.  I see a traceback here, but not the top error message on the stack.  Is there one?

**Comment by pllim** [comment]
The top error message just tells me which method in my plugin that `cutout_shape()` was called from, I didn't think it would be useful information here. I am trying to implement my own `contains_arr()` method in `Annulus` but can't get it to work properly yet.

**Comment by pllim** [comment]
@ejeschke , I see what you mean by the "top error message" now. I updated my traceback above. Please let me know if you know of a fix. Thanks!

**Comment by pllim** [comment]
Below is the accompanying screen output to go with the traceback above:
```
.../numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
.../numpy/core/_methods.py:71: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
.../numpy/core/_methods.py:83: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
.../numpy/core/_methods.py:95: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
.../numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
```

**Comment by pllim** [comment]
Okay, I think I solved it. I had to add two more methods:
```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

# THIRD-PARTY
import numpy as np

# GINGA
from ginga.canvas.CanvasObject import CompoundObject, Circle


class Annulus(CompoundObject):
    """Class to handle annulus shape in Ginga.

    See https://github.com/ejeschke/ginga/issues/128 for more details.

    Examples
    --------
    >>> tag = canvas.add(Annulus(Circle(100, 200, 10), Circle(100, 200, 15)))
    >>> obj = canvas.getObjectByTag(tag)
    >>> arr_masked = image.cutout_shape(obj)

    """
    def __init__(self, *args, **kwargs):
        super(Annulus, self).__init__(*args, **kwargs)

        if len(self.objects) != 2:
            raise ValueError('Annulus can only have 2 objects')

        circ1, circ2 = self.objects

        if (not isinstance(circ1, Circle) or not isinstance(circ2, Circle)):
            raise ValueError('Annulus can only contain circles')

        if not np.allclose([circ1.x, circ1.y], [circ2.x, circ2.y]):
            raise ValueError(
                'Inner and outer circles must have the same centroid')

        if circ2.radius < circ1.radius:
            raise ValueError('Outer circle is smaller than the inner circle')

    def contains(self, x, y):
        """Containment test."""
        circ1, circ2 = self.objects
        return circ2.contains(x, y) and np.logical_not(circ1.contains(x, y))

    def contains_arr(self, x_arr, y_arr):
        circ1, circ2 = self.objects
        arg1 = circ2.contains_arr(x_arr, y_arr)
        arg2 = np.logical_not(circ1.contains_arr(x_arr, y_arr))
        return np.logical_and(arg1, arg2)

    def get_llur(self):
        """Bounded by outer circle."""
        circ2 = self.objects[1]
        return circ2.get_llur()
```

**Comment by pllim** [comment]
If you don't want this in the Ginga distribution, feel free to close this issue. If you want it, I can submit a PR by putting this under `canvas/CanvasObject.py`.

**Comment by ejeschke** [comment]
@pllim, this looks useful.  I'm thinking that `CanvasObject` should probably only contain a few primary shapes, however.  I'm wondering if we should create a new module that includes "derived" shapes such as annulus, compass, ruler, etc.  Thinking about this.  If you have any comments, let me know.

**Comment by pllim** [comment]
No problem. Once you decide on a place to put this, let me know.

**Comment by ejeschke** [comment]
@pllim, now that `Annulus` is added as an official canvas type, should we close this issue?

**Comment by pllim** [comment]
Sure. Thanks!
