### ISSUE TITLE
Update plugin_Contents.cfg example

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#130]
Update `plugin_Contents.cfg` to reflect new addition in 1ca03e8de0b0a1bdd582e54944359cbf98601c59

**Comment by ejeschke** [comment]
@pllim, this is addressed in commit cbcd6b88f58a8327d8dfb3cde4a50df68b184974.

**Comment by ejeschke** [comment]
@pllim, can we close this issue?

**Comment by pllim** [comment]
Sure. Thanks :)
