### ISSUE TITLE
MultiDim fails on reloading

### ISSUE THREAD

**Issue by rupak0577** [ejeschke/ginga#132]
The plugin fails to recreate the HDU list on reload. This is probably due to redo() returning True if the image is the [same](https://github.com/ejeschke/ginga/blob/master/ginga/misc/plugins/MultiDim.py#L420).

**Comment by rupak0577** [comment]
@ejeschke Any comment?

**Comment by ejeschke** [comment]
How was the image reloaded--by dragging a new image on to the window?  If so the image (as tested by the line you highlighted) should be different.  I need to know how to reload the image to reproduce this error.

**Comment by rupak0577** [comment]
@ejeschke The image was loaded using the File menu. You also need to select an HDU before closing the plugin, otherwise the error cannot be reproduced(I fixed this selection problem in #123). Then, after simply closing and reloading the plugin, it fails to create the list.

**Comment by ejeschke** [comment]
Could you try commit 325c642c90f32115551c170349fbc360ccf16a76?  I believe this should fix the issue.

**Comment by rupak0577** [comment]
That works, thanks!
