### ISSUE TITLE
How to create a False colour Image ?

### ISSUE THREAD

**Issue by sclooney94** [ejeschke/ginga#135]
I'm trying to convert from ds9 to ginga and I'm trying to produce a false colour image. In ds9 there is the new RGB tab to do this and I'm wondering is there any equivalent in ginga or is there another way to do it ?

**Comment by ejeschke** [comment]
@sclooney94, although the viewer supports RGB images there is no released plugin that does this.

However, I have an experimental (very rough) plugin that does something like this using the `LayerImage` mixin.  It lets you select different images and composite them as an RGB image.  You can adjust the mix to control how much R/G/B is added from each of the constituent images.

Would you be interested in testing it and help develop (at least with feedback) a more refined plugin?

**Comment by sclooney94** [comment]
Yes that would be perfect I'll test it and help out with feedback as best I can. How do I start ?

**Comment by sclooney94** [comment]
@ejeschke, that sounds exactly like what I'm looking for. I would be happy to test it and help out as much as I can with feedback. How do I start ?

**Comment by ejeschke** [comment]
@sclooney94, can you contact me via email (addr is in ginga code)?  I'll send you the plugin with instructions.

**Comment by sclooney94** [comment]
@ejeschke <https://github.com/ejeschke>, this is my email address, I will
get to work with the plugin as soon as you send it to me thank you.

**Comment by ejeschke** [comment]
I've now overhauled up the plugin quite a bit and included it in commit f520d6d4744e348495643f5b10681f847d62744f.

@sclooney94, you might want to update your ginga repo and give the new version a try (look for "Compose" in the Operation menu).

In the new version, you simply start the plugin, drag your constituent files to the large (main) window (drag them in this order: R, G then B).  Then simply adjust cut levels and contrast as desired and adjust your mix of R, G and B in the plugin.  When you have something you like, enter a file path (ending in .tif, .jpg, .png, etc) in the path box and click "Save Image As".  *Voila!*

**Comment by ejeschke** [comment]
I forgot to mention that you will need to have the Python Imaging Library (PIL or Pillow) installed to save images.

**Comment by sclooney94** [comment]
I updated ginga but I can't see "Compose" in the operations menu. Do you
have any idea what may be the problem ?

**Comment by ejeschke** [comment]
@sclooney94, did you update from the github repo?  I just tested by checking out on a new laptop and the plugin is there.  "Compose" is at the very bottom of the operation menu.

**Comment by sclooney94** [comment]
@ejeschke, I have it working now and it works perfectly. Thank you very much.

**Comment by ejeschke** [comment]
Excellent.  You are welcome!
