### ISSUE TITLE
Reference Viewer, Cuts plugin: add Bezier cut

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#136]
This is carried over from PR #124 to keep that issue contained to everything but Bezier cuts improvements.

Original question by @rupak0577 : "There has been a discussion about adding a Bezier cut but I am not sure how to go about it. Could you give me a few pointers?

**Comment by ejeschke** [comment]
@rupak0577, the `contains_arr(x_arr, y_arr)` method for a shape is a vector test for data coordinate inclusion in the shape.  It returns an array of booleans, where the corresponding element is `True` if that x, y coordinate is in the shape and `False` if not.  This test is required to implement the full functionality of a shape, and will be needed to get the points along the shape to plot the cut.

The link that I posted in PR #124 basically describes an algorithm that can be used to determine whether a point is on a Bezier curve.  Since the `BezierCurve` is subclassed from the polygon stuff, I believe the bounding box provided by `get_llur()` will be sufficient to find the set of points that *could* be on the curve, but we need to implement the vectorized contains test to fully integrate it as a cuts type.

**Comment by ejeschke** [comment]
@rupak0577, @Cadair, @nabobalis
I've updated the Cuts plugin to support cubic Bezier curves.  Its in commit 4c98055f1131affe9ae39f56889a7bbdb40380ec if you want to give it a try.  It will be a little more useful once we merge in a checkbox to put the canvas in edit mode, as described in Issue #137, because then you can edit the control points easily.

**Comment by nabobalis** [comment]
From what I've played with, the cut types work but it seems that for the Bezier curve, it does not draw the actual curve, just the straight lines.

**Comment by rupak0577** [comment]
@nabobalis You need to press 'v' to add the vertices(currently supports only two).

**Comment by nabobalis** [comment]
I have done that, it doesn't actually draw a curve, just the straight lines.

**Comment by ejeschke** [comment]
@nabobalis, does it work when you draw it in the Drawing plugin?  You have to click&drag.  *While dragging* you press 'v' twice.  After the second 'v' it should become a curve (you are still holding down the mouse or trackpad button) at this point keep dragging and release to set the very endpoint of the curve.

If this doesn't work we should confirm which version (qt or gtk) you using and what platform.

**Comment by nabobalis** [comment]
I can get the vertex added, but after the second 'v', the two straight lines do not become curved. Also, if I attempt to do it again, it does not draw the new curve, until I do it for a third time.

It is QT (Python 2) and Linux. I'll try GTK.

**Comment by ejeschke** [comment]
@nabobalis, I am using the following version on Ubuntu 14.04
```python
In [6]: from PyQt4.QtCore import QT_VERSION_STR

In [7]: print("Qt version:", QT_VERSION_STR)
('Qt version:', '4.8.6')
```

**Comment by ejeschke** [comment]
I've merged @rupak0577's PR #139, so you can now edit the bezier cuts more easily.

For me, the interface now feels a bit confusing in that I want to use the left mouse button to edit similarly to what is done in `Drawing`.  I think `Cuts` and other plugins need a slight adaptation: you are in one of the following states:
1) neither drawing nor editing, but simply moving cuts around, by clicking or dragging
2) drawing a new cut (possibly to replace an existing cut)
3) editing a cut
All should use the left mouse button (which translates to a standard trackpad well)

I'm thinking that with some minor changes to the UI this should be easily possible.  Thoughts?

**Comment by nabobalis** [comment]
@ejeschke It says I have ('Qt version:', '4.8.7'). I also have QT 5 installed beside it. 

I'll update it on my laptop and get back to you!

**Comment by ejeschke** [comment]
Hmm, you may have discovered something interesting with 4.8.7.  I have also tested the following version successfully under python3/linux:
```python
>>> from PyQt5.QtCore import QT_VERSION_STR
>>> print("Qt version:", QT_VERSION_STR)
Qt version: 5.2.1
```

**Comment by Cadair** [comment]
@ejeschke Is there a way to force ginga into Qt5 mode?

**Comment by ejeschke** [comment]
@Cadair, you can do 
```python
$ ginga -t qt5 ...
```
or you can add a setting to your `$HOME/.ginga/general.cfg`:
```python
widgetSet = 'qt5'
```

**Comment by nabobalis** [comment]
@ejeschke  On my laptop, it does not work regardless of QT4 or QT5. I do wonder if its an Arch Issue.

**Comment by Cadair** [comment]
I like @nabobalis don't get a curve when I try and draw a bezier cure.

@nabobalis I just installed ginga for the first time on my cics machine. It seems to be working fine under qt5 but under qt4 I don't see the cuts plugin.

**Comment by nabobalis** [comment]
@cadair the same for qt4

**Comment by Cadair** [comment]
@nabobalis weirdly on my laptop I don't get cuts on qt5 either...

**Comment by ejeschke** [comment]
@Cadair, @nabobalis 
On the machines where the Cut plugin doesn't show up, can you start ginga with the following options: `--loglevel=20 --log=/tmp/ginga.log`

Then close ginga and look through the file for 'Cuts'.  You should find a line with an error message about loading the plugin.  What does it say?

**Comment by nabobalis** [comment]
@ejeschke 

For QT5:

**Comment by ejeschke** [comment]
One other thing to help troubleshoot: when you run `.../examples/qt/example2_qt.py` and select "beziercurve" in the drawing menu, can you draw it?  Wondering if cubic Bezier curve has trouble in some versions of qt.  If so, we can draw it using paths instead, which is what I ended up doing for one backend.  The performance is slower, but shouldn't matter much for Cuts.

**Comment by ejeschke** [comment]
@nabobalis, do you have Qt5 installed for python 2?  I think this is one scenario I haven't tested--I have qt5 for python3 and qt4 for python 2.  I wasn't aware that the two versions of Qt could coexist for one version of python.

**Comment by nabobalis** [comment]
@ejeschke I do indeed have both versions of PyQt (4,5) for Python 2 and 3.

**Comment by ejeschke** [comment]
Hmm, then I think the problem with loading the plugin has to do with matplotlib, actually.  Because only `Pick`, `Cuts` and `Histogram` have an embedded matplotlib widget.  How about the `example2_qt.py`--does it work to draw the beziercurve?

**Comment by nabobalis** [comment]
That example code does not draw the curve under Python 2.

**Comment by ejeschke** [comment]
Interesting.  The Qt backend also uses Beziers to draw ellipses.  Can you draw an ellipse with example2?  Are you using python 2.7?

**Comment by nabobalis** [comment]
Yeah, 2.7.10. Also I can't draw an ellipse. 

@Cadair  What about you? Is this an Arch Issue?

**Comment by ejeschke** [comment]
Regarding the loading of the Cuts plugin, etc., could you try setting the following environment variable?
```python
$ export QT_API=pyqt
```
I found this necessary to do in order to use matplotlib with Qt at times.

Also, if you wanted to try using PySide (instead of Qt), you could install that and then set `QT_API` to "pyside".

**Comment by nabobalis** [comment]
On my end, that didn't fix anything. I just have to think that this is some odd Arch Linux issue. 
How would debugging work? Just with -loglevel=20 --log=/tmp/ginga.log ?

**Comment by ejeschke** [comment]
Yes, if you add `--stderr` to the command line then you'll also get output to stderr.  You would look for some error happening right as you add the second vertex.

**Comment by nabobalis** [comment]
Error seems to be this:
```python
2015-07-23 09:05:22,417 | E | ImageView.py:698 (redraw_now) | Error redrawing image: 'module' object has no attribute 'QPainterPath'
2015-07-23 09:05:22,424 | E | ImageView.py:703 (redraw_now) | Traceback:
  File "/home/nabobalis/GitRepos/ginga/ginga/ImageView.py", line 686, in redraw_now
    self.redraw_data(whence=whence)
  File "/home/nabobalis/GitRepos/ginga/ginga/qtw/ImageViewCanvasQt.py", line 53, in redraw_data
    super(ImageViewCanvas, self).redraw_data(whence=whence)
  File "/home/nabobalis/GitRepos/ginga/ginga/ImageView.py", line 716, in redraw_data
    self.canvas.draw(self)
  File "/home/nabobalis/GitRepos/ginga/ginga/canvas/DrawingMixin.py", line 115, in draw
    super(DrawingMixin, self).draw(viewer)
  File "/home/nabobalis/GitRepos/ginga/ginga/canvas/CompoundMixin.py", line 126, in draw
    obj.draw(viewer)
  File "/home/nabobalis/GitRepos/ginga/ginga/canvas/DrawingMixin.py", line 117, in draw
    self._draw_obj.draw(viewer)
  File "/home/nabobalis/GitRepos/ginga/ginga/canvas/CanvasObject.py", line 878, in draw
    cr.draw_bezier_curve(cpoints)
  File "/home/nabobalis/GitRepos/ginga/ginga/qtw/ImageViewCanvasTypesQt.py", line 133, in draw_bezier_curve
    path = QtGui.QPainterPath()

QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active```

**Comment by ejeschke** [comment]
@nabobalis, I think you've nailed it.  We have to figure out where QPainterPath went in Qt 4.8.7.  It's very curious, because I'm using both 4.8.6 and 5.2.1 and in both cases it is still in `QtGui`.

**Comment by ejeschke** [comment]
Maybe you can test most things with gtk for now... until we get this sorted

**Comment by nabobalis** [comment]
Yeah, I will stick to GTK for now. Thanks @ejeschke.

**Comment by ejeschke** [comment]
@nabobalis, are you still having difficulty drawing the Bezier cut on ginga/qt4? qt5?

**Comment by ejeschke** [comment]
I think this issue is sorted for most platforms.
