### ISSUE TITLE
Editing canvas objects

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#137]
Ginga has slowly been developing editing capabilities for canvas objects.  So far this has been largely unadvertised, but now it may be ready for initial review and wider testing and documentation.

This has the potential to simplify many reference viewer plugins, which currently have to manage the relocation of canvas objects themselves.  Using the new editing capabilities, they can simply respond to an edit-event similarly to how they now handle a draw-event--by calling `redo()`.

Requesting feedback on the current scheme via testing of the `Drawing` plugin in the reference viewer.  With commit 78447825801e2c2f2abcef92cdc003bc7f0c7429, the plugin now features an "Edit mode" checkbox that places the canvas into edit mode.  Items can be selected and their points manipulated, they can be moved and their attributes can be changed dynamically via widgets in the plugin.

**Comment by ejeschke** [comment]
@pllim, @Cadair, @rupak0577, I would appreciate your feedback trying out the `Drawing` plugin editing.
I think the node editing capabilities will be helpful for plugins like `Cuts`, especially for something like a path or bezier cut.  We could add something like the "Edit mode" check box to Cuts that would put the canvas into edit mode and allow the user to manipulate the cut vertices.

**Comment by rupak0577** [comment]
@ejeschke Agree, that would be really helpful. I have modified Cuts to do that.

**Comment by ejeschke** [comment]
@rupak0577, which PR is this modification in?

**Comment by rupak0577** [comment]
@ejeschke Haven't committed it yet.

**Comment by ejeschke** [comment]
I've modified the `Cuts` plugin in commit c8a410ca14566efe2b04e95a838331f9dd9d828d to show how the new changes can be used in the plugins.  It's now possible to operate Cuts without using a right mouse button or using "draw" mode (although these will still work).  Thinking of rolling this kind of change out to the rest of the plugins that do drawing: `Pick`, `Histogram`, `Ruler`, etc.

**Comment by ejeschke** [comment]
`Pick`, 'Ruler`, `Histogram` all modified in commit c2bb11a52446b23a22f03f5eb93b243a3f8a0ade to work in the new style.  They are all backward compatible with the previous way of working as well--right mouse button (in the default mapping) always draws.

**Comment by pllim** [comment]
I am not sure if I like this new change. I am used to drawing with right button and moving with left button. Now if I forget to click on the new radio buttons, I screw things up.

**Comment by pllim** [comment]
Also the instructions do not match the new GUI behavior.

**Comment by ejeschke** [comment]
@pllim, right button always draws even with the changes.  if you keep the radio button marked as move, you can operate in the old style.  (I realize that for `Cuts` this does not quite work at the moment, as I put in logic to switch to draw mode when there are no extant cuts, but it does work for Pick).

We could make an option (possibly default) to make Cuts not change the button when there are no cuts.  That way if it stays on "Move", you can always operate in the old style.

I should definitely update the instructions, Tnx.

**Comment by pllim** [comment]
Okay. Please don't remove the "old style" way of doing things. Because my own plugins use the "old style" and I do not want them to break.

**Comment by ejeschke** [comment]
Do the other plugins work fine for you in the "old style"?  How about your plugins?  Everything ok, except Cuts?  I think this change has the potential to make trackpad users much happier while still accommodating those of us using mice.

**Comment by pllim** [comment]
`Histogram` and `Cuts` only work with "new style" now, as you indicated above. Or are they supposed to work with "old style" too?

`Drawing` does not have "new style" options, and "old style" does not seem to work anymore.

I don't use `Ruler` or `Pick` much, so I have no comments on those.

My own plugins seem fine. I don't have plans to add "new styles" to them.

**Comment by ejeschke** [comment]
For plugins that never had any left mouse functionality, like `Drawing` and `Ruler`, the new style is enabled by simply having an "Edit" checkbox.  Now that I think about it, for consistency these should have two radio buttons: "Draw" and "Edit".

**Comment by ejeschke** [comment]
@pllim, could you try commit 6b29c6ca782586f086f5b05c2614e6cc8ec3f14a?  This should provide for backward-compatible drawing behavior for `Cuts` and `Histogram`.  Also, I've changed `Pick`, `Ruler` and `Drawing` to have the same radio-button scheme for draw/edit (minus "move").

**Comment by pllim** [comment]
@ejeschke , your commit looks good. Thank you!
