### ISSUE TITLE
Unicode characters in README.txt prevent installation in Python 3 on Windows 

### ISSUE THREAD

**Issue by mwcraig** [ejeschke/ginga#138]
It looks like the default encoding on Windows is `charmap`, which doesn't understand the unicode characters in the `README.txt`. When `setup.py` hits `read('README.txt')` it throws an error when it hits the first non-ASCII character.

I think I have a fix coming in a moment (adding an encoding the `open` in the definition of `read` in `setup.py`), want to make sure it doesn't break other platforms/python versions.

**Comment by mwcraig** [comment]
@ejeschke -- I've worked around this for building conda packages by writing a recipe that applies a patch on Windows/Python 3.4. 

To completely fix this is in `setup.py` would be a little messy...maybe 8-10 lines of code to check python version and platform and set encoding if necessary.

It is probably easier just to direct Windows users to install the conda package: `conda install -c astropy ginga` will do the trick.

**Comment by ejeschke** [comment]
@mwcraig, thanks for looking into this!  Windows testing is my "blind spot" for ginga--I don't actually know anyone here that uses that combination, but we have a number of users on macs and linux boxes.

I think most Windows users are installing via anaconda/conda--but how does this work around the issue exactly?

**Comment by mwcraig** [comment]
@ejeschke -- I wrote a recipe that patches `setup.py` [here](https://github.com/ejeschke/ginga/blob/master/setup.py#L15) to add the argument `encoding='utf-8'` on Windows + python 3.x builds for the affiliated package builder-bot.

**Comment by ejeschke** [comment]
@mwcraig, I understand.  Seems like there should be a "clean" way to handle it with a couple of lines of python that would be platform independent and 2/3 independent.  Seems like the problem is just needing to specify the encoding explicitly?  Would it be simpler if it is only python 2.7 or above (ginga doesn't support 2.6 or below without patching)?

**Comment by mwcraig** [comment]
@ejeschke, with the caveat that I haven't looked into it much, I'm guessing there is a better way. It could be as simple as this pseudo-code:

```python
if python_version_is_3:
    buf = open(os.path.join(srcdir, fname), 'r', encoding='utf-8').read()
else:
    buf = open(os.path.join(srcdir, fname), 'r').read()
```

Python 2 doesn't like the `encoding` argument to open.

**Comment by pllim** [comment]
FYI -- This won't be an issue anymore after #313 is merged. Because following the Astropy template, `read()` is no longer used. Instead, long description is extracted from `package.__doc__`.

**Comment by pllim** [comment]
@mwcraig , this should not be an issue anymore with the latest master. Could you please check again and confirm? Thanks.

**Comment by mwcraig** [comment]
@pllim -- finally getting around to this. Has this been included in a release yet?

**Comment by pllim** [comment]
I usually just grab the dev version. @ejeschke is the one who can answer this.

**Comment by ejeschke** [comment]
@mwcraig, I think the release has been bumped since this fix at least once, and PyPI updated.

**Comment by mwcraig** [comment]
This can be closed, it is no longer an issue in the automated package builds I'm doing (which was where it first turned up).
