### ISSUE TITLE
Reference Viewer new feature: Draggable Thumbs

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#148]
If you create a new channel (Channel>Add Channel, you can now drag thumbs from the `Thumbs` pane into the new channel.  Currently they are moved from the existing channel to the new channel, so this offers a way to reorganize the images in the channels, or to quickly set up a group for a plugin like `Blink`.

An early version of this feature resulted in a segfault for me when removing the thumb (since worked around) so would very much be interested in any feedback.  

Oh, and presumably we would want a way to just copy rather than move the image--maybe by holding down the "Ctrl" key?  I'd like eventually to offer the same kind of functionality with `Contents`.

**Comment by ejeschke** [comment]
@pllim, would really appreciate your testing of this, if you get a chance.

**Comment by ejeschke** [comment]
I'm getting segfaults again with this feature.  Seems to be having to do with removing a Thumb, because when I make it just copy images between channels there is no problem.

**Comment by pllim** [comment]
I only use 1 channel, i.e., the default Image channel. But I can check this out when I get a chance some time this week.

**Comment by ejeschke** [comment]
Great, Tnx.  Thinking this might be a workaround for setting up a `Blink` with just the images you want in the order you want (until we can get to some of the other feature requests).  You just create a new channel, drag the images you want in it in the order that you want and run `Blink`.

**Comment by pllim** [comment]
1. What do you mean by "removing a Thumb"? I did not get seg fault when I moved an image from the new channel back to the old, or when I deleted the image from the new channel.

2. This might work for just blinking a select few of the images. :+1: to an option to copy instead, but it is still the same cache right, or do you actually make a real copy of the data? 

3. This might *not* work for re-ordering the images. For instance, if I want to re-order 50 open images, I do not want to drag an image over to the new channel 50 times.

4. I understand that this is still experimental, so I am not surprised when `Cuts` stopped working after I created a new  channel and dragged one image onto it. Nothing crashed, no error messages; It just does not make a new cut, nor display the existing one.

5. Also somewhat related: I noticed that the new channel does not automatically inherit "channel_Image.cfg" but instead complains about:
```
2015-08-18 11:57:33,734 | W | Control.py:1107 (add_channel) | no saved preferences found for channel 'Image1': Error opening settings file (~/.ginga/channel_Image1.cfg): [Errno 2] No such file or directory: '~/.ginga/channel_Image1.cfg'
```

**Comment by ejeschke** [comment]
This feature is currently reverted.  Leaving this issue open until we decide whether this is something desirable to keep.

Another possibility is just providing drap-drop reordering within `Contents`.

**Comment by pllim** [comment]
I am not sure where this is going. #226 that enables blinking by load time or alphabetical name order works for me. Are you saying that you also want to enable blinking by how the images are visually ordered in the listing?

**Comment by ejeschke** [comment]
Sorry for the confusion.  I am talking about the ability to drag thumbs is reverted (no longer working).  Given the issues that you mentioned above and the fact that there might be more efficient ways to move images between channels, I am not sure I want to put the effort into getting this working again right away until there is a good idea of what it would be used for.

**Comment by pllim** [comment]
Okay, yes, I agree. :+1:
