### ISSUE TITLE
Adding "width" to Cuts

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#156]
Commit 8772c092e2d3e5da63101ee6dea8a48f379db4ce adds the ability to specify a "width" for cuts in the `Cuts` plugin.  _Currently this is allowed for "line" (straight) cuts only._

When a cut has a width the value plotted is not simply the pixel value at the point along the cut, but the sum of the pixel values along a cut oblique to the main cut direction, in a line of 2*radius+1.  The purpose of this enhancement is to show absorption lines clearly in the quick look cut plots for spectrograph images.
### The way it works

There is a new set of controls under the collapsible "Cut Width" heading.

The width of 'line' cuts can be changed using the "Width Type" menu:
- "none" indicates a cut of zero radius; i.e. only showing the pixel values along the line
- "x" will plot the sum of values along the image X axis oblique to the cut.
- "y" will plot the sum of values along the image Y axis oblique to the cut.
- "perpendicular" will plot the sum of values along an axis perpendicular to the cut.

The "Width radius" controls the width of the oblique summation by an amount on either side of the cut: 1 would be 3 pixels, 2 would be 5 pixels, etc.

Currently, these controls affect _all "line" cuts_; i.e. they are global controls.

**Comment by ejeschke** [comment]
@pllim, @Cadair, @nabobalis, @rupak0577 
Recently we got a request from a local user for this enhancement. Wondering if this new feature is useful in your work.  Would appreciate any feedback (it's in master) or comment on how it might be used with (to be merged) Slit additions.

**Comment by Cadair** [comment]
This looks interesting, I don't know how useful this exact feature would be but there are a couple of related things that I can think of that would be useful:

1. Being able to 'integrate' rather than sum to maintain correct flux.
2. Being able to extract a series of cuts perpendicular to the main cut.

**Comment by nabobalis** [comment]
I do like the look of it. I've never considered it before.

One small suggestion, the width line is not drawn at the end of the cut if the line is at certain lengths. I assume since the width lines are equally spaced, it is not always possible to draw the last one. 

@Cadair There was a way to draw a perpendicular cut to the main cut, I can not seem to remember how.

**Comment by pllim** [comment]
I don't currently work with spectra but this looks promising. Some comments below:

* I notice that you added arrow icons to expand/hide `Instructions` and `Cut Width`. They look nifty but... Initial arrow is `V` (pointing down) with frame minimized. When I expand the frame, the arrow does not change to `-->` but the frame is shown. So when I hide the frame again, now the arrow becomes `-->`, hence out of sync with that it represents from here onwards.
* Somewhere on the GUI (inside `Instructions` or `Cut Width` frame), there should be a clarification that the width only applies to lines and that it is a global setting.
* I am not sure if width setting being global is desirable. I can see cases where users might want different widths for each cut.
* Could be useful to add an "algorithm" option for width calculation, similar to what @Cadair suggested above. If width eventually becomes specific to a particular cut (not global), this should also be the same.
* Eventually, would be nice to see this width being expanded to all cut types. Then, it would be also useful for Echelle data and cases where the spectrum is not straight on the image.

**Comment by ejeschke** [comment]
Thanks for all the comments.

@Cadair, I agree it would be useful to allow the user to specify a custom function instead of simply summing. I think the next person with a use case will help drive the implementation of that.

@nabobalis: yes, the algorithm that draws the "tines" needs a little work to spread them evenly.

@pllim: Arrow icons for the expandable regions should be fixed in recent commits.  I agree that having different width lines may be useful.  I would like to sort out how this feature should interoperate with paths and curves before making it an individual attribute of a cut.

**Comment by pllim** [comment]
@ejeschke , yes, the arrows work properly now. Thanks!
