### ISSUE TITLE
Local plugin focus change

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#158]
When I have multiple local plugins active, clicking on its tab on upper right does not change the "green" (focused) box below the main image display. Is this a bug or intentional design decision?

Sometimes this gets confusing when I select the plugin with upper-right tabs and do not see expected behavior. 

EDIT: If what I described does not make sense to you, let me know and I'll post some screenshots.

**Comment by ejeschke** [comment]
It might be possible to make the focus change by clicking on the plugin notebook tab.  I'll have to look at this.  It won't work to click on the channel tab because there can be several plugins working on the same channel.

But, if you can consider an alternate approach there is a solution already there.  If you click on the "icon" for the plugin in the Plugin Manager bar (the bar containing the menu labeled "Operation") it will 
1) change focus to the selected plugin
2) raise it's plugin window
3) raise the channel window associated with the plugin

**Comment by pllim** [comment]
Okay, just want to make sure it is not a bug. My first instinct was to click on the "notebook tab" on top to focus, not the "manager bar" at the bottom.

Maybe have the focused plugin also colored green on "notebook tab"? Then even when I click on a different plugin there, I know it is actually not focused because the tab I clicked is not green. Just a thought.

**Comment by ejeschke** [comment]
The gtk version does color the channel tabs green for channels that are focused.  Maybe we could extend this to the plugin tabs and roll it out to the qt versions too.

**Comment by pllim** [comment]
Yes, that would be nice. :)

**Comment by pllim** [comment]
@ejeschke , I noticed that the active channel tab now has green text highlight. Would it be possible to extend that to local plugin tabs behavior?

**Comment by ejeschke** [comment]
@pllim, can you take a look at commit 576faa29904811e26ba60eff916e20d14113eab1?  This adds support for fixing the main question in this issue, namely: when you now click on a local plugin tab, it should focus the plugin and raise the associated channel window.  I think this will be a huge help in reducing confusion (especially at our summit!)

Tab highlighting to be addressed subsequently, in this issue, so leaving open.

**Comment by pllim** [comment]
> when you now click on a local plugin tab, it should focus the plugin and raise the associated channel window

It works if I click on the "tab" under image display, which is not really a tab. Nothing happens when I click on the tab on upper right (under "Dialogs").

**Comment by pllim** [comment]
Oh wait, is it a brand new commit? Hold on, let me grab it and see. Sorry.

**Comment by pllim** [comment]
> when you now click on a local plugin tab, it should focus the plugin and raise the associated channel window

Yes, it works now! That's great. Thanks! :+1: :smile:
