### ISSUE TITLE
Info bar displays values of the colorbar

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#159]
Not necessarily needs fixing, but I just want to bring it to your knowledge. If you mouse over the colorbar below the main image display, the info bar (that displays RA, DEC, X, Y, and Value) now displays:
```
Value: some_random_number
```

**Comment by ejeschke** [comment]
This is a feature (and a bug), actually.  It is supposed to show in the Readout the approximate value at that position in the color bar.  Unfortunately the value is not accurate, currently.  This will be fixed.

**Comment by ejeschke** [comment]
Commit ae89dfc44cb79d12c092d3f2b91744bd3d830d6a fixes the issue so that the color bar labeling is consistent with the mouseover values.  The accuracy of the ticks labels is improved.

**Comment by pllim** [comment]
:+1:
