### ISSUE TITLE
Any paint capability?

### ISSUE THREAD

**Issue by stscieisenhamer** [ejeschke/ginga#160]
There is the Drawing plugin that can draw objects.

However, there does not appear to be any painting capability: I.e. use a shape as a brush and paint an object with that brush. Typical use would be to create masks, etc. Or, am I just missing an already existing plugin?

**Comment by pllim** [comment]
Theoretically you can draw using the existing shape classes and then extract the mask using:
```python
image.cutout_shape(shape_obj)
```

We can talk in person on Monday if you wish.

**Comment by ejeschke** [comment]
There is no mask painting plugin currently.  I was helping someone get started on one at a python workshop in April, but I haven't heard anything further about it.  As @pllim notes, this would be a pretty straightforward (I think) based on current shape capabilities.

**Comment by pllim** [comment]
To clarify, `cutout_shape()` only returns the mask with the smallest possible bounding box, so it is not in the shape of the original image. To get mask in the original shape, use `get_shape_mask()` (see #152).

**Comment by ejeschke** [comment]
For example, if you have created an array called `mask` of the same dimensions as the image data, then you can do something like:
```python
view, contains = image.get_shape_view(obj)
mask[view][contains] = True
```
Or assign a value if creating a numerical mask.

You could do this in a callback for `cursor-move` (button 1 drag).

**Comment by stscieisenhamer** [comment]
Thanks. That will be enough to get started on. I'll find @pllim and discuss further.
