### ISSUE TITLE
example2_qt not showing shapes

### ISSUE THREAD

**Issue by stscieisenhamer** [ejeschke/ginga#163]
Just to make sure its not me, but 

python -m example2_qt

seems to operate fine, loading images, etc. except that no shapes actually draw.

this is os x, and conda install.

**Comment by ejeschke** [comment]
@stscieisenhamer, that's fine for example2_qt.py, but the default for ginga is not to draw shapes with the left mouse button unless the canvas has been put in draw mode.  Try using the right mouse button, or press the space bar, release and then draw with the left.  Or press space bar, release, then 'L' to lock draw mode and then draw away.

**Comment by stscieisenhamer** [comment]
DOH! Sorry, I had looked to see if there was a mode issue, but missed the "blue box note". Issue retracted.

**Comment by ejeschke** [comment]
@stscieisenhamer, I think you have identified a common issue here, though.  New users likely won't have read any documentation and are just trying examples.  This is one reason that issue #137 and it's changes came about.  In the reference viewer you now have these radio buttons for most of the plugins that do drawing.  It's time I updated the examples to follow suit, and enable the use of the left mouse button for drawing.

Could you update your repo for commit cda99530242c84fb254eaa914695ea8851724218 or later and try `example2.py` in `.../examples/gw/example2.py`?   If you want to force a qt rendering just give it the "-t qt" option on the command line. This is the "generic widgets" version of the  common example2 and if it is working well for you I'll try and update the other widget-specific examples.

**Comment by stscieisenhamer** [comment]
That works well! :+1:
