### ISSUE TITLE
basics of a mask overlay

### ISSUE THREAD

**Issue by stscieisenhamer** [ejeschke/ginga#165]
Based on the Overlays plugin, I've distilled the creation/displaying of an mask overlay on an ImageViewCanvas to the [following gist](https://gist.github.com/stscieisenhamer/25bf6287c2c724cb9cc7). Just wondering if this is the basics, or is there something more basic that can be done.

Note: I'm in need of doing this not in a reference viewer, but using only the ImageView-based widgets, hence why distilling out the mask viewing.

**Comment by pllim** [comment]
Just brainstorming here: If you can somehow convert your mask into, say, a Ginga polygon object, then it already has built-in options like "fill" and "alpha", and you can overlay it by using something like `canvas.add(...)` without having to build RGB image.

**Comment by ejeschke** [comment]
@stscieisenhamer, I think you've nailed the basics here.  Does it work for you?  I don't have access to some of the classes referenced in the gist so I cannot test it, but it looks right to me.

**Comment by ejeschke** [comment]
@pllim, I have found that rendering many small polygons with each one having a large number of vertices is slower than rendering a pixel overlay.  So there is a tradeoff there.  I think with a large number of irregularly shaped areas a traditional pixel mask might be more efficient.

**Comment by stscieisenhamer** [comment]
Yes, it works quite well actually. Just wanted to make sure there wasn't some concept/code I missed, such as exactly what @pllim suggested.

@pllim Yes, which is why I wanted to get the basic mask down, so the option of either or would be available. As, expected, while developing masks, one will have shapes. But to save the region, which will ultimately be a composite of many shapes, the shapes will get render out, then later read back in, as pixel masks anyways.

So, w00t1, not too far off the boat...

**Comment by pllim** [comment]
With what you are doing, @stscieisenhamer , you might need an extra option to specify mask color, to distinguish the different types of mask. But yeah, if polygon is not the thing for you, this should be okay. Good luck!

**Comment by stscieisenhamer** [comment]
@pllim Oh, most definitely, and opacity at least.

Thanks to all!

**Comment by pllim** [comment]
It just so happens this `masktorgb()` function also comes in handy for me to overlay a mask for #162. Any chance a more general version can be include in Ginga? If so, I am willing to open a PR for it; Just need to know where to put the code.

**Comment by ejeschke** [comment]
There are a lot of possibilities, but how about `.../ginga/util/dp.py`?  It's kind of a grab bag of module functions for dealing with images or direct numpy arrays.
