### ISSUE TITLE
Ginga install on Mac

### ISSUE THREAD

**Issue by colinaspin** [ejeschke/ginga#167]
I followed the Mac install instructions at the link below 

https://ginga.readthedocs.org/en/latest/install.html#mac

and when I ran ginga got:

[caa@kree ejeschke-ginga-3cd3d27]% ginga
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ginga", line 5, in <module>
    pkg_resources.run_script('ginga==2.5.20151001032930', 'ginga')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/EGG-INFO/scripts/ginga", line 11, in <module>
    from ginga import main
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/main.py", line 51, in <module>
    from ginga import AstroImage
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/AstroImage.py", line 19, in <module>
    from ginga.util import wcsmod, io_fits
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/util/wcsmod.py", line 1249, in <module>
    if use(name, raise_err=False):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/util/wcsmod.py", line 118, in use
    if LooseVersion(astropy.__version__) <= LooseVersion('1'):
UnboundLocalError: local variable 'astropy' referenced before assignment

Anyone any ideas??

**Comment by ejeschke** [comment]
@colinaspin, I think this is due to a problem detecting the correct version of astropy.  As a temporary workaround , could you create a folder (`$HOME/.ginga`) and inside that place a text file called `general.cfg`.  In that, put the line:
```python
WCSpkg = 'astropy'
```
and try restarting ginga?  Let me know the results.  Tnx.

**Comment by colinaspin** [comment]
Hi,

OK, did that but no difference, see below.

[caa@kree ~/.ginga]% pwd
/Users/caa/.ginga
[caa@kree ~/.ginga]% ls -ltr
total 8
-rw-r--r--  1 caa  _lpoperator  19 Oct  1 10:40 general.cfg
[caa@kree ~/.ginga]% cat general.cfg
WCSpkg = 'astropy'
[caa@kree ~/.ginga]% which ginga
/Library/Frameworks/Python.framework/Versions/2.7/bin/ginga
[caa@kree ~/.ginga]% ginga
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ginga", line
5, in <module>
    pkg_resources.run_script('ginga==2.5.20151001032930', 'ginga')
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py",
line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py",
line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/EGG-INFO/scripts/ginga",
line 11, in <module>
    from ginga import main
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/main.py",
line 51, in <module>
    from ginga import AstroImage
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/AstroImage.py",
line 19, in <module>
    from ginga.util import wcsmod, io_fits
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/util/wcsmod.py",
line 1249, in <module>
    if use(name, raise_err=False):
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/util/wcsmod.py",
line 118, in use
    if LooseVersion(astropy.__version__) <= LooseVersion('1'):
UnboundLocalError: local variable 'astropy' referenced before assignment

**Comment by colinaspin** [comment]
I also uninstalled py-astropy and reinstalled, still get the error, see
below.

[caa@kree ejeschke-ginga-3cd3d27]% sudo port install py-astropy
--->  Computing dependencies for py-astropy
--->  Fetching archive for py-astropy
--->  Attempting to fetch py-astropy-1.0.4_0.darwin_14.noarch.tbz2 from
http://packages.macports.org/py-astropy
--->  Attempting to fetch py-astropy-1.0.4_0.darwin_14.noarch.tbz2.rmd160
from http://packages.macports.org/py-astropy
--->  Installing py-astropy @1.0.4_0
--->  Activating py-astropy @1.0.4_0
--->  Cleaning py-astropy
--->  Updating database of binaries
--->  Scanning binaries for linking errors
--->  No broken files found.
[caa@kree ejeschke-ginga-3cd3d27]% ginga
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ginga", line
5, in <module>
    pkg_resources.run_script('ginga==2.5.20151001032930', 'ginga')
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py",
line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py",
line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/EGG-INFO/scripts/ginga",
line 11, in <module>
    from ginga import main
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/main.py",
line 51, in <module>
    from ginga import AstroImage
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/AstroImage.py",
line 19, in <module>
    from ginga.util import wcsmod, io_fits
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/util/wcsmod.py",
line 1249, in <module>
    if use(name, raise_err=False):
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/util/wcsmod.py",
line 118, in use
    if LooseVersion(astropy.__version__) <= LooseVersion('1'):
UnboundLocalError: local variable 'astropy' referenced before assignment

**Comment by ejeschke** [comment]
Alternatively, if you don't have `astropy` installed, but *do* have one of {`kapteyn` | 'starlink/ast` | `astLib`} you can use that instead.

**Comment by ejeschke** [comment]
Ah, I think I see the problem.  Could you try commit 981817f47429d8d759161ce50c652e979c11d6f4 from master?

**Comment by ejeschke** [comment]
It's using `astropy` without that being properly declared in the version check.

**Comment by colinaspin** [comment]
from within python?   Not sure where to do the commit, sorry.

**Comment by ejeschke** [comment]
If possible, can you checkout ginga via:
```bash
$ git clone https://github.com/ejeschke/ginga.git
```
and install from there, via the usual 
```bash
$ python setup.py install 
```
Use python that was installed for macports.

**Comment by ejeschke** [comment]
This is an interesting error, most people are installing via anaconda+pip or anaconda+git clone and I haven't had any reports of this error.

**Comment by colinaspin** [comment]
OK, removed the old ginger repository and now re-downloading, getting
150kB/sec, will take a while!  More when I've installed and tested.

**Comment by colinaspin** [comment]
OK, got the new git version, and did the build/install.  Still get the
same, see check on version of ginga then run:

[caa@kree ~/ginga]% which ginga
/Library/Frameworks/Python.framework/Versions/2.7/bin/ginga
[caa@kree ~/ginga]% ls -ltr
/Library/Frameworks/Python.framework/Versions/2.7/bin/ginga
-rwxr-xr-x  1 root  admin  281 Oct  1 11:16
/Library/Frameworks/Python.framework/Versions/2.7/bin/ginga
[caa@kree ~/ginga]% ginga
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ginga", line
5, in <module>
    pkg_resources.run_script('ginga==2.5.20151001032930', 'ginga')
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py",
line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py",
line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/EGG-INFO/scripts/ginga",
line 11, in <module>
    from ginga import main
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/main.py",
line 51, in <module>
    from ginga import AstroImage
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/AstroImage.py",
line 19, in <module>
    from ginga.util import wcsmod, io_fits
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/util/wcsmod.py",
line 1249, in <module>
    if use(name, raise_err=False):
  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga-2.5.20151001032930-py2.7.egg/ginga/util/wcsmod.py",
line 118, in use
    if LooseVersion(astropy.__version__) <= LooseVersion('1'):
NameError: global name 'astropy' is not defined
[caa@kree ~/ginga]%

**Comment by ejeschke** [comment]
Great, this makes iterating fixes easier.  I added another fix in commit 0a10289c880531f3d2069bd36f06b2e22058233a to avoid raising any exception in the case of importing a WCS package on startup.  You can update to that by:
```bash
$ git fetch origin
$ git merge origin/master
```
Then reinstall with `python setup.py ...`

Let me know how this goes.

**Comment by colinaspin** [comment]
OK, did this:

[caa@kree ~/ginga]% git fetch origin
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/ejeschke/ginga
   981817f..0a10289  master     -> origin/master
[caa@kree ~/ginga]% git merge origin/master
Updating 981817f..0a10289
Fast-forward
 ginga/util/wcsmod.py | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

and it worked!   I see the ginga window, many thanks!

OK, I did

[caa@kree ~]% ginga NFP02294_2_new.fits
No handlers could be found for logger "ginga"

and got the window but the image display isn't there, I see the pixel
values but just a grey screen, tried a different cut but nothing, see
attached.

**Comment by ejeschke** [comment]
Can't see attachment.  Is there a place I can download this FITS file?

**Comment by ejeschke** [comment]
Or send it to me by email, my address is in the source somewhere, I think.

**Comment by ejeschke** [comment]
Suspect this is related to the fact that no WCS package could be imported, but ginga does display FITS files without valid WCS all the time, so interested to see if I can load that file (or similar type of file).

**Comment by ejeschke** [comment]
I managed to reproduce the error after testing in an environment with no support packages installed.  The problem is that there is no FITS package to load the file.  Commit f45ed135db4572907eef0e4c47fb734a2de7a312 fixes this to show an error in the GUI (it was shown in the log file only).

So we have to figure out why macports version of astropy can't be imported.  Could you open a python session and issue the following code:
```python
>>> from astropy.version import version
>>> version
```
Let me know which version was installed.

In the meantime, if you can install `kapteyn` or `starlink` you could test with those--ginga will pick them up automatically.

**Comment by colinaspin** [comment]
It's weird but even though I installed astropy with port, it doesn't pick
it up, see below.

[caa@kree ~/ginga]% sudo port install py-astropy
--->  Computing dependencies for py-astropy
--->  Cleaning py-astropy
--->  Scanning binaries for linking errors
--->  No broken files found.
[caa@kree ~/ginga]%
[caa@kree ~/ginga]% python
Python 2.7.2 (v2.7.2:8527427914a2, Jun 11 2011, 15:22:34)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.version import version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named astropy.version

**Comment by colinaspin** [comment]
I installed py27-kapteyn using port and already have Starlink but still
have the problem.

**Comment by ejeschke** [comment]
Sorry, I edited my comment after the email went out. `starlink` will work for the wcs, but you will need something to open the FITS file, since no `astropy`.  Try installing `fitsio` (see comment just above)--easiest way is to git clone it and install in the normal way.  Incidentally, it might be worth trying to install `astropy` that way as well, since it doesn't seem to be picking up from the port install.

**Comment by ejeschke** [comment]
Issue solved by user reinstalling a couple packages using pip.
