### ISSUE TITLE
Canvas Image object pushed to background layer

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#172]
In my plugin, I build my canvas like this:
```python
self.canvas.setSurface(self.fitsimage)
...
m_obj = self.dc.Image(0, 0, RGMImage(...), linewidth=10)
p_obj = self.dc.Point(x, y, r)
t_obj = self.dc.Text(x, y, 'label')
self.tag = self.canvas.add(self.dc.CompoundObject(m_obj, p_obj, t_obj))
```
The point and text objects show up fine, but the image is somehow behind `self.fitsimage` (when `linewidth` is non-zero, I see some color I set for the image object behind the data). Am I missing something here?

**Comment by ejeschke** [comment]
@pllim, what happens if you add the line
```python
self.fitsimage.get_canvas().lower_object(self.canvas)
```
just after you add your compound object?

**Comment by pllim** [comment]
Need to leave now. I'll try that next week. Thanks.

**Comment by pllim** [comment]
@ejeschke , I get:
```python
Traceback (most recent call last):
    self.fitsimage.get_canvas().lower_object(self.canvas)
  File ".../ginga-2.5.20151003224836-py2.7.egg/ginga/canvas/CompoundMixin.py", line 187, in lower_object
    self.objects.remove(obj)
ValueError: list.remove(x): x not in list
```
My `self.fitsimage.get_canvas().objects` only has one object that is a `NormImage`. My `self.canvas` is a `DrawingCanvas` with a single `CompoundObject`, which contains `[Image, Point, Text]` that I added.

**Comment by pllim** [comment]
This is the `RGBImage` I am attempting to overlay (blue lines over transparent background):
![ztmp](https://cloud.githubusercontent.com/assets/2090236/10437783/75025d1c-70fd-11e5-88ab-18df28c3ed15.png)

This is the result I see (when I set `linewidth=10`, note that default color for `self.dc.Image` is light green):
![screenshot](https://cloud.githubusercontent.com/assets/2090236/10437798/95abbbb2-70fd-11e5-9658-cc47d08a4698.png)

**Comment by pllim** [comment]
Maybe it is not pushed to background? Maybe I am just not doing it properly? So the alternate question is, "How do I overlay a semi-transparent RGB image on the displayed data without changing the data cache?"

**Comment by ejeschke** [comment]
@pllim, you definitely can overlay that compound object.  Ginga does have a limitation (currently) that image objects will be placed below other kinds of objects, regardless of the stacking order, but the images should respect the stacking order with regard to each other, so that your overlay should appear on top of the background image and your other graphics (point, text) on top of that.

I'm a little surprised at the exception, I am assuming your canvas is added to the main canvas (otherwise we wouldn't be seeing any of the compound stuff).  How about the alpha channel of your RGBImage?  Is it set to 0?  Are you creating an RGBA array with 4 channels (1 or alpha?)

**Comment by ejeschke** [comment]
> My self.fitsimage.get_canvas().objects only has one object that is a NormImage
You definitely should also have the canvas from your plugin on there too.  In your `start()` method for your plugin, do you do something like:
```python
    p_canvas = self.fitsimage.get_canvas()
    if not p_canvas.has_object(self.canvas):
        p_canvas.add(self.canvas)
``` ?

**Comment by pllim** [comment]
Ah, okay. I didn't realize you change the way `start()` works in b3716df1. My plugins are based on your older versions. I'll give that a try and get back to you.

**Comment by pllim** [comment]
So, it turns out the overlay works even without `lower_object()` after I changed `start()` and `stop()` to use `p_canvas`. Thanks!

**Comment by ejeschke** [comment]
Excellent.
