### ISSUE TITLE
Line Profile Plugin: behavior on 2D images

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#188]
As @pllim reports in comments to PR#146, there is an error message when the plugin is used with a 2D image, apparently due to an instance variable not being initialized.  Probably some indication should be given that the plugin will not work with 2D images, both in the instructions and maybe with a small label widget that says "LineProfile disabled for 2D images"--you would set the label when a 2D image appears and clear it when you have a valid 3D image.

**Comment by ejeschke** [comment]
Also, with 3D images, if I start the plugin before any image is loaded and then load a 3D image, it won't let me set a point.

ping @rupak0577
cc: @nabobalis, @Cadair

**Comment by pllim** [comment]
Partially fixed by #187?

**Comment by rupak0577** [comment]
@ejeschke You are probably clicking outside the boundaries, which it does not allow. Also, it works fine for me.

**Comment by ejeschke** [comment]
Fixed the error message and some other minor issues in commit 376bf76ebeabb3235b41bb0d83602b11f26fe573

**Comment by Cadair** [comment]
@ejeschke I don't think slit should work with 2D images at all, same as line profile.

**Comment by ejeschke** [comment]
Roger that, but it was spewing exceptions into the log when loading 2D images (*even when not using the plugin*).  Not good.

**Comment by Cadair** [comment]
@ejeschke Interesting. I guess it should be disabled if the image is not 3D+ and it should obviously not be doing much if it's not being used.

**Comment by ejeschke** [comment]
My bad for not catching it earlier.  The plugin was registering for new image notifications (via a callback) to rebuild the  axes options, but this is unnecessary, since `redo()` is called when there is a new image and is only called if the plugin is active.  So it is the preferred way to handle new images in plugins.

**Comment by rupak0577** [comment]
@ejeschke Thanks for the fixes. It was wrong to use the callback - I used it for rebuilding the axes only when a new image is loaded instead of using `redo()` which does it everytime.

**Comment by ejeschke** [comment]
@rupak0577, you wouldn't have known due to the poor documentation, but both of those were triggered off of the same event (image-set, which is an image being displayed in the channel window--not necessarily a "new" image--just an image now displayed).  What's different is that `redo()` is called only when the plugin is actively being used (i.e. is open on that channel).  So in a sense it is the optimal way to know that the user has changed the image in the channel where your plugin is active and you need to "redo" whatever it is that you do.  In your case you want to see if this is a change in the structure of the image dimensions.

We should consider optimizing that routine (i.e. don't rebuild the checkboxes if the number of checkboxes for the new image is identical to what it already is) and also preserving the state of the checked boxes from image to image.

**Comment by pllim** [comment]
> preserving the state of the checked boxes from image to image

Yes, I think just toggle them enable/disable would  be obvious enough to the users. :+1:

**Comment by rupak0577** [comment]
@ejeschke Hmm, I missed it - we don't need to rebuild the axes if the new image loaded has the same number of axes as the current one which simplifies it.

**Comment by pllim** [comment]
@ejeschke and @rupak0577, is this still an issue? Just wondering.

**Comment by pllim** [comment]
I don't see any problem with 2D image anymore.
