### ISSUE TITLE
Header plugin sorting is not working for me

### ISSUE THREAD

**Issue by hcferguson** [ejeschke/ginga#189]
The manual says: "Clicking on a column header will sort the table by values in that column, which may be useful for quickly locating a particular keyword." 

This isn't working for me (running using Qt on a Mac.)

**Comment by pllim** [comment]
Did you check the "Sortable" checkbox at the bottom left? Just wanting to make sure.

**Comment by ejeschke** [comment]
Works for me on your huge header example if I click the `Sortable` box in lower left.  Maybe I should mark this as a documentation fix?

**Comment by hcferguson** [comment]
Yes. I didn't notice the checkbox. It works for me when I click ```Sortable```.

**Comment by ejeschke** [comment]
Maybe we should make this a stored preference?  Currently you have to check the box whenever you start up ginga.  It persist for the entire session, but not between sessions.

**Comment by hcferguson** [comment]
Seems sensible. Or just make it sortable by default?

**Comment by ejeschke** [comment]
Hmm, when I make it sortable by default, it sorts the header (as expected).  I think for many of our users (at least), they are familiar with the order in which the instrument wrote the file, and having ginga sort it by default might be confusing.

**Comment by pllim** [comment]
I agree with @ejeschke that sorting by default is not desirable. I am one of those people who already familiar with the header layout and wish to keep it that way.

**Comment by hcferguson** [comment]
Agreed that I would want to have the first view be in the order they appear in the header. But more intuitive to me would be to have it so that  just clicking on a column sorts by that column without having to click another button to enable that functionality. And then I would want the option to put it back in the original order (i.e. rename the Sortable button something like "reset" and have it undo the sort, if that's feasible).

**Comment by pllim** [comment]
Currently, unchecking `Sortable` undoes the sorting. I think for now, it is sufficient to make the checkbox a preference.

**Comment by ejeschke** [comment]
Merged #196.  Leaving this issue open until the documentation is updated.

**Comment by ejeschke** [comment]
I believe the documentation is addressed in commit 10fe0ceb9bb051d0832915b6f21ef6b73d87c43c.  If there is no objection, I will close this issue.

**Comment by pllim** [comment]
@ejeschke, there appears to be a broken reference in the sentence just above your commit.
