### ISSUE TITLE
Text partially cutoff in plugin windows

### ISSUE THREAD

**Issue by hcferguson** [ejeschke/ginga#192]
The word "Instructions", for example, is half obscured by the sub-window below it as in the attached screenshot. This is a generic issue for @hcferguson but not for @stscieisenhamer who is also running Qt on a Mac. Also, @pllim, on linux with Qt doesn't see the problem.
![screen shot 2015-10-26 at 5 16 55 pm](https://cloud.githubusercontent.com/assets/2261329/10742817/82761c96-7c05-11e5-83bb-657c516983ee.png)

**Comment by ejeschke** [comment]
@hcferguson, are you running with an Anaconda python distribution?

**Comment by hcferguson** [comment]
@ejeschke Yes.

**Comment by pllim** [comment]
@hcferguson, would be useful if you could paste the output of your `conda list` command here.

**Comment by hcferguson** [comment]
Here's condo list for my laptop

'''
Henrys-MacBook-Pro:~ hcferguson$ conda list
# packages in environment at /Users/hcferguson/anaconda:
#
_license                  1.1                      py27_0  
abstract-rendering        0.5.1                np19py27_0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.3.0                np19py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               0.8.9                    py27_0  
astropy                   1.0.3                np19py27_0  
babel                     1.3                      py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.9.0                np19py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.8.0                     <pip>
blaze-core                0.8.0                np19py27_0  
blz                       0.6.2                np19py27_1  
bokeh                     0.9.0                np19py27_0  
boto                      2.38.0                   py27_0  
bottleneck                1.0.0                np19py27_0  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
cffi                      1.1.0                    py27_0  
clyent                    0.3.4                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     3.16.0                   py27_0  
conda-build               1.14.1                   py27_0  
conda-env                 2.4.1                    py27_0  
configobj                 5.0.6                    py27_0  
cryptography              0.9.1                    py27_0  
curl                      7.43.0                        0  
cython                    0.22.1                   py27_0  
cytoolz                   0.7.3                    py27_0  
datashape                 0.4.5                np19py27_0  
decorator                 4.0.2                    py27_0  
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
emcee                     2.1.0                     <pip>
enum34                    1.0.4                    py27_0  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
freetype                  2.5.2                         2  
funcsigs                  0.4                      py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
ginga                     2.5.20151022033143           <pip>
glueviz                   0.5.1                np19py27_1  
greenlet                  0.4.7                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.5.0                np19py27_3  
hdf5                      1.8.15.1                      1  
idna                      2.0                      py27_0  
ipaddress                 1.0.7                    py27_0  
ipython                   3.2.0                    py27_0  
ipython-notebook          3.2.0                    py27_0  
ipython-qtconsole         3.2.0                    py27_0  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.8.1                    py27_0  
jinja2                    2.7.3                    py27_1  
jpeg                      8d                            1  
jsonschema                2.4.0                    py27_0  
launcher                  1.0.0                         3  
libdynd                   0.6.5                         0  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvmlite                  0.5.0                    py27_0  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_3  
mistune                   0.5.1                    py27_1  
mock                      1.0.1                    py27_0  
multipledispatch          0.4.7                    py27_0  
networkx                  1.10                     py27_0  
nltk                      3.0.3                np19py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_0  
numba                     0.19.1               np19py27_0  
numexpr                   2.4.3                np19py27_0  
numpy                     1.9.2                    py27_0  
odo                       0.3.2                np19py27_0  
openpyxl                  1.8.5                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py27_0  
patsy                     0.3.0                np19py27_0  
pep8                      1.6.2                    py27_0  
pillow                    2.9.0                    py27_0  
pip                       7.1.0                    py27_1  
ply                       3.6                      py27_0  
psutil                    2.2.1                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.27                   py27_0  
pyasn1                    0.1.7                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.14                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_2  
pyflakes                  0.9.2                    py27_0  
pygments                  2.0.2                    py27_0  
pyopenssl                 0.15.1                   py27_1  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_0  
pytables                  3.2.0                np19py27_0  
pytest                    2.7.1                    py27_0  
python                    2.7.10                        0  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.6                         3  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.7.0                    py27_0  
rope                      0.9.4                    py27_1  
runipy                    0.1.3                    py27_0  
runstats                  0.5.3                     <pip>
scikit-image              0.11.3               np19py27_0  
scikit-learn              0.16.1               np19py27_0  
scipy                     0.16.0               np19py27_1  
setuptools                18.0.1                   py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
snowballstemmer           1.2.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
specview                  0.2.dev383                <pip>
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.5.2                  py27_0  
spyder-app                2.3.5.2                  py27_0  
sqlalchemy                1.0.5                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1                np19py27_0  
sympy                     0.7.6                    py27_0  
tables                    3.2.0                     <pip>
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py27_0  
tornado                   4.2                      py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.9.4                    py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.24.0                   py27_0  
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.7.3                    py27_0  
xlwings                   0.3.5                    py27_0  
xlwt                      1.0.0                    py27_0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
'''

**Comment by hcferguson** [comment]
Here is conda list for my desktop. 

````
ferguson% source Docondasetup 
Fetching package metadata: ....
Solving package specifications: ................
# All requested packages already installed.
# packages in environment at /Users/ferguson/anaconda:
#
tk                        8.5.13                        1  
[ssbx-osx] [planxty:~] ferguson% conda list
# packages in environment at /Users/ferguson/anaconda:
#
_license                  1.1                      py27_0  
abstract-rendering        0.5.1                np19py27_0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.3.0                np19py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               0.8.9                    py27_0  
astropy                   1.0.3                np19py27_0  
babel                     1.3                      py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.9.0                np19py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.8.0                     <pip>
blaze-core                0.8.0                np19py27_0  
blz                       0.6.2                np19py27_1  
bokeh                     0.9.0                np19py27_0  
boto                      2.38.0                   py27_0  
bottleneck                1.0.0                np19py27_0  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
cffi                      1.1.0                    py27_0  
clyent                    0.3.4                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     3.18.3                   py27_0  
conda-build               1.14.1                   py27_0  
conda-env                 2.4.2                    py27_0  
configobj                 5.0.6                    py27_0  
cryptography              0.9.1                    py27_0  
curl                      7.43.0                        0  
cython                    0.22.1                   py27_0  
cytoolz                   0.7.3                    py27_0  
datashape                 0.4.5                np19py27_0  
decorator                 3.4.2                    py27_0  
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
emcee                     2.1.0                     <pip>
enum34                    1.0.4                    py27_0  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
freetype                  2.5.2                         2  
funcsigs                  0.4                      py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
ginga                     2.5.20151022033143           <pip>
greenlet                  0.4.7                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.5.0                np19py27_3  
hdf5                      1.8.15.1                      1  
idna                      2.0                      py27_0  
ipaddress                 1.0.7                    py27_0  
ipython                   3.2.0                    py27_0  
ipython-notebook          3.2.0                    py27_0  
ipython-qtconsole         3.2.0                    py27_0  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.8.1                    py27_0  
jinja2                    2.7.3                    py27_1  
jpeg                      8d                            1  
jsonschema                2.4.0                    py27_0  
launcher                  1.0.0                         3  
libdynd                   0.6.5                         0  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvmlite                  0.5.0                    py27_0  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_2  
mistune                   0.5.1                    py27_1  
mock                      1.0.1                    py27_0  
multipledispatch          0.4.7                    py27_0  
networkx                  1.9.1                    py27_0  
nltk                      3.0.3                np19py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_0  
numba                     0.19.1               np19py27_0  
numexpr                   2.4.3                np19py27_0  
numpy                     1.9.2                    py27_0  
odo                       0.3.2                np19py27_0  
openpyxl                  1.8.5                    py27_0  
openssl                   1.0.2d                        0  
pandas                    0.16.2               np19py27_0  
patsy                     0.3.0                np19py27_0  
pep8                      1.6.2                    py27_0  
pillow                    2.8.2                    py27_0  
pip                       7.1.2                    py27_0  
ply                       3.6                      py27_0  
psutil                    2.2.1                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.27                   py27_0  
pyasn1                    0.1.7                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.14                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_2  
pyds9                     1.2                       <pip>
pyflakes                  0.9.2                    py27_0  
pygments                  2.0.2                    py27_0  
pygoods                   2.2                       <pip>
pyhm                      0.0.1                     <pip>
pyopenssl                 0.15.1                   py27_1  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_0  
pytables                  3.2.0                np19py27_0  
pytest                    2.7.1                    py27_0  
python                    2.7.10                        2  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.6                         3  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.8.1                    py27_0  
rope                      0.9.4                    py27_1  
runipy                    0.1.3                    py27_0  
scikit-image              0.11.3               np19py27_0  
scikit-learn              0.16.1               np19py27_0  
scipy                     0.15.1               np19py27_0  
setuptools                18.4                     py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
snowballstemmer           1.2.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.5.2                  py27_0  
spyder-app                2.3.5.2                  py27_0  
sqlalchemy                1.0.5                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1                np19py27_0  
subtract-background       1.0                       <pip>
sympy                     0.7.6                    py27_0  
tables                    3.1.1                     <pip>
terminado                 0.5                      py27_0  
tk                        8.5.13                        1  
toolz                     0.7.2                    py27_0  
tornado                   4.2                      py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.9.4                    py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.26.0                   py27_1  
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.7.3                    py27_0  
xlwings                   0.3.5                    py27_0  
xlwt                      1.0.0                    py27_0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by pllim** [comment]
Mine appears comparable on Linux.

**Comment by hcferguson** [comment]
Hmm....looking at the ginga script, it appears that it used ssbx on the install. Not sure how that happened. 

```
#!/Users/ferguson/ssbvirt/ssbx-osx/bin/python
#
# ginga -- astronomical image viewer and toolkit
#
"""
Usage:
    ginga --help
    ginga [options] [fitsfile] ...
"""
import sys
from ginga import main

if __name__ == "__main__":
    main.reference_viewer(sys.argv)
```

**Comment by hcferguson** [comment]
Nope...nevermind...I wasn't using the ssbx version in testing. I have been using the anaconda version, just hadn't set the environment in that window. The startup script for that is quite different. 
```
#!/Users/ferguson/anaconda/bin/python
# EASY-INSTALL-SCRIPT: 'ginga==2.5.20151022033143','ginga'
__requires__ = 'ginga==2.5.20151022033143'
__import__('pkg_resources').run_script('ginga==2.5.20151022033143', 'ginga')
```

**Comment by pllim** [comment]
After speaking offline with @hcferguson, my suspicion is that there are some mixed up in his paths:

* `PATH` has a mix of Anaconda, SSBX, `/sw/...`, `/usr/...`, and `/opt/...` directories.
* `LD_LIBRARY_PATH` is not explicitly set to use Anaconda libraries.
* `PYTHONPATH` does not explicitly set to use Anaconda packages first.

My recommendation is to clear up the above first, and see if the problem goes away.

**Comment by pllim** [comment]
@hcferguson reported that the problem "magically" disappeared.
