### ISSUE TITLE
Any special drawing facilities that work in WCS spaces?

### ISSUE THREAD

**Issue by stscieisenhamer** [ejeschke/ginga#194]

**Comment by pllim** [comment]
@stscieisenhamer , if you open the `Drawing` plugin, you can select "Coord type" to be "data" or "wcs", so I think the answer is yes.

**Comment by stscieisenhamer** [comment]
Which leads to the drawing parameter 'coord' = 'data' | 'wcs'

Thanks! Will leave open to see if there is more to be said on this.

**Comment by pllim** [comment]
It is set in `ginga/canvas/DrawingMixin.py`:
```python
crdmap = viewer.get_coordmap(crdtype)
```
The actual implementation appears to be in `ginga/canvas/coordmap.py`.

**Comment by ejeschke** [comment]
As you figured out, it's the `coord` keyword.  This functionality is somewhat new in ginga, meaning not tested as thoroughly as some other features.

**Comment by stscieisenhamer** [comment]
Thanks and thanks! Will be testing, as soon as the meetings are over...
