### ISSUE TITLE
match->WCS and lock->WCS functionality

### ISSUE THREAD

**Issue by hcferguson** [ejeschke/ginga#197]
This may be a documentation problem, but I haven't yet figured out how to lock images together by WCS so that I can step through a stack of them and have them be aligned even if they have different WCS's.

I thought that the Pan settings in Preferences (within a single channel) would do this if I chose WCS, but that didn't work for me. That is perhaps a bug? 

Ideally, I think this functionality would be needed between channels if the way the color-cuts work isn't changed, because in my fairly common use case I need different color cuts for the different images and when I put them within a single channel I don't have the option to give them different cuts (or at least haven't figured that out).

**Comment by ejeschke** [comment]
@hcferguson, you'll have to elaborate just a little for me.  When you say "align", do you mean to match scale, rotation and distortion as well as pan position, or just pan position according to wcs?  The former is not implemented (although it might be a fairly easy plugin for someone familiar with the astropy `reproject` module).  

The latter ought to work, once a pan position is established in wcs coordinates, and assuming that you have turned the autocenter feature to "off" (Under "New Images" in `Preferences`, set "Center New").  Keep in mind that issue #191 has not been fixed, so you might need to use the "WCS sexagesimal" checkbox.  A value of "once" or "override" might also be appropriate for autocentering (if "once" then the first image loaded will be centered, if "override" then they will continue to be centered until you set a pan position).

**Comment by ejeschke** [comment]
When you say "different color cuts", do you mean that you have set different cut levels for each image, or that you have changed the color map for each image?

**Comment by hcferguson** [comment]
@ejeschke I meant different cut levels.

**Comment by hcferguson** [comment]
@ejeschke I meant the functionality of ds9 ```Frame->Match->Frame->WCS``` or ```Frame->Lock->Frame->WCS```. I don't know if these handle distortions, but for frames that have a good WCS, these will ensure that the sources generally line up even if the pixel scales, centers and orientations on the sky are different.

**Comment by ejeschke** [comment]
It might be good to separate the issue of the cuts vs. the reprojection/alignment.  

Regarding maintaining the cuts values, if I choose "Save Cuts" under the "Remember" preferences then it saves any cut levels I apply to an image and restores those to the image when I view it again. At any time while viewing an image with saved cut levels I can manually or automatically set the cuts and they will be resaved into the image.   It sounds like this is the behavior you are looking for?  Xref issue #179 

Regarding the reprojection/realignment of various images to match a reference image, I think this sounds not too hard, but I think I need to consider whether it goes in as a plugin, as a built-in in the reference viewer, or as a feature of the basic widget.  Leaning toward a plugin as this offers the easiest path for users to customize.

**Comment by ejeschke** [comment]
Sorry, misspoke above in regard to one item: when "Save Cuts" is used, currently only manually adjusting the cuts levels will resave them to the image.  If you do an "Auto Levels" on an image it will adjust the cuts automatically, but they are not saved unless you *then* press "Cut Levels"

**Comment by hcferguson** [comment]
@ejeschke I put a movie of my workflow in ds9 at https://trello.com/c/mk77Ejyd/53-equivalent-of-ds9-frame-lock-frame-wcs

**Comment by ejeschke** [comment]
@hcferguson, I made an example plugin that implements WCS match/lock.  I made a movie showing how it works.  Is it possible for me to attach that to your Trello card?

**Comment by ejeschke** [comment]
@pllim, @hcferguson , I've uploaded the example movie to @pllim's "Ginga-dev" Box account, along with a README.  Check it out and let me know what you think.

**Comment by ejeschke** [comment]
I've added this plugin in commit d2bd67fdfb30278c76a8726d2ac1d657f74d3dc9.  It is marked as experimental in the plugin documentation.  You can access it from "Plugins"->"WCSMatch". Please let me know your feedback.

**Comment by pllim** [comment]
@ejeschke , thanks for the video demo! :+1:  @stscieisenhamer , what do you think?

**Comment by pllim** [comment]
@ejeschke , I get the following traceback:
```python
2015-11-12 12:10:50,564 | E | QtMain.py:116 (update_pending) | gui error: 'ref_channel'
2015-11-12 12:10:50,579 | E | QtMain.py:120 (update_pending) | Traceback:
  File ".../ginga-2.5.20151112024614-py2.7.egg/ginga/qtw/QtMain.py", line 111, in update_pending
    res = future.thaw(suppress_exception=False)
  File ".../ginga-2.5.20151112024614-py2.7.egg/ginga/misc/Future.py", line 36, in thaw
    res = self.method(*self.args, **self.kwdargs)
  File ".../ginga-2.5.20151112024614-py2.7.egg/ginga/misc/plugins/WCSMatch.py", line 131, in _reset_channels_gui
    self.w.ref_channel.clear()
  File ".../ginga-2.5.20151112024614-py2.7.egg/ginga/misc/Bunch.py", line 217, in __getattr__
    return self.tbl[attr]
```

**Comment by stscieisenhamer** [comment]
Basic tests work :+1:

**Comment by ejeschke** [comment]
@pllim, just pushed an update.  Does this fix the stack trace you are seeing?

**Comment by ejeschke** [comment]
@stscieisenhamer , good to hear.  Would be interested to hear how your workflow goes with this approach.

**Comment by pllim** [comment]
@ejeschke , yes, ed07506 fixed the problem. Thank you!

**Comment by stscieisenhamer** [comment]
@ejeschke Actually, I think the immediate issue is the one @hcferguson had brought up: that you have key shortcuts to rotate through images in a channel, but not through channels. This may have been resolved (or has a resolution). WRT the MultiImage relies on rotating images in a channel, though manly as convenience. If moving through images in channel space is as easy as within channel space, then there should be no issue. The MultiImage plugin currently is channel agnostic, though there should be an issue to remind me to think about this.

**Comment by ejeschke** [comment]
@stscieisenhamer , it should certainly be easy enough to make shortcut keys to rotate through the channels--I'll look at that.

**Comment by ejeschke** [comment]
Commit 909a647b718b64c280a535713eccdae06b2e8470 adds support for moving between channels using the left/right arrow keys.  If you press the up/down arrow keys it will cycle through the images in the channel.  I think it makes sense.  Give it a try.

Caveats:
- doesn't yet work with individual (sub) workspaces, only with the main workspace

I think longer term we need to find good key bindings for laptops that don't have arrow keys.  Of course it should be possible to customize the bindings, but I think there should be reasonable defaults if this is generally useful.  Also, the GUI needs to be updated so that the left/right current arrows get mapped to the new functionality and we add up/down arrows.  Let em know what you think.

**Comment by pllim** [comment]
@ejeschke , "left" and "right" works. But...

1. "up" and "down" do not work. I can no longer cycle through images in the same channel (Qt).
2. Also, please comment out the print statements in `Control.py`.

Thanks!

**Comment by ejeschke** [comment]
Commit 4d30be58adcae485ee765b8ef72290c01122765d fixes #2 and adds up/down buttons to the `Toolbar` plugin.  The channel navigation is still based on temporal load history, which I realize is not intuitive when you are referring to alpha-sorted `Contents` and `Thumbs` panes.  I'm working on an update for this, which I will submit as a PR for testing and comment.

@pllim, if up/down arrow keys are not doing anything when you have several images in the channel then it may be the keys on your keyboard/platform are generating some sort of keysym that ginga is not recognizing.  If so, let's open a separate issue for that.  It will be fairly easy to debug following the log messages.

**Comment by pllim** [comment]
@ejeschke , okay, I opened #225.

**Comment by pllim** [comment]
Also, addressing the non-intuitive channel navigation would fix #119 as well.

**Comment by pllim** [comment]
c/c @larrybradley who is also interested in this feature.

**Comment by pllim** [comment]
`WCSMatch` has been implemented some time ago.
