### ISSUE TITLE
Testing new Crosshair canvas type and plugin

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#199]
There is a new canvas type called "crosshair", which, not surprisingly, renders a crosshair on the ginga canvas.  There is a new plugin for the reference viewer that uses it, called "Crosshair".  

Requesting feedback.

**Comment by ejeschke** [comment]
ping @pllim, @stscieisenhamer, @hcferguson

**Comment by pllim** [comment]
@ejeschke, seems to work in both `Crosshair` (only single crosshair possible) and `Drawing` (multiple ones possible).

How do you envision this to be used? It is nice, but it tells me nothing new that I cannot already see on the info bar at the bottom of the image display.

**Comment by pllim** [comment]
If `Crosshair` were to be a permanent plugin, we might also consider:

* Adding a `plugin_Crosshair.cfg` file to set user preferences for, say, default color and format.
* Adding additional GUI to adjust its parameters like color, line width, line style, and maybe even font size.
* Not sure if this will overcomplicate things but some users might ask for it: Allowing multiple crosshairs, like in `Drawing`?

**Comment by ejeschke** [comment]
@pllim, I envision a couple of use cases. One is when examining some detail in an image it is useful to be able to see the coordinates or the data value without moving your eye too far away from the point of interest--the distraction of looking to the readout and back becomes greater with some really high resolution displays that we have these days.  It can also be used as a kind of "straight edge" to see features that roughly line up in a plane, etc.

**Comment by ejeschke** [comment]
Yeah, preferences would be nice.  I added it mostly for a specific use case we have, but I think it may be handy in custom plugins or non-reference viewer apps because programmatically you can also set the text easily to whatever you want.

**Comment by ejeschke** [comment]
Crosshair has been in a while.  Closing this issue.
