### ISSUE TITLE
How to directly open multi-ext FITS with non-default ext?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#201]
This was brought up during a sprint involving @hcferguson, @gderosa2004, @eteq, @perrygreenfield, @stscieisenhamer, and myself.

Let's say we have an image named `image01.fits` with the following multi-extension FITS layout:

Ext. Num. | EXTNAME | EXTVER
------ | ------ | ------
0 | PRIMARY | --
1 | SCI | 1
2 | ERR | 1
3 | DQ | 1
4 | SCI | 2
5 | ERR | 2
6 | DQ | 2

And the user wishes to open extension 4 directly. With DS9, there are two ways to do this (that I actually used, could  be more):

* Via PyRAF/IRAF: 
```
--> !ds9 &
--> display image01.fits[4] 1
```

* Via DS9 GUI:
```
File -> Open -> Click on the filename -> Manually append "[4]" to the name -> OK
```

I have yet found such shortcut in Ginga without having to load the default extension first (e.g., `[SCI,1]`) and then use the `MultiDim` plugin. I tried passing in `image01.fits[4]` via command line, using `File -> Open`, and `FBrowser`; None of those let me open extension 4 directly.

**Comment by ejeschke** [comment]
Did you try it from the command line?  e.g. 
```bash
$ ginga foo.fits[1]
```

**Comment by pllim** [comment]
Yes, I did. I get an error:
```
ginga: No match.
```

**Comment by ejeschke** [comment]
I was able to do it by quoting the brackets, because depending on your shell (e.g. `bash`) they are special characters.  For example, if I do:
```bash
$ ginga .../testdata/HST/"iaby02x7q_flt.fits[4]"
```
it does just what you would expect.  You can probably also use backslash to escape the brackets.

**Comment by ejeschke** [comment]
The `load_file` method in ginga does parse the HDU extension syntax, so it's simply a matter of getting the path with the "[...]" bits on the end in to that function.   I think it is also supported by drag and drop if the URL happens to have the syntax at the end.

Probably we should modify the file open dialog and the `FBrowser` plugin to allow you to specify the HDU extension.

**Comment by pllim** [comment]
Ah, okay. I can confirm that this also works:
```
ginga "image01.fits[4]"
ginga image01.fits\[4\]
```

Yes, would be nice for `FBrowser` to support this, if possible.

**Comment by ejeschke** [comment]
Remote control also works.  Be sure to invoke the "RC" plugin from the "Plugins" menu, then:
```bash
grc ginga load_file testdata/HST/"iaby02x7q_flt.fits[4]"
```

Type
```bash
$ grc help
```
to get a brief help message for using the remote feature.

**Comment by pllim** [comment]
I'll see if I can get a prototype PR in today.

**Comment by pllim** [comment]
This is now possible in Qt, which effectively closes this issue for  @hcferguson, @gderosa2004, @eteq, @perrygreenfield, and @stscieisenhamer , as per the STScI Sprint.
