### ISSUE TITLE
WCS problems

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#205]
"Issue reading WCS coordinates" as stated by @gderosa2004 in spacetelescope/stginga#19.

**Comment by ejeschke** [comment]
Ginga does not implement it's own wcs, but forwards all wcs handling to one of the supported wcs packages.  When reporting wcs problems, it is important to know which wcs package was used. Please set your desired WCS package as described in the [FAQ](http://ginga.readthedocs.org/en/latest/FAQ.html) under "What library are you using for WCS?".

If the package you are using creates the WCS fine in isolation (e.g. from the command line), the problem probably lies with the interface between ginga and the package.  For debugging these issues it is very important to have a FITS file that can reproduce the error that can be made available for testing.

**Comment by pllim** [comment]
@ejeschke, I think she used the same image that was mentioned in #203. She was trying to draw a compass via the `Drawing` plugin but was unsuccessful because of bad WCS. She claimed that she had no problem seeing the compass in DS9.

In my own test with DS9 (screenshot attached below), I find that DS9 also cannot read the WCS, but it draws a compass anyway that goes along X and Y axes. Feel free to correct me if your experience with DS9 is different, @degrosa2004.

![untitled](https://cloud.githubusercontent.com/assets/2090236/10852826/4d1f3b98-7f09-11e5-8786-6146d623ad87.png)

**Comment by gderosa2004** [comment]
The image is different - it is in the repo folder wcs_issue. 
We've found out that the image does not have WCS keywords in the header. ds9 reads RA, DEC & scale plate, assumes an orientation and gives an estimate of RA & DEC over the full image.

**Comment by pllim** [comment]
Ah, okay. I apologize for the confusion, @gderosa2004. I emailed you the data file, @ejeschke .

```python
>>> from astropy.io import fits
>>> pf = fits.open('osmos110326.0013.xof.fits')
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
MISFILT                        / MIS Filter Number                               [astropy.io.fits.card]
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
MISFLTID                       / MIS Filter ID                                   [astropy.io.fits.card]

>>> pf.info()
Filename: osmos110326.0013.xof.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU      85   (4064, 4064)   float32   

>>> pf[0].header
SIMPLE  =                    T / Written by IDL:  Sat Nov 26 15:59:21 2011      
BITPIX  =                  -32 /                                                
NAXIS   =                    2 /                                                
NAXIS1  =                 4064 /                                                
NAXIS2  =                 4064 /                                                
BSCALE  =                    1 / PHYSICAL=INTEGER*BSCALE+BZERO                  
BZERO   =                    0 /                                                
GROUP   =                    0 /                                                
COMMENT  Detector Information                                                   
DETECTOR= 'STA0500A ITL5339'   / Detector name                                  
GAINDL  =                   32 / Pixel integration time, in sequencer clocks    
PIXITIME=            9.9000E-6 / Pixel integration time, in seconds             
CCDXBIN =                    1 / CCD X-axis Binning Factor                      
CCDYBIN =                    1 / CCD Y-axis Binning Factor                      
OVERSCNX=                   32 /                                                
OVERSCNY=                    0 /                                                
READOUT = 'ARLBRL  '           / Amplifiers used in readout                     
COMMENT  Observatory Information                                                
OBSERVAT= 'MDM     '           / Observatory name                               
TELESCOP= '2.4m Hiltner'       / Telescope name                                 
INSTRUME= 'OSMOS   '           / Instrument name                                
OBSLONG =           111.615556 / Site Longitude [deg W]                         
OBSLAT  =            31.951389 / Site Latitude [deg N]                          
OBSELEV =               1938.5 / Site Elevation [meters]                        
OBSERVER= 'Calvet  '           / Observer Name(s)                               
COMMENT  Exposure Information                                                   
IMAGETYP= 'OBJECT  '           / Type of observation                            
OBJECT  = 'NGC2748 '           / Name of object                                 
EXPTIME =                240.0 / Exposure time [seconds]                        
DARKTIME=               242.27 / Cumulative Dark Time [seconds]                 
LEDFLASH=            0.0000E+0 / Time to flash lab LEDs [seconds]               
FILENAME= 'osmos110326.0013'   / filename to be written to                      
UNIQNAME= '0210114K.049'       / Unique filename; if filename is invalid        
ACQTAG  = 'OSMOS.20021013063343' / Unique Acquisition ID Tag                    
DATE-OBS= '2011-03-27'         / UTC Date at start of obs                       
TIME-OBS= '02:48:31.335'       / UTC Time at start of obs                       
TIMESYS = 'UTC     '           / Time System                                    
JD      =       2455647.617029 / Julian Date at start of obs                    
MJD     =         55647.117029 / Modified JD=JD-2400000.5                       
COMMENT  OSMOS Configuration                                                    
SLIT    =                    3 / Slit Wheel Position                            
SLITID  = 'Open    '           / Slit ID                                        
FILTER1 =                    1 / Filter Wheel #1 Position                       
FILTID1 = 'SDSS r  '           / Filter1 ID                                     
FILTER2 =                    5 / Filter Wheel #2 Position                       
FILTID2 = 'Open    '           / Filter2 ID                                     
DISPPOS =                    2 / Disperser Wheel Position                       
DISPID  = 'Open    '           / Disperser ID                                   
CAMFOC  =               5800.0 / Camera Focus Position [microns]                
COLFOC  =               2300.0 / Collimator Focus Position [microns]            
COMMENT  OSMOS Housekeeping Information                                         
IEBTEMP =                 12.6 / IEB Box Air Temperature [deg C]   
AIRTEMP =                 10.4 / Instrument Air Temperature [deg C]             
OBTEMP  =                  9.6 / Optical Bench Temperature [deg C]              
AMBTEMP =                  8.1 / Outside Ambient Air Temperature [deg C]        
COMMENT  TCS Information                                                        
TCSLINK = 'Active  '           / TCS Communications Link Status                 
RA      = '09:13:44'           / Telescope RA                                   
DEC     = '+76:28:30'          / Telescope DEC                                  
HA      = '-01:36:10'          / HA at start of obs                             
LST     = '07:38:50'           / LST at start of obs                            
ZD      =                45.91 / Zenith Distance at start of obs                
SECZ    =                 1.44 / Secant of ZD at start of obs                   
COMMENT  MIS Information                                                        
MISFILT                        / MIS Filter Number                              
MISFLTID                       / MIS Filter ID                                  
GPROBEX =                 2156 / MIS Guide Probe X                              
GPROBEY =                 4407 / MIS Guide Probe Y                              
MIRROR  = 'OUT     '           / MIS Pickoff Mirror Position                    
LAMPS   = 'OFF     '           / MIS Calibration Lamps                          
COMMENT                                                                         
ROTANGLE=                -2.36 /                                                
TELFOCUS=                 4159 /                                                
EQUINOX =               2000.0 /                                                
BIASSEC1= '[1:32,1:2032]'      / Amp1 Bias Section                              
BIASSEC2= '[4097:4128,1:2032]' / Amp2 Bias Section                              
BIASSEC3= '[1:32,2033:4064]'   / Amp3 Bias Section                              
BIASSEC4= '[4097:4128,2033:4064]' / Amp4 Bias Section                           
DATASEC1= '[33:2064,1:2032]'   / Amp1 Data Section                              
DATASEC2= '[2065:4096,1:2032]' / Amp2 Data Section                              
DATASEC3= '[33:2064,2033:4064]' / Amp3 Data Section                             
DATASEC4= '[2065:4096,2033:4064]' / Amp4 Data Section                           
TRIMSEC = '[33:4096,1:4064]'   / Trim Section                                   
SECPIX  =             0.273000 / Arcsec per Pixel                               
EPOCH   =                 2000 /                                                
```

DS9 does indeed display WCS, as shown below:
![untitled](https://cloud.githubusercontent.com/assets/2090236/10853802/73e8d860-7f0e-11e5-8668-5babed5cd3ce.png)

In Ginga, I tried all the possible WCS options in `~/.ginga/general.cfg` below; None of them worked:
```
#WCSpkg = 'choose'
#WCSpkg = 'astlib'
#WCSpkg = 'kapteyn'
#WCSpkg = 'starlink'
WCSpkg = 'astropy'
#WCSpkg = 'astropy2'
#WCSpkg = 'barebones'
```

I also tried loading the WCS directly in Python via `astropy.wcs`. That did not work either.

**Comment by pllim** [comment]
Update: @ejeschke , the file is too large to attach in email, so I put it on Box. You should have a separate email on how to access it. If not, please let me know. Thanks!

**Comment by ejeschke** [comment]
@pllim, this is good to know.  Unless `astropy.wcs` could pick up a fix for this (which is probably not wise, the file is fundamentally broken if wcs keywords are missing), the only thing I can recommend is to try to fix up the keywords *before* ginga creates the astropy WCS in `wcsmod`.  We had a case for doing something like this at Subaru (although not for bad WCS, just to prevent `astropy.io.fits` warnings) and there is a function called `fix_bad_headers` in `wcsmod`.  Something like this could be used to calculate and add the necessary keywords to make a working wcs.

**Comment by gderosa2004** [comment]
@ejeschke what about a similar fix as ds9 but issuing a warning to the user? Sometimes even though the astrometry is not completed having an idea of where you are in the field can still be useful.

**Comment by pllim** [comment]
@ejeschke, yes, that seems like a good place to place a fix in.

@gderosa2004, do you know the correct WCS keywords/values to use for this case? I don't know much about WCS and I don't know how DS9 extracted those WCS values it is showing.

**Comment by ejeschke** [comment]
It would be useful to figure out a way to "fingerprint" certain types of FITS files to be able to fix up the headers in them before creating the WCS.  That way the fixes could be very precisely applied.  You might discuss this in your meeting today.  Maybe @eteq, @embray or @nden would be able to inform the approach.

**Comment by embray** [comment]
I don't understand the context to this so maybe this is off topic, but when it comes to "fingerprinting certain types of FITS files" that was partly the idea behind FITS Schema: http://embray.github.io/PyFITS/schema/users_guide/users_schema.html

**Comment by eteq** [comment]
That may well make sense, but it also might be overkill because my impression is that most of the failure modes this was about are the sort of failure along the lines of "FITS files from instrument x at telescope y taken in setup z are messed up in this particular way".  So a formal schema validation may be a lot of work for a fairly limited payoff.  I wonder if there should just be a registry of functions/classes that are run only if the WCS fails.  So it would go through the list, and if any of them match, run a function to "fix up" the WCS object seen by ginga.

**Comment by ejeschke** [comment]
I'm open to any approaches, but I was thinking along the lines of what @eteq is describing.  It might be a bit like the observatory list in `astroplan`, where an observatory or institution could add some keywords to a simple file registry for "known broken" instrument FITS files.  If the FITS file has those keywords with those values it would apply a simple "fix-up" function, also supplied when the fingerprint was added to the registry.

Some keywords I can imagine using to establish the fingerprint might include: `OBSERVAT`, `TELESCOP` and `INSTRUME`, among others.

**Comment by pllim** [comment]
After discussions with @nden and @ejeschke at Python in Astronomy 2016, it is decided that non-standard WCS standards are not Ginga's problem nor JWST's problem. Therefore, it needs external resources to actually implement Python interpreters for those standards in question.
