### ISSUE TITLE
Qt signals: anything special?

### ISSUE THREAD

**Issue by stscieisenhamer** [ejeschke/ginga#209]
Question: Do Qt signals have any wrappers or otherwise special treatment? Besides the CallBacks, would there be any other abstraction on any of the UI toolkit events.  I'm looking to key off of window resize events to resize/re-zoom image view.

**Comment by ejeschke** [comment]
@stscieisenhamer, you can register for the callback "configure":
```python
fitsimage.add_callback('configure', window_resized_cb)

def window_resized_cb(fitsimage, width, height):
    ...
```

**Comment by stscieisenhamer** [comment]
This does it! thanks!
