### ISSUE TITLE
edit_cb: know which handles were used?

### ISSUE THREAD

**Issue by stscieisenhamer** [ejeschke/ginga#212]
Is it possible in the edit callback for an object, to know which handle has used: either moving from the center handle, or resizing had occured?

**Comment by ejeschke** [comment]
@stscieisenhamer, I believe there is no information in the edit callback about that.  That callback is fairly new and not widely used, I guess, so it might be possible to add that information.  But perhaps there is a different possibility be querying the canvas.  Can you elucidate the use-case?

**Comment by stscieisenhamer** [comment]
For me, more of just a convenience. If I know the size of the object hasn't changed, just position, it saves some calculation. In my case, some extra WCS calculation.

**Comment by pllim** [comment]
It is possible to track the object properties yourself and then compare within your own `edit_cb()` method. Maybe something like:
```python
def edit_cb(self, canvas, obj):
    # pseudo-code, might not work, but you get the idea
    if obj.x == self._xcen and obj.y == self._ycen:
        self.logger.debug('object has not moved, no need to recalculate')
        return True
```

**Comment by ejeschke** [comment]
This might be the easiest thing to do.  To simplify, you could make use of the `data` attribute of a `CanvasObject` (all objects that you place on a ginga canvas has this as a base class).  You could set the `xcen`/`ycen` in the data like so:
```python
obj.set_data(xcen=obj.x, ycen=obj.y)
```
and later check it after an edit:
```python
if obj.x != obj.data.xcen or obj.y != obj.data.ycen:
    ...
```

**Comment by stscieisenhamer** [comment]
@pllim Yep, that was doing anyways. Was just wondering how detailed the events were.

Thanks all!
