### ISSUE TITLE
Add "Modified" column to Contents

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#215]
I see that Ginga as a `'modified'` callback. I propose that `Contents` adds a new column at the end named "Modified", which would change from "no" to "yes" when an image issues the aforementioned callback. What do you think, @ejeschke? If you agree, I can attempt a PR since I already have something similar going on in my subclass. Please let me know.

**Comment by ejeschke** [comment]
There are more than one `modified` callbacks.  There is one issued by an `AstroImage` class object to indicate that the file has been modified in memory (but not on disk).  This is not typically done by most plugins that I know of.  

There is a `modified` issued by a canvas to indicate that a redraw is necessary for any viewers looking at that canvas.

Are you thinking of the first case?  Do you have a plugin that modifies the image's data and resets it using `set_data`?

**Comment by pllim** [comment]
> the file has been modified in memory (but not on disk)

Yes, that one.

> Do you have a plugin that modifies the image's data

Yes, I have multiple.

**Comment by pllim** [comment]
Currently, I manually set the status by directly accessing the subclassed `Contents` plugin method. But since you already have such a callback, I thought it would be more elegant to use the callback. And there is no reason not to include in core to show that Ginga already support such a thing?

**Comment by ejeschke** [comment]
I have no objections.  I would keep in mind that 1) it is possible for an image to be in more than one channel at a time, and 2) image names are not necessarily unique.  AFAIK, the `modified` callback comes from the image directly, with no information about which channel it is in, so that might complicate figuring out which contents entries to modify.

How about instead adding a modification time (`time.time()`) to the image object itself and showing that in the `Contents`? That certainly would be easier, and very accurate.

**Comment by pllim** [comment]
Hmm. Modification time tells me nothing unless I can somehow memorize all the original mod times and mentally compute whether it has changed. However, if you are saying that we can use modification time as a basis to decide whether the status is "yes" or "no", then it works for me.

**Comment by ejeschke** [comment]
If you set the initial modification time of the image to `None`, then in the column you could show "no" or if modified, the time.

**Comment by pllim** [comment]
Yes, that sounds great! :+1:

**Comment by pllim** [comment]
@ejeschke , I started a prototype at #223 but it needs some help.

**Comment by pllim** [comment]
This is resolved.
