### ISSUE TITLE
get_channelName() returns incorrect channel name

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#218]
I have channel named "Image" and I want to programmatically add another image to the same channel using my plugin like this:
```python
chname = self.fv.get_channelName(self.fitsimage)
chinfo = self.fv.get_channelInfo(chname)
chinfo.datasrc[my_image_key] = my_image_obj
```

This used to work but now does not work anymore because `get_channelName()` returns "image" (all lowercase) instead of "Image" (capitalized), so my new image is in the wrong channel.

**Comment by ejeschke** [comment]
@pllim, please use `self.fv.add_image(name, image, chname)` to add an image to the channel (use the `silent=True` kwarg if you don't want the channel to switch to it).  Using the `Datasrc` directly is probably going to cause some weird issues.  If you have a *lot* of images to add, use `bulk_add_image()`.

**Comment by pllim** [comment]
`silent=True` does not list the image under `Thumbs` nor `Contents`. Is this intentional?

**Comment by pllim** [comment]
Anyways, I managed to get it listed using `self.fv.advertise_image(...)` and I still have the same problem. See attached screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/2090236/11094437/d498bb82-885d-11e5-93b2-33b7e68d09d1.png)

**Comment by pllim** [comment]
I am able to temporary fix this (see below), but it is kind of hacky.
```python
chname = chname.capitalize()
```

**Comment by ejeschke** [comment]
@pllim, does commit e9fff458ece9f62a0ff92459444afff1f41a9df0 fix this for you?

**Comment by ejeschke** [comment]
`advertise_image` is good to use.  Are you trying to add an image to the channel without switching to it?

It's possible `silent=True` may not invoke the callback, which is probably why there is `advertise_image`.  Anyway, would be interested to hear a little more clearly what you are trying to do, maybe we can clean up the API a little.

**Comment by pllim** [comment]
> does commit e9fff45 fix this for you?

Yes. Thank you!

> Are you trying to add an image to the channel without switching to it?

Yes. `add_image(..., silent=True)` followed by `advertise_image(...)` works for me.
