### ISSUE TITLE
Missing channel in Workspace

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#222]
This can be recreated as follows:

1. Start Ginga, which will load the default "Image" channel.
2. Create a new channel by doing `Channel -> Add Channel`. This creates "Image1" channel.
3. Create a new workspace by doing `Workspace -> Add Workspace`. Click OK to accept default values.

Now the workspace only has 3 channels, although I was expecting 4. It is as if the second channel "stole" a channel from the workspace. See screenshot below.
<img width="601" alt="untitled" src="https://cloud.githubusercontent.com/assets/2090236/11129685/c6a9bafc-894e-11e5-8c77-ef5f788e2823.png">

**Comment by ejeschke** [comment]
Fixed in 9a9b3839ce77a8412105838509de940a49ba40ad.  Can you check, @pllim ?

Thanks!

**Comment by pllim** [comment]
You mean 08fa60c?

**Comment by pllim** [comment]
Yeah, I think it's fixed. Thanks!

**Comment by ejeschke** [comment]
Ok, this is fixed with a much better solution in commit 880fc13e3afc0bf0296f36165926c471b55b2958.  Ginga now also complains if you try to use a channel or workspace name that is already in use.

**Comment by pllim** [comment]
I think you meant commit cf6427e4, but yeah, the problem is gone. Thanks!
