### ISSUE TITLE
Blinking across channels, rather than blinking images in a channel

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#240]
@pllim, @stscieisenhamer, @hcferguson 

What do you think about changing the default of `Blink` to blink _across_ channels, or at least have the option (instead of blinking the images in a channel)?

**Comment by hcferguson** [comment]
I think having the option is pretty essential. My use case would be putting HST images in one channel, Spitzer images in another, Herschel in another, and stepping between them (not so much blinking as being able to easily step through them...generally matched in WCS). Another use case is a supernova search, but in that case they generally would have the same plate scale and color stretch.

**Comment by ejeschke** [comment]
@hcferguson, I'm thinking that `Blink` then becomes a global plugin.  I'm also wondering if it works kind of in tandem with `WCSMatch` whether the two plugins can be combined in one.  That way the GUI is all in one place.

@pllim, I think you were the one requesting the `Blink` originally.  Do you use it in its current incarnation?

**Comment by pllim** [comment]
I don't oppose to blinking across channels, but having an option to turn that feature off would be nice. Where do we draw the line though? Do you also want the option to only blink through *some* channels but not all?

> stepping between them (not so much blinking as being able to easily step through them...generally matched in WCS

@hcferguson , this is already addressed in 909a647 by @ejeschke (see #197)

> Do you use it in its current incarnation?

@ejeschke , yes. My work that requires it right now only uses one channel, so blinking across the channel does not apply to me. Once I set `sort_order = 'alpha'` in `~/.ginga/channel_Image.cfg`, `Blink` works like a charm. Thank you! :+1:

**Comment by pllim** [comment]
c/c @larrybradley since he asked about this feature recently.

**Comment by pllim** [comment]
Implemented for some time already, closing.
