### ISSUE TITLE
AstropyWCS pixtocoords incompatible with Astropy 1.1RC2?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#250]
I have Astropy 1.1RC2 and the latest dev Ginga. I get traceback about `frameClass` when I load some of my images. I do not remember getting this before using the same image. Here is my manual attempt to recreate the traceback:

```python
>>> import logging
>>> from astropy import coordinates
>>> from astropy.io import fits
>>> from ginga.util import wcsmod
>>> logger = logging.getLogger()
>>> filename = 'ergS20071007S0122.fits'
>>> header = fits.getheader('ergS20071007S0122.fits', 2)
>>> wcsmod.use('astropy')  # Not astropy2!
>>> mywcs = wcsmod.WCS(logger)
>>> mywcs.load_header(header)
>>> mywcs.wcs
WCS Keywords

Number of WCS axes: 2
CTYPE : 'LINEAR'  'LINEAR'  
CRVAL : 5750.8999999999996  1.0  
CRPIX : 1109.0  1.0  
CD1_1 CD1_2  : -0.46354405531176002  0.0  
CD2_1 CD2_2  : 0.0  1.0  

>>> mywcs.pixtoradec([0, 1])
(6264.506813285429, 2.0)
>>> mywcs.pixtocoords([0, 1])
.../ginga-2.5.20151208223618-py2.7.egg/ginga/util/wcsmod.pyc in pixtocoords(self, idxs, system, coords)
    595         else:
    596             frameClass = coordinates.frame_transform_graph.lookup_name(self.coordsys)
--> 597             coord = frameClass(ra_deg * units.degree, dec_deg * units.degree)
    598             toClass = coordinates.frame_transform_graph.lookup_name(system)
    599             # Skip in input and output is the same (no realize_frame

TypeError: 'NoneType' object is not callable

>>> mywcs.coordsys
'pixel'
>>> coordinates.frame_transform_graph.lookup_name(mywcs.coordsys)

>>>
```

Somewhat related to #113 ?

**Comment by pllim** [comment]
c/c @eteq, @Cadair

**Comment by eteq** [comment]
@pllim - can you clarify whether or not this works with the dev ginga and astropy v1.0.x?

**Comment by pllim** [comment]
Now I get the error even with 1.0.6, and of course, the latest dev version.

It could be that I simply overlooked this error before, as I don't use this image often for testing...

**Comment by ejeschke** [comment]
I have this FITS file and I can verify that it "works" with astropy 1.0.2.  This is tangentially related to #105--which is how I received the file for testing.  With astropy 1.0.2, and wrapper "astropy" ginga reports the units in pixels. Wrappers "kapteyn" and "astropy2" do not work with this file. Interestingly, "starlink" does, but produces very different values.

**Comment by ejeschke** [comment]
@pllim, did you try to build a valid astropy WCS from the command line with this image?

**Comment by pllim** [comment]
@ejeschke - No, I am not familiar with the data enough to fix it. Also, I believe the correct issue is #205.

I still get the same error with `iris_l2_20151009_041433_3620263378_SJI_1330_t000.fits` data cube (forgot how I got it but it was from one of the Ginga issue threads).

```python
>>> filename = 'iris_l2_20151009_041433_3620263378_SJI_1330_t000.fits'
>>> header = fits.getheader(filename, 0)
>>> mywcs.wcs
WCS Keywords

Number of WCS axes: 3
CTYPE : 'HPLN-TAN'  'HPLT-TAN'  'Time'  
CRVAL : -0.0067637222222222222  0.088743333333333327  6249.5200000000004  
CRPIX : 925.5  546.5  100.0  
PC1_1 PC1_2 PC1_3  : 0.99999523162799997  0.011274402961099999  0.0  
PC2_1 PC2_2 PC2_3  : -0.011274402961099999  0.99999523162799997  0.0  
PC3_1 PC3_2 PC3_3  : 0.0  0.0  1.0  
CDELT : 4.6208333333333329e-05  4.6208333333333329e-05  63.125  
NAXIS    : 1850 1092

>>> mywcs.pixtocoords([0, 1, 0])
.../ginga-2.5.20151208223618-py2.7.egg/ginga/util/wcsmod.pyc in pixtocoords(self, idxs, system, coords)
    595         else:
    596             frameClass = coordinates.frame_transform_graph.lookup_name(self.coordsys)
--> 597             coord = frameClass(ra_deg * units.degree, dec_deg * units.degree)
    598             toClass = coordinates.frame_transform_graph.lookup_name(system)
    599             # Skip in input and output is the same (no realize_frame

TypeError: 'NoneType' object is not callable

```

**Comment by ejeschke** [comment]
I think you need the "astropy2" wrapper (and `sunpy`) to resolve the 'helioprojective' type--that was one of @Cadair's contributions.

**Comment by astrofrog** [comment]
Would it be worth adding a more explicit error if the frame lookup returns None?

**Comment by pllim** [comment]
Yes, explicit error message might reduce the confusion.

**Comment by ejeschke** [comment]
@astrofrog, it certainly should have a more visible result, I think.  Currently if the user's wcs package cannot build a WCS you just get a `None` internal wcs obejct in the wrapper (e.g. astropy.wcs throws an exception, we just set the `wcs` attribute to None).  This results in a "BAD WCS" message as you mouse around the image.

But people work with images with broken WCS *all the time*.  So I don't want some error message that is too "in your face".  Ultimately the solution is in something like suggested in #205, where the FITS header can be fixed up before trying to create the WCS.

**Comment by ejeschke** [comment]
If this is a broken WCS file I suggest closing the issue and adding a comment in #205 referring here.

**Comment by pllim** [comment]
I also just happen to grab the TWO files with unsupported `coordsys` back to back... What luck!

**Comment by pllim** [comment]
Okay. Thanks for the feedback. I'll submit a PR with a more graceful error message shortly.

**Comment by ejeschke** [comment]
Please don't submit a PR that requires the user to dismiss a dialog box or some such, unless that can be made a preference.  One possibility is to use `self.fv.show_error()` with the `raise` argument set to `True` or `False` (depending on a user preference).  This visibly logs an error in the `Errors` plugin.
