### ISSUE TITLE
Left panel layout a bit weird in Qt

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#252]
Latest dev Ginga, REHL6 64-bit, Qt4 that comes with Anaconda.

As you can see below:

* There is an usually blank space between "Synopsis" box with scrollbar and the rest of the info like zoom, cuts, etc. I see that there is a "stretcher" between scroll widget and the rest of the stuff in `misc/plugins/Info.py`, so this was done intentionally?
* There is a blank (grey) horizontal strip at the very bottom, stretching from lower left to lower right of the Ginga window. Started seeing this maybe like 2 weeks ago?

![screenshot-1](https://cloud.githubusercontent.com/assets/2090236/11730325/4cb6c45e-9f62-11e5-9ab7-cd60a281bc26.png)

**Comment by ejeschke** [comment]
It was done intentionally as part of layout improvement and consistency.  Now the coordinates are visible in `Info` as they update, which wasn't always the case.  Also looks consistent with gtk version.

Sorry, not sure I see the blank strip, but this may be from some padding/margin in a widget that should be set to 0.

**Comment by pllim** [comment]
Ah, okay. I traced the "blank strip" to this in `main.py`:
```python
dict(row=['hbox', dict(name='status')], stretch=0),
```

So, it is supposed to be some kind of status bar, but I never see anything reported there. What is it really used for?

**Comment by ejeschke** [comment]
The status bar message can be set by the call `self.fv.statusMsg()` from a plugin, for example.  The message will appear in the bar and then disappear after a few seconds.  It's one way to provide feedback to users, but it also provides a resize grip in the lower right hand which is very useful for some platforms.

**Comment by pllim** [comment]
Okay. Thanks for the clarifications!
