### ISSUE TITLE
Sorting by numbers with TreeView

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#257]
`TreeView` does not sort numeric column properly because it internally stores the numbers as strings. I tried passing in numbers in `set_tree()` but that didn't work. Also tried padding them with leading spaces or filler characters, also didn't work.

How do I fix this?

![screenshot](https://cloud.githubusercontent.com/assets/2090236/11883963/6fd42eb8-a4e4-11e5-9637-387221d6e1ad.png)

**Comment by ejeschke** [comment]
I discovered that also just a couple days ago.  And I really need numerical sorting.  Currently looking into this as a priority issue as it downgraded one of our applications.  Will keep you posted here.

**Comment by pllim** [comment]
Okay, thank you!

**Comment by pllim** [comment]
@ejeschke , any update on this? Just wondering.

**Comment by ejeschke** [comment]
Not yet.  Are you going to PiA2016?  Might be one of the sprints to fix it.

**Comment by letyrodridc** [comment]
Hi, I'm starting my GSoC PR. Can I take a look to this?

**Comment by ejeschke** [comment]
@letyrodridc, sounds good!

Pointers:
1. You are going to want to fix the `ginga.qtw.Widgets` module (and then the other widgets can follow the same solution--see below)--look for the `TreeView` class
2. The key to solving this for all widget sets is changing the `shadow` type from a `dict` to an `OrderedDict`, and being able to sort the ordered dict, which can be arbitrarily nested.
3. You then change the click events to sort the shadow dict and simply rebuild the table.

[Here](http://stackoverflow.com/questions/4110665/sort-nested-dictionary-by-value-and-remainder-by-another-value-in-python) and [here](http://stackoverflow.com/questions/11753660/sorting-python-dictionary-based-on-nested-dictionary-values) are a couple of links on sorting dictionaries that may give you a start.

I'd suggest starting by solving the problem of sorting an arbitrarily nested ordered dictionary, which is a nice little self-contained problem.

**Comment by ejeschke** [comment]
@pllim, jump in if you have other suggestions!

**Comment by pllim** [comment]
@ejeschke , I actually have a different thought about the fix. For Qt at least, the underlying problem is that `QTreeWidgetItem` only takes a list of strings. So as a result, in Ginga's `TreeView._add_subtree()` method, the values are converted to string prior to being passed into the widget. So, `1234` and `25` becomes `'1234'` and `'25  '` in the widget, although for them to sort properly, they actually need to be `'1234'` and `'  25'` instead. See the problem illustrated below:

```python
>>> sorted(['1234', '  25'])
['  25', '1234']
>>> sorted(['1234', '25  '])
['1234', '25  ']
```

**Comment by ejeschke** [comment]
Yes, a fix for Qt only would be to implement a subclass of `QAbstractItemModel`.  But I think that is a rather limited solution and fixes only one back end.  Since the back ends all share a shadow structure containing the data in a normal python-standard data structure, might as well just sort that and reload the interface.  I think this actually keeps the GUI logic simpler.

**Comment by pllim** [comment]
@ejeschke, Ah okay, I see what you're saying now about the shadow + ordered dict. Sounds good to me.

**Comment by letyrodridc** [comment]
Thanks a lot. I'm taking a look to the code and working with the solution.

**Comment by pllim** [comment]
Now I remember why I had to explicitly cast DQ flags to `str` before passing it into `TreeView` (see traceback below if I don't). So, this means the shadow itself only recognizes the DQ flags as strings as well, which means the shadow itself won't sort properly. Does that make sense?

In the plugin:
```python
treedict[str(flag)] = Bunch.Bunch(FLAG=flag, DESCRIP=val)
```

The traceback from Ginga when running the plugin:
```
Traceback (most recent call last):
  File ".../ginga/qtw/Widgets.py", line 697, in _selection_cb
    res_dict = self.get_selected()
  File ".../ginga/qtw/Widgets.py", line 739, in get_selected
    self._get_item(res_dict, item)
  File ".../ginga/qtw/Widgets.py", line 730, in _get_item
    d[dst_key] = s[dst_key].node
KeyError: u'128'
```

**Comment by letyrodridc** [comment]
Why you cast flags as strings? Could you use the TreeView with just
numbers?

The TreeView view is sorting right. It has strings as you said.

**Comment by pllim** [comment]
Sorry, the traceback happens *after* I removed the `str` casting. I corrected my example above.

**Comment by pllim** [comment]
If anyone wants to try the `DQInspect` without the `str` casting, just pull my branch associated with spacetelescope/stginga#105
