### ISSUE TITLE
Extend LineProfile to accept aperture

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#259]
This was requested in spacetelescope/stginga#40, but the parts where user can draw some kind of aperture and then use it for simple statistics up the ramp would be useful in general, no?

We should probably address #188 ~~and merge #187~~ first though.

**Comment by ejeschke** [comment]
@pllim, if you or @rupak0577 would want to work on this that would be good.  I don't have a good handle on how this plugin is used.

**Comment by ejeschke** [comment]
#187 merged.

**Comment by pllim** [comment]
Thanks, @ejeschke ! Yes, it is on my to-do list but not high priority right now. So if @rupak0577 etc wants to give this a shot first, I won't object. :wink:

**Comment by rupak0577** [comment]
@ejeschke @pllim Thanks! I would like to but don't know much about it although it looks simple. I will look into it.

**Comment by pllim** [comment]
@rupak0577 , are you still looking into this? If not, I'll take a stab at it.

**Comment by rupak0577** [comment]
@pllim Sorry, I haven't made much progress so it's probably better if you do it.

**Comment by pllim** [comment]
Okay, something else came up for me as well. But I'll see if I have time in the next few weeks.

It currently loads the whole data cube in, yes?

**Comment by rupak0577** [comment]
@pllim Yeah, it loads the entire cube. 

Okay, if I get some free time, I will try to get something done. So for the aperture, it will be similar to the 'Drawing` plugin, right? Should it be a separate plugin? Or can we add a tab to `LineProfile`?

**Comment by pllim** [comment]
@rupak0577 , I was thinking the same plugin, but we don't need a separate tab. Rather a new drop-down menu that let user to choose whether to use a point or some kind of aperture (e.g., box, circle, or polygon). And if an aperture is chosen, then another drop-down menu will be activated to let user choose what algorithm to use to "flatten" the data (e.g., sum, median, or mean). And if you are up for it, additional parameters for sigma clipping (e.g., number of iterations and sigma value). Then under the hood, if aperture is chosen, data is "flattened" accordingly before it is plotted. The rest should be the same.

For sample GUI, see http://stginga.readthedocs.org/en/latest/plugins_manual/backgroundsub.html

**Comment by rupak0577** [comment]
@pllim Is it possible to subclass a plugin without creating another? Adding the code to LP makes it more complex. 

For the gui, do we need the other attribute boxes like `Radius`, `X`, `Y` etc? Also, can you point me to some references for the algorithms?

**Comment by pllim** [comment]
@rupak0577 , that was just an example, there is no need to include everything shown if they don't make sense. That particular example was written before @ejeschke introduced "draw" and "edit" radio buttons for canvas drawings. On your end, I don't think you need to worry about the extra GUI elements that allow users to explicitly set drawing parameters (e.g., `Radius`, `X`, and `Y`) unless you think there is a good reason to do so.

As for subclassing, it creates a new plugin that is similar to parent but not entirely (depending on how much new stuff you add to the subclass). If you look in https://github.com/spacetelescope/stginga/tree/master/stginga/plugins , both `MIPick.py` and `MosaicAuto.py` are subclassed plugins. I am not sure what you mean with "without creating another" though.

As for sigma clipping algorithm, perhaps `calc_stat()` function in https://github.com/spacetelescope/stginga/blob/master/stginga/utils.py might be useful to you.

**Comment by rupak0577** [comment]
@pllim Okay, I will focus on the drawing side then. We can add the rest later if necessary.

Regarding the subclassing, I simply wanted to move the aperture code into another class to avoid adding the subclass as a new plugin but it seems that's not possible. So I guess it will be a new plugin (subclassed from `LP`) and added to the list. Otherwise, `LP` becomes complex with all the drawing and calculation code. Or should I add everything to it?

**Comment by pllim** [comment]
With a new subclassed plugin that does all the same things but the only difference is region selection, I don't know how confusing that would be for the user. @ejeschke , you have any thoughts?

**Comment by ejeschke** [comment]
I think the situation is analogous to the changes we made to `Cuts` last year to add width capability or the slit.  It's just slight variation on what is already being done, but sometimes involving significant new calculations, or a slight variations in the drawing object.

It's not entirely clear to me whether the use case is so different to warrant a separate subclass.  Typically, we use a subclass when our institution wants to customize one of the "stock" plugins without reinventing the wheel.  In this case what is being proposed is just to enhance the stock plugin.  @rupak0577, you can always put the aperture code in another module/class and import it into the plugin to avoid bloat or to enable reuse, if it seems useful outside of the plugin.  

And I agree that you probably want to avoid adding lots of drawing options that have to do with formatting, etc. like there are in `Drawing`.  I would suggest simply providing a shape selection and make reasonable defaults for the attributes.  If important enough, you can make some of them user-configurable via plugin settings.

**Comment by rupak0577** [comment]
@pllim It seems we cannot use the same plot for both the aperture and the mark feature in `LP`. Since the mark plots the data at a point, flattening the same data would be incorrect. So another plot tab is necessary.

**Comment by pllim** [comment]
I am okay with another tab if that works best.

**Comment by rupak0577** [comment]
@pllim By "pixels within the aperture" do you mean the pixels or the pixel data values?

@ejeschke Is there any method to find the list of data points inside a shape object(circle,box) ? I think it's `contains_arr()` but not sure.

**Comment by pllim** [comment]
@rupak0577 , I meant the statistics are to be done to the actual data in the affected pixels. To be more precise, the values from the input image, not the displayed RGB stuff. Does this make sense?

Also, you can extract the data with something like this in the plugin... Some of the codes are merely for example, but you should get the general idea.

First you need to store the canvas tag when aperture is drawn:
```python
def __init__(...):
    self.apertag = None

def add_aper_drawing(self, ...):
    self.apertag = self.canvas.add(self.dc.CompoundObject(...))
```

Then, in the method that extracts the data:
```python
try:
    obj = self.canvas.getObjectByTag(self.apertag)
except KeyError:
    return True
if obj.kind != 'compound':
    return True
aper_obj = obj.objects[0]  # The index depends on how you built the CompoundObject above

# This returns the masked data
data_masked = image.cutout_shape(aper_obj)

# Use this for statistics
try:
    data_for_stats = data_masked.data[~data_masked.mask]
except:
    self.logger.error('Failed to extract aperture')
    return
results = self.do_statistics(data_for_stats)
self.report_results(results)
```

**Comment by pllim** [comment]
Depending on how you actually compute the statistics, you might also flatten the `data_for_stats` first.

**Comment by rupak0577** [comment]
That will definitely help so thanks!

For calculating the stats, I was thinking about simple passing the array to the `calc_stat()` code above. 
Also, what should be the list of shapes and algos? For now its just Box,Circle and all algos in the `calc_stat()` (mean, median,mode,stddev).

**Comment by pllim** [comment]
I am not sure of what shapes that are the most useful for most cases. I think polygon might be the most flexible, if that is not too hard to add. Otherwise, box and circle are good starting points. The existing algos should be okay, unless you can think of otherwise.

**Comment by pllim** [comment]
@rupak0577 , does that mean you are also moving `calc_stats` over from `stginga` to Ginga's util area? Ginga should **not** add `stginga` as a dependency.

**Comment by rupak0577** [comment]
Yeah, I only moved that method to util.

Not sure how to calculate the points for the polygon. But we can add that later. I just want to get the basic functionalities working.

**Comment by pllim** [comment]
The code I posted above should also work for polygon. Polygon is just another shape like box and circle. But yeah, you don't have to add it now if you don't want to.

**Comment by rupak0577** [comment]
Hmm, I thought it would be difficult with multiple edges intersecting. Anyways, will try to push the changes soon.

**Comment by ejeschke** [comment]
@rupak0577, the key method is what @pllim referred to above:
```python
# This returns the masked data
data_masked = image.cutout_shape(aper_obj)
```
this will return a rectangular array of data for the bbox of the shape, but with the data that are not inside the shape masked out.  It should work for all "enclosing" ginga shapes, so code doesn't have to do any special processing for each kind of shape.

**Comment by rupak0577** [comment]
@pllim I am not sure what the `ydata` for `plot()` will be

`self.ap_plot.plot(plot_data, ?)`

Will that be a sliced array like in `LP` ?

**Comment by pllim** [comment]
@rupak0577 , yes. But instead of the values of selected point, it displays the calculated stats from values of points within the selected aperture. Does that make sense?

**Comment by rupak0577** [comment]
But the sliced array in `LP` is according to the axis selected. It isn't similar, is it?

**Comment by pllim** [comment]
Nothing should change except for the values inside aperture going through stats first. For the axis where the aperture does not apply, then it is just the same thing as existing functionality.

**Comment by rupak0577** [comment]
Okay, so it's the `LP` plot code with only the plot array being replaced - `self.ap_plot.plot(flattened_data, mddata[slice_obj])`.

Are there some axes where the aperture would not apply?

**Comment by pllim** [comment]
Not knowing what kind of data user is going to display, it is best to be flexible and just assume it applies to everything. If users choose something that does not make sense, they should expect crazy plots.

**Comment by rupak0577** [comment]
I missed this somehow but how do I apply the stat value returned by `calc_plot()` on the array?

**Comment by pllim** [comment]
Yes. For example, if I have a data cube (`a`) that is a series of 10x10 images (100 of them), and I want to plot the sum of each of the 10x10 image across the series (in this case, the 10x10 would be the chosen aperture), I would expect the plugin to do the equivalent of this manual operation:

```python
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> a = np.random.random((10,10,100))
>>> b = a.sum(axis=(0,1))
>>> b.shape
(100, )
>>> plt.plot(b)
```

**Comment by pllim** [comment]
I followed up again with the user who made the original request. Turns out NIRCam image that will use this feature has 4 dimensions and the requirements are pretty specific, so moving this development to `stginga`.

**Comment by pllim** [comment]
Actually, now that I think about it more, a more general implementation is possible. And I can simply subclass this one for a more specific one in `stginga` if needed.
