### ISSUE TITLE
Follow-up to time modified in callback

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#262]
This is for follow-up discussions on #223 and its subsequent modification via c6c8e77.

@ejeschke, by getting rid of `image-modified` callback and only using `modified`, we have that issue again where a plugin cannot tell which channel the modification happened in, because `modified` callback only takes the image object as the argument.

**Comment by pllim** [comment]
For instance, if I want my plugin to listen for the `modified` callback and then compile a list of modification history, I can no longer accomplish it without the `image-modifed` callback because I lost the channel info by just using `modified`. Without knowing the channel, I cannot even extract the "reason" using `channel.get_image_info(image_name)` as you suggested in #223.

**Comment by ejeschke** [comment]
But "add-image-info" is now called when the image is modified, and it includes the channel in the callback.  You simply need to check whether the `time_modified` attribute of the `info` parameter has changed.

**Comment by ejeschke** [comment]
This is a callback exported by the ginga shell (i.e. usually bound to `fv` in the plugin).

**Comment by pllim** [comment]
So, instead of listening for the 'modified' callback, my plugin should instead listen to 'add-image-info'?

**Comment by ejeschke** [comment]
Yes, it has a parameter in the callback called `info`.  This is a `Bunch` that contains attributes of information about the image, whether in memory or not.  It has a `time_modified` attribute, which will be either `None` or a `datetime` (utc) value.  It is this same info in which you could store a "reason" if desired, it will persist for the lifetime of the ginga session.

**Comment by pllim** [comment]
Ah, okay! I also noticed that `Contents` now have a `redo()` method. That is very nice. Thanks!
