### ISSUE TITLE
Treeview column widths

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#263]
Is there a way to tell `Treeview` the optimal column widths for some of the columns? Or perhaps tell it that the given column is important and should always be expanded to at least X  number of characters? I find that I always have to manually expand the column widths (by dragging its border), as shown below.

First and last columns not showing meaningful info unless fully expanded:
![untitled](https://cloud.githubusercontent.com/assets/2090236/12024357/41362a9e-ad71-11e5-9b91-a136f43def40.png)

First column not showing meaningful info unless fully expanded:
![untitled2](https://cloud.githubusercontent.com/assets/2090236/12024386/78f032fe-ad71-11e5-9e4c-1af7a4a90bf6.png)

**Comment by ejeschke** [comment]
There is a call for both qt and gtk that will set "optimal" column width for a column (for qt one of these is `treeview.resizeColumnToContents()`).  IIRC, there may be an issue for this in that it can slow down significantly the insertion of rows in the table, when the number of rows is high (i.e. over a couple of thousands).  I vaguely remember an issue we had with this with large tables of stars.

IMO, if we add such a feature that works "automatically" we need to test carefully with large tables.

**Comment by pllim** [comment]
What if there is an option to turn this auto-resize feature on or off via plugin config file? Maybe like this:

```python
# Resize columns to contents. This might affect performance if a lot of rows are displayed.
resize_columns_to_contents = True
```

Alternately, perhaps a plugin config for user to manually specify initial column widths (see example below), which can be used once at start-up via `treeview.setup_table()`? That way, it will not affect performance.

```python
# Column widths in number of characters to display. Set to None to use software default.
column_widths = [25, None, None, None, 50]
```

**Comment by ejeschke** [comment]
I like the idea of a method on the `TreeView` to set column sizes.  That would be easy and I think if you set fixed column sizes there is no penalty for row insertion.  You could then optionally call this in `build_gui()` or anytime before or after table operations.

**Comment by ejeschke** [comment]
In the next commit you will find three new methods on a `TreeView`: `set_column_width(i, width)`, `set_column_widths(list_of_widths)` and `set_optimal_column_widths()`.  These work for both qt and gtk.

If the number of rows is not large, you can simply call `set_optimal_column_widths()` after the treeview is populated to set all the widths optimally.

**Comment by pllim** [comment]
@ejeschke , thanks! Do you have plans to let `Contents` use this feature?

**Comment by ejeschke** [comment]
I'm a little concerned about calling it by default in `Contents`.  But maybe with a check against the size of the table it might be ok.

**Comment by pllim** [comment]
>  maybe with a check against the size of the table it might be ok

That sounds reasonable. The size can be a user configurable parameter, if you wish.
