### ISSUE TITLE
Setting background color in Frame widget 

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#265]
I have a piece of Qt code in my plugin like this:

```python
frame.widget.setStyleSheet('QFrame {{ background-color: {0} }}'.format(status_color))
```

where `frame` is an instance of `ginga.gw.Widgets.Frame`. I got that piece of code from http://zetcode.com/gui/pyqt4/widgets/ example.

I am wondering if it is possible to do this in Ginga without accessing the Qt-specific widget. If not, that's fine, I'll try something else. Either way, please let me know!

**Comment by ejeschke** [comment]
@pllim, for widget specific hacks, you can use something like `hasattr` to prevent causing a problem for a  different widget set. A bit ugly, but probably ok for things that are purely cosmetic:
```python
nativew = frame.get_widget()
if hasattr(nativew, 'setStyleSheet'):
    nativew.setStyleSheet('QFrame {{ background-color: {0} }}'.format(status_color))
```
If you find yourself setting the background of a lot of different frames, then it may be worth adding a `set_bg` method to `Widgets.Frame`.

**Comment by pllim** [comment]
I was able to substitute the colored frame with a label with very large font. Since `Widgets.Label` already has `set_color()` method, there is no changes to Ginga necessary. Thanks anyway!
