### ISSUE TITLE
Follow up on QLabel text selection by mouse

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#266]
This is a follow up on #256. The `setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)` incantation used to work in an older version of Ginga (2.5.20151028003943) but now it has no effect. I cannot figure out why.

If there is no fix for this, it is better to undo #256.

**Comment by pllim** [comment]
A little background: The original idea was to let users copy and paste some displayed values to somewhere else for future reference. But now they prefer to have a button to save the parameters to JSON files instead, so not being able to select/highlight `QLabel` values is not really an issue anymore.

**Comment by ejeschke** [comment]
Ok, @pllim, I will remove the line in a near future commit.

**Comment by pllim** [comment]
I see that you commented it in 759c299c0c36 .

**Comment by ejeschke** [comment]
Shall we close the issue then?

**Comment by pllim** [comment]
Sure. Thanks.
