### ISSUE TITLE
FBrowser plugin to auto resize columns

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#274]
Quoting @ejeschke from #268, "... maybe we should do something similar for `FBrowser`?"

Auto resizing columns in `FBrowser` would make sense. However, unlike `Contents`, I do not think there is a need to turn the feature off based on a max number of rows. What do you think, @ejeschke ?

Also see #263.

**Comment by ejeschke** [comment]
It might make sense to put a large limit, like a few thousand rows.  Building the tree is not invoked on a callback that happens with regularity, like adding or switching images, so its not so important.

**Comment by pllim** [comment]
Okay, @ejeschke , I added the limit in #276.
