### ISSUE TITLE
Should ChangeHistory remember changes even when inactive?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#277]
This is a follow up of #270.

Currently, the `ChangeHistory` global plugin only records changes to buffers when it is active, via its `redo()` method. This means that it might not reflect all the buffer changes in Ginga if user does not start it immediately after Ginga loads. Is this a desirable behavior?

If not, then we should move the actual change history to `chinfo` like the modification time. But now, instead just the latest modification time, we store all of it. Also I propose formally adding modification reason to the metadata as well because it does not make sense not to remember what was actually modified. To this end, perhaps modification metadata as a whole can be an ordered dictionary storing all the timestamps and reasons.

What do you think, @ejeschke ? I want to make sure we are on the same page before attempting a PR on this.

**Comment by ejeschke** [comment]
@pllim, do you start the plugin immediately when `stginga` starts up?

**Comment by pllim** [comment]
@ejeschke , yes. In fact, I added the "close" button just to be consistent with the rest of Ginga optional plugins when I submitted the PR to you. So, now there is option to open/close/open/close this plugin, and this can be an issue to people who do that.

**Comment by ejeschke** [comment]
@pllim, I have no objection to putting a modification history in the channel metadata. Out of curiosity, what is the rationale for using an ordered dictionary for the history rather than a simple list or sequence type of records?

**Comment by pllim** [comment]
> what is the rationale for using an ordered dictionary

My thinking was just so that it can link the `time_modified` to `reason_modified`, and also preserve the order. But now that I think about more, perhaps just a list of tuples will do.

I'll attempt a PR when I have a chance. This is not high priority on my side currently, and I don't think there is a need on your side yet.

**Comment by ejeschke** [comment]
We don't have any significant current uses of modification except `Mosaic`--in which the trail of reasons would be uninteresting to the user.  I would prefer if we can do it without e.g., introducing a new callback or additional overhead for non-modification type operation.

**Comment by pllim** [comment]
@ejeschke , why don't we just close this as "won't fix" for now? At least it is documented in the issues. If there is a need for persistent history in the future, we can always revisit.
