### ISSUE TITLE
Deleted mosaic still in Thumbs

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#278]
When a mosaic (created via `Mosaic` plugin) is removed from a channel, its thumbnail is not removed from `Thumbs` even when it has disappeared from both `Contents` and `Datasrc`.

**Comment by ejeschke** [comment]
@pllim, did you get any change to delve into why?  I suspect it has something to do with the fact that mosaics don't have an associated path, but I haven't had a chance to investigate it yet.

**Comment by pllim** [comment]
No, I haven't.

**Comment by pllim** [comment]
@ejeschke , are you okay with my fix in #286?
