### ISSUE TITLE
Cannot guarantee a key_release_event after a key_press_event which messes with modifiers

### ISSUE THREAD

**Issue by stscieisenhamer** [ejeschke/ginga#288]
I have been using the CanvasView in a standalone Qt app for awhile. I have been fighting a very weird issue where CanvasView would seem to get stuck in Pan mode. The Cntrl-Left button would do nothing but pan. Other symptoms include f you explicity went into one-shot Pan mode, the Q-key, panning would not work, or one could not draw objects.

The workaround was to hit the Ctrl key. But this would only be temporary; at some point the stuck-in-Pan would occur again.

Well, finally sat down to figure this out and discovered that this always happened when using a menu shortcut, such as Command-O to open a file. This always resulted in the stuck-in-Pan. Getting the debugging messages going, it was seen that the Command modified translates into the Ctrl modifier. Since this particular action opens a window, the CanvasView looses focus. Hence, the Command ala Ctrl key-release event never makes it to the CanvasView. Since CanvasView.BindingMapper never sees the release, the modifier remains in the BindingMapper._modifiers set. Subsequent button actions get the modifier applied. This also explains why hitting the Ctrl (or Command), clears the issue.

The general solution would require that any defocus event clear the BindingMapper._modifiers set.  It is not immediately obvious to me where this should be done, though I suspect this would go into one of the base classes of the Viewers.  If this issue is as described, I can further investigate how best to solve.

**Comment by ejeschke** [comment]
This particular bug has been biting me for a long time too, under a different scenario. I get it when I use a Ctrl key combination to switch virtual desktops under Linux--then, also, the Ctrl-key release event never makes it back to Ginga.  I'm using the `grabKeyboard()` Qt API call in the Qt version, which I thought was supposed to fix this, but apparently it doesn't (at least for Control or Command keys).  Ginga can't be the first program to deal with this problem.  Wonder what the correct solution is?

Lacking a better solution, I suppose the focus out event could reset the BindingMapper modifiers--that would not be too hard to do.  What about the case though where you just move out of the window briefly, lose focus, and then move back in (like in a Unix box with mouse over focus)?

**Comment by ejeschke** [comment]
@stscieisenhamer, I'm not sure this solves the problem I mentioned above, but I think it may solve yours.

Can you upgrade to commit 0bb7f8190947fb936ee8916ab36b5318aa7b4b1d and give it a whirl?

There is still an issue where the cursor is stuck in the pan cursor, but I think that should be easy to fix.

**Comment by stscieisenhamer** [comment]
That will do it; essentially the same as my patch to my local class. I'll leave closing to you, in case further discussion is needed, as per below.

About the "general" solution. When I did this regularly 20+ years ago, the presumption was always that the application needed to handle 'cleanup' when losing focus. It was actually a necessary feature of any GUI toolkit that the events occur only to what has focus. If a widget has lost focus while "in the middle of something", the presumption usually is that the user didn't really want to do whatever it was, and abort the operation-in-progress.  That said, there was some system (can't remember), that handled modifiers more internally and hence keeping modifier state was not handled by the apps.

Using things like grabKeyboard() could result in breaking the situation I am in: the file dialog popup is receiving the key-release event. If the grabbing was done, the file dialog would not receive events, and there would be no way to enter file names or click on the directory to choose files. Doing such grabs is fraught with landmines.

Another general solution is instituting a timeout: One can presume that any modifier use is short-lived: after X seconds, if a modifier hasn't cleared on its own, clear them.

**Comment by ejeschke** [comment]
@stscieisenhamer, does the Command-O shortcut work as expected now?  There is still a `grabKeyboard()` call initiated by a key press and the corresponding release call in the key release event.  I'm not sure these even work as imagined on a mac.  I'll try removing them and see if I can detect any negative change in behavior.

**Comment by stscieisenhamer** [comment]
Yes, sorry, it works just fine. If there is a grabKeyboard occurring, it has no effect; I can type into the file dialog just fine. This may be because it is using the 'native' file dialog, over which the grab may have no effect.

**Comment by stscieisenhamer** [comment]
FYI: Tried the non-native file dialog and was able to still type into it. But this does reveal what the actual issue is: The file dialog is modal; it blocks the rest of the UI. The grabkeyboard can have no effect, almost by definition.

There goes another landmind...

**Comment by ejeschke** [comment]
Both gtk and qt versions have had the keyboard grab removed.  Closing this issue.
