### ISSUE TITLE
New plugin to save image(s)

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#312]
This was brought up by @ejeschke in #292, *"... let's add a 'Save As FITS' menu item that starts the 'Save Image' plugin (which you should submit as a separate PR which we can merge first). That way after creating the mask they can either start the save image plugin from the Operations menu or they will discover it under the File menu."*

From the description above, it sounds like the idea is to keep `SaveImage` as a local plugin, as it currently is in `stginga`. But if it were to be started via `File` menu item, shouldn't it be a global plugin instead? Please clarify, @ejeschke .

Screenshot of current implementation:

![saveimage_screenshot](https://cloud.githubusercontent.com/assets/2090236/14109353/9a5330c0-f58f-11e5-8471-96c22a36198e.png)

**Comment by ejeschke** [comment]
Actually, there is no problem starting a local plugin from a menu item.  If it were a global plugin it would have to decide which channel's image to save, but if we simply have it start the local plugin in the active channel that would work fine.

**Comment by pllim** [comment]
Okay, that sounds good. I notice that you did a similar implementation with `FBrowser`, I'll look into that as example. Thank you!

**Comment by ejeschke** [comment]
The only tricky part is making sure to throw up an error message with `show_error()` if the plugin is not loaded.  To check whether the local plugin is loaded, do something like:
```python
channel = self.get_channelInfo()
if (channel is not None) and channel.opmon.has_plugin(plugin_name):
    ...
```
