### ISSUE TITLE
Modify unit tests to use Astropy pytest framework

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#317]
This is a follow-up for after #313 is merged.

**Comment by ejeschke** [comment]
@pllim, I'm open to this.  What do you have in mind?

**Comment by pllim** [comment]
It would follow the [pytest syntax](https://pytest.org/latest/example/) and [Astropy guidelines](http://docs.astropy.org/en/latest/development/testguide.html#writing-tests).

For example (this list is non-exhaustive):
1. Any test that uses data stored remotely would have the `@remote_data` decorator.
2. Any test that checks for exception would use [raises](https://pytest.org/latest/assert.html#assertions-about-expected-exceptions).
3. Any test that uses optional dependency (e.g., SciPy) or is expected to fail under certain enviroment(s) would use [skipif or xfail](https://pytest.org/latest/skipping.html).
4. A test that accepts multiple sets of parameters would use [parametrize](https://pytest.org/latest/parametrize.html).

**Comment by ejeschke** [comment]
I think the `setup.py` linkage to tests is broken now anyway.  I get the following traceback when I try to run `python setup.py test` (it seems to be coming from the `astropy-helpers`):
```python
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    **package_info
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/gen2/share/arch/64/lib/python2.7/site-packages/astropy-1.1.1-py2.7-linux-x86_64.egg/astropy/tests/command.py", line 158, in run
    self._build_temp_install()
  File "/opt/gen2/share/arch/64/lib/python2.7/site-packages/astropy-1.1.1-py2.7-linux-x86_64.egg/astropy/tests/command.py", line 213, in _build_temp_install
    os.path.basename(self.docs_path))
  File "/usr/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by pllim** [comment]
@ejeschke , you need to use the *development* version of Astropy, it is fixed in astropy/astropy#4748

**Comment by ejeschke** [comment]
Is the installer pulling the correct version to use for the tests?

**Comment by pllim** [comment]
Travis CI is using the *development* (correct) Astropy version. I have opened #335 to switch back to *stable* Astropy after 1.2 is released.

**Comment by pllim** [comment]
However, when you run the tests locally, they do not follow `.travis.yml` settings. You will have to make sure your local version of Astropy matches Travis CI. Does that make sense?

**Comment by ejeschke** [comment]
I see. Is `setup.py` installing the development version of astropy for regular installs?

**Comment by pllim** [comment]
This is in `setup.py`:
```python
install_requires=['astropy', 'numpy>=1.7']
```

So, I *think* it would just pull the latest stable version. I am not sure if it is even capable of pulling in a dev version...

**Comment by pllim** [comment]
But if you already have the *dev* version, it will *not* overwrite.
