### ISSUE TITLE
Replace ginga.util.six with astropy.extern.six

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#323]
I don't see any reason not to.

**Comment by ejeschke** [comment]
How often does `astropy.extern.six` change?  I think this might be ok too, but I use the `six` module *everywhere*.  That could entail massive changes if the external `six` module is updated.

**Comment by pllim** [comment]
I would say not often. Here is the [commit history](https://github.com/astropy/astropy/commits/master/astropy/extern/six.py).

**Comment by Cadair** [comment]
I was warned against doing this by @embray because it means you have to have astropy installed to install ginga. Rather than `pip install ginga` being able to pull in astropy.

**Comment by pllim** [comment]
Ah, okay. That's good to know, @Cadair . Closing then.
