### ISSUE TITLE
Replace RTD domain name

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#332]
There is a need to replace all mention of `readthedocs.org` with `readthedocs.io` for RTD hosted sites. This is not urgent but should happen eventually.

**Comment by ejeschke** [comment]
You beat me to filing this issue, @pllim!

Anyway, commit 33c15be75b0829513e0b988bea53e76c9ab19342 should fix this.

**Comment by pllim** [comment]
Thanks, @ejeschke ! Your commit, in addition to #333 should resolve this.
