### ISSUE TITLE
Re-enable Astropy stable version on Travis CI after Astropy 1.2 is released

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#335]
This is actually a follow-up of #313 and only valid after it is merged. I am opening an issue now so I don't forget about it.

Currently, because Ginga documentation is stored in `doc` and not `docs`, Travis CI tests will fail using #313 unless Astropy development version is used because of astropy/astropy#4748, which hopefully would be in v1.2.

**Comment by ejeschke** [comment]
I think this has been fixed, right @pllim?

**Comment by pllim** [comment]
Ops, yes. Fixed in 04605a6eb51f. Closing!
