### ISSUE TITLE
AttributeError: 'module' object has no attribute 'githash' (SOLVED)

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#340]
With major changes involving using Astropy package template (see #313), I just want to document this for those who encounter this error in the future when attempting to install Ginga from source and already has an existing installation from the pre-PR313 days:

``` python
Traceback (most recent call last):
  File "setup.py", line 63, in <module>
    get_debug_option(PACKAGENAME))
  File ".../ginga/astropy_helpers/astropy_helpers/version_helpers.py", line 236, in generate_version_py
    last_githash = version_module.githash
AttributeError: 'module' object has no attribute 'githash'
```

**SOLUTION**
1. Find out where you install Ginga. Let's call it `install_dir`. For example, `blahblah/python2.7/site-packages/`.
2. Remove Ginga installation from `install_dir` manually. For example, `rm -r blahblah/python2.7/site-packages/ginga*` (use with care).
3. Just to be safe, clean your _source_ directory. For example, `git clean -xdf` (be careful of any new untracked files you wish to keep).
4. Now, you can install Ginga as usual. For example, `python setup.py install`.

**Comment by pllim** [comment]
There is no need to keep this open. Anyone who searches for this in `Issues` should find this regardless.

**Comment by ejeschke** [comment]
Actually, @pllim, I'm wondering if we shouldn't leave this open for a little while.  I encountered this several times installing after merging #313.  At the very least, it may prevent some filing of duplicate issues.

**Comment by pllim** [comment]
Sure.

**Comment by rirze** [comment]
Thanks for keeping this open, helped me out when I ran into this error.

**Comment by pllim** [comment]
This is pretty old now, so closing.
