### ISSUE TITLE
Case-sensitive file naming conflict

### ISSUE THREAD

**Issue by larrybradley** [ejeschke/ginga#341]
The `ginga` repo has both a `ginga/gw/ColorBar.py` and `ginga/gw/colorbar.py`.  These files cannot co-exist on OSX (case-insensitive filesystem).  (and `git` gets very confused)

**Comment by pllim** [comment]
Looks like `colorbar.py` was added via 5f5db2649d7255 about 2 weeks ago. There are three options:

1. Merge them.
2. Rename one of them.
3. Or follow through with the comment in `ColorBar.py` -- *Possible TODO: replace above colorbar implementations with this generic one.*

@ejeschke ?

**Comment by ejeschke** [comment]
@larrybradley, thanks for pointing out this problem!  I kept seeing a wierd issue with this file on my mac laptop with Git, but could not replicate the issue anywhere else (I use Linux on the desktop).

@pllim, I think I'm not ready (yet) to replace the two widget specific color bars with the generic one (although I think that is desirable in the long run).  I'll merge them or rename one of them.

**Comment by ejeschke** [comment]
This issue should be resolved in commit 60c519612d9623e16fe663bada007aacbd7dd8e3.
