### ISSUE TITLE
Make use of QtPy instead of QHelp

### ISSUE THREAD

**Issue by astrofrog** [ejeschke/ginga#348]
The [QtPy](https://pypi.python.org/pypi/QtPy/) package now provides a common way to deal with the PyQt4/5/PySide differences, and it would make sense for as many projects as possible to use this.

This issue is just to suggest that it might be good for ginga to also migrate to using QtPy?

(I can provide advice if needed, since I'm going through the migration myself for glue)

**Comment by ejeschke** [comment]
@astrofrog, thanks for pointing that out!  I'm very interested. Does it seem to work well and is stable?

**Comment by ejeschke** [comment]
BTW, is it in conda?

**Comment by astrofrog** [comment]
@ejeschke - it is in conda by default I believe, and it seems pretty stable. I've been making a few PRs to port over some of the patches I had in qt-helpers. For the record, here's the PR to change it for glue: https://github.com/glue-viz/glue/pull/1018

Essentially you have to make sure you treat QtPy as if it was PyQt5 (in glue we did the opposite and assumed the PyQt4 API, which is why there was a fair bit to update)

**Comment by astrofrog** [comment]
@ejeschke - just for info, I've now switched over to it in glue: https://github.com/glue-viz/glue/pull/1018#issuecomment-238117149

The latest version can be accessed in the ``conda-forge`` channel in conda:

```
conda install -c conda-forge qtpy
```

But there is also a (slightly older) version available in the default channel.

**Comment by ejeschke** [comment]
Closing this issue, as qtpy is now used via #367
