### ISSUE TITLE
Release new ginga version

### ISSUE THREAD

**Issue by montefra** [ejeschke/ginga#364]
Hi, 

I've tried to update ginga and it fails with:

```
-> pip install -U ginga
Collecting ginga
  Using cached ginga-2.5.20160627100500.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bgcz2zyi/ginga/setup.py", line 25, in <module>
        conf = config.ConfigParser()
    AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bgcz2zyi/ginga/

```
I've seen that commit 26d627a should fix the issue with configparser.
Would you mind releasing a new version with that fix? As it is now the ginga version on pypi is broken as it does not install.

My current situation:
-> pip search ginga
ginga (2.5.20160627100500)  - An astronomical image viewer and toolkit
  INSTALLED: 2.5.20160420043855
  LATEST:    2.5.20160627100500

Thank you in advance

**Comment by pllim** [comment]
Until an official release is made, you can workaround this problem by installing from STScI's AstroConda channel (see http://astroconda.readthedocs.io/en/latest/). The "release" on that channel is currently at 5eca5d9afe72d676baf4aef2ef4f4101254075e5.

**Comment by montefra** [comment]
@pllim : I don't use conda and neither does tox.
Do you have plans for the next release?

For now I'll lock ``ginga<=2.5.20160420043855`` in the ``setup.py``.

Thank you for your work.

**Comment by pllim** [comment]
@montefra , I can't do a Ginga release, only @ejeschke can.

**Comment by pllim** [comment]
Alternately, if possible for your case, you can also try this:

```
pip install git+https://github.com/ejeschke/ginga.git@<commit_hash>
```

**Comment by montefra** [comment]
@pllim : Ok I'll wait.

about pip: it's easier to lock ginga to the earlier version on Pypi until a new version arrives than pointing to a specific commit.

**Comment by ejeschke** [comment]
@montefra, @pllim, I've pushed a new release.

**Comment by ejeschke** [comment]
@pllim, I am comfortable to add you as an admin to this repo if you are interested. Lmk.

Also, I'd like to start using the github release feature instead of just manually making releases.  I'll take a look at it but might want your advice.

**Comment by montefra** [comment]
@ejeschke : Thank you for it. 

When you add a tag and push it here, automatically github mark it as a release. I think that if you add a comment to the tag, it uses that too. Then you can edit the release message and title from the website.

**Comment by ejeschke** [comment]
@montefra, does any tag signal a release, or only tags following a version specification?

**Comment by montefra** [comment]
I think any tag, but I'm not 100% sure.

**Comment by montefra** [comment]
@ejeschke : thank you very much. Now ginga works fine.

**Comment by ejeschke** [comment]
@montefra, I've released a new version today with quite a few updates. FYI.

**Comment by montefra** [comment]
Thank you for the info. I'll check it asap
