### ISSUE TITLE
PixTable values run together and cut off

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#373]
For very large pixel values, the numbers run together, so it is hard to tell one value separate from a neighboring value. Maybe using E representation would help in this case.

Also, on my screen, the right side is cut off from view. It used to have a horizontal scroll bar, so that at least I could scroll to the right and see the cut off values. But now there is no scroll bar anymore.

Screenshot attached:
![screenshot](https://cloud.githubusercontent.com/assets/2090236/18843807/8f89412e-83e8-11e6-9175-77f0ff1a76fb.png)

**Comment by ejeschke** [comment]
This is fixed in commit 1ec2cd8a5ce827523bcb7849845eb059d512f5fe
