### ISSUE TITLE
Plot table data

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#379]
Now that we have a table viewer (#370), the next logical thing to do is to enable some sort of basic plotting. For example, user starts a plugin for such a plot, select a column for X axis, then another for Y axis, and a plot would show up in the plugin. This would be useful to visualize spectrum data (wavelength vs flux).

This is just an idea. Personally, I just read the table in and plot it with `matplotlib` from within a Python session. But I can see that some users who are not Python-savvy might like such a thing.

If this is out of scope, feel free to close.

**Comment by pllim** [comment]
I'll try to make a prototype to see if this can work.

**Comment by ejeschke** [comment]
That seems logical, and not too difficult of a problem.  Would you provide options for the user to select the axis scaling, etc.?

**Comment by pllim** [comment]
I will start with a very basic prototype first. Bells and whistles can always be added later, if necessary.
