### ISSUE TITLE
Cannot scroll in colormap picker

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#381]
I notice that there is a new global plugin to pick colormap. It is very nice. But the list extends beyond plugin area and I cannot scroll up and down to access the full list.

**Comment by ejeschke** [comment]
@pllim, did you try the mouse scroll wheel or trackpad?  You can also pan in the window using the usual Ginga panning methods--the latter is not ideal.  I'm thinking about adding some key handling also to page up and down through the list.

**Comment by pllim** [comment]
@ejeschke , trackpad works but not very intuitive without a visible scroll bar. Also the trackpad scrolling does not stop at the top/bottom of the list, it just keeps going.

**Comment by ejeschke** [comment]
@pllim, I added a hard stop to the scrolling.  I agree that a GUI scrollbar would be more useful.  I am working on that with somewhat low priority.

**Comment by ejeschke** [comment]
Scroll bars have been added.  Closing.
