### ISSUE TITLE
Automatically display table if file has no image?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#386]
Since now Ginga has a basic table viewer, when an input file only contains table (or table and primary header), it would be convenient to have Ginga automatically opens the first table extension instead of displaying just the primary header (thus needing user to manually open `MultiDim` to display the table).

**Comment by ejeschke** [comment]
I think we will need to make some changes to the data type autodetect.  This code is in `Control.py` and is already somewhat convoluted--probably be a good idea to refactor it.  Basically, it needs to decide based on "file type" (e.g. mime type, extension, etc) or HDU type (after determining the file is a FITS file and accessing the relevant HDU) what type of object to create: `AstroImage`, `RGBImage` or `AstroTable`.

If it is a file, then it needs to call `load_file()` on that file; if an HDU, `load_hdu()`.

**Comment by pllim** [comment]
Thanks for the info, @ejeschke . I'll work on this.

**Comment by pllim** [comment]
Should be fixed by #397.
