### ISSUE TITLE
Allow loading of the reference viewer from a script

### ISSUE THREAD

**Issue by Cadair** [ejeschke/ginga#388]
I have some data which is not in FITS files but I would like to load into the reference viewer, it's multidim data, I have a dict and a 4D array. I would really like to be able to do something like:

``` python
from ginga.main import ReferenceViewer

r = ReferenceViewer()
r.main(data, header)
```

Looking at the code for the reference viewer this looks like it might be a little bit of a fiddle, do you have any suggestions?

(FWIW, the data is loaded independently of the header from a raw binary file, so a reader would be a major pain as well)

**Comment by pllim** [comment]
FWIW, over at Glue, users are allowed to define their own data readers (see http://glueviz.org/en/stable/customizing_guide/customization.html#custom-data-loaders). That would be a better solution for the long run if Ginga is to support non-standard formats.

**Comment by ejeschke** [comment]
@Cadair, you can check out the [Jupyter notebook examples on doing this](https://github.com/ejeschke/ginga/blob/master/ginga/examples/ipython-notebook/Remote_control_of_a_Ginga_reference_viewer.ipynb).

I just tried this with Python 3 and found it has some issues (planning to file an issue on that), but you can test it on Python 2 if that works for you.

**Comment by ejeschke** [comment]
I think the very last example is what you are looking for.  You can pass a dictionary with the header data, but I think there are some restrictions on the kind of things that can be in the header, based in the fact that it is communicating with the viewer via xml-rpc.

**Comment by pllim** [comment]
@ejeschke , but using notebook loses access to plugins like `LineProfile`, right?

**Comment by ejeschke** [comment]
The notebook I listed shows how to connect to the reference viewer running the usual plugins.  I just used a notebook to put together the "client" example.

**Comment by ejeschke** [comment]
@Cadair, python 3 issue I referred to above is fixed.  Assuming you started the `RC` plugin (from the plugins menu or when starting ginga just add `--modules=RC`) you can do what you are asking with:
```python
from ginga.util import grc
viewer = grc.RemoteClient('localhost', 9000)
ch = viewer.channel("Image")
ch.load_np("image1", data, 'fits', header)
```

There is more info in [the manual page for the RC plugin](http://ginga.readthedocs.io/en/latest/manual/plugins_global/rc.html)
