### ISSUE TITLE
Display RA and DEC lines on display

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#391]
As discussed during JWST Data Analysis Workshop II on Nov 9, 2016. We can have a local (or global?) plugin that can toggle lines connecting RA and DEC tickmarks across the image, accounting for any WCS distortion. Maybe also allow user control; e.g., how finely to space those lines, line style, line color, or line thickness.

**Comment by pllim** [comment]
Note: Similar visualization already possible on https://reproject.readthedocs.io/en/stable/

**Comment by ejeschke** [comment]
I think `reproject` just reprojects images, right?  It doesn't draw graphical lines.  Are you thinking of `wcsaxes`?

**Comment by pllim** [comment]
Ah, yes, you are correct -- https://wcsaxes.readthedocs.io/en/latest/overlaying_coordinate_systems.html
