### ISSUE TITLE
How does Ginga handle memmap-ed FITS handlers?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#392]
As discussed during JWST Data Analysis Workshop II on Nov 9, 2016. Does Ginga close FITS handlers properly when `memmap=True` (default)? See http://docs.astropy.org/en/stable/io/fits/#working-with-large-files 

*When opening a file with memmap=True, because of how mmap works this means that when the HDU data is accessed (i.e. hdul[0].data) another handle to the FITS file is opened by mmap. This means that even after calling hdul.close() the mmap still holds an open handle to the data so that it can still be accessed by unwary programs that were built with the assumption that the .data attribute has all the data in-memory.*

*In order to force the mmap to close either wait for the containing HDUList object to go out of scope, or manually call del hdul[0].data (this works so long as there are no other references held to the data array).*

**Comment by pllim** [comment]
Well, I think I answered my own question... See STScI-JWST/wss_tools#26

@ejeschke , how do I set `memmap=False` in Ginga reference viewer? I don't see any way to actually do that currently without changing `GingaShell.load_image()` code in `Control.py`.

**Comment by ejeschke** [comment]
@pllim, in the `ginga.util.io_fits` module, the appropriate methods have a `memmap` kwarg that is passed to the opener.  Furthermore, that keyword can be passed as part of the kwargs in `Control`'s `load_image()` which is the basis for loading most files (as you note above).  

So there is a mechanism for passing it in, but it is currently not used.

The default is `None` in `io_fits`.  My understanding that unless `memmap=False` the default is `True` for astropy.  So I think it is being turned on by default.

Are you thinking of making a setting in `general.cfg` or something?

**Comment by pllim** [comment]
Either "general.cfg" or "channel_Image.cfg" is fine by me. Another option is command line argument but I think config setting is more elegant.

**Comment by pllim** [comment]
By the way, it does default to `memmap=True`: https://github.com/astropy/astropy/blob/master/astropy/io/fits/file.py#L86

```python
memmap = True if memmap is None else memmap
```

This line was added 3 years ago (according to "git blame"), so this is not something terribly new.

**Comment by pllim** [comment]
Or... we can just force `memmap=False`. Does Ginga really need `memmap`?

**Comment by ejeschke** [comment]
Well, in my own testing, `memmap=False` is actually faster for the case of mosaicing, or any typical use case in Ginga.  So maybe we can consider to set the default to `False`.  Can you see whether that solves your issue?

**Comment by ejeschke** [comment]
When I set the default to False in `io_fits` I don't see any difference, except that it seems a little snappier loading files.

**Comment by pllim** [comment]
Actually, `memmap=False` didn't solve my problem. For whatever reason, mosaicking 624 files somehow exceeded system limit and I don't have privilege to up the limit.
```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63376
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I have `numImages=0` (unlimited) set in Ginga because I fear the mosaic itself would fall out of cache, but as a result, all the input images also stay in cache (open). However, I don't understand how mosaicking 624 images would exceed the limit of 1024, as 624 inputs plus one mosaic should  be 625.

**Comment by pllim** [comment]
Turns out my problem can be solved without any code changes (see below), so feel free to close #501 if you don't want it. And I guess you can close this too now if you want. Thanks!

**SOLUTION**

Make the following changes in `~/.astropy/config/astropy.cfg` under `[io.fits]` section and save your changes:
```python
use_memmap = False

lazy_load_hdus = False
```

**Comment by pllim** [comment]
My original question is answered.
