### ISSUE TITLE
MultiDim: Play button broken for playing through image cubes

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#406]
The play button in the `MultiDim` plugin appears to be broken for playing through image cubes.  All the other controls seem to work: First, Last, Next, Prev, etc.

The symptom is either slow playing or no playing, followed by a viewer freeze.

**Comment by pllim** [comment]
Just curious... Is this using FITSIO or `astropy.io.fits`?

**Comment by ejeschke** [comment]
`astropy.io.fits`.

**Comment by pllim** [comment]
Potential fix in #408.

**Comment by ejeschke** [comment]
@pllim, could you try current commit in master.  I think it fixes this issue nicely.  I am no longer able to crash or freeze the viewer, and it simply caps out at whatever the maximum FPS is possible.  Moreover, the viewer remains quite responsive while the movie is playing.

**Comment by pllim** [comment]
Yes, that is very nice. Thanks!
