### ISSUE TITLE
FBrowser does not open selected image when table is displayed

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#409]
`FBrowser` no longer works (does not open selected image) when it is started from "global plugins" menu *and* a table is being displayed. It works properly when opened from "Operations" as local plugin.

**Comment by ejeschke** [comment]
@pllim, I believe this is fixed in 703f8d814994b8337c198363e3a8cd57fcafeeb5.  When you get the chance, can you please confirm? Tnx.

**Comment by pllim** [comment]
Yes, it works now. Thank you!
