### ISSUE TITLE
Cannot draw polygon anymore

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#411]
In `Drawing` plugin (and any other plugin using shapes), I can no longer draw a polygon by pressing "v" to add a vertex. I am using Qt5 on RHEL6.

**Comment by ejeschke** [comment]
@pllim, do you have an error message or something to go on?  I just tested with `-t qt5` on Ubuntu 16.04--no problem drawing a polygon.

**Comment by pllim** [comment]
I did a fresh install. And I cannot reproduce this problem anymore. Never mind! :sweat_smile:

**Comment by ejeschke** [comment]
I just tested on Mac OS X with Qt5.  Seems ok.

**Comment by ejeschke** [comment]
Might have been an issue where the ginga widget didn't have the keyboard focus for some reason.

**Comment by pllim** [comment]
Could be. I had like 20 different windows open. Now only down to 5. :smile:
