### ISSUE TITLE
No handlers found for logger after ginga installation on mac

### ISSUE THREAD

**Issue by TomProm** [ejeschke/ginga#414]
Hello, I installed anaconda and ginga using pip as described but after launching only half of the functionality is available. Unfortunately the one I would need like "Pick" or the WCS is not available. 

Now I am a bit stuck as i suspect from reading other issues that it might be a version issue between different installed python versions and astropy but unfortunately I am not proficient enough to know where to lok and how to fix it.

Thanks for helping
Thomas

This is the error message I see on the terminal after launching:

$ ginga

** (process:9329): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:9329): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:9329): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'

(process:9329): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
No handlers could be found for logger "ginga"

**Comment by ejeschke** [comment]
@TomProm, if you installed using anaconda, try the `Qt` toolkit instead--I think it is much better supported on the Mac.  Try invoking ginga with the `-t qt4` or `-t qt5` options.  Let me know how these work.

The "No handlers could be found for logger "ginga"" message is normal if you don't specify any logging options when starting it.  It will not affect anything.

**Comment by TomProm** [comment]
Hello, thanks for the fast response. This unfortunately did not work either. 
The error is copied below, it seems to not find the right path ..

Additional information:
After installation, in order to make it work I already had use the macports version of python, which was achieved by modifying the ginga script to call /opt/local/bin/python2.7 rather than /usr/bin/python.

Because ginga was installed using pip, maybe astropy is still with a wrong link?

Thanks for the help!
Thomas

Here is the output when I try invoking qt5 (qt or qt4 showed the same):

$ ginga -t qt5
No handlers could be found for logger "ginga"
Traceback (most recent call last):
  File "/usr/local/bin/ginga", line 11, in <module>
    load_entry_point('ginga==2.6.0', 'console_scripts', 'ginga')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga/main.py", line 590, in _main
    reference_viewer(sys.argv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga/main.py", line 585, in reference_viewer
    viewer.main(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga/main.py", line 316, in main
    from ginga.gw.GingaGw import GingaView
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga/gw/GingaGw.py", line 15, in <module>
    from ginga.gw import GwHelp, GwMain, PluginManager
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga/gw/GwHelp.py", line 8, in <module>
    from ginga.qtw.QtHelp import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ginga/qtw/QtHelp.py", line 94, in <module>
    raise ImportError("Failed to import qt4, qt5 or pyside. There may be an "
ImportError: Failed to import qt4, qt5 or pyside. There may be an issue with the toolkit module or it is not installed

**Comment by pllim** [comment]
@TomProm , you said you installed Anaconda but then you were using Mac's version of Python. That does not sound right. You should be using the Python that came with Anaconda, e.g., `/my/anaconda/install/path/bin/python` or if you use conda environment, `/my/anaconda/install/path/envs/envname/bin/python`. When you want to install Ginga into Anaconda, you also  have to use `pip` that comes with Anaconda (or the conda environment).

**Comment by ejeschke** [comment]
@TomProm, yes it doesn't really work to mix macports and anaconda libraries.  You can run ginga with either macports or anaconda, but it is just easier with anaconda because it already comes with everything needed.

**Comment by ejeschke** [comment]
@TomProm, any progress?

**Comment by TomProm** [comment]
Hello, 
yes this worked.  Had to do manually:

conda install -c astropy ginga=2.6.0

unset PYTHONPATH

Thanks for the fast and great support!
Thomas

**Comment by ejeschke** [comment]
Great, glad to hear you got things working.
