### ISSUE TITLE
Error converting profile: ImageCms not defined

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#416]
I have `pillow` 3.4.2 installed under Anaconda for Python 3.5.2 using Qt5, the latest dev version of Ginga. OS is RHEL6 64-bit.

When I click on `Operations`, then `Preferences`, scroll down to `ICC Profiles`, and select "AdobeRGB" as "Output ICC profile", I get this on the terminal but no error in log file:
```
Error converting profile from 'working' to 'AdobeRGB':
    Failed to build profile transform: name 'ImageCms' is not defined
```

I was not doing anything in particular. Just was randomly playing with preferences. Maybe I have a missing dependency for this, but the error is obscure to me.

More info:
```python
>>> import PIL
>>> PIL.__version__
'3.4.2'
>>> import PIL.ImageCms as ImageCms
.../PIL/ImageCms.py in <module>()
     22 try:
---> 23     from PIL import _imagingcms
     24 except ImportError as ex:

ImportError: cannot import name '_imagingcms'

During handling of the above exception, another exception occurred:

.../PIL/ImageCms.py in <module>()
     25     # Allow error import for doc purposes, but error out when accessing
     26     # anything in core.
---> 27     from _util import deferred_error
     28     _imagingcms = deferred_error(ex)
     29 from PIL._util import isStringType

ImportError: No module named '_util'
```

The error above sounds like ContinuumIO/anaconda-issues#371 that is apparently fixed in conda/conda-recipes#342, so why am I getting this error?

**Comment by ejeschke** [comment]
Sometimes the LittleCMS component is installed separately from PIL/pillow, although in most distributions it should be included.  I think we certainly could output a more useful error message.

And probably these comboboxes should be disabled unless the module is installed.
