### ISSUE TITLE
New save_layout option feedback

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#417]
@ejeschke , I tried out the new `save_layout = True` option in `general.cfg`. Overall, I like it as well as I also tend to resize my window, so this will save some time. Some comments:

* When I first use it, I got an error message `Desktop.py:627 (build_desktop) | Error reading saved layout: [Errno 2] No such file or directory: '~/.ginga/layout'`. I think Ginga should just create it silently if it does not yet exist instead of throwing out an error.
* The first session using it, I was unable to resize the window vertically. But then I restarted the application, that the problem went away. Not sure if that was related.
* It seems to remember main window size and workspace option. :+1: 
* It does **not** remember which monitor (I have dual-monitor display) nor position of Image channel on MDI workspace (I moved the channel window to bottom right but it went back to top left in the next session). Perhaps out of scope but I just want to point it out.
* As you said before, it does not remember how many other channels I opened. Although would be a nice enhancement as that will save me the work of opening up extra channels in the next session.

In my own work, I rarely work on MDI workspace nor have multiple channels. So the existing functionality is already pretty nice. Thank you!

**Comment by ejeschke** [comment]
> When I first use it, I got an error message Desktop.py:627 (build_desktop) | Error reading saved layout: [Errno 2] No such file or directory: '~/.ginga/layout'. I think Ginga should just create it silently if it does not yet exist instead of throwing out an error.

I agree, and I'm not sure why this error doesn't just appear in the normal logged output.  But I haven't looked into it yet.

> The first session using it, I was unable to resize the window vertically. But then I restarted the application, that the problem went away. Not sure if that was related.

I find that with Qt, sometimes the first time it reads the saved result it makes an odd-sized box for the toolbar. BUT, on subsequent looks as expected.  This sounds like a similar problem in that it appears after the first session, and disappears thereafter.

 > It does not remember which monitor (I have dual-monitor display) nor position of Image channel on MDI workspace (I moved the channel window to bottom right but it went back to top left in the next session). Perhaps out of scope but I just want to point it out.

Interesting.  I think this was handled correctly on my dual-monitor setup.  It may depend on how the windows are handled in X.  Do you have them set up as separate displays or as one large space?

**Comment by pllim** [comment]
>  Do you have them set up as separate displays or as one large space?

How do I find out? ITSD set it up for me, as I don't have root access. I can drag a window from one display to another. But the task bar is only visible on one of them.

**Comment by ejeschke** [comment]
Type `?dpyinfo` into a terminal.  Is there just one "screen" with a large resolution?

**Comment by ejeschke** [comment]
That should be `xdpyinfo`.

**Comment by pllim** [comment]
`number of screens:    1`

**Comment by ejeschke** [comment]
> When I first use it, I got an error message Desktop.py:627 (build_desktop) | Error reading saved layout: [Errno 2] No such file or directory: '~/.ginga/layout'. I think Ginga should just create it silently if it does not yet exist instead of throwing out an error.

I've changed this to be an Info level message and not an Error level one.

I'd like to make this feature standard in the next release.  Regarding what information to save and restore, let's take it up in #482.
