### ISSUE TITLE
Feature Request: RC generation of a Graphics Object in a Channel

### ISSUE THREAD

**Issue by profxj** [ejeschke/ginga#420]
I would like to be able to add one or more Graphics objects
on the canvas of a given Channel via RemoteControl.  For example,
the ability to draw a line connecting an input set of (x,y) points.

If I understand the current implementation of RC correctly (have examined it
but haven't fully digested it), then I would need to add a new method to Channel
to enable this.  But perhaps another approach would be preferable.

If you provide some guidance, I'll try to implement.  Thanks.

**Comment by pllim** [comment]
Can you use plugins in RC? If so, you can just fire up the `Drawing` plugin and draw whatever you want.

**Comment by profxj** [comment]
Indeed, that works fine (Plug-ins do work in RC).
But I have a 'custom' curve in memory and wish to overlay that on my image.

One (not as elegant) way would be to write that curve to disk and then read it
in with a Plug-In and overplot.  But I should prefer to use RC if possible.

**Comment by pllim** [comment]
If scripting is what you need, maybe you are better off with Ginga's Jupyter notebook interface. Then, you can just create a notebook to draw that curve that you need, and update your image on notebook as needed. If I remember correctly, the notebook also supports remote connection.

**Comment by pllim** [comment]
If you are interested in the notebook approach, you might also be interested in [imexam](http://imexam.readthedocs.io/en/latest/), which has a [Ginga interface](http://imexam.readthedocs.io/en/latest/imexam/examples.html#usage-with-ginga-viewer).

Or, if you want to use `imexam` from Ginga reference viewer (not notebook), there is also an [Imexam plugin](https://github.com/ejeschke/ginga/blob/master/experimental/plugins/Imexam.py) you can "install" yourself. FYI.

**Comment by ejeschke** [comment]
Would something like a file interface work?  In other words, if you put the object types with parameters in a file and then had a command for ginga to process the file?  This could be combined with an option for `Drawing` to save such files, but of course with the right format you could create the file programmatically or even manually.  I think Ginga definitely needs something like that.

Or do you want something where the object and its coordinates can be specified on the command line?

**Comment by pllim** [comment]
@ejeschke , re: file interface

Incidentally, I implemented some kind of JSON I/O for saving/loading `stginga` plugin parameters. If you are interested, the mixin class is [ParamMixin](https://github.com/spacetelescope/stginga/blob/master/stginga/plugins/local_plugin_mixin.py#L207) and [SNRCalc plugin](https://github.com/spacetelescope/stginga/blob/master/stginga/plugins/SNRCalc.py) shows an example on how to use it for the file interface feature.

**Comment by profxj** [comment]
This is all very helpful.  Am going to explore imexam a little and
quite likely close this Issue.  Much thanks.

**Comment by ejeschke** [comment]
> Incidentally, I implemented some kind of JSON I/O for saving/loading stginga plugin parameters. If you are interested, the mixin class is ParamMixin and SNRCalc plugin shows an example on how to use it for the file interface feature.

@pllim, sounds interesting, I will take a look!

@profxj, I think what you are suggesting is worth doing, because this is not the first time I've been asked about it.  I'm trying to think what approach would provide the most benefit.  If we could load graphics objects from some kind of serialized text format it might be super-useful to a lot of other users.  When you say you have "a custom curve in memory", what does that mean, exactly?  Since the reference viewer is running in a different process, we have to get the object parameters into some kind of format and send it to ginga.

**Comment by profxj** [comment]
Well, I have explored further (after examining the HTML5 interface which
is nice but not quite ideal).

Here is a simple example method that works if I add it to ImageViewerQT
(or ImageViewBase):

```
    def show_line(self, x, y):
        canvas = self.get_private_canvas()
        Path = canvas.get_draw_class('path')
        points = zip(x,y)
        canvas.add(Path(points, color='red'))
        return
```
I can then call it with lists for x and y,  e.g.

```
x = np.arange(50).tolist()
y = np.arange(50).tolist()
ch.show_line(x,y)
```

My concerns from here are:

1.  I may need to make quite a few of these methods (not such a big deal)
1.  I'd prefer to add them somewhere other than these high-level Classes, 
 but I'm not sure where.  Would it be best to sub-class ImageViewQT?

Anyhow, I'm close to heading this way, but should prefer to do it
in a way that the core developers approve of.

**Comment by ejeschke** [comment]
> I may need to make quite a few of these methods (not such a big deal)

It doesn't really make sense to duplicate all the calls you can make to a canvas object and put them in the viewer object.  It would be better to add a method to the  [`RC`](https://github.com/ejeschke/ginga/blob/master/ginga/rv/plugins/RC.py) plugin to expose the canvas. Example:
```python
def add_canvas_obj(self, chname, typename, *args, **kwargs):
        chinfo = self.fv.get_channel(chname)
        canvas = chinfo.viewer.get_canvas()
        klass = canvas.get_draw_class(typename)
        obj = klass(*args, **kwargs)
        return self.fv.gui_call(canvas.add, obj)
```

I still think it would be useful to add a way to serialize the canvas items so that they can be saved and loaded.  It would be more generally useful.

**Comment by profxj** [comment]
Excellent suggestion.  I have now submitted PR #425 in response.

I agree that serializing the Canvas items would be useful but that calls
for a separate thread and PR.  Will let you know if I choose to take it on.

**Comment by profxj** [comment]
Closing
