### ISSUE TITLE
IRAF plugin cannot load on Windows

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#421]
I see this error when starting Ginga on Windows 7 (64-bit). Not that I plan to use IRAF on Windows (a deadly combination), still the error suggests that the plugin code is not compatible with Windows OS.

```
2016-12-29 13:25:28,782 | I | ModuleManager.py:53 (loadModule) | Loading module 'IRAF'...
2016-12-29 13:25:28,785 | E | PluginManager.py:70 (loadPlugin) | Failed to load plugin 'IRAF':
    module 'os' has no attribute 'getuid'
```

Also see: http://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python

Looks like the offending code is on [Line 1081 in IIS_DataListener.py](https://github.com/ejeschke/ginga/blob/master/ginga/rv/plugins/IIS_DataListener.py#L1081). Does not look that it is meant to support Windows at all. Perhaps it will be more elegant to avoid loading IRAF plugin at all on Windows?

**Comment by ejeschke** [comment]
But otherwise it seems ok on this platform? I have no Windows machines to test on.

**Comment by ejeschke** [comment]
I think there is probably another way other than getuid()

**Comment by pllim** [comment]
As I noted above (in my edit), I don't think IRAF plugin should load at all on Windows. Otherwise, Ginga seems okay, but I will report more if I see more problems.

**Comment by ejeschke** [comment]
I think you can use the IRAF plugin with IRAF running on a different host.  In that case I think it would be fine to run it on Windows.  And if it is possible to run IRAF on Windows then I suppose people might want that combination...

**Comment by pllim** [comment]
Since IRAF is moved to experimental, we can close this as "won't fix".
