### ISSUE TITLE
Ruler pixel precision too long

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#422]
In the Ruler local plugin, when unit of pixel is specified, the display value precision is too long (especially those in yellow). I think `%.1f` should be enough for pixel value.

Example screenshot:
<img width="246" alt="untitled" src="https://cloud.githubusercontent.com/assets/2090236/21553807/a1345046-cdd8-11e6-86fc-0acce3cf9770.png">

**Comment by ejeschke** [comment]
I suppose it depends on the application, but I agree this is too long.  How about `%.2f` for the default?

**Comment by pllim** [comment]
Sure. Even `.3f` (the green one) is tolerable but I don't see much point in that myself. Thanks for the quick response!

**Comment by ejeschke** [comment]
@pllim, how about when "degrees" is chosen as the unit?  What do you think the default precision should be?

**Comment by ejeschke** [comment]
Can you try master and see if the chosen precision's are reasonable?  I'm not sure it is worth the work to make these preferences, but that is also a possibility if someone complains.

**Comment by pllim** [comment]
@ejeschke looks much better now. Thanks! I agree that it does not have to be a user preference.

![screenshot-1](https://cloud.githubusercontent.com/assets/2090236/23761073/a2d37576-04bf-11e7-9cf6-baa86608abcd.png)

I think "degrees" is fine as is, as the precision varies from detector to detector. I don't really use that one. Does it account for distortion?

**Comment by ejeschke** [comment]
> Does it account for distortion?

Only insofar as the WCS does.  If the WCS has a reasonable distortion solution mapped in, then the distance in degrees will be reasonable accurate.
