### ISSUE TITLE
LineProfile feedback

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#427]
@ejeschke , I am using latest dev of Ginga including your changes in 00bcc853ed9159d17dde003e33be2a7ecd6b834c. I find that:

- [ ] NAXISn does not have a default value on start-up or image change or defocus, resulting in error messages. Maybe should default to NAXIS3?
- [ ] Y-axis label "flux" is not always accurate representation of the data. I don't have a good alternative label that is general enough though.
- [x] ~~The plugin does not work for other image cubes that I have. One is an IRIS image provided by SunPy when this plugin was developed some time ago. Another is a fake JWST image cube.~~ EDIT: It was a fluke. I restarted Ginga and it works now.

**Comment by ejeschke** [comment]
> The plugin does not work for other image cubes that I have. One is an IRIS image provided by SunPy when this plugin was developed some time ago. Another is a fake JWST image cube.

Indeed, the plugin does not work for me for image cubes that don't have the proper keywords, primarily because it uses these to construct the X-axis data for the plot.  Hoping we can come up with a decent "default" for these types of images.

> Y-axis label "flux" is not always accurate representation of the data. I don't have a good alternative label that is general enough though.

I understand and agree, but I also am not sure of a better solution for that at the moment.

**Comment by ejeschke** [comment]
> NAXISn does not have a default value on start-up or image change or defocus, resulting in error messages. Maybe should default to NAXIS3?

That would make sense to me.

**Comment by pllim** [comment]
> Indeed, the plugin does not work for me for image cubes that don't have the proper keywords, primarily because it uses these to construct the X-axis data for the plot. Hoping we can come up with a decent "default" for these types of images.

Sorry, the plugin not working was a fluke. I updated my original issue above. Seem to work after I restarted Ginga but whether the values displayed are correct or not, I cannot sure sure because (a) I am not familiar with SunPy data (b) the JWST image is fake.
