### ISSUE TITLE
How to place each image in a different channel from command line

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#428]
Is it possible to place each image in a different channel in the reference viewer from command line? I notice that there is a `-c` option for channels and I can also specifically request what image(s) to open by providing their names as a comma-separated string at the end of the command, but I don't know how to use both to do what I want here.

For example, I have `image1.fits` and `image2.fits`. I want the first image to be in `Image` channel, and the second to be in `Image0` channel. All done from a single command line. Is this possible?

**Comment by ejeschke** [comment]
Currently not, but it would be a trivial modification.  And I think it would be very useful, especially with an option to specify the initial workspace type for 'channels'  (i.e. `--wstype=grid`)

We could also make a way so that when you drag and drop a group of files that they show up in different channels.  I've often wanted that.

**Comment by pllim** [comment]
Either command line or drag-and-drop is fine. Perhaps the latter is more flexible. Currently, the does not appear to be any one-step way to do this.

**Comment by ejeschke** [comment]
There is a `for` loop in `main` that loads the command line files.  That just needs an extra parameter or call to specify the channel.  I'll take a look at this.

**Comment by ejeschke** [comment]
@pllim when you get a chance, try latest master using `--sep` option on the command line, e.g.
```bash
ginga --sep file*.fits
```

**Comment by pllim** [comment]
@ejeschke , it works. Thanks! As a follow up, I also expanded the command line functionality in #429.
