### ISSUE TITLE
Blink should not blink when no image is loaded

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#432]
When I start `Blink` local plugin without any image loaded in a channel, I get non-stop error messages until I press the stop button:

```
2017-02-02 16:37:11,297 | E | Channel.py:243 (next_image) | No next image!
2017-02-02 16:37:12,297 | E | Channel.py:243 (next_image) | No next image!
2017-02-02 16:37:13,298 | E | Channel.py:243 (next_image) | No next image!
...
```

IMHO the plugin don't need to start blinking if there is no image loaded.

**Comment by ejeschke** [comment]
I think it starts automatically.  It should be an easy fix to check whether there is an image present and decline to start unless there is.

**Comment by ejeschke** [comment]
But it probably should only do that if started in local mode.

**Comment by ejeschke** [comment]
@pllim, could you try latest master and see what you think of Blink plugin improvements?

It now checks whether there are multiple images before blinking in local mode, and doesn't automatically resume blinking if you switch focus away from the plugin to another and then back.

**Comment by pllim** [comment]
@ejeschke seems to work fine for me now. Thanks! However, what does the "Max: 30.0   Min: 0.25" mean? There is no tooltip and also not mentioned in Help.

**Comment by ejeschke** [comment]
I'd better add a tooltip then.  Those are simply the min/max allowable values for the blink interval.  Set as preferences and simply reported there so the user knows that they can't exceed them.
