### ISSUE TITLE
How to temporarily rebind arrows to go to next pixel?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#435]
Currently, up-down-left-right on keyboard cycle through images within a channel or across multiple channels. I find myself in a situation where I am very zoomed in on an image and have cursor painstakingly centered on a pixel. Now, I want to just press up-down-left-right to inspect neighboring pixels. Is there a way to do this? Maybe a `modifier + arrow` to temporarily enable this?

**Comment by ejeschke** [comment]
@pllim, there is something almost like this.  If you go into Pan mode (pressing 'q') and then hold Shift+Ctrl and press an arrow key it will move a small amount in the direction you want (but not exactly one pixel).  The amounts of movement are measured in screenfuls or fractions thereof (I think no modifier == 2/3 of a screen or something like that), the fractions being multiplied (becoming yet smaller) by adding shift or ctrl.  

It would be pretty easy to add a similar binding/command that moves exactly one pixel.  The question is whether that should be a mode, or a plugin, and if it is a plugin, what kind.  presumably the user might want to define another unit than 1 pixel.

**Comment by pllim** [comment]
@ejeschke , I am okay with either plugin or binding, whichever is easier to implement. The binding might also benefit people using Ginga via notebook (will it?) while plugin definitely will not.

Anyway, this is not urgent. Just something I sometimes wish it is nice to have.

**Comment by ejeschke** [comment]
Could you try commit 19b2d0c52f76190a4e9301cf58ab439bdde18dcc?

Hold Shift while using the arrow keys to move 1 pixel. Unlike the pans described above, these bindings always move you:
* Shift+Left: minus 1 pixel in the X dimension
* Shift+Right: plus 1 pixel in the X dimension
* Shift+Down: minus 1 pixel in the Y dimension
* Shift+Up: plus 1 pixel in the Y dimension

Press Shift+Home to center on the pixel.

**Comment by pllim** [comment]
@ejeschke , I find that even though the screen moves when shift + arrow is pressed, the plugins do not get that update. For instance, "Value" at the bottom does not change and `PixTable` does not update.

**Comment by pllim** [comment]
In addition, I had to delete my old `~/.ginga/bindings.cfg` file for this to work. Does that mean that if I have custom binding, I need to update it somehow?

**Comment by ejeschke** [comment]
>  I find that even though the screen moves when shift + arrow is pressed, the plugins do not get that update. For instance, "Value" at the bottom does not change and PixTable does not update.

Well, I think that is because it only changes the pan position.  What update are your plugins responding to?  A new image arriving in the channel?  Mouse movement?

**Comment by ejeschke** [comment]
> In addition, I had to delete my old ~/.ginga/bindings.cfg file for this to work. Does that mean that if I have custom binding, I need to update it somehow?

Currently, a custom binding completely replaces the built in one.  So, yes, you would need to merge in the new bindings into your custom one.  Which reminds me that I need to add these bindings to the examples files (perhaps after we've figured out exactly what it is that they are supposed to do).

**Comment by pllim** [comment]
> Well, I think that is because it only changes the pan position.

But even the "Value" in the info bar does not change. It changes when I move the cursor or pan around.

As for plugins like `PixTable`, it changes when I move cursor around but not when I pan. Not sure what event to listen to, but I feel that `PixTable` should reflect what is being displayed (unless locked).

**Comment by ejeschke** [comment]
> But even the "Value" in the info bar does not change. It changes when I move the cursor or pan around.

The Cursor plugin (which is responsible for the "Value") registers with a callback that is responding to mouse movement.  Moving the pan position from the keyboard does not change the mouse cursor position (relative to the screen).  It does possibly change it relative to the data under the cursor.  But this change would have to be detected in a different way than we do now.

Are you thinking that the arrows should directly warp the mouse cursor to a new location (in other words, the cursor moves, and not the data under the cursor)?  That might be somewhat disorienting for the user (try to think of another program that actually moves the mouse cursor without you touching the mouse).  This capability does exist in Ginga (Qt/Gtk), but is only used in the freepan mode, and I'm not entirely sure it is a good thing.

Perhaps we could figure out a way to add a callback for when the cursor moves relative to the previous position even if the user does not touch the mouse or keyboard. I need to think a bit about how to accomplish that...

**Comment by ejeschke** [comment]
One idea that might be fairly straightforward is to have a cursor that is not directly tied to the mouse cursor (think of, for example, the cursor in a VNC window and the local cursor).  The canvas cursor could be made to follow the mouse or keyboard or programmed control.  And you could have a callback for its movement around the canvas.

Or we could have a callback for when the pan position changes.  But then would you want the position under the cursor, or under the pan position?  For the former we would need to be able to query the current mouse position.  Pretty sure this is straightforward under most toolkits.

**Comment by pllim** [comment]
@ejeschke , I prefer the first idea of "a cursor that is not directly tied to the mouse cursor".

**Comment by ejeschke** [comment]
> Perhaps we could figure out a way to add a callback for when the cursor moves relative to the previous position even if the user does not touch the mouse or keyboard.

This now looks straightforward, and may actually solve one or two other nagging issues. Stay tuned.

**Comment by ejeschke** [comment]
@pllim, can you try commit fc74dea1e02bde2bfd8a337795aa6dc2c9a7a835 ?

**Comment by pllim** [comment]
This is perfect! Is it still necessary to define the shift + arrow explicitly in a custom binding?

**Comment by ejeschke** [comment]
> Is it still necessary to define the shift + arrow explicitly in a custom binding?

Yes.  We could consider a plan to allow preference files to be merged, but that gets into some issues of deciding what overrides what.  Maybe a future enhancement?

**Comment by pllim** [comment]
@ejeschke , that is fine. Please let me know when you have the binding examples updated. Would like to use this with DS9 binding. :smile:

**Comment by ejeschke** [comment]
I think the ds9 binding was updated yesterday.

**Comment by pllim** [comment]
Yes, I see that now. Thank you!

**Comment by ejeschke** [comment]
@pllim, try the shift+home binding.  I updated it yesterday and it now moves the image so that the cursor is centered on the pixel.  This maybe useful in conjunction with the shift+arrows.

**Comment by pllim** [comment]
@ejeschke , just tested it with latest master. It is great addition. Thank you!

**Comment by ejeschke** [comment]
You are welcome, @pllim.
