### ISSUE TITLE
Menu not responsive until Ginga is re-focused (Mac OSX)

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#441]
@jamienoss has OSX 10.11.6 (El Capitan) desktop and installed dev version of Ginga. Once Ginga is loaded, all file menu items are not responsive (not traceback given) until an external window in clicked (to defocus Ginga) and then click Ginga again (to refocus it). Only then, it works normally.

Python 3.5 with Qt 5.

**Comment by ejeschke** [comment]
I think this issue can be seen with other python apps on Mac OS X.  When this has happened to me, if I click the terminal window that spawned ginga then the menu items become accessible.  It seems to relate to some focus issue with Mac OS X.  I remember discussing this briefly with @astrofrog, that Glue sometimes experienced the same issue.  @astrofrog do you know anything more about this phenomenon?  Is it related to Qt or is it in general an issue with a python script popping up a new window and the focus not necessarily following?

**Comment by astrofrog** [comment]
This is related to how conda deals with GUI executables, see https://github.com/ContinuumIO/anaconda-issues/issues/446 - maybe consider leaving a comment there to say it affects you too, but sadly it doesn't look like much has happened there for a little while.
