### ISSUE TITLE
Save image as PNG/JPEG

### ISSUE THREAD

**Issue by migueldvb** [ejeschke/ginga#445]
Is there any plugin to export an image view to a PNG or JPEG image? It seems that the SaveImage plugin and `AstroImage.save_as_file` method do not support those formats.

**Comment by pllim** [comment]
Take a screenshot? :wink: 

What is your use case here? You can build RGB with "Compose" local plugin. Unfortunately, the RTD doc (http://ginga.readthedocs.io/en/latest/manual/plugins_local/compose.html) currently is not very informative but the plugin instructions should have basic info.

**Comment by ejeschke** [comment]
@migueldvb, both of the supported back ends for the reference viewer have a method to save the screen as a PNG, so programatically-speaking there is already support for that. 

I think this would be a fairly simple and short plugin to write.  You just need a text box for the file name and a button to save the file.  Then the callback for the button is just:
```python
def save_file_cb(self, path):
    self.fitsview.save_rgb_image_as_file(path, format='png')
```

With a little nicer error wrapping:
```python
def save_file_cb(self, path):
    self.fv.error_wrap(self.fitsview.save_rgb_image_as_file, path, format='png')
```

**Comment by migueldvb** [comment]
Thank you @plim @ejeschke 

To test this I have tried to write a script that reads a FITS image as an `AstroImage` object and used `save_rgb_image_as_file` on a view of all the pixels in the image but it does not work. Is there any example to save an AstroImage object as a PNG file for any of the backends?

**Comment by ejeschke** [comment]
@migueldvb, can you update your git repo from master and take a look at the new plugin called [ScreenShot](http://ginga.readthedocs.io/en/latest/manual/plugins_local/screenshot.html) ?

Is this more or less what you were looking for, or are you looking to script the creation of many RGB snapshots outside of the context of the reference viewer.  That is also fairly easily done.

**Comment by pllim** [comment]
@ejeschke , comments:

1. A "browse" button for the folder would be nice.
2. What if I want a screenshot of tiled images, either all in one channel or across multiple channels? I feel like this should be a global plugin to support the latter.

**Comment by migueldvb** [comment]
That is great, than you very much.

**Comment by ejeschke** [comment]
> A "browse" button for the folder would be nice.

I agree. I'm happy to accept any PR's (:smiley_cat:) if I don't get around to it soon!

> What if I want a screenshot of tiled images, either all in one channel or across multiple channels? I feel like this should be a global plugin to support the latter.

Yes, but that would actually require piecing together the separate images and recreating the tiled grid or whatever.  Since these aren't really larger than the screen window, you may just as well take a real screenshot of the whole reference viewer and edit out the bits you don't want.

**Comment by ejeschke** [comment]
We could maybe add a way to make a screenshot of every viewer and save them all as separate files... Not sure how often something like that would be used.  With this current plugin it probably covers the most common case of wanting to make a small number of quality PNGs for a publication.

**Comment by pllim** [comment]
> Not sure how often something like that would be used

Yeah, let's just leave that as an idea until someone actually uses it. :smile:
