### ISSUE TITLE
"Help" tab not always on the side

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#450]
I think it makes sense to have "Help" tab to be always on the side (preferably right, but left okay too). When I open Ginga, open "Help", and then open another channel, "Help" is sandwiched between the two channels, which appears to be an awkward position. I am also unable to manually drag it to the side, so it is stuck there.

Screenshot:
<img width="129" alt="untitled" src="https://cloud.githubusercontent.com/assets/2090236/25151611/2cc36b34-2454-11e7-9726-177601301ea3.png">

Note: If I manually close "Help" and then re-open, then it is on the right side again.

**Comment by ejeschke** [comment]
@pllim, I'm open to that.  But that does sort of rule out the possibility of using it nicely as an MDI window in the central workspace.  But maybe this could be solved by having a clear and easy way to move windows between workspaces. Dragging would be best, but I think it is problematic for Qt.

**Comment by ejeschke** [comment]
Perhaps I misunderstood.  When you say "right", and "left", do you mean just in the set of tabs of the workspace or the actual *workspaces* to the left and right of the central one?

**Comment by pllim** [comment]
Just the placement of the tab, as shown in screenshot.

**Comment by ejeschke** [comment]
In that case, I think this may be a super easy fix.  We just need to enable rearrangeable tabs when building a workspace.  I think this just requires us to add the parameter `reorderable=True`, [here](https://github.com/ejeschke/ginga/blob/master/ginga/gw/Desktop.py#L712).  You might try this and see whether you can then rearrange the tabs by dragging them.  Would that be acceptable?

**Comment by pllim** [comment]
> Would that be acceptable?

Sure! That is actually quite nice, because now I can also re-order other tabs everywhere in Ginga. :+1:

**Comment by ejeschke** [comment]
Excellent. 👌
