### ISSUE TITLE
Pixel value colorbar visibility

### ISSUE THREAD

**Issue by ysBach** [ejeschke/ginga#453]
As in the following figure, the counts (numbers) are not very visible in Ginga.
I think it is better to put the numbers outside of the colorbar like ds9.

![values](https://cloud.githubusercontent.com/assets/17214293/25223032/3671af2c-25f5-11e7-9f3e-154634c61fdd.png)

**Comment by ejeschke** [comment]
@ysBach, I agree.  And I think that should not be a difficult change. We basically just need to plot the numbers a little lower in the Y axis, outside the color bar.  I'll take a look at this.

**Comment by ejeschke** [comment]
@ysBach, could you try the most recent version from master (commit 2c0b15ed5a748d426eeef647105823e09100c3bf)?  Let me know your feedback.

**Comment by ysBach** [comment]
Thanks for such a fast feedback! :)

Things look better, but the left-most number is sometimes at the "too left" position.
As an example, I opened an image. Then I opened the same image but subtract by 0.1 and multiplied by 10^8 to see how the minus sign looks. 
![values](https://cloud.githubusercontent.com/assets/17214293/25253538/46794ef4-265c-11e7-9525-0e380a4d6968.png)


It is at least visible, but I think it can be improved if the numbers are placed at non-edge places as ds9, or shifted to the right side by few pixels (since the rightmost number is not interrupted by the right side terminator). In the following figure, I compared ds9 and ginga:
![values_comp](https://cloud.githubusercontent.com/assets/17214293/25253913/fcf62dc2-265d-11e7-8063-d165cf6f260e.png)

While comparing these, I found the colorbar of ginga is not enclosed in a box as ds9 or default colorbar of matplotlib so the "whiter" part is not distinguishable from background color (this can be other issue but..). 

I also guess it'd be better if these numbers are as large as that of the bottom side (which has alpha, delta, X, Y, and value). The numbers for colorbar is slightly smaller than ds9 on my computer. Since larger fontsize may make the numbers "hit the boundary" of the panel, one suggestion is to reduce the number of significant figures to 2~3 as ds9.

**Comment by ejeschke** [comment]
@ysBach, could you try commit 7dc4b783129a239742b081407f86d286b427a272?  Thanks for the feedback to help improve Ginga!

**Comment by ejeschke** [comment]
Font sizes are tricky across platforms, but I'll see what I can do about that.

**Comment by ejeschke** [comment]
I've tweaked it just a little more and I think I've found a kind of reasonable default font size for all the various platforms and toolkits I've tried.  I've added a preference setting, so you can change the font size and overall color bar height by copying [this file](https://github.com/ejeschke/ginga/blob/master/ginga/examples/configs/plugin_Colorbar.cfg) to your `$HOME/.ginga` directory and editing the settings, if you are not happy with the defaults.

**Comment by ysBach** [comment]
Sorry for late reply, and it became fantastic!
Now that you have made a "cfg" file, I think making further modification is much easier for people like me (non-developers). 

Thanks for your effort! :D

**Comment by ejeschke** [comment]
> I am serving as a TA of observation course at my home univ, and I believe students, as well as I, will give further comments on ginga. I hope I can make more constructive comments throughout this semester :)

Excellent!  Can we close this issue then?

**Comment by ysBach** [comment]
@ejeschke I closed :)
