### ISSUE TITLE
Pick with Moffat profile

### ISSUE THREAD

**Issue by ysBach** [ejeschke/ginga#454]
Currently ginga pick can do the fitting only by Gaussian.

But the Moffat profile is a more reasonable and realistic stellar profile, and Moffat has already been implemented to astropy: [`astropy.modeling.functional_models.Moffat1D`](http://docs.astropy.org/en/stable/api/astropy.modeling.functional_models.Moffat1D.html#astropy.modeling.functional_models.Moffat1D).

I think giving flexibility of using both Gaussian and Moffat will greatly improve the reliability of the FWHM values of ginga pick when we use it for star finding (e.g., DAOStarFinder of photutils).

**Comment by ejeschke** [comment]
@ysBach, what do you think about a 2D fitting?  In particular, for the case where there is some elliptical character to the profile.

> I think giving flexibility of using both Gaussian and Moffat will greatly improve the reliability of the FWHM values of ginga pick when we use it for star finding (e.g., DAOStarFinder of photutils)

How about just using `DAOStarFinder` then in `Pick`?  I have in mind that it would make sense to migrate `Pick` to using `photutils`.  But that is a more major undertaking.  Anyway, if there is some good example for doing the Moffatt fitting we could add it as an option in the current `Pick`.

**Comment by ysBach** [comment]
@ejeschke, 

>  what do you think about a 2D fitting? In particular, for the case where there is some elliptical character to the profile.

2D fitting would be great too. But as far as I know, elliptical Moffat fitting is not available by default using Astropy. I am thinking of asking Astropy for this.

> How about just using DAOStarFinder then in Pick?

But before doing `DAOStarFinder`, we need the FWHM as an input of it. In IRAF, people did DAOEDIT for finding the input FWHM to DAOPHOT. In Python, I use ginga for this purpose. What I think is that it would be great if we can get the Moffat FWHM from ginga, and then put that FWHM as an input of `DAOStarFinder`. 

I think the following code is an "identical twin" to your Gaussian fitting.

```python
def moffat(self, x, p):
    """Moffat fitting function in 1D. 
    p[0]==mean, p[1]==corewidth(gamma), p[2]=power(alpha), p[3]=maxv
    """
    y = (1.0 + (x - p[0])**2/p[1]**2)**(-1.0 * p[2]) * p[3]
    return y


def calc_Moffat_fwhm(self, arr1d, medv=None, moffat_fn=None):
        """FWHM calculation on a 1D array by using least square fitting of
        a gaussian function on the data.  arr1d is a 1D array cut in either
        X or Y direction on the object.
        """
        if not moffat_fn:
            moffat_fn = self.moffat

        N = len(arr1d)
        X = numpy.array(list(range(N)))
        Y = arr1d
        # Fitting works more reliably if we do the following
        # a. subtract sky background
        if medv is None:
            medv = numpy.median(Y)
        Y = Y - medv
        maxv = Y.max()
        # b. clamp to 0..max (of the sky subtracted field)
        Y = Y.clip(0, maxv)

        # Fit a moffat
        p0 = [0, N-1, 2, maxv]              # Inital guess
        # Distance to the target function
        errfunc = lambda p, x, y: moffat_fn(x, p) - y
        # Least square fit to the gaussian
        with self.lock:
            # NOTE: without this mutex, optimize.leastsq causes a fatal error
            # sometimes--it appears not to be thread safe.
            # The error is:
            # "SystemError: null argument to internal routine"
            # "Fatal Python error: GC object already tracked"
            p1, success = optimize.leastsq(errfunc, p0[:], args=(X, Y))

        if not success:
            raise IQCalcError("FWHM moffat fitting failed")

        mu, width, power, maxv = p1
        self.logger.debug("mu=%f width=%f power=%f maxv=%f" % (mu, width, power, maxv))

        fwhm = 2.0 * width * numpy.sqrt( 2.0**(1.0/power) - 1.0)
        #return (fwhm, mu, sdev, maxv)
        return (float(fwhm), float(mu), float(width), float(power), maxv)
```


Or, if we want to use Astropy, the following might be used, I guess

```python
from astropy.modeling import models, fitting

def calc_fwhm(self, arr1d, medv=None, gauss_fn=None):
    """FWHM calculation on a 1D array by using least square fitting of
    a gaussian function on the data.  arr1d is a 1D array cut in either
    X or Y direction on the object.
    """
    if not gauss_fn:
        gauss_fn = self.gaussian

    N = len(arr1d)
    X = numpy.array(list(range(N)))
    Y = arr1d
    # Fitting works more reliably if we do the following
    # a. subtract sky background
    if medv is None:
        medv = numpy.median(Y)
    Y = Y - medv
    maxv = Y.max()
    # b. clamp to 0..max (of the sky subtracted field)
    Y = Y.clip(0, maxv)

    # Fit a gaussian
    
    fitter = fitting.SLSQPLSQFitter()
    moffat_init = models.Moffat1D(amplitude=maxv, x_0=0, gamma=N-1, alpha=2) # Initial guess
    moffat_fit = fitter(moffat_init, X, Y)
    
#    p0 = [0, N-1, maxv]              # Inital guess
#    # Distance to the target function
#    errfunc = lambda p, x, y: gauss_fn(x, p) - y
#    # Least square fit to the gaussian
#    with self.lock:
#        # NOTE: without this mutex, optimize.leastsq causes a fatal error
#        # sometimes--it appears not to be thread safe.
#        # The error is:
#        # "SystemError: null argument to internal routine"
#        # "Fatal Python error: GC object already tracked"
#        p1, success = optimize.leastsq(errfunc, p0[:], args=(X, Y))
#
#    if not success:
#        raise IQCalcError("FWHM gaussian fitting failed")

    mu = moffat_fit.x_0.value
    width = moffat_fit.gamma.value
    power = moffat_fit.alpha.value
    maxv = moffat_fit.amplitude.value
    self.logger.debug("mu=%f width=%f power=%f maxv=%f" % (mu, width, power, maxv))
    
    fwhm = 2.0 * width * numpy.sqrt( 2.0**(1.0/power) - 1.0)
    #return (fwhm, mu, sdev, maxv)
    return (float(fwhm), float(mu), float(width), float(power), maxv)
```

**Comment by pllim** [comment]
Why not use `imexam`? It supports Ginga viewer. http://imexam.readthedocs.io

**Comment by pllim** [comment]
You can also call `imexam` from within Ginga as a plugin -- https://github.com/ejeschke/ginga/blob/master/experimental/plugins/Imexam.py

**Comment by ejeschke** [comment]
@ysBach, can you try commit ee0c92b2df292c789b47741d0b1b572377f9da27?

You can set the type of FWHM fitting in the "Settings" tab near the bottom.  Currently the default is "gaussian" (as before).  If you want to always use "moffat" you can copy the [plugin_Pick.cfg](https://github.com/ejeschke/ginga/blob/master/ginga/examples/configs/plugin_Pick.cfg) configuration file to your `$HOME/.ginga` and edit the `calc_fwhm_alg` entry to "moffat".

This uses a close match to your "identical twin" example above.  I did need to take the absolute value of the `width` found, because sometimes it appears to be negative.  I'm also a little concerned that the moffat fit seems to fail on more objects than gaussian.  Does that sound normal?  When this happens, it appears that one of the fits (X or Y) is quite a bit off.

I suppose that the `astropy` moffat fitter would be better, but it is significantly different from the current two examples and I could not get your example working well.  That may be a future modification, or perhaps we'll just use a completely different approach as @pllim suggests here.

**Comment by ysBach** [comment]
@pllim It would be really nice if `imexam` can be used. But I actually have spent quite much time to make `imexam` work on my machine, but it almost never worked correctly for me, so I stopped using it since last year. Many key strokes do not show the desired results (especially `c`, `l`) and the resulting graphics window cannot be size-tuned (e.g., maximize does not work, so the xy labels are truncated). This time I tried it again with version 0.7.1, using both ginga and ds9, but failed as before.

Now I tested it with ginga, and used, e.g., `ginga 000.fits --plugins=Imexam &`, but it did not give me the "Imexam" button in "operations", so I couldn't use it.

@ejeschke 

> I did need to take the absolute value of the width found, because sometimes it appears to be negative. 

Oh, you are absolutely right. Thanks for pointing that out! :)

> I'm also a little concerned that the moffat fit seems to fail on more objects than gaussian. Does that sound normal? When this happens, it appears that one of the fits (X or Y) is quite a bit off.

Honestly I am not so sure. If the size of the "pick" region is quite small, I guess the fit *may* fail more often than Gaussian due to many local minima. But (based on personal experience) I haven't felt that Moffat fails more frequently than Gaussian.

> @ysBach, can you try commit ee0c92b?

I tried your "plugin_Pick.cfg" file, and checked other parameters, such as `calc_center_alg` works as expected. But changing the `calc_fwhm_alg` to `"moffat"` gave no difference to the final result:

![comparison](https://cloud.githubusercontent.com/assets/17214293/25389116/b200599a-2a0a-11e7-9c15-2318eff66ae3.png)

Both case gave exactly identical "Readout" panel values, which cannot be if "moffat" and "gaussian" worked differently. I tested it for some other stars, but changing the `calc_fwhm_alg` to `"moffat"`does not seem to affect the result.

I guess  the `calc_fwhm_alg` is not used in the code. If I change `calc_center_alg = 'ff'`, ginga crashes, but `calc_fwhm_alg = 'ff'`did the fitting with no problem.

**Comment by pllim** [comment]
Another option is to use Ginga viewer in Jupyter notebook, then you can just do whatever you want outside of Ginga and then only pipe your image to the viewer when you want to view it.

As for your imexam troubles, I think it is still worth reporting it at https://github.com/spacetelescope/imexam/issues so @sosey can have a look. Thank you!

**Comment by pllim** [comment]
> but it did not give me the "Imexam" button in

You need to copy "Imexam.py" to your `~/.ginga/plugins` directory and then restart Ginga for Ginga to pick it up. It is not automatically "installed".

**Comment by ysBach** [comment]
@pllim 
> As for your imexam troubles, I think it is still worth reporting it at https://github.com/spacetelescope/imexam/issues so @sosey can have a look.

Yes, I am thinking of, but just I couldn't yet. But thanks for your suggestion! I am far from a developer so was hesitating to open issues on github until about a week ago :)

> You need to copy "Imexam.py" 

I guess the following is what you mean, but it doesn't show the `Imexam` button in `Operation`...

```
aaa@YSB:~/.ginga/plugins$ ls
Imexam.py  __pycache__
aaa@YSB:~/.ginga/plugins$ ginga ~/workspace/testings/000.fits --plugins=Imexam &
```

**Comment by pllim** [comment]
Hmm. Try starting Ginga outside of `~/.ginga`. That is, try this:
```
cd
ginga --loglevel=40 --stderr workspace/testings/000.fits --plugins=Imexam
```
Then if you see any errors on the terminal, copy and paste it in your reply.

**Comment by ysBach** [comment]
@pllim 
Oh I found the problem: mistakenly used different one as `Imexam.py`.
Now it works as desired.
Some problems are the problem of `imexam`, not `ginga`.

Thanks for the kind suggestion and help :)

**Comment by ejeschke** [comment]
> But changing the calc_fwhm_alg to "moffat" gave no difference to the final result

@ysBach, did you press the "Redo Pick" button after changing the setting from "gaussian" to "moffat"?  Just changing the setting does not recalculate anything until you make another pick or press "Redo Pick".

I see a slight change in the fwhm calculated between moffatt and gaussian almost every object.  And some objects, particularly ones that are overexposed and "capped", gaussian seems to fit better.  But then the data is kind of bad anyway with that sort of exposure.

**Comment by ejeschke** [comment]
By turning on the logging to debug, I can see that a different function is called for the moffat fitting. 

> I guess the calc_fwhm_alg is not used in the code. If I change calc_center_alg = 'ff', ginga crashes, but calc_fwhm_alg = 'ff'did the fitting with no problem.

I need to change the code a little--it currently doesn't complain if something other than "gaussian" or "moffat" is used, but just falls back to "gaussian".

**Comment by ysBach** [comment]
@ejeschke I am out of office so cannot check it again right now; but I turned off ginga, changed the file to `moffat` or `gaussian`, and turned ginga on, and then did the pick again for the same star. That's the capture I put above.

I will check again thoroughly tomorrow if I've made any mistake. 
Thanks for your effort and comments.

**Comment by ejeschke** [comment]
> I turned off ginga, changed the file to moffat or gaussian, and turned ginga on, and then did the pick again for the same star. 

Thanks for testing.  It's possible that the preference from the file is not picked up yet correctly, so just try changing the value in the drop down box in "Settings" and hit "Redo Pick".  Both X and Y FWHM numbers should change slightly, and the FWHM plot key should show "data" and "moffat".

**Comment by sosey** [comment]
Yes, please @ysBach, post any issue you continue to have with imexam to it's github home so I can try and fix them! :smile: If you would rather, you can also email me the problems and I'll open an issue. It would be great if you could include details on your conda environment and an example of how you are using it.  thanks!

**Comment by ysBach** [comment]
@ejeschke Sorry for late reply.
And oh, I now can see slight change in FWHM and fitting!
It was just almost identical (down to 0.001 ) on my image by chance,
and it gave ~0.01 difference with some different images.
Thank you so much for your hard-working.

I am not sure you intended it, but the graph of function fitting shows the legend still "gauss", not "moffat":

![fwhm](https://cloud.githubusercontent.com/assets/17214293/25480684/c5930a18-2b84-11e7-8556-140d2d77e47a.png)

If it were not for this, I think the issue can be closed as it is perfectly implemented :)


@sosey Thanks for such encouraging comment :) I will find some time to make issues to `imexam` too! It'd be so nice if I can use `imexam` fully on my computer.

**Comment by ejeschke** [comment]
@ysBach, I don't think you have the update installed correctly.  The graph key should show either "gaussian" or "moffat" *not* "gauss".  Did you do a 
```bash
$ git pull 
$ python setup.py install
```
?  From this graph, I don't think the update was applied.

**Comment by ysBach** [comment]
@ejeschke Oh, I am sorry, from some point I forgot to do the `python setup.py install`.... Stupid mistake.

Thanks a lot and I think it is now working perfectly as expected! :)

**Comment by ejeschke** [comment]
@ysBach, feel free to close the issue if you are satisfied with the result.
