### ISSUE TITLE
Pick error when changing radius

### ISSUE THREAD

**Issue by ysBach** [ejeschke/ginga#457]
As can be seen from the figure below, the pick gives error message after I change the `radius` for pick settings:

![pick](https://cloud.githubusercontent.com/assets/17214293/25651378/a9cedc2e-301d-11e7-9a0a-952e8d34ba56.png)

I guess this is because the `radius` changes into a float when I modify it, while ginga takes only integer radius.

**Comment by pllim** [comment]
I don't think it is the radius. I can't reproduce the error on my own image by setting radius to 9.0 as you did. Looks like FWHM calculation failed.

One thing you can do is save and post the Ginga log when you encounter this again.

`ginga --loglevel=10 --log=ginga.log`

**Comment by ejeschke** [comment]
@ysBach, can you try commit a3514524e406c97c4682c00e1186c6c91a2238f2?  I think this fixes the problem.

I think I introduced this bug recently when I added an additional centroid calculation to the FWHM results.

**Comment by pllim** [comment]
Huh. I have your recent change in my installation but I couldn't produce that error...

**Comment by ejeschke** [comment]
@pllim, it actually does the FWHM fine.  It was in an additional centroid calculation that the error with a float radius manifested itself.  numpy doesn't want to let you index arrays with floats (which makes sense).

**Comment by ysBach** [comment]
@ejeschke Thanks for fast feedback!
I confirmed it and it now works fine, so let me close this issue. :)
