### ISSUE TITLE
"git describe" not reading proper tagged release

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#460]
Found this out in another package. It turns out that when a release is tagged using GitHub's web interface, it does not play well with "git describe" command. The current workaround is to tag it using "git" command line, push the tag out, and then insert release notes after-the-fact.

```
$ git tag
v2.6.0
v2.6.1
v2.6.2
v2.6.3

$ git show-ref --tags -d
3dd9d68ababac85c90b600d9c4eddc2d23517c99 refs/tags/v2.6.0
47a85a1a5a1bd436c3a8161a459759139b9f7861 refs/tags/v2.6.1
c29f9214828ede13675210cb649977b306f2d5d2 refs/tags/v2.6.2
647c6550ad3979a1cc15e9e48dc220dfa8941f53 refs/tags/v2.6.3

$ git describe
fatal: No annotated tags can describe 'a9943ebfb868e53bdb5d897db05617b06de282ba'.
However, there were unannotated tags: try --tags.

$ git describe --tags
v2.6.3-59-ga9943eb
```

c/c @jhunkeler

**Comment by jhunkeler** [comment]
@pllim *nods* This describes the issue well enough. We'd expect to see something like below in the `show-ref` output:

```
$ git show-ref --tags --dereference
3dd9d68ababac85c90b600d9c4eddc2d23517c99 refs/tags/v2.6.0
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa refs/tags/v2.6.0^{}
47a85a1a5a1bd436c3a8161a459759139b9f7861 refs/tags/v2.6.1
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb refs/tags/v2.6.1^{}
c29f9214828ede13675210cb649977b306f2d5d2 refs/tags/v2.6.2
cccccccccccccccccccccccccccccccccccccccccccccc refs/tags/v2.6.2^{}
647c6550ad3979a1cc15e9e48dc220dfa8941f53 refs/tags/v2.6.3
ddddddddddddddddddddddddddddddddddd refs/tags/v2.6.3^{}
```

Where `^{}` is a pointer to the real commit hash in the timeline.

**Comment by pllim** [comment]
@ejeschke , a reminder about tagging for next release.

**Comment by ejeschke** [comment]
>  insert release notes after-the-fact

The tagging and pushing out is fairly straightforward, but I haven't tried to add release notes after the fact.  Is that straightforward from the github web interface?

**Comment by pllim** [comment]
> add release notes after the fact

Yes, it should be.
1. Go to "releases".
2. Click on the tag you just pushed out.
3. Click "Edit tag" button on top right.

**Comment by ejeschke** [comment]
Release v2.6.4 made.

```python
$ git describe
v2.6.4-1-g42dc5aa
```

**Comment by ejeschke** [comment]
Any word on whether github is going to address this problem?

**Comment by pllim** [comment]
> github is going to address this problem?

Not that I know of. Maybe @jhunkeler has heard something back?

**Comment by pllim** [comment]
Seems proper now, so I am closing this issue. Thanks!
```
$ git show-ref --tags --dereference
3dd9d68ababac85c90b600d9c4eddc2d23517c99 refs/tags/v2.6.0
47a85a1a5a1bd436c3a8161a459759139b9f7861 refs/tags/v2.6.1
c29f9214828ede13675210cb649977b306f2d5d2 refs/tags/v2.6.2
647c6550ad3979a1cc15e9e48dc220dfa8941f53 refs/tags/v2.6.3
6b1ce30d7f4dab1d83bde8b25cf71d90359f2715 refs/tags/v2.6.4
12ca316a51544f29598f7d6eea844e7b513d2a24 refs/tags/v2.6.4^{}
```
