### ISSUE TITLE
Grid layout prevent vertical resizing

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#463]
I opened 4 `2k x 2k` images, each in its own channel. Then I choose the grid layout. Half of Ginga was outside my screen (small monitor + remote access) and I was unable to resize Ginga vertically.

**Comment by ejeschke** [comment]
It might be possible to get around this by adding a `ScrollArea` around the grid, but that also tends to mess up the idea of the available space for sizing the grid.

Were you unable to resize because you couldn't access the lower right hand resize handle?

**Comment by pllim** [comment]
Yes, lower half of Ginga was outside the screen. I couldn't find a way to access it.

**Comment by ejeschke** [comment]
@pllim, is this aided at all by the fix for #478?

**Comment by pllim** [comment]
Well, what do you know... The problem is gone now. Thanks! 😄
