### ISSUE TITLE
Is new Help compatible with __doc__ override?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#464]
For instance in `ChangeHistory.py`, we added this to auto-insert config file contents to online documentation:
```python
# Replace module docstring with config doc for auto insert by Sphinx.
# In the future, if we need the real docstring, we can append instead of
# overwrite.
from ginga.util.toolbox import generate_cfg_example  # noqa
__doc__ = generate_cfg_example('plugin_ChangeHistory', package='ginga')
```

However, `WBrowser` now reverts to displaying module docstring when RTD or online doc fails to display.

How should we consolidate these two? It seems like a chicken-and-egg thing.

**Comment by ejeschke** [comment]
So this just inserts the settings file as part of the documentation, right?  As you mention in the comment, would it be possible to append it to the docstring?  Or maybe it should be something that is accessed as a separate link from the generated documentation.

**Comment by pllim** [comment]
One thought is to move the *entire* RST content of the current plugin help page to docstring. That way, we can change the incantation to `__doc__ += ...` without problem of duplicating help info. Also, it eliminates the need of keeping two different versions of doc. One downside is that, your "docutils" fallback will render it a bit weird due to missing ref but I think that is a small price to pay.

> separate link from the generated documentation

That is not as convenient as just being able to see the contents on the page. Also just inserting the link has a risk of link being broken, whereas if something is wrong when inserting contents, we will know from Travis' Sphinx test or RTD log.

**Comment by pllim** [comment]
Note: I'll come back to this after #499 and #546 to avoid merge conflicts.

**Comment by pllim** [comment]
FYI: I'm looking into an alternate implementation that does not require so much Sphinx-fu.
