### ISSUE TITLE
Cannot vertically resize (or reposition) Ginga window with OSX

### ISSUE THREAD

**Issue by larrybradley** [ejeschke/ginga#478]
Under OSX (10.11.6), the Ginga window opens with maximum vertical size.  I can resize the window horizontally, but not vertically.  This is an issue if one has a visible OSX Dock at the bottom, because it hides the Ginga app.  One workaround is to put Ginga in "fullscreen" model (which hides the Dock).

Also, if I try to move the window vertically it snaps back to the original position.

I'm using version 2.6.3 with python 3.5.3 and Qt 5.6.2.

**Comment by ejeschke** [comment]
@larrybradley , could you see whether providing the `--geometry=HxW` option allows you to set the  size so that it fits on the screen?

**Comment by larrybradley** [comment]
@ejeschke I just discovered that this issue affects only my macbook pro (retina) laptop.  It works fine on an OSX desktop (same OS version, python, Qt, etc.).  That suggests it's a retina display issue(?).

Setting the `--geometry` on my laptop has no effect, but it works on the desktop.

@stscieisenhamer said that this is a known Qt/OSX issue.  Double clicking on the Ginga title bar resizes the window vertically to fit just above the OSX Dock (thanks, @stscieisenhamer!), but still no further vertical resizing or repositioning.

**Comment by ejeschke** [comment]
I'm using ginga frequently on my macbook pro retina.  My setting under Settings/Displays is "scaled/more space".  But that may make some applications like terminals have too small a default font.  To counteract that I just set the default font for terminals to be a larger size. 

I think there is a set of flags that can be applied to Qt windows to allow them to be resized down.  We'll have to identify which widgets are actually prevented from vertical resizing.  My guess is that one of the plugins probably is taking too much vertical space and prevents the resizing of the overall application.  Sometimes adding a `ScrollArea` widget to the offending plugin can make it adapt to less space in a reasonable way.

Good to hear that there is a workaround to at least let you get the application to fit on the screen.

**Comment by larrybradley** [comment]
Indeed with display set to "scaled/more space" (or the setting just to the left), I can vertically resize/reposition the window.  But I can't resize smaller than some minimum vertical size (this size must be larger than the screen for the default display size).

**Comment by ejeschke** [comment]
@larrybradley, I tried resizing the Ginga window just after I had started it and before loading anything.  I was able to resize it down to this:


<img width="575" alt="ginga_resized_small" src="https://cloud.githubusercontent.com/assets/1305473/26083293/9e5b8c32-3970-11e7-9eb4-7b0d0eb86277.png">

Mac OS X 10.11.6 (El Capitan), Qt 5, python 3

**Comment by mkelley** [comment]
I have the same issue, but with GNU/Linux.  It isn't clear to me which toolkit is being used at startup, but the resizing behavior is broken with the default.  Starting on the command-line with `-t gtk3` and `-t qt` the window decorations are changed, but the resizing still does not work.

The first time the ginga window is drawn, everything fits, but once a blank image is opened, the window size increases vertically, and is too large for my screen (I have a 24-pixel tall panel across the top).  I close the channel, so that there are no open channels, and resizing works normally.  I add a new channel and the vertical size increases to fit the blank image, and the vertical resizing is again broken.  So the issue seems to be related to the channel area.  I hope that helps.

ginga 2.6.4 (and latest), python 3.5.3

**Comment by ejeschke** [comment]
@mkelley, that is indeed helpful.  I'll experiment with opening new channels and resizing.

> Setting the --geometry on my laptop has no effect, but it works on the desktop.

It sounds like you might at least have a workaround on Linux, according to what @larrybradley wrote above.  Try using the `--geometry` option and let us know if this works.

**Comment by mkelley** [comment]
@ejeschke, I tried `--geometry` but it had no effected.  My work around is to use a fullscreen mode, where everything fits on the screen.

**Comment by ejeschke** [comment]
>  I'll experiment with opening new channels and resizing.

@mkelly, I am able to reproduce the non-vertical resizing with gtk3 back end, but not qt.  Both qt4 and qt5 allow me to resize the window even when I add new blank channels.  I'm running Ubuntu 16.04 on the desktop and Mac OS X on the laptop as described above.

Could you try explicitly with -t qt5 and -t qt4 to let me know the result?  I'd really like to address this, but I need to be able to reproduce it under Qt to figure out where the issue is originating for that toolkit.

**Comment by ejeschke** [comment]
@larrybradley, I tried setting my laptop retina display back to the "Default for display" setting (Settings/Displays).  I am able to resize the window well down below the screen size.  Adding new channels, or loading files  does not change the Ginga window size.  I'm using the latest Ginga with qt5.  My environment sounds almost identical to yours.  Not sure how to reproduce this error.  Wondering if you could try the latest Ginga with `-t qt5` and let me know if the problem still persists?  There has been a couple of changes to the layout of plugins recently and it may have changed the way the layout is constrained.

**Comment by mkelley** [comment]
@ejeschke , OK I've tried with -t qt5 and -t qt4 with the current master branch and got the same result.  I am actually using my office desktop now, which has more screen real estate.  However, I can still see the issue.  I cannot resize the window below the initial size until I remove all channels.  After removing all channels, resizing to a small vertical dimension, and opening a new channel, the window immediately increases in size to cover the new channel, and I cannot resize it back to the smaller size.

There is a minimum size when no channels are open, but this is fairly small and not an issue for my smaller screens.  It would be great if this could be the minimum size when channels are open too.

Initial size, Qt5:
![screenshot_2017-06-26_16-45-39](https://user-images.githubusercontent.com/1138643/27559560-f2bf7d94-5a8e-11e7-9793-f3c2d5ba4856.png)

Minimum size with a channel open:
![screenshot_2017-06-26_16-43-51](https://user-images.githubusercontent.com/1138643/27559489-c41cf70a-5a8e-11e7-870d-01dd47b77ddb.png)

Minimum size without any channels:
![screenshot_2017-06-26_16-44-07](https://user-images.githubusercontent.com/1138643/27559494-cb7f96c4-5a8e-11e7-8cdb-01dfd3d46085.png)

**Comment by larrybradley** [comment]
@ejeschke I tried `v2.6.4` with `-t qt5` and got the same result.  I'm seeing exactly the same thing as @mkelley.  If I delete the default "Image" channel, then I can resize vertically to some minimum size.  However, with the window at the small size (no channel), as soon as I add a channel the window immediately resizes back to the large vertical size and cannot be reduced.

Is there some minimum vertical size for the "Image" channel?  It's a bit odd that this affects only the vertical direction.

**Comment by ejeschke** [comment]
@larrybradley, @mkelley I'm finally able to reproduce this!  I had forgotten that I am using an option to save the size and position of the ginga window between sessions.  Once I removed that saved layout, I experienced the issue.  This suggests a workaround until the issue can be fixed:
1) make sure there are no running instances of the reference viewer
2) edit the file `$HOME/.ginga/general.cfg` with a text editor (create one if you don't have one).
3) add the line
```python
save_layout = True
```
to the bottom.
4) copy the content at the bottom of this message to a file `$HOME/.ginga/layout`
5) start the reference viewer

You should be able to resize the viewer as you like and it will remember it between sessions.

Can you confirm?
----------------------- content below goes in $HOME/.ginga/layout ----------------------
['seq',
 {'wexp': None, 'ypos': 33, 'width': 1040, 'spacing': None, 'name': 'top_1', 'height': 434, 'xpos': 48, 'hexp': None},
 ['vbox',
  {'wexp': None, 'ypos': -1, 'width': 1040, 'spacing': None, 'name': 'top', 'height': 434, 'xpos': -1, 'hexp': None},
  {'row': ['hbox',
           {'wexp': None, 'ypos': -1, 'width': 1040, 'spacing': None, 'name': 'menu', 'height': 35, 'xpos': -1, 'hexp': None}],
   'stretch': 0},
  {'row': ['hpanel',
           {'detachable': False,
            'group': 2,
            'height': 924,
            'hexp': None,
            'name': 'right',
            'scrollable': True,
            'show_border': False,
            'show_tabs': True,
            'sizes': [527, 988, 564],
            'spacing': None,
            'tabpos': 'top',
            'title': None,
            'use_toolbar': False,
            'wexp': None,
            'width': 564,
            'wstype': 'tabs',
            'xpos': -1,
            'ypos': -1},
           ['ws',
            {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 307, 'tabpos': 'top', 'group': 2, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'left', 'height': 321, 'xpos': -1, 'wstype': 'tabs'},
            [('Info',
              ['vpanel',
               {'detachable': False,
                'group': 3,
                'height': 516,
                'hexp': None,
                'name': 'lleft',
                'scrollable': True,
                'show_border': False,
                'show_tabs': True,
                'sizes': [359, 516],
                'spacing': None,
                'tabpos': 'top',
                'title': None,
                'use_toolbar': False,
                'wexp': None,
                'width': 523,
                'wstype': 'tabs',
                'xpos': -1,
                'ypos': -1},
               ['ws',
                {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 303, 'tabpos': 'top', 'group': 3, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'uleft', 'height': 112, 'xpos': -1, 'wstype': 'stack'},
                []],
               ['ws',
                {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 303, 'tabpos': 'top', 'group': 3, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'lleft', 'height': 160, 'xpos': -1, 'wstype': 'tabs'},
                []]])]],
           ['vbox',
            {'wexp': None, 'ypos': -1, 'width': 459, 'spacing': None, 'name': 'main', 'height': 321, 'xpos': -1, 'hexp': None},
            {'row': ['ws',
                     {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': True, 'width': 459, 'tabpos': 'top', 'group': 1, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'channels', 'height': 212, 'xpos': -1, 'wstype': 'tabs'},
                     []],
             'stretch': 1},
            {'row': ['ws',
                     {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 459, 'tabpos': 'top', 'group': 99, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'cbar', 'height': 48, 'xpos': -1, 'wstype': 'stack'},
                     []],
             'stretch': 0},
            {'row': ['ws',
                     {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 459, 'tabpos': 'top', 'group': 99, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'readout', 'height': 24, 'xpos': -1, 'wstype': 'stack'},
                     []],
             'stretch': 0},
            {'row': ['ws',
                     {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 459, 'tabpos': 'top', 'group': 99, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'operations', 'height': 37, 'xpos': -1, 'wstype': 'stack'},
                     []],
             'stretch': 0}],
           ['ws',
            {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 262, 'tabpos': 'top', 'group': 2, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'right', 'height': 321, 'xpos': -1, 'wstype': 'tabs'},
            [('Dialogs',
              ['ws',
               {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 560, 'tabpos': 'top', 'group': 2, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'dialogs', 'height': 1628, 'xpos': -1, 'wstype': 'tabs'},
               []])]]],
   'stretch': 1},
  {'row': ['ws',
           {'detachable': False, 'title': None, 'spacing': None, 'hexp': None, 'use_toolbar': False, 'width': 1040, 'tabpos': 'top', 'group': 2, 'wexp': None, 'scrollable': True, 'ypos': -1, 'show_border': False, 'show_tabs': True, 'name': 'toolbar', 'height': 46, 'xpos': -1, 'wstype': 'stack'},
           []],
   'stretch': 0},
  {'row': ['hbox',
           {'wexp': None, 'ypos': -1, 'width': 1040, 'spacing': None, 'name': 'status', 'height': 32, 'xpos': -1, 'hexp': None}],
   'stretch': 0}]]

**Comment by ejeschke** [comment]
Just for anyone that wants to use this workaround, I made this layout as follows:
1) add the `save_layout=True` option as described above
2) remove any `$HOME/.ginga/layout` file that you may have
3) start ginga--size will exhibit problem
4) resize the viewer to be LARGER than initial size and close ginga normally
5) restart ginga--toolbar will look odd--floating in the extra space you created in the previous step
6) without resizing, close ginga normally
7) open ginga again--it will expand to the large size and look "correct"
8) resize ginga to the smallest that you can--it should collapse down nicely
9) close viewer normally

You now have a layout that can be resized to almost any size and will not exhibit the problem

**Comment by mkelley** [comment]
Confirmed, this layout config allows me to resize the window at will!  :+1:

**Comment by ejeschke** [comment]
I believe this issue is fixed in commit 232366b878ce0baa9871421e64d9e6203e8d7050.  If you folks would kindly confirm that is so--comment out the workaround above from your `general.cfg`, remove the saved layout and restart, you should be able to resize the window.  I've also made the default size a little smaller for older laptops or folks running in a reduced desktop area configuration.

Of course you may want to return to using the saved layout feature--I like it a lot.

**Comment by mkelley** [comment]
That works for me.  I tried out Qt4, Qt5, and GTK3.  The minimum GTK3 horizontal width is significantly larger than the others, but the minimum vertical is good.  Qt5's minimum horizontal is about 600 px.

**Comment by larrybradley** [comment]
Thanks, @ejeschke.  I installed the latest master and everything is working great now!
