### ISSUE TITLE
Screenshot warning: 'PngImageFile' object has no attribute '_getexif'

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#480]
Should I be worried about this?

```
2017-05-15 14:36:22,880 | W | io_rgb.py:97 (_imload) |
    Failed to get image metadata: 'PngImageFile' object has no attribute '_getexif'
```

**Comment by ejeschke** [comment]
That may indicate a possible change in API of the `pillow` (PIL) package. Is it happening just trying to load a PNG file?  Does it happen for every PNG file or just some?

**Comment by ejeschke** [comment]
Nevermind, I can reproduce that error.  Taking a look.

**Comment by ejeschke** [comment]
As far as worrying about it, I think it only means you won't see any metadata in the `Header` plugin.

**Comment by ejeschke** [comment]
@pllim, commit f2e79c87a076c80e0e7efa3a56321cb33bb9788d fixes this warning by testing for the `_getexif()` method.  Probably a future update can figure out a good way to extract metadata from PNG images.  For now, the `Header` plugin will just show blank.

**Comment by pllim** [comment]
I saw this warning when I was using the `ScreenShot` plugin, so I did not really care about the header, but was simply confused by the warning. Looks like warning is gone. Thanks!
