### ISSUE TITLE
Feature Request: Use Astroquery for catalog queries

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#483]
Both Ginga and Astroquery are affilliated packages, so this makes sense.

Available services: http://astroquery.readthedocs.io/en/latest/#available-services

c/c @keflavich @bsipocz

**Comment by ejeschke** [comment]
I think Ginga can/does use `astropy.vo.client.conesearch` for catalog searches.

**Comment by pllim** [comment]
@ejeschke , I moved Cone Search to `astroquery` recently. It will be deprecated in Astropy 2.0 and removed in Astropy 3.0. FYI.

**Comment by pllim** [comment]
We have example using `astroquery` now in

https://github.com/ejeschke/ginga/blob/8e51fd51ef2bece03f9e79b1191b19008c9cd3ad/ginga/rv/plugins/Catalogs.py#L18

and implementations in 

https://github.com/ejeschke/ginga/blob/8e51fd51ef2bece03f9e79b1191b19008c9cd3ad/ginga/util/catalog.py#L203

and 

https://github.com/ejeschke/ginga/blob/8e51fd51ef2bece03f9e79b1191b19008c9cd3ad/ginga/util/catalog.py#L67-L69
