### ISSUE TITLE
Does Ginga support MEF visualization?

### ISSUE THREAD

**Issue by austinbeauch** [ejeschke/ginga#496]

**Comment by pllim** [comment]
Did you try the `MultiDim` local plugin? It is designed for MEF. Can you be more specific of what you are looking for?

**Comment by austinbeauch** [comment]
This looks like it could do the job! Just need a way to display multi extension files basically. I haven't tried anything yet, wanted to see if Ginga had a way of doing it.

**Comment by ejeschke** [comment]
See also the comments at the bottom of #311, kind of a duplicate of this issue.

**Comment by ejeschke** [comment]
BTW, @austinbeauch, if you mean to create a mosaic of MEF tiles, ginga can do that using the `Mosaic` plugin:

![mef_mosaic](https://cloud.githubusercontent.com/assets/1305473/26614479/6678cc24-455c-11e7-969c-807610f17754.png)

If you want to use this feature, I highly recommend that you preset the field size using FOV parameter and also install one of the [ginga accelerators](http://ginga.readthedocs.io/en/latest/optimizing.html).  This CFHT megacam image is mosaiced from 36 tiles in about 42 sec with the opencl enabled.  I just set the field size to 1.2 deg, checked "Drop new" (to create a new mosaic on each drop) and dragged the megacam image into the window.

**Comment by austinbeauch** [comment]
Thank you @ejeschke for the continued support! 
I've actually been experimenting with Ginga in a Jupyter notebook versus using the reference viewer, mostly using [this notebook](https://github.com/ejeschke/ginga/blob/master/ginga/examples/jupyter-notebook/ginga_ipython_demo.ipynb) as an example. Is there a way to use widgets from ginga.web.pgw in the viewer that notebook creates?
The idea is to create an application in a Jupyter notebook for viewing/interacting with FITS images. 

I know widgets are a different topic than I originally asked, if you want I could open up another thread. Thank you, once again!

**Comment by pllim** [comment]
@eteq made this notebook as well, which you might find useful. I think there's a widget to interact with MEF:

https://github.com/spacetelescope/stginga/blob/master/docs/stginga/notebooks/ginga_nbinteract.ipynb

In that example, you need to also install `stginga` (https://stginga.readthedocs.io) but I don't think `stginga` is strictly necessary for such widgets. It was just a matter of convenience.

**Comment by ejeschke** [comment]
@austinbeauch, yes, you can create other widgets.  The goal is eventually to support the reference viewer in the browser.  But there are some key widgets that need to be implemented for that to happen.  Let me know if you are interested working on those in a new issue and I can provide more info on that.  You may wish also to browse the text of issue #168 to see what kinds of things you can do now.

So, depending on how sophisticated a UI you want to build you may be able to build a fancier Jupyter web viewer even now.

You may also be interested in browsing issue #497, which deals with making a Jupyter widget compatible viewer.  There are some serious limitations with direct UI interaction with the viewer window, but full control is possible via external widgets and already there are many interested Jupyter widgets available.  See the notebook mentioned there for details.
