### ISSUE TITLE
MultiDim a bit broken again

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#498]
9ab11d2f144625e271dde3b122bafb1ab2fb0c8c reverted some features I added in #461. For instance, now when I open a cube or switch image, `MultiDim` does not automatically update anymore.

**Comment by ejeschke** [comment]
> For instance, now when I open a cube or switch image, MultiDim does not automatically update anymore.

How about for non-cubes?  For me when I switch via `Thumbs` or `Contents` the HDU control updates correctly.

I think #461 introduced the mutually recursive calls.  For some reason it didn't show up in the Qt version, but I am afraid it may eventually.  The basic problem is that `redo()` was calling `set_hdu()` which indirectly invokes a `redo()`...

Let me see what I can do about the cube case...

**Comment by ejeschke** [comment]
@pllim, can you try commit db0a72632f42d66bb6e0c3fbb44aede261c00c9c and let me know if this fixes the issue for you.  It's working in my brief testing here with a couple of different cubes,

**Comment by pllim** [comment]
Yes, seems to work now. But I notice one thing (that I probably didn't fix in my PR either):

1. Open a 4D image.
2. Click "next slice" (the double-right-arrow button).

Note that the first click does nothing. But subsequent clicks work normally.

**Comment by ejeschke** [comment]
> Note that the first click does nothing. But subsequent clicks work normally.

@pllim can you verify (by checking out an older commit) that this problem exists for that as well (with your same 4D cube)?  If so, we should open it as a new issue.  Otherwise, we carry on the reporting in this issue since it would be the recent changes that broke it.

**Comment by pllim** [comment]
Does "current latest master" count?

**Comment by ejeschke** [comment]
I mean with a version right after you added your changes for "MultiDim improvement" branch.  I believe it can be any commit between 2fc06567ae7b17aadaa5abb01f430f25b6e590c2 (when I merged your changes) to 301002a1b6422e03afda0544586f0bf47198f66b (when I merged my recent changes).

**Comment by pllim** [comment]
I checked out 9e22e80ec8a8cfafb2 (the one just before 301002a). I find two behaviors with 4D cube.

Behavior 1:
1. Open a 4D image.
2. Click "next slice" (the double-right-arrow button).
3. It works.

Behavior 2:
1. Open a 4D image.
2. Use radio button to switch to NAXIS4.
3. Click "next slice" (the double-right-arrow button).
4. First click does nothing but subsequent ones are okay.

And despite what I said in https://github.com/ejeschke/ginga/issues/498#issuecomment-305826093 , these are also the same behaviors for the current master (8a8b16afa815fb2cb7619b51f4586665a927dc6c).
