### ISSUE TITLE
Disable padding in Mosaic

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#514]
@Skyhawk172 is using `Mosaic` to build a big mosaic using a lot of smaller images. The result has a border around it all with all zeros. Is it possible to remove that border or make it tighter?

Screenshot:
<img width="489" alt="screen shot 2017-06-16 at 10 08 48 am" src="https://user-images.githubusercontent.com/2090236/27230206-7c08ed62-527c-11e7-942c-3392de626bf2.png">

**Comment by ejeschke** [comment]
I believe this is set by the `expand_pad_deg` parameter in `mosaic_inline()` in `ginga.AstroImage`.  You might try modifying the `Mosaic` plugin (or whatever you are using) to pass a 0.0 value for that (or perhaps something very small, if 0.0 doesn't work).

**Comment by pllim** [comment]
Turns out it is configurable! Should be fixed on my side via STScI-JWST/wss_tools@81b00cfe. Thanks, @ejeschke !
