### ISSUE TITLE
Mosaic has padding on one side even when padding is disabled

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#515]
This is a follow-up of #514. Padding is disabled but for one use case, @Skyhawk172 still sees padding at the top. My hunch is that this is an edge-case bug in the expansion logic of the mosaic in `AstroImage.py` but I'll have to code-dive more to be sure.

Screenshot (ignore the red square):
![screenshot20170620](https://user-images.githubusercontent.com/2090236/27351474-7ce65f24-55cb-11e7-968a-994eac86e856.png)

**Comment by ejeschke** [comment]
Well, remember that the basic logic is to generate an empty array the size of the field and then scale/rotate/flip the tiles to fit.  So there may be some areas that don't get filled in exactly.  These will show up black.

**Comment by pllim** [comment]
@ejeschke , the undesirable blank part of the mosaic is the big chunk of grey area on top.

**Comment by pllim** [comment]
I can't confirm whether this is from the exact input files I used for the original issue (if it is, then this bug is also non-deterministic), but the extraneous padding can also happen on the side, not just top/bottom:

![untitled](https://user-images.githubusercontent.com/2090236/28227141-ac909e18-68a6-11e7-87e1-6347ace2e96b.png)

**Comment by pllim** [comment]
I might have tracked this down to `fov_deg = 0.1` in `plugin_Mosaic.cfg`. The padding disappears when I set the FOV small enough, for example, to 1 arcsec.

Closing for now. If I encounter it again despite this fix, will re-open.
