### ISSUE TITLE
MultiDim breaks with Astropy v2

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#517]
As discovered in https://github.com/ejeschke/ginga/pull/512#issuecomment-310497596, `MultiDim` breaks due to changes in astropy/astropy#6124. This is because https://github.com/ejeschke/ginga/blob/master/ginga/util/io_fits.py#L220 hardcodes the index locations:

```python
            if len(tup) > 5:
                d.setvals(htype=tup[2], dtype=tup[5])
```

The correct approach is to use the relevant FITS file handler attributes directly without using `.info()`.

**Comment by ejeschke** [comment]
> The correct approach is to use the relevant FITS file handler attributes directly without using .info()

Are these available in the older versions of `astropy`? (e.g. 1.X onwards)

**Comment by pllim** [comment]
Should be. Most attributes from `info` were ported from the PyFITS days.

**Comment by pllim** [comment]
Upon further code-diving in `astropy.io.fits`, I stumbled upon the problem of no easy way to extract `dtype` directly without re-implementing a `_summary()` hidden method, so I changed my mind about directly accessing FITS attributes. We can simply shift the indices by 1 as the `.info()` is unlikely to have another column added/removed.
