### ISSUE TITLE
Catalog server

### ISSUE THREAD

**Issue by ppmim** [ejeschke/ginga#52]
I can't select neither a Image server nor Catalog server can't be selected; do I need to setup something before ?

**Comment by pllim** [comment]
Here is some info about how to use `Catalog` plugin, @hcferguson, @gderosa2004, @eteq, @perrygreenfield, @stscieisenhamer

**Comment by pllim** [comment]
User finds catalog config very confusing, wants a proper GUI to specify catalogs. @stscieisenhamer can provide more details.

**Comment by stscieisenhamer** [comment]
The commentary from a class was, "why not already configured", i.e. for the common cases. The next reaction was "let me specify in the gui, why does it have to be configured". Considering that direct solutions may be a bit down the line, the stginga project could take the idea of subclassing, and apply it pre-configuring MAST.

**Comment by ejeschke** [comment]
> The commentary from a class was, "why not already configured", i.e. for the common cases.

That's probably a good thing to do.  Maybe just working off of the common set provided by `astroquery` or the default `conesearch` sources.
