### ISSUE TITLE
Ginga fails to display using the Windows Subsystem for Linux

### ISSUE THREAD

**Issue by robertoabraham** [ejeschke/ginga#521]
Hi, I'm thinking of transitioning from macOS to running Linux on a Windows laptop using the Windows Subsystem for Linux (WSL). If you've never heard of this thing, it's amazing: basically it lets you run Linux executables directly on Windows and it basically means you've got Ubuntu on your windows laptop without a VM. I've found that almost all the standard astro tools run (Astroconda, ds9, SExtractor, SWARP, etc etc.) and they install easily (generally using apt-get) and so far I'm pleased with this setup. The counterexample for things working seems to be ginga though... when I try to start ginga up here's what happens:

(iraf27) abraham@blackbird:~$ ginga
No handlers could be found for logger "ginga"
failed to get the current screen resources
process 100: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)

Any ideas for things I could try to get this to work? Since it seems the issue is figuring out X11 screen resources I tried explicitly setting the geometry with the --geometry switch but that didn't work.

**Comment by ejeschke** [comment]
@robertoabraham, this sounds like a gtk thing, possibly.  Ginga doesn't do anything explicitly with "dbus".  Do you have pyqt installed on your Windows system?  Then you could run
```bash
ginga -t qt4
```
(or qt5, if you have qt5 installed).  I think this is a better bet on Windows than Gtk.

**Comment by ejeschke** [comment]
The [WSL FAQ](https://msdn.microsoft.com/en-us/commandline/wsl/faq) does state that they don't officially support GUI applications, only command line ones.

**Comment by robertoabraham** [comment]
Hi @ejeschke, thanks, I've got pyqt installed by the -t qt5 switch still gives the same error. I think Dbus must be bing used behind the scenes for interapp communications. I'll play around with dbus configuration files and see if I can get somewhere with this. Anyway, while GUI applications aren't supported, so far the ones I've tried seem to work except for ginga. (Well, I've only tried a few, but the ones I care about do, anyway, e.g. ds9).

**Comment by ejeschke** [comment]
@robertoabraham, Ginga runs natively on Windows.  I think that would be the preferred way to run it.  Just install [Anaconda for Windows](https://www.continuum.io/downloads) and then open a shell and type
```bash
$ pip install ginga
```

That's all there is to it!

Or you can install [AstroConda](http://stsci-env.readthedocs.io/en/latest/installing_anaconda.html) which comes with Ginga already (although it is a slightly old version).

**Comment by pllim** [comment]
Disclaimer: AstroConda channel currently does not have Windows build.

I wonder if Ginga can be added to https://github.com/astropy/conda-channel-astropy/tree/master/recipe_templates for Windows support.  @mwcraig?

**Comment by pllim** [comment]
Also for Linux and Mac, Ginga release on the AstroConda channel is up-to-date at 2.6.4. :smile:

**Comment by pllim** [comment]
Last but not least, I can confirm that Ginga runs natively on Windows. That is what I use for *live demo* on Windows 7. :scream:

**Comment by robertoabraham** [comment]
Thanks all... I'll try using the native Windows version for now, I'm sure that'll be good enough for what I need to do. The linux subsystem stuff looks pretty slick and I suspect it'll be able to run everything very soon so I'll revisit this in a few months and check if ginga works with it then.

**Comment by ejeschke** [comment]
> Ginga release on the AstroConda channel is up-to-date at 2.6.4

Oops, my mistake.  I just helped someone yesterday who had AstroConda installed on their laptop and the version of Ginga that they had was 2.6.3.  I just assumed it was the latest version of AstroConda, but that obviously was not not the case, in hindsight.

**Comment by pllim** [comment]
> had AstroConda installed on their laptop and the version of Ginga that they had was 2.6.3

All they have to do is `conda update ginga` :smile:

**Comment by mwcraig** [comment]
The astropy conda channel is up to date on all platforms: `conda install -c astropy ginga` (or update instead of install).

**Comment by ejeschke** [comment]
> The WSL FAQ does state that they don't officially support GUI applications, only command line ones.

Given the above, I don't think this qualifies as a bug.  Closing.
