### ISSUE TITLE
Refactored internal shapes code not completely backward compatible

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#522]
Looks like #519 is not completely backwards compatible. I have a plugin that uses drawn shape to create masked data for calculation, which failed with this error now:

```python
2017-07-03 15:26:36,348 | E | Callback.py:139 (make_callback) |
  Error making callback 'draw-event': setting an array element with a sequence.
2017-07-03 15:26:36,348 | E | Callback.py:140 (make_callback) | Traceback:
  File ".../ginga/misc/Callback.py", line 123, in make_callback
    res = method(*cb_args, **cb_kwdargs)

  File ".../stginga/plugins/BadPixCorr.py", line 371, in draw_cb
    return self.redo()

  File ".../stginga/plugins/BadPixCorr.py", line 234, in redo
    sci_masked = image.cutout_shape(sig_obj)

  File ".../ginga/BaseImage.py", line 388, in cutout_shape
    view, mask = self.get_shape_view(shape_obj)

  File ".../ginga/BaseImage.py", line 376, in get_shape_view
    contains = shape_obj.contains_arr(xi, yi)

  File ".../ginga/canvas/CanvasObject.py", line 551, in contains_arr
    return self.contains_pts(pts)

  File ".../ginga/canvas/types/astro.py", line 512, in contains_pts
    arg1 = obj2.contains_pts(pts)
```

**Comment by ejeschke** [comment]
@pllim, this looks like a quick fix, probably.  What shape did you draw to force the error?

**Comment by pllim** [comment]
The plugin draws both circle and annulus at the same time, but traceback points to `astro.py`, so probably came from the annulus. Thanks for the quick response!

**Comment by ejeschke** [comment]
Very odd.  It seems that I cannot do this:
```python
x_arr, y_arr = np.asarray(pts, dtype=np.float).T
```
nor can I do
```python
x_arr, y_arr = np.asarray(pts).astype(np.float).T
```
but instead am forced to do
```python
x_arr, y_arr = np.asarray(pts).T
x_arr, y_arr = x_arr.astype(np.float), y_arr.astype(np.float)
```
Which fixes the problem.

Any insight in to why this is, @pllim?

**Comment by ejeschke** [comment]
I believe commit f0fcdc4f84e99b579cfbfc5e3201db275861b61c fixes the problem.  Can you confirm, @pllim?

**Comment by ejeschke** [comment]
@pllim, any chance to test whether this fixed the issue for you?

**Comment by pllim** [comment]
Not yet... Let me see if I can fix the rest, seems like just typo.

**Comment by pllim** [comment]
As response to https://github.com/ejeschke/ginga/issues/522#issuecomment-312731977 , if you print out `pts` at that point, you will see that `pts` is actually like this:
```python
[array([[1, 2, 3, 4, 5]]), array([[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])]
```
When you do a `np.asarray(pts).T`, it returns:
```
array([array([[1, 2, 3, 4, 5]]),
       array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])], dtype=object)
```
The array type now is `object`, as Numpy is unsure on how to combine the different dimensions; hence you cannot cast it as float. 

Going through the rest of your calculations in `Circle.contain_pts()`, if `x_arr` has shape of `(1, 5)` and `y_arr` has `(5, 1)`, then `res` and `contains` (the returned mask) will be `(5, 5)`. Does this sound right to you?

**Comment by ejeschke** [comment]
> The array type now is object, as Numpy is unsure on how to combine the different dimensions; hence you cannot cast it as float.

I could see that (I printed them myself, debugging this), but I thought that `numpy` would just treat them as arrays of arrays, and should still be able to handle a conversion to `float`.

> Going through the rest of your calculations in Circle.contain_pts(), if x_arr has shape of (1, 5) and y_arr has (5, 1), then res and contains (the returned mask) will be (5, 5). Does this sound right to you?

Yes, it does.  Maybe there is a different way to handle this, but numpy seems to broadcast things so that the containment test works.  I was able to create masks for circle, ellipse, annulus, etc. which had given the error before.  I guess I must have missed checking in `BaseImage.py`...

**Comment by ejeschke** [comment]
Is this fixed then, after merging #525?

**Comment by pllim** [comment]
Haven't tested all the shapes but definitely works for rectangle, circle, and annulus.

**Comment by ejeschke** [comment]
I've tested all the shapes you can draw that would give you a sensible mask.

**Comment by ejeschke** [comment]
Let's reopen if you notice anything funky that looks like it might be related to this PR merge.

**Comment by pllim** [comment]
Sounds good. Thanks! :)
