### ISSUE TITLE
Update Astropy affiliated package info

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#526]
@ejeschke , please check Ginga's entry in https://github.com/mwcraig/astropy-affiliated-numfocus-blog/blob/master/registry.yml and see if anything needs updating. For instance, Ginga can also display JPEG and Astropy tables now, but I don't know how much details you want to put there.

"Please take a look at the information for your affiliated package at https://github.com/mwcraig/astropy-affiliated-numfocus-blog and edit the yml file there to add a bit more information information about your package: a representative image, a link to educational materials (e.g. a notebook or tutorial or ...) and an update of your packages description, if it is out of date or missing." -- Matt Craig

**Comment by ejeschke** [comment]
@pllim, can I put you as co-maintainer?

**Comment by pllim** [comment]
I won't say no... :wink:  Thanks for your generosity!

**Comment by ejeschke** [comment]
Do you want your email address listed?

**Comment by pllim** [comment]
Re: email -- No, thanks! :sweat_smile:

**Comment by ejeschke** [comment]
Got it.  BTW, in the process of updating this I updated the github pages for Ginga.  [Check it out](https://ejeschke.github.io/ginga/) and let me know what you think!

**Comment by ejeschke** [comment]
Submitted a PR to update the entry.

**Comment by pllim** [comment]
Closed by mwcraig/astropy-affiliated-numfocus-blog#12 . Thanks, @ejeschke !

> Check it out and let me know what you think!

The page looks good! (Except for a missing Oxford comma but that's just me being nitpick-y.) Although, I wonder, since now that I am also mentioned as maintainer, whether STScI should be mentioned in addition to Subaru. 🤔

**Comment by ejeschke** [comment]
> whether STScI should be mentioned in addition to Subaru

Absolutely!  You can pull the gh-pages branch and update it if you want, otherwise I'll update it when I get a chance.
