### ISSUE TITLE
Feature Request: Add "deselect_path" to TreeView widget

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#532]
Currently, `TreeView` widget has a `select_path()` method but no public API to de-select, except to clear the whole tree. I propose a new method named `deselect_path()`. In Qt, it is simply the opposite of `select_path()`, as follows:

```python
class TreeView(...):

    def select_path(self, path):
        item = self._path_to_item(path)
        item.setSelected(True)

    def deselect_path(self, path):
        item = self._path_to_item(path)
        item.setSelected(False)
```

**Comment by pllim** [comment]
I am torn between my original suggestion above and simply re-using `select_path()` like this:
```python
class TreeView(...):

    def select_path(self, path, state=True):
        item = self._path_to_item(path)
        item.setSelected(state)
```
`state` might not be the best name either, so suggestions welcome. @ejeschke , do you have a preference between the two possible implementations?

**Comment by ejeschke** [comment]
Hmm, in the case of multiple selections, this would actually just deselect the one row out of many?

**Comment by ejeschke** [comment]
I ask because there is `clear_selection()` to clear the selection completely, it looks like.

**Comment by ejeschke** [comment]
I think between the two that you show, I'd prefer reusing `select_path`.  The reason is that it makes the code simpler in cases where you want to calculate selections--you don't end up having to write conditional branches or use first-class functions to choose a different method.  Instead it just changes the `state` kwarg, which seems more readable to me.

**Comment by pllim** [comment]
> this would actually just deselect the one row out of many?

Yes. I have many rows selected but then I want to only de-select one of them. I use this feature in `MosaicAuto` plugin in `stginga`.
