### ISSUE TITLE
Canvas get_items_at method not completely backward compatible

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#533]
As a result of #519, I found that API of `CompoundMixin.get_items_at()` has changed. It used to take `x` and `y` separately, but now only takes `pt` (a tuple of `x` and `y` together). This is not a hidden method, so it is a bit unfortunate. Is there something else that I should be using instead of this method?

Also related: #522

**Comment by ejeschke** [comment]
I probably should have changed the name and added a compatibility method like
```
def get_items_at(data_x, data_y):
    return self.get_items_at_pt((data_x, data_y))
```

but it may be too late for that now.  Can you just switch to using a tuple around your parameters?

**Comment by pllim** [comment]
Yes, I had to put in a logic to anticipate two possible APIs. But I solved the problem on my end. Thanks!
