### ISSUE TITLE
setup.cfg not configured correctly for new pypi uploads

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#539]
I get an error trying to push releases to pypi after their recent transition to a new server:
```bash
$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading ginga-2.6.4.tar.gz
HTTPError: 400 Client Error: classifiers: 'Intended Audience :: Science/Research,' is not a valid choice for this field for url: https://upload.pypi.org/legacy/
```
there seems to be something about the way that `astropy-helpers` is picking up the classifications that does not create a compatible string.

This needs to be fixed for pypi downloads, pip installs and proper building on debian.

**Comment by ejeschke** [comment]
@pllim, @bsipocz, @olebole 

I used to use the following invocation:
```bash
$ python setup.py sdist register upload
```
but the new pypi server gives me the above error (after removing the "register" part, which is no longer supported).  I followed the [directions here](https://packaging.python.org/guides/migrating-to-pypi-org/#uploading), and installed a compatible version of "twine", but as you can see from the above snippet it no longer works.  Have you run across something like this?

Any ideas would be appreciated!

I'm not sure, but [this answer](https://stackoverflow.com/questions/45323897/400-client-error-web-environment-is-not-a-valid-choice-for-this-field-for-url) leads me to think that there may be something wrong either with the `setup.cfg` structure or some incompatibility with `astropy-helpers`.

**Comment by pllim** [comment]
Sorry, I am not familiar with PyPi. But seems like it is picking up the comma. In Astropy, the classifiers are listed inside `setup.py`. When I translated that to Ginga, instead I moved it to `setup.cfg` but did not remove the commas. But that was a year ago, so I am surprised it did not come up sooner. My suggestion is to remove the commas in `setup.cfg` and try again.

Does not appear to be related to recent `astropy-helpers` update.

**Comment by bsipocz** [comment]
``python setup.py sdist upload`` stopped working for me a while ago, too but switching to twine solved the issues. Other than that I don't have any idea what goes wrong, and would need to dig into google and SO myself.

**Comment by ejeschke** [comment]
Thanks for the input, @pllim, @bsipocz . I fixed it by moving the classifiers back to `setup.py` as a regular python list.  I used `twine` to upload it, and no complaints.  It [shows up](https://pypi.python.org/pypi/ginga/2.6.5) on pypi.python.org .

**Comment by ejeschke** [comment]
And I didn't change the classifiers.  I think this only started showing up after pypi moved to their new system.

**Comment by pllim** [comment]
Glad you found the solution. It was my bad to move them to `setup.cfg` in the first place. Sorry!

**Comment by ejeschke** [comment]
> It was my bad to move them to setup.cfg in the first place. Sorry!

No problem at all.  Just wondering whether the other items that are in `setup.cfg` are getting propagated to the record.  When I look at [astropy's page on pypi](https://pypi.python.org/pypi/astropy/2.0) it shows more of the items, like recommended packages, required packages, etc. Ginga also has these, but they don't show up there.  Maybe I should move those back to `setup.py` as well.

As an additional point, when I look at the [2.6.4 link for Ginga on pypi](https://pypi.python.org/pypi/ginga/2.6.4) it doesn't even show the categories.  That's why I wonder whether our `setup.cfg` is properly set up for `astropy-helpers`.

**Comment by ejeschke** [comment]
> Ginga also has these, but they don't show up there. Maybe I should move those back to setup.py as well.

I see now from looking at astropy's `setup.py` that the "requires" and "provides" are separate from the `setup_requires` and `install_requires`.  I should add the running requirements as "requires".

**Comment by pllim** [comment]
Strictly speaking, `setup.cfg` is not really required but just make updating metadata cleaner.

Also, any issues with `setup.cfg` should theoretically go to https://github.com/astropy/package-template but it has been overhauled to use "cookiecutter", so maybe not relevant to them now.

**Comment by ejeschke** [comment]
> Strictly speaking, setup.cfg is not really required but just make updating metadata cleaner.

Hmm, I'd be in favor of removing it then.  I thought the simple `setup.py` was easier to understand.

**Comment by bsipocz** [comment]
@pllim - Yes, please do update the template ``setup.cfg`` whenever you think it's useful. The only trick is that the default branch now is the ``cookiecutter`` one, and the the actual template lives in the 
``{{ cookiecutter.package_name }}`` subdir.
