### ISSUE TITLE
Undefined decoded_data, file, socketError in IIS_DataListener.py

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#543]
In the method below:
```python
    def decode_iis(self, data):
        f = file('/tmp/pippo', 'wb')  # <-- Not compatible with Python 3
        f.write(data)
        f.close()
        return (decoded_data)  # <-- Undefined!
```
and also
```python
    if not match:
        # Error
        raise socketError("I don't understand the format of addr IMTDEV: '%s'" % (imtdev))  # <-- Undefined exception
```

For `file()`, see https://stackoverflow.com/questions/112970/python-when-to-use-file-vs-open

**Comment by ejeschke** [comment]
Grepping the code, it doesn't look like `decode_iis()` is used anywhere either in `IIS_DataListener` or `IRAF.py`.  It can probably be removed.

**Comment by pllim** [comment]
What about `socketError`?

**Comment by ejeschke** [comment]
I think it could be changed to `ValueError`.  It's not actually a socket error anyway.
