### ISSUE TITLE
unichr in IRAF.py not Python 3 compatible

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#544]
In `IRAF.py`, the `IRAF_AstroImage.info_xy()` method uses `unichr(...)` function that is not Python 3 compatible.

See https://stackoverflow.com/questions/2352018/cant-use-unichr-in-python-3-1

**Comment by ejeschke** [comment]
I'm thinking about "decommissioning" the IRAF plugin by removing it from the default globals and maybe just dropping it into the "experimental" folder. When I wrote it I thought that maybe it might be useful for folks that are stuck on IRAF.  But my guess now is that most Ginga users do not want to use IRAF and, if they do, they are probably happy enough with the IRAF/ds9 combination.

That's not to say that we shouldn't fix this issue in the meantime.

**Comment by pllim** [comment]
James Turner recently ported IRAF to Python 3, so for now, I agree that this plugin should at least also work on Python 3 until decommissioning. 😄

**Comment by ejeschke** [comment]
Fixed in commit b642336bbebf475bb17d574979953262b3440ed4

**Comment by pllim** [comment]
Thanks!
