### ISSUE TITLE
Remove/replace deprecated matplotlib colormaps?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#553]
As part of testing #548, I see these `MatplotlibDeprecationWarning`s. Please advise on how to get rid of them:
```
.../matplotlib/cbook.py:136: MatplotlibDeprecationWarning:
The spectral and spectral_r colormap was deprecated in version 2.0.
Use nipy_spectral and nipy_spectral_r instead.
warnings.warn(message, mplDeprecation, stacklevel=1)
...
The Vega10 colormap was deprecated in version 2.0. Use tab10 instead.
...
The Vega20 colormap was deprecated in version 2.0. Use tab20 instead.
...
The Vega20b colormap was deprecated in version 2.0. Use tab20b instead.
...
The Vega20c colormap was deprecated in version 2.0. Use tab20c instead.
...
The Vega10_r colormap was deprecated in version 2.0. Use tab10_r instead.
...
The Vega20_r colormap was deprecated in version 2.0. Use tab20_r instead.
...
The Vega20b_r colormap was deprecated in version 2.0. Use tab20b_r instead.
...
The Vega20c_r colormap was deprecated in version 2.0. Use tab20c_r instead.
```

**Comment by ejeschke** [comment]
That's a good question.  I imagine some matplotlib users may be getting similar warnings, depending on what they are importing.  I think this comes from iterating over the names of the color maps [here](https://github.com/ejeschke/ginga/blob/master/ginga/cmap.py#L13313).  If there is a way to get all the colormap names from matplotlib that does not include these we could change the code to use that instead.

**Comment by ejeschke** [comment]
@pllim: I've commented out the default import of matplotlib colormaps until we can figure out how to iterate over only the ones that are not flagged for deprecation.  This should squelch the warnings in the mean time.
