### ISSUE TITLE
astropy dev and Python 2 support

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#554]
Astropy dev has dropped Python 2 support as of astropy/astropy#6556 . CI setup here will need to be updated to avoid chronic failure. What is Ginga's plan going forward?

1. Drop Python 2 support as well.
2. Python 2 version will be in a separate branch with `astropy<3` pinned in `setup.py`.

**Comment by ejeschke** [comment]
I don't think it is reasonable to drop Python 2 support for Ginga at this time.  At our telescope we are still transitioning to python 3 and I think we're even more aggressive on that schedule than some other Ginga users.  Also, although some features in the reference viewer plugins depend on astropy, the basic widget does not (and should not) depend on astropy.

If possible it would also be good to avoid having to maintain a separate branch, at least as long as reasonable.  Unless the astropy API diverges rapidly under python 3 this shouldn't be a huge issue for the code for a while.  For Travis, can we just pin the version 2 builds to astropy < 3, as suggested in (2)?

**Comment by pllim** [comment]
Yes, that sounds reasonable.
