### ISSUE TITLE
Ginga start very slow with Python 3.4 on Mac

### ISSUE THREAD

**Issue by cdeil** [ejeschke/ginga#57]
I tried starting `ginga` with the latest Astropy and Ginga git master versions and Python 3.4 on Mac OS X 10.10.

It does start, but runs for over a minute at 100% CPU and prints several errors and warnings to the console (I killed with `CTRL + C` after a minute or two):
https://gist.github.com/cdeil/c89f1c4b8d1d4513e4c4

@ejeschke Can you reproduce or have an idea what is going on from the console output?

**Comment by ejeschke** [comment]
Just checked CPU use on RHEL 6.6.  Current master (9e6199e6959484790c1aa7bd9b6b4a55c415a483) uses about 6% CPU idling (python2.6).  On Ubuntu 14.04 (python2.7 and python3.4) it uses 105% or so.

**Comment by ejeschke** [comment]
This is fixed in recent versions of ginga after a timer module refactoring.  Currently seeing about 8.3% CPU usage with python3/qt5 on Ubuntu.  Start up is just as fast or faster than for python 2.
