### ISSUE TITLE
Prev/Next Channel gives traceback when encountering workspace

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#594]
Workflow to reproduce this (either in Ginga 2.6.5 or dev):

1. Start Ginga.
2. Create a workspace.
3. Press left or right arrow to cycle between channels. The workspace would still be in focus but I see the following traceback on the terminal.

```
Error making callback 'activated': 'ws1'
Traceback:
  File ".../ginga/misc/Callback.py", line 123, in make_callback
    res = method(*cb_args, **cb_kwdargs)

  File ".../ginga/rv/plugins/Toolbar.py", line 79, in <lambda>
    lambda w: self.fv.next_channel()),

  File ".../ginga/rv/Control.py", line 793, in next_channel
    self.next_channel_ws(ws)

  File ".../ginga/rv/Control.py", line 785, in next_channel_ws
    self.change_channel(chname, raisew=True)

  File ".../ginga/rv/Control.py", line 958, in change_channel
    channel = self.get_channel(name)

  File ".../ginga/rv/Control.py", line 1003, in get_channel
    return self.channel[name]
```

**Comment by ejeschke** [comment]
> Press left or right arrow to cycle between channels. The workspace would still be in focus but I see the following traceback on the terminal.

@pllim, can you confirm that when you press the left/right arrows *in the workspace toolbar for the workspace that was added* that the channels are cycled correctly?

**Comment by ejeschke** [comment]
Also, I think commit c7db292047b0c116a7826d7dcab57e9b6932e160 partially fixes this issue.  It removes the error messages.

But there is a larger issue which is outlined in #377.  I think it may be time to remove the arrows from the `Toolbar`.  Then I believe it the arrows in each workspace toolbar will not surprise anyone with their actions.

**Comment by ejeschke** [comment]
> Then I believe it the arrows in each workspace toolbar will not surprise anyone with their actions.

Have to qualify this somewhat: when a workspace is added as a subworkspace, and the upper workspace is shown in "grid" mode, there appears to be a bug in how that is displayed.  I'll raise this as a separate issue.

**Comment by pllim** [comment]
Thanks! I'll re-review this when I get a chance.

**Comment by pllim** [comment]
@ejeschke , with the latest dev as of c7db292047b0c116a7826d7dcab57e9b6932e160 , I see **three** sets of arrows:

![screenshot from 2017-11-22 13-55-32](https://user-images.githubusercontent.com/2090236/33144988-e50066f0-cf8c-11e7-8e56-c9fe164fdadd.png)

![screenshot from 2017-11-22 13-56-01](https://user-images.githubusercontent.com/2090236/33144996-e8fff78e-cf8c-11e7-8b10-b4bc9bbbdb5c.png)

The top- and bottom-most cycle through "Image" and "ws1" (but not the individual channels inside "ws1"), while the middle one cycles through only the 4 channels within "ws1".

Three sets of arrows are getting too confusing. Even if you remove one of them (as you mentioned above), there are still two sets that actually have different behaviors but share the same icons. I wonder if having slightly different arrow appearances would be less confusing; e.g., the arrows that control channels *inside* the workspace have "W" on them (or something to that effect).

**Comment by ejeschke** [comment]
@pllim, could you let me know your thoughts about button behavior on commit a7648819f2ebf998f7cdec031999ee5ea7bacf8c ?  i believe this might be the best interim solution until/unless we decide to make a new navigation system for workspaces and channels.

Basically, I removed the `Toolbar` plugin arrows, and changed the workspace toolbar up/down arrows to only affect the channel that is active in that workspace. So there are no longer any arrows that are redundant and do the same thing.

One possibly confusing issue is that the button gives no feedback if there are no images to cycle. For example, in the screen shot you show above, the up/down arrows in the very topmost toolbar will do nothing while "ws1" is selected, since it is a workspace and not a channel.

**Comment by ejeschke** [comment]
> One possibly confusing issue is that the button gives no feedback if there are no images to cycle. For example, in the screen shot you show above, the up/down arrows in the very topmost toolbar will do nothing while "ws1" is selected, since it is a workspace and not a channel.

I'll look at adding something to disable the buttons if there are no images to cycle.

**Comment by ejeschke** [comment]
> I'll look at adding something to disable the buttons if there are no images to cycle.

Sorry, please wait a little until I add a couple more commits!

**Comment by ejeschke** [comment]
Ok, ready for review.  Please take a look at commit 7cf505d33ac30fb2541b73518e86e86ffb1ebbd7 or later.

I've rethought this issue a bit and come to the conclusion that there should only be one set of up/down arrow buttons, and these should always behave as the up/down arrow keys on the keyboard--they change the image in the currently active channel.  So they are back in the Toolbar plugin, and like the other buttons there, they update when the channel changes.

The left/right arrow buttons remain in the workspace toolbar, and as before, they simply change the active window in the workspace attached to that ws toolbar.  They only control the windows in their respective workspaces.  I assume that most users will not need these in the "Tabs" or "Grid" configuration of a workspace, but they are very useful in the "Stack" and "MDI" configurations.  They can also be used as a kind of manual blink feature.

**Comment by ejeschke** [comment]
All the arrow buttons also now are sensitive only when they will actually do something.

**Comment by pllim** [comment]
I'll have a look today. Thanks!

**Comment by pllim** [comment]
@ejeschke , the arrows in the latest `master` are certainly less confusing. The fact that they gray out helps a lot too. Thanks! :+1:
