### ISSUE TITLE
Editing drawings in simple fitsviewer example (example2_mpl.py)

### ISSUE THREAD

**Issue by nluetzge** [ejeschke/ginga#598]
Hi! I was using the example2_mpl.py file to use Ginga in my own code. What I'm trying to do is to draw something ontop of fits image. And then move this drawing around (either with the cursor or with extra buttons to move them up and down and left and right). I have no idea if thats possible. I tried with creating a button that changed the `canvas.objects.x` coordinates but that doesn't seem to do the trick. Is it possible? And does it have something to do with the commented line `canvas.enable_edit(True)`

Thanks in advance!
Nora

**Comment by ejeschke** [comment]
Hi @nluetzge.  If you have a handle to the object itself, you can change it's attributes like `x` and `y` and then just call a `canvas.update_canvas()` to have the change updated.

If you check out the latest version from github, I updated both the `qt/example2_qt.py` and the `matplotlib/example2_mpl.py` files to show editing objects.  After drawing an object, select the "edit" button to put the canvas in edit mode and then you can click on the object to edit it or move it around.

BTW, unless you have other reasons to use the matplotlib back end, you will get better performance with one of the other back ends, like Qt.  The `example2_mpl.py` uses Qt widgets anyway, so unless you need to plot on top of the canvas using the matplotlib API, I'd recommend using the Qt backend.

**Comment by nluetzge** [comment]
Aaah yes was looking for the `update_canvas()` that was exactly what I needed it works now thank you. And thanks for the backend tip, I never really know what I'm using for this.

**Comment by ejeschke** [comment]
Glad to hear, @nluetzge.  If you have any more questions you can add them to this issue, otherwise feel free to close it when you are ready.
