### ISSUE TITLE
Overlay and TVMask highlights do not clear on close

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#600]
When I close the `Overlay` plugin, the highlighted regions do not disappear. Is this a bug or feature? Same thing with `TVMask`.

**Comment by ejeschke** [comment]
Is it possible that that plugin is not removing the canvas that it added on `stop()`?  The highlighted regions *should* disappear.

**Comment by ejeschke** [comment]
Try zooming the image after closing.  Do the highlighted areas disappear?  If so, we may just be missing a `canvas.redraw(whence=0)` on `stop()`.

**Comment by pllim** [comment]
Ah, yes. Zooming in/out cleared the highlights. Thanks!

**Comment by ejeschke** [comment]
`self.canvas.update_canvas(whence=0)` may also do the job.
