### ISSUE TITLE
Pressing Clear in Log shrinks text area too much

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#604]
Workflow to reproduce this:

1. Start `Log` global plugin.
2. Do something with warnings or errors, so `Log` text area gets populated.
3. Press "Clear" button.

Now, the text area is very small. As a result, the next time you get warnings/errors, they are very hard to read. The workaround for now is to close the `Log` plugin and restart it.

**Comment by ejeschke** [comment]
@pllim, using qt5 on Ubuntu 16.04, or qt5 on Mac OS X, I don't see this issue.  When I press clear, the log text area shrinks, but as soon as any log messages begin arriving again it stretches out with each message until it fills the size of the plugin area again.

**Comment by pllim** [comment]
This is what I am seeing (this time I only went through Steps 1 and 2, not 3).

![screenshot from 2017-11-22 15-27-19](https://user-images.githubusercontent.com/2090236/33148405-bf7746da-cf99-11e7-8abd-873409a5745f.png)

```
$ ginga --version
ginga 2.7.0.dev1795

$ uname -a
Linux ... 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

$ conda list qt
pyqt                      5.6.0            py36h0386399_5  
qt                        5.6.2                         5  
qtconsole                 4.3.1            py36h8f73b5b_0  
qtpy                      1.3.1            py36h3691cc8_0 
```

**Comment by pllim** [comment]
I attempted to debug this but realized that I can't reproduce it anymore. Not sure what happened there as I do a clean install every time... `¯\_(ツ)_/¯`

I'll re-open if it comes back and consistently. Sorry for the noise.
