### ISSUE TITLE
TST: Use Travis CI build stages?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#606]
Are you interested in this new Travis CI feature? See https://docs.travis-ci.com/user/build-stages/ for info and see https://travis-ci.org/astropy/astropy for the feature as used by `astropy`.

The motivation to use this is when you don't want bother with running the rest of the builds if some important ones fail. However, this also adds to total testing time, because subsequent stages are not started until the earlier ones pass.

Please close this issue if you are not interested.

**Comment by pllim** [comment]
@ejeschke , are you interested to make PEP 8 test the "first stage"? That is, if code does not satisfies our PEP 8 test, other tests will not attempt to run.

**Comment by ejeschke** [comment]
@pllim, I haven't yet had time to take at look at this.  Will do so soon.

**Comment by ejeschke** [comment]
Ok, I've had a look at the new travis feature.

I'm wondering if there is any really good rationale in ginga's case for serializing the CI.  Per your example, if a commit fails the PEP8 test, it doesn't really matter whether that came first, last or in parallel--it will show up as a failed build.  Probably better to just do it in parallel. 

Also, Travis is showing 38 min 45 sec for the last run with `ginga`.  For an all-python package that seems quite long.  I understand that there are a lot of different reasons for that delay.  But I think adding stages will just lengthen than unnecessarily.

@pllim, are there some other things that would be a convincing argument for stages in ginga's case? I think astropy is a much more complex package and I can imagine more examples of useful staging for that.

**Comment by pllim** [comment]
Perhaps not so much currently. Do you just want to close this and revisit when there are more complicated GUI driven tests?

**Comment by ejeschke** [comment]
Yes, if you are ok :ok_hand:  with that.

**Comment by pllim** [comment]
OK
