### ISSUE TITLE
Citable record?

### ISSUE THREAD

**Issue by adrn** [ejeschke/ginga#608]
We're planning to reference and cite all Astropy affiliated packages in the upcoming Astropy v2.0 paper. I couldn't find a citable record for this package - are you interested in creating one so that we can cite it? For example, you can create a [zenodo](zenodo.org) record and just comment back here to let me know that it's done. Please also let me know if you'd like to opt out of a citation and we'll just link to the package. Thanks!

**Comment by ejeschke** [comment]
There are a few citations [here](https://github.com/ejeschke/ginga/blob/master/doc/ginga_papers.bib).

I'll take a look that the zenodo link and reply back here.

**Comment by ejeschke** [comment]
Hmm, the zenodo link above is broken.

**Comment by ejeschke** [comment]
Ok, enabled Zenodo integration with github and enabled for `ginga`.  I'm not sure it will grab the latest release but we are making a new release in the next couple of days and it should pick it up. 

@adrn, if you need it ASAP, can you suggest how to tell Zenodo to pick the most recent release?

**Comment by adrn** [comment]
By end of week is fine - thanks!

**Comment by ejeschke** [comment]
@adrn, [![DOI](https://zenodo.org/badge/4758330.svg)](https://zenodo.org/badge/latestdoi/4758330)

**Comment by adrn** [comment]
Thanks!
