### ISSUE TITLE
Second table won't display when loading two FITS tables from command line

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#611]
To reproduce this bug, use command line to start Ginga: `ginga --loglevel=30 --stderr table1.fits table2.fits`

Now, you will see the filenames listed in `Thumbs` and `Contents`. However, when you bring the second table into focus, the displayed table in "Image" does not change.

In contrast, when the tables are manually loaded using "File -> Load Image" menu, there is no problem switching between the tables.

**Comment by ejeschke** [comment]
> when you bring the second table into focus,

Does it make a difference if you use Thumbs or Contents to select the next table?

**Comment by pllim** [comment]
Not that I can see. I tried single-click on thumbnail and (separately) double-click on `Contents` listing.

**Comment by pllim** [comment]
My hunch is that something went awry in the `datasrc` caching. If you don't get to it first, I'll investigate tomorrow.

**Comment by ejeschke** [comment]
@pllim, testing using two FITS files that have a table as HDU 1, when I do:
```bash
$ ginga -t qt5 image1.fits[1] image2.fits[1]
```
I get two thumbnails. Each table loads properly when I click its associated thumb.  It also works from `Contents` with double clicking.  Can I get some test data from you that shows the issue?

**Comment by pllim** [comment]
Not sure what happened that day but it works now. Sorry for the noise!
