### ISSUE TITLE
PEP-8 clean up broke polygon containment check

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#616]
Recent PEP-8 clean up breaks polygon containment check of points.  Basically, the following check will fail:
```python
res = poly.contains_pts(arr_pts)
```
and possible other polygon containment operations, e.g. regular `contains()` may fail as well.

The problem occurs between commits 1ad667eb5e64ca5f1390dcb064feccc2f4fef389 and 0442e2b97f10e0a71d64f52fd6b2c50222d80540.  If you checkout the first one and do a git diff with the second you can find the issue in the `ginga.canvas.types.mixin` module.  In particular, the change
```python
-            result[tf == True] ^= cross[tf == True]
+            result[tf is True] ^= cross[tf is True]
```
results in an incorrect check, because in this case the `tf` variable contains a result that we want to test for truth in the general python numerical sense (non-zero).

**Comment by ejeschke** [comment]
This issue is fixed in commit e128e6c2dc036afcfbd10e2a32fff0c15b64fcbc.  I changed `tf is True` to:
```python
idx = np.nonzero(tf)
result[idx] ^= cross[idx]
```
This better illustrates what is going on.

Looking through the diff with the current master from 1ad667eb5e64ca5f1390dcb064feccc2f4fef389, I believe this is probably the only place where this problem was introduced.

**Comment by ejeschke** [comment]
Ping @pllim, FYI.

**Comment by pllim** [comment]
Ops, my bad. Sorry and thanks for fixing!
