### ISSUE TITLE
PEP8: change package names to snake_case?

### ISSUE THREAD

**Issue by cdeil** [ejeschke/ginga#62]
[PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) suggests to use `snake_case` for package and module names and `CamelCase` for class names.
I find that very convenient because when reading code it's clear what's an imported module and what's a class name ... `ginga` in many places uses `CamelCase` for both, i.e. I have to scroll up and check the imports to be able to know if `AstroImage` is the module or the class.

I realise changing this would be a complete break in backwards compatibility and thus painful for your users, but I think in the long run worth it ... Ginga as the astro image viewer of the next decade or two with a clean Python codebase!

(Obviously, feel free to just close this issue if you don't want to do this!)

**Comment by ejeschke** [comment]
This is solved by @pllim's recent PRs to PEP8-ize the rest of the legacy code base and the addition of a `flake8` check to Travis.

**Comment by pllim** [comment]
Not exactly... #589 did not address camel-case at all because `flake8` is not complaining about it.

**Comment by ejeschke** [comment]
Re-reading the original issue more closely, I see that the main complaint is that the modules within ginga often use camelcase; i.e. `AstroImage` for the module and `AstroImage` again for the class within that module.  It's true that this has not changed.  And it would break a very large amount of developers code to make that change at this point.  Perhaps for Ginga 3.0.

**Comment by ejeschke** [comment]
Most of the newer modules are lower case. e.g.
```
from ginga.canvas.types.basic import Path, Polygon
```
