### ISSUE TITLE
DOC: Add code of conduct

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#628]
Why not?

**Comment by ejeschke** [comment]
Seems reasonable.  Can we just make a file with a short statement saying basically that as an astropy affiliated project we adopt the astropy code of conduct, along with a pointer to that document?

Seems unnecessary to create a new one if there is a well thought out one out there that we can use.

**Comment by pllim** [comment]
IMHO the Astropy one (http://www.astropy.org/code_of_conduct.html) should be sufficient. Otherwise, it can be a good starting point.

p.s. astropy/package-template#295 would add one to the Astropy package template if merged, if you want to wait for it.
