### ISSUE TITLE
Ginga does not load IRAF image

### ISSUE THREAD

**Issue by olebole** [ejeschke/ginga#643]
I tried to use the interface between IRAF and ginga (with Python 3). When I do a 

```
ecl> display dev$pix
```

in a freshly started IRAF, I get the following output on Ginga (with `--loglevel=9`, after enabling IRAF plugin):

```
2018-03-15 10:08:35,837 | D | IIS_DataListener.py:750 (handle) | PACKET IS 14
2018-03-15 10:08:35,837 | D | IIS_DataListener.py:785 (handle) | ?NO OP (014)
2018-03-15 10:08:35,837 | E | IIS_DataListener.py:169 (handle_request) | error handling the request: '<=' not supported between instances of 'bytes' and 'int'
<class 'TypeError'>
'<=' not supported between instances of 'bytes' and 'int'
<traceback object at 0x7f9de30b4a48>
```

**Comment by pllim** [comment]
I thought at one point, it was discuss to deprecate IRAF support in Ginga, but I can't find that issue now. Maybe @ejeschke can correct me if I am wrong.

**Comment by olebole** [comment]
Don't hesitate to remove it. I just by chance discovered it and thought adding ginga as possible Debian-`Recommends:` for iraf (as image display).

**Comment by ejeschke** [comment]
The IRAF plugin is definitely not frequently used and needs a maintainer who is an active IRAF user.  Probably I should move it to the "experimental" folder and if someone doesn't pick it up in the next few months, delete it.

Before doing that I'll take a brief stab at reproducing this error.  Python 3, right @olebole ?

**Comment by ejeschke** [comment]
IRAF plugin has been moved to `experimental` folder.
