### ISSUE TITLE
Make inherit_primary_header a channel setting

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#648]
I have a use case for using the `inherit_primary_header` setting, but I want to use it only selectively, for certain channels.  I suggest to make this a channel preference with default `False`.

If we were to do this, the question then is: does the setting in `general.cfg` override the channel setting or vice versa?

**Comment by pllim** [comment]
FWIW, I would prefer a backward-compatible behavior. In my use case, I need it for almost everything. Thus, it would be shocking to my users to have to suddenly set it on a channel-by-channel basis. I guess, I am saying that I am in favor of `general.cfg`  overriding channel, however this is the opposite of generic `cfg` behavior?

**Comment by ejeschke** [comment]
In general, the channel settings override the setting in `general.cfg` (where they overlap).  But we could either a) make an exception for this setting, or b) not explicitly add it to the channel settings when a channel is created, but if a user adds it manually to a channel's settings file it would take effect.

Option b) might be preferable because it preserves the principle of least surprise (i.e. backward compatible behavior) except when the user has to go out of their way to enable it.

**Comment by ejeschke** [comment]
Another issue is that the image is usually loaded (and header processed) outside of the context of a channel, before being loaded into a channel.  So it may be a little convoluted with the current scheme to make that a channel setting anyway.  And what happens when you move an image from one channel to another, and they have different values for this setting?

**Comment by ejeschke** [comment]
What I really want (I think) is a way to dynamically show the primary header inherited or not.  For example, a checkbox on the `Header` plugin that says to mix in the primary header or not.  Then you could click it on or off to examine the header with or without the primary header items mixed in.  In order to do something like that we'd need to maintain the primary header and hdu header as separate entities in the `AstroImage` that would be combined in the `Header` plugin for display purposes.

**Comment by pllim** [comment]
Yes, a check box to toggle sounds good to me. There's already a box to sort anyway.

**Comment by ejeschke** [comment]
See PR #651

**Comment by ejeschke** [comment]
Closing this issue because there is better approach to this problem than making this a channel preference.
