### ISSUE TITLE
DOC: Does RTD need to display all the old versions?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#655]
On http://ginga.readthedocs.io (which now points to "stable" by default instead of "latest", as discussed in https://github.com/ejeschke/ginga/pull/652#issuecomment-396733401 , if you click on the available versions, bottom left (see attached screenshot), you see older versions available all the way back to 2.6.0. Can we hide some of the older ones? Maybe just display, say, "latest", "stable" (now at 2.7.0), and "2.6.6"?

![screenshot from 2018-06-14 12-00-25](https://user-images.githubusercontent.com/2090236/41424124-2ecdf08e-6fcb-11e8-8722-0ae6141fb8e6.png)

**Comment by ejeschke** [comment]
So which version is considered "stable", the last release?

**Comment by ejeschke** [comment]
Since we basically consider any release stable, it would be nice to just have "latest", plus the releases.  Think that is possible?

**Comment by ejeschke** [comment]
And we could limit to the last 3 releases or something.

**Comment by pllim** [comment]
Yes, "stable" always points to last release, which is currently 2.7.0.

**Comment by pllim** [comment]
If 2.6.6 is a bug fix release of 2.6.0, is anything `<2.6.6` needed to be displayed?

**Comment by ejeschke** [comment]
I think not.

**Comment by pllim** [comment]
So, display only these then?

* latest
* stable (2.7.0)
* 2.6.6

(When 2.8.0 is out, 2.7.x can be made visible again separately.)

**Comment by ejeschke** [comment]
@pllim, what do you think?

**Comment by pllim** [comment]
I would tend to agree with myself at https://github.com/ejeschke/ginga/issues/655#issuecomment-397429091 :sweat_smile:

**Comment by pllim** [comment]
I have made changed on RTD to display

* latest
* stable
* 2.7.1
* 2.6.6
