### ISSUE TITLE
Feature Request: Add requirements files

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#663]
It would be nice to have requirements files, so user can simply do, say, `pip install -r requirements_qt5.txt`, if they want all dependencies for Ginga to run under Qt5.

This thought came to mind when I re-install Anaconda and I run into this or that not found when trying to use a Ginga widget for Jupyter notebook. I had to go back and reinstall missing dependency multiple times until things started working.

**Comment by ejeschke** [comment]
This is a great idea.  Is the format of the file something compatible with `pip` or `conda` ?

**Comment by ejeschke** [comment]
Maybe better to put them in a directory, because there are a lot of possible back ends.  Could use the `doc` directory, but what about `reqs` or `install`?

**Comment by ejeschke** [comment]
I'm just a little concerned that there might be quite a few and it will clutter up the root directory.  How about a directory named `requirements`?

**Comment by pllim** [comment]
> How about a directory named requirements?

That sounds good. Even better if it is explained in README and perhaps also in installation doc.

**Comment by ejeschke** [comment]
I noticed that there is a `rtd-pip-requirements` file in the `doc` directory.  Maybe this should be moved into the directory with the other requirements files.

**Comment by pllim** [comment]
> Maybe this should be moved into the directory with the other requirements files.

Sure. However, please be advised that RTD admin settings need to be updated accordingly to find that file's new location.

**Comment by pllim** [comment]
Idea from Scipy: Have a wizard that walk user through what backends they wish to use (e.g., `astropy` or `fitsio`, `astropy.wcs` or starlink`, etc) and then produce a customized requirements file. If we go this way, we might even format it different by asking if user wants to use `pip` or `conda`. *However*, this help function cannot be inside Ginga installation because it is needed to install Ginga in the first place. Plausible options:

* Standalone Python script that someone has to download manually from GitHub repo and run on their arbitrary working directory. This way, we can still package the script with the repo without introducing a chicken-and-egg problem. (Simplest)
* Fancy JavaScript to do this interactively on one of the Ginga doc pages. (Hardest)
* Put the script in a separate installable package in the `ejeschke` account. (Makes the least sense)
