### ISSUE TITLE
aggdraw cannot load font (no text renderer)

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#664]
@ejeschke , are you familiar with this error? What dependency am I missing here? I was attempting to initialize `EnhancedCanvasView` from `jupyterw` on Jupyter Lab. Problem is this is a new installation of Miniconda3, so while this used to work in the old installation, it does not anymore.
```
2018-06-29 15:46:06,431 | E | ImageView.py:1272 (redraw_now) | Error redrawing image: cannot load font (no text renderer)
2018-06-29 15:46:06,434 | E | ImageView.py:1277 (redraw_now) | Traceback:
  File "...\ginga\ImageView.py", line 1258, in redraw_now
    self.redraw_data(whence=whence)
  File "...\ginga\ImageView.py", line 1303, in redraw_data
    self.private_canvas.draw(self)
  File "...\ginga\canvas\DrawingMixin.py", line 723, in draw
    super(DrawingMixin, self).draw(viewer)
  File "...\ginga\canvas\CompoundMixin.py", line 143, in draw
    obj.draw(viewer)
  File "...\ginga\canvas\types\basic.py", line 86, in draw
    cr.set_font_from_shape(self)
  File "...\ginga\aggw\CanvasRenderAgg.py", line 56, in set_font_from_shape
    alpha=alpha)
  File "...\ginga\aggw\AggHelp.py", line 77, in get_font
    font = get_cached_font(name, size, color, op)
  File "...\ginga\aggw\AggHelp.py", line 22, in get_cached_font
    font = agg.Font(color, info.font_path, size=fontsize, opacity=alpha)
```

**Comment by pllim** [comment]
Minimally reproducible code:
```python
>>> from aggdraw import Font
>>> font = Font('black', 'C:\Windows\Fonts\sseriff.fon')
OSError: cannot load font (no text renderer)
```
So this is not a Ginga problem per se, but I can't get Ginga viewer to display without fixing this.

**Comment by ejeschke** [comment]
Did you try with a TrueType font?  I think only truetype fonts are supported.

**Comment by pllim** [comment]
Maybe this never worked even before. I uninstalled `aggdraw` completely, so now Ginga falls back to `pillow` and it is working. :woman_shrugging:

**Comment by ejeschke** [comment]
[This link](https://stackoverflow.com/questions/17770413/aggdraw-cannot-load-font-no-text-renderer) and [this one](https://stackoverflow.com/questions/26497041/installing-aggdraw-with-freetype-support) look like they might have more information for this error.

I've never tried to build `aggdraw` on Windows before.

**Comment by pllim** [comment]
I stared at that `FREETYPE_ROOT` reply for a while but I don't know how to apply it to a `conda install`. I shouldn't have to modify source code myself for such things? Anyway, I am moving on... Thanks anyway!

**Comment by ejeschke** [comment]
Yes, it requires more intervention to install aggdraw.  Also, I think the package has been mostly abandoned by the original author.  There are several forks on github, including (mine)[https://github.com/ejeschke/aggdraw]. I've fixed a few bugs and added python3 support.

It does nice antialiased drawing, so I think the results are maybe a little better than pillow, but difficult to install on non-linux platforms.  Perhaps the freetype configuration could be improved...

**Comment by pllim** [comment]
For the record, I did get `aggdraw` to work on Windows by following the following steps:

1. Clone the `aggdraw` repository. Here, I clone Eric's bug fix branch instead (might as well): https://github.com/ejeschke/aggdraw/tree/vectorized-drawing
2. Modify `setup.py` like mentioned in https://stackoverflow.com/questions/17770413/aggdraw-cannot-load-font-no-text-renderer
3. `python setup.py install`

**Comment by pllim** [comment]
OK. I opened an issue upstream at pytroll/aggdraw#28

**Comment by djhoese** [comment]
@ejeschke and @pllim I mentioned this in the related aggdraw issue, but if you have ideas for a fallback for finding freetype libraries that doesn't include the freetype-config command, let me know. Previously aggdraw used to have a hardcoded path and after I took over the project I included the functionality from someone else for using `freetype-config --prefix`. It seems that freetype on conda-forge does not include this binary command so aggdraw can't be built with it. There seems to be an issue for this (see reference above) on the freetype feedstock.

**Comment by ejeschke** [comment]
> There seems to be an issue for this (see reference above) on the freetype feedstock.

Well that is good news then. If conda can include that it would help a lot. I see that it is installed with the Ubuntu (and presumably Debian) freetype packages.

**Comment by pllim** [comment]
Just a note to my future self because I wasted an hour trying to figure out what I set `FREETYPE_ROOT` to manually before. Hey, future self, it is:
```python
"C:\\Users\\username\\Miniconda3\\envs\\envname\\Library\\"
```

**Comment by djhoese** [comment]
@pllim Could you try the most recent aggdraw 1.3.5 and see if this issue is now fixed? I added the functionality to the setup.py to use `ctypes.util.find_library` as a fallback when freetype-config doesn't exist. I tested your simple font load on my Windows VM and it seemed to work.

**Comment by pllim** [comment]
@djhoese , thanks for the fix. However, while I see `aggdraw` 1.3.5 on `conda-forge` on Linux, it does not appear to be available yet on Windows. I'll have to wait a little.

**Comment by djhoese** [comment]
It is available on windows but you may have to force the version since i think it pinned itself to a newer version of freetype. @ocefpaf may know more.

**Comment by pllim** [comment]
Pinning `conda install aggdraw=1.3.5` worked. And `FREETYPE_ROOT` problem has disappeared. Thank you very much!
