### ISSUE TITLE
MNT: Python 3.7 support

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#673]
1. Ensure Ginga works with Python 3.7
2. Add Python 3.7 to Travis CI matrix

**Comment by ejeschke** [comment]
Just tested with a fresh `miniconda` install.  Tests all pass.  Reference viewer seems to run fine with the sampling of plugins I tried.

**Comment by pllim** [comment]
Thanks for checking! When I get the chance, I'll try it more extensively and report back.

**Comment by ejeschke** [comment]
I've been testing almost exclusively lately with 3.7.  I haven't found any issues.  I think this will be a straightforward PR.

**Comment by pllim** [comment]
Fixed in #699
