### ISSUE TITLE
plot a sequence of points on a ginga image from the command line

### ISSUE THREAD

**Issue by jhennawi** [ejeschke/ginga#678]
Hi All, 

I am having trouble figuring out how to plot a point on an image in RC mode. This does not appear to documented anywhere, and I cannot figure out the syntax. 

Here is what I'm doing: 

viewer = grc.RemoteClient(host, port)

Then I display the image, which works fine. 

canvas = viewer.canvas(ch._chname)
canvas.add('point', [870.0],[826.0],[10.0],style='plus', color='red')

My understanding is that the above should add a point at location [870.0,826.0] on the image but it does nothing. Furthermore, this command returns 

Out[83]: '@3'

to the command line. And at that point the viewer then appears to have some problems, i.e. I can no longer zoom into the images. Things become unresponsive. 

Thanks for your help, 
Joe Hennawi

**Comment by pllim** [comment]
Hello. Do you really need the remote client functionality? If you are trying to plot things locally, I would recommend the HTML5 interface instead.

**Comment by jhennawi** [comment]
Yes, I'm developing data reduction pipelines and the plotting absolutely needs to be launched from the command line using the remote client functionality.

**Comment by jhennawi** [comment]
Hi All, 

To make this issue much more concrete here are my suggestions: 

The documentation here

https://ginga.readthedocs.io/en/stable/manual/plugins_global/rc.html#sec-plugins-rc

is very nice, but if falls short of explaining how to actually plot things (like points) on a ginga image using the remote client interface. There is a nice example there for a path, which I have used, but I am not able to understand how to generalize this to points or other Canvas objects. I tried to look through the source code, but quickly got lost. 

The other thing I would like to be able to do, is adjust things like cuts from the command line, rather than interacting with the viewer directly.

If it possible to add a few more examples to the docs above along these lines, or let me know what the commands are, that would be greatly appreciated!

Best,
Joe Hennawi

**Comment by ejeschke** [comment]
> canvas.add('point', [870.0],[826.0],[10.0],style='plus', color='red')

Hi Joe.  Sorry for late reply; just returned from vacation.

Your example works for me if I do the following, instead:

    canvas.add('point', 870.0, 826.0, 10.0, style='plus', color='red')

I apologize for the poor documentation.  In general, for the plot objects you can figure out the API from looking at the class constructors, e.g. [here](https://github.com/ejeschke/ginga/blob/master/ginga/canvas/types/basic.py#L1050)

We can see that a `Point` object takes x, y, radius as scalars and then kwargs for style.

@pllim and I have plans to overhaul the manual, so we will keep your recommendations in mind.

> The other thing I would like to be able to do, is adjust things like cuts from the command line, rather than interacting with the viewer directly.

Easily done:

    ch = viewer.channel(ch._chname)
    ch.cut_levels(low, high)

You can find out many of the possibilities for manipulating a channel by perusing the API [in this class](https://github.com/ejeschke/ginga/blob/master/ginga/ImageView.py#L43)

Cheers,
~Eric

**Comment by jhennawi** [comment]
Many thanks Eric! One last question. If I want to plot a list of points on an image, how would I do that?

Best Wishes,
Joe

**Comment by jhennawi** [comment]
Finally, while I have your attention. If I want to show another image in a existing RC ginga window, but would like the zoom level stay fixed, is there a way to do that. Currently every time I show a new image, it resets to the default zoom level. Basically I'm looking for an analog to the /align keyword in IDL atv.pro. 

Thanks!
Joe

**Comment by ejeschke** [comment]
> If I want to show another image in a existing RC ginga window, but would like the zoom level stay fixed, is there a way to do that.

Sure:

    ch.enable_autozoom('off')

**Comment by ejeschke** [comment]
> If I want to plot a list of points on an image, how would I do that?

@jhennawi, could you install from master and try the following?

    pts = np.random.randint(0, 100, (20, 2)) 
    # note: must cast numpy floats to regular python floats to pass the remote interface
    spec = [dict(type='point', args=(float(pts[i][0]), float(pts[i][1]), 10))
                 for i in range(20)]
    canvas.add('constructedcanvas', spec)

I've added a `ConstructedCanvas` type that lets you build up a canvas from a series of specifications of plot objects. Basically, you pass a list of specs, where each spec is a dict containing a `type` key that names the type you want to add, an `args` parameter which gives the list of fixed position parameters and an optional `kwargs` key that contains any keyword parameters.  Pretty flexible system that allows you to construct a whole bunch of different objects and then add them all at once. 

We're currently working on a plan for vector shapes (e.g. `Points`, `Circles`), but it is in the early stages. It's very likely that when those get added it will be a simpler call to just pass a list of coordinates.  Stay tuned, if interested.

**Comment by jhennawi** [comment]
Hi All, 

Thanks for all of the help. Happy to close this issue. Is there a way to create a cheat sheet for grc interface in the new docs with all of these examples listed. From my perspective the more the merrier. At present, I'm usually having to grep around in the code to find these commands, or else I have to bother everyone here. 

Thanks!
Joe

**Comment by pllim** [comment]
@jhennawi , that's a great idea! Would you like to contribute? As a frequent user of this feature, you would be a good candidate to write up such a document.
