### ISSUE TITLE
Use setuptools entry_points for command line scripts

### ISSUE THREAD

**Issue by cdeil** [ejeschke/ginga#68]
The recommended way (in Astropy and Python package in general) is to install command line scripts via the setuptools entry_points method. For `console_scripts` it's simple to do:
https://github.com/astropy/package-template/pull/116

I think for GUI scripts it's also easy to do but should be tested:
https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation

@ejeschke Let me know if you want me to give this a try ...

**Comment by ejeschke** [comment]
@cdeil, this looks like it should be pretty easy for the reference viewer, based on ginga's current scripts/ginga.  Sure, have at it!

**Comment by pllim** [comment]
This is already solved in #313
