### ISSUE TITLE
Is there a way to enable the WCS Match Analysis plugin from the RC interface?

### ISSUE THREAD

**Issue by jhennawi** [ejeschke/ginga#693]

**Comment by ejeschke** [comment]
Using the RC "ginga" handle, invoke the method `start_global_plugin()` with the string "WCSMatch".  LMK if you need more info, @jhennawi.

**Comment by jhennawi** [comment]
Hi @ejeschke 

I'm a bit lost. What is the RC "ginga" handle?

I know I want to run 

start_global_plugin() and then try out your 

call_global_plugin_method(plugin_name, method_name, args, kwargs)

command, but I don't understand what object I'm running these commands from. 

P.S. Do you guys have a Slack channel, I fear I'm adding a ton of noise to your GitHub. 

Joe

**Comment by pllim** [comment]
Well... Given Ginga is an Astropy affiliated package, we can possibly create a `#ginga` channel over at Astropy Slack... http://joinslack.astropy.org/

**Comment by ejeschke** [comment]
First: reinstall from this PR branch again--I just added a method to `WCSMatch` that you can call (previously it was just designed to have a GUI callback method, which is not suitable really for a remote call).  @pllim, I added docstrings.

Assuming you have your two images loaded already into channels "Image" and "Image0" (if not, add those commands to these):
```python
from ginga.util import grc
cl = grc.RemoteClient('localhost', 9000)
sh = cl.shell()
sh.start_global_plugin('WCSMatch')
sh.call_global_plugin_method('WCSMatch', 'set_reference_channel', ['Image'], {})
```
`sh` is the "ginga handle" I was referring to above.  If you are using the command line interface I can let you know that as well..LMK.

**Comment by pllim** [comment]
I think this would be great info to add to https://ginga.readthedocs.io/en/latest/manual/plugins_global/rc.html

**Comment by jhennawi** [comment]
Okay let me give it a spin. Thanks @ejeschke and @pllim

**Comment by jhennawi** [comment]
Hi @ejeschke, 

This worked like a charm. The only slightly weird behavior is that the "Reference Channel" pulldown menu in the WCSMatch  GUI actually never got toggled to the channel name I chose as the reference. Although it did match the WCS as I desired. 

It would be great to see this functionality in the main repository!

**Comment by ejeschke** [comment]
Ok, I pushed another commit that fixes this.

I forsee a lot of issues/changes in the future if we get more usage of RC-type calls.  Most of the plugins were written without this use in mind and only respond to GUI changes.  It will be some work to retrofit them to make the GUI match changes being dialed in from elsewhere.  But perhaps we can develop a design pattern approach to dealing with these.

**Comment by ejeschke** [comment]
@jhennawi, can you give it one more spin to make sure everything is working as expected. If so I will merge it.

**Comment by jhennawi** [comment]
Great that worked! Many thanks!

I do think the RC-type calls make ginga particularly powerful since one can then script all of its powerful functionality without a bunch of human clicking. 

Joe

**Comment by jhennawi** [comment]
One last question, what are the RC shell commands to clear all the channels out of the current ginga viewer, and/or reset the viewer. 

Thanks!
Joe

**Comment by ejeschke** [comment]
> I think this would be great info to add to https://ginga.readthedocs.io/en/latest/manual/plugins_global/rc.html

@pllim, ok to merge? I think we are planning a significant doc PR for plugins, so let's just address this there?

**Comment by ejeschke** [comment]
> One last question, what are the RC shell commands to clear all the channels out of the current ginga viewer, and/or reset the viewer.

```python
sh.delete_channel(chname)
```
You can use `get_channel_names()` to get the list of channels.  There is no call to delete all channels, at present.

**Comment by pllim** [comment]
Yes, ok to merge. Thx!

**Comment by ejeschke** [comment]
@jhennawi, please close if merged PR fixes this issue for you.
