### ISSUE TITLE
Table file icon upside-down in Thumbs

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#713]
Workflow:

1. Start Ginga (the one with fix for #708 already in)
2. Open a FITS table (e.g., Vega spectrum)

Its `Thumbs` image (a file icon with shadow at the bottom and star in the middle) looks upside-down. Can't tell if flipped too (maybe?).

**Comment by ejeschke** [comment]
I think this is fixed.  Can you confirm, @pllim?  And close if it is? Tnx
