### ISSUE TITLE
Bug in Qt Contents plugin?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#74]
In `qtw/plugins/Contents.py`

```
    def recreate_toc(self):
        self.logger.debug("Recreating table of contents...")
        toclist = list(self.nameDict.keys())
        toclist.sort()

        self.treeview.clear()

        for key in toclist:
            chitem = QtGui.QTreeWidgetItem(self.treeview, [chname])
            chitem.setFirstColumnSpanned(True)
            self.treeview.addTopLevelItem(chitem)
```

`chname` is undefined. Is this a bug?

**Comment by ejeschke** [comment]
It certainly is!  Thanks for catching that.  Most likely it hasn't been noticed because in typical cases people don't delete channels all that frequently and that's the only time this is really called.  I'll submit a fix.

**Comment by ejeschke** [comment]
Commit a9b6862e101ac30b9018c882dcbb100ae413e706 should fix this.
