### ISSUE TITLE
RTD: Switch to using webhooks

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#744]
GitHub Services no longer works. There is a RTD webhook URL available. Just need to add it to GitHub webhooks in repo settings, which I cannot see.

**Comment by ejeschke** [comment]
@pllim, I added a webhook for RTD.  As a part of doing this, I logged into RTD and tried to manually trigger a build.  It gave me this error:
*Problem in your project's configuration. Invalid "requirements_file": path doc/rtd-pip-requirements does not exist*

**Comment by ejeschke** [comment]
[Here's the link](https://readthedocs.org/projects/ginga/builds/8569047/) to the build.

**Comment by pllim** [comment]
@ejeschke , I think I know what the problem is and I'll try to fix it on the RTD side. Looks like webhook works though!

**Comment by pllim** [comment]
Update: I found the cause -- A missing quote! Fixed it in cd0884f8e2e16968358cf066cc229eb490b5aab5
