### ISSUE TITLE
Change README into MD or RST format?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#747]
Would be nice to be able to see Travis CI and RTD badges on README. But for that to happen, README has to change from plain text to either markdown (MD) or restructured text (RST). What do you think, @ejeschke ? (Markdown was picked as solution in conversation below.)

Goals:

* Reformat the plain text doc into markdown.
* Add badges for RTD, Travis, Appveyor, and Astropy.

**Comment by ejeschke** [comment]
@pllim, I'm ok with either.  Which do you suggest?

**Comment by pllim** [comment]
@ejeschke , I don't have a preference. GitHub renders them both, with slight favoritism for markdown.

**Comment by ejeschke** [comment]
I suppose RST offers a little more functionality, but I MD is more common for READMEs.  Shall we go with MD?

**Comment by pllim** [comment]
> Shall we go with MD?

Sure!
