### ISSUE TITLE
Remove dependency on astropy-helpers

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#758]
Following the ideas in [APE 52](https://github.com/astropy/astropy-APEs/pull/52), we should remove the `astropy-helpers` dependency and move to the standard Python ecosystem tools.  Since Ginga is a pure-Python package, this should be relatively straightforward, following the suggestions at the link.

**Comment by pllim** [comment]
I would wait a bit for the APE to be accepted first, otherwise I have no objection.

**Comment by pllim** [comment]
APE 17 is accepted. Look out for a "conversion guide" that Tom Robitaille will send out to astropy dev mailing list in the near future.

**Comment by ejeschke** [comment]
Will likely need your help with that PR, @pllim!

**Comment by pllim** [comment]
It is on my todo list... :grimacing:
