### ISSUE TITLE
TST: Appveyor failed

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#765]
https://ci.appveyor.com/project/pllim/ginga/builds/23759091 for the latest commit to `master`.

**Comment by ejeschke** [comment]
Looks like something related to a site upgrade to python 3.6?  What do you think, @pllim?

**Comment by pllim** [comment]
Unfortunately I can't investigate right now. But Python 2 job shouldn't be running, so this is very perplexing.

**Comment by ejeschke** [comment]
I saw that Travis is also moving to a default python 3.6 configuration, so there may be related issues showing up there.

**Comment by ejeschke** [comment]
@pllim, I know what it is!  I pushed a cherry-picked commit to the v2.x branch.  Hmm, I don't know whether it is worth it, because there probably won't be too many commits to that branch, but I was thinking of porting a few more back fixes before abandoning that branch for the most part.

**Comment by pllim** [comment]
Still worth investigating, given theoretically we still support that branch... But probably not high priority. Thanks for the clarification!

**Comment by pllim** [comment]
Not an issue anymore with #784 in place.
