### ISSUE TITLE
ginga pick gets central position in 1-indexing

### ISSUE THREAD

**Issue by ysBach** [ejeschke/ginga#769]
While doing my data analysis for PSF photometry, I found my code always give warning because the ginga pick location (which are fed as initial guess to the true centroid) and the ``DAOStarFinder`` centroid differ more than 1 pixel all the time.

To test, I made a perfect Gaussian star at center = (31, 31) to a (51, 51) array.
```python
from astropy.modeling.functional_models import Gaussian2D
g = Gaussian2D(amplitude=1, x_mean=31, y_mean=31, x_stddev=2, y_stddev=2)
test = np.zeros((51, 51))
test_xx, test_yy = np.mgrid[:51,:51]
test += g(test_xx, test_yy)

finder = DAOStarFinder(fwhm=5, threshold=0, exclude_border=True)
test_found = finder(test)
test_pos = (test_found["xcentroid"][0], test_found["ycentroid"][0])
print(test_pos)
# (31.0, 31.0)

plt.imshow(test, origin="lower")
plt.plot(*test_pos, 'rx', ms=10)

test_ccd = CCDData(data=test, unit='adu')
test_ccd.write("test.fits", overwrite=True)
```
The position by ``DAOStarFinder`` is correct: ``(31.0, 31.0)``
![image](https://user-images.githubusercontent.com/17214293/58076145-73f97900-7be4-11e9-8a88-80faf9370d2a.png)

But ginga found ``(32.0, 32.0)``
![image](https://user-images.githubusercontent.com/17214293/58076242-b0c57000-7be4-11e9-8d84-9d40c18d6c2a.png)

Maybe I guess this is not expected...?

**Comment by ejeschke** [comment]
`Pick` reports location in FITS coordinates (1-based indexing) by default, whereas `DAOstarfinder` probably uses 0-based indexing.  Ginga's internal reporting is 0-based, however, and you can change the value shown in `Pick` by adding
```python
pixel_coords_offset = 0
```
to a text file `general.cfg` in your `$HOME/.ginga` folder.

**Comment by ysBach** [comment]
@ejeschke Oh, I didn't know that! OK, it's understandable to use FITS convention in interactive FITS viewers like ginga.
I was just unaware of it.

Thanks anyway for your answer!

**Comment by ejeschke** [comment]
@ysBach, glad to know that some astronomers are moving away from the archaic practice of 1-indexing.  Maybe in the future we will make the default `pixel_coords_offset = 0`.

**Comment by ejeschke** [comment]
BTW, excellent example of code for making a fake star!  I was looking for something like that for a guiding simulator I am working on, so this is really useful!  Now I just need to add some small artifacts to simulate the atmospheric distortion...

**Comment by ejeschke** [comment]
Might make for some good unit tests, @pllim!
