### ISSUE TITLE
MultiDim errors out on PrimaryHDU

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#77]
I use `MultiDim` on multi-extension FITS as such
```
0    Primary Header
1    SCI
2    ERR
3    DQ
```

When I select Extension 0, I get
```Error loading FITS HDU #1: 'NoneType' object has no attribute 'shape'```

Would be nice if it just displays the header and some sort of filler value for image display (grey? black? white?) instead of throwing an error. Primary header with no image data in Extension 0 is widely used by STScI. And the header has a lot of useful information, so it would be nice for Ginga to show it.

**Comment by ejeschke** [comment]
@pllim, I agree that the handling is poor for HDUs that ginga does not grok.  And currently the reference viewer can't do anything with table HDUs.  I was sort of hoping that someone with enough knowledge of the astropy table workings could add some support for tables.  Maybe Tom Aldcroft can help with this.

Can you send me an example FITS file so that I can test with it?  At least I ought to be able to handle the empty data HDU case pretty easily.

**Comment by pllim** [comment]
Unfortunately, I am not allowed to share the file I am working on. But you can get any multi-extension FITS from STScI Archive at http://archive.stsci.edu/hst/search.php . Example: http://archive.stsci.edu/cgi-bin/mastpreview?mission=hst&dataid=J8BT08041

That is a ACS/HRC image, which should give you a nice `[PRI, SCI, ERR, DQ]` set if you ask for FLT.

**Comment by ejeschke** [comment]
Could you try commit 16a8ace2f513319cbd3c865264b60b667fd196f5 and see whether the behavior is a little better?  This does not fix the fact that it reloads the HDUs from the file each time, but should provide better handling for non-data HDUs.

**Comment by pllim** [comment]
That fixed the error messages, but it does not display PrimaryHDU header in the `Header` plugin. Not sure if this is a good idea, but here it is: Do not make image-less PrimaryHDU an option at all, but instead have all the other extensions inherit the primary header (like one would see when one uses "imheader" in IRAF).

**Comment by ejeschke** [comment]
Could you check commit 0d1102997a3242e8e21484479b6d4dbfa69e0b11 ?  This should now show the primary header when you select HDU 1 and should not complain visually (except in the log) about missing data segments, etc.

**Comment by pllim** [comment]
Works for me. Thank you very much! I think this horse is also quite beaten up.
