### ISSUE TITLE
TST: Port CI to GitHub Actions?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#771]
Maybe? Only if you are interested, @ejeschke .

**Comment by ejeschke** [comment]
As an alternative to Travis-CI, or in addition?

Given Micro$oft's acquisition of `github`, I would think the integration should be pretty good (eventually?).  Goodness knows we've had some occasional trouble with Travis (weird failed builds due to http timeouts, etc).

**Comment by pllim** [comment]
> As an alternative to Travis-CI, or in addition?

Alternative to both Travis and Appveyor.

**Comment by ejeschke** [comment]
Ooh, Windows build and test as well?  Sounds good and maybe simplify the CI testing.

**Comment by pllim** [comment]
OSX too :smile_cat:

**Comment by ejeschke** [comment]
Triple-play!

**Comment by pllim** [comment]
Or if you want, maybe GitHub Actions instead? It uses the same underlying machinery as Azure Pipelines. I think it is just a different way to code it up.

**Comment by ejeschke** [comment]
@pllim, I'm fine with porting to a new CI pipeline. We have had trouble with Travis builds, but I feel like most of the frustrating problems have to do with download timeouts, which could also happen on any build host.

Are you getting some good info on the porting process from Travis to Azure or Github actions?

**Comment by pllim** [comment]
Azure is faster but still lacking the `[ci skip]` feature for a PR. That is a blocker for big project like `astropy` but maybe not so much for Ginga?

**Comment by pllim** [comment]
It's Actions now. It uses the same stuff as Azure but is more tied to GitHub.

**Comment by ejeschke** [comment]
I'm still ok with changing. Travis builds have been very fast lately. Maybe because more projects have moved off their infrastructure? :shrug:

**Comment by pllim** [comment]
I don't think there is a rush for this. 😄
