### ISSUE TITLE
Use setuptools-scm for version numbering

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#772]
See https://github.com/pypa/setuptools_scm for details.

What do you think, @ejeschke ?

**Comment by ejeschke** [comment]
Is this the package that other `astropy`-family projects are using to move away from relying on `astropy-helpers`?  I don't know anything about `setuptools_scm`, and just wondering what it's dependencies are and/or whether it has "traction" in the python community.

Otherwise, it looks reasonable.

**Comment by pllim** [comment]
Oh, yeah. Closing as this is a subset of #758
