### ISSUE TITLE
Contents listing order

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#78]
I just noticed that the file listing order in `Contents` are sorted
```
d
c
b
a
```
and not
```
a
b
c
d
```

Is this intentional? I was expecting alphabetically ascending order.

**Comment by ejeschke** [comment]
@pplim, if you click on the little arrow next to the word "Name" in the column header it will reverse the sort order.  You can sort on the other fields (e.g. Object) in the same way.  

I see what you mean though--seems like the default order ought to be increasing alphanumerically, not decreasing.  I'll take a look.

**Comment by ejeschke** [comment]
Could you try commit 0d1102997a3242e8e21484479b6d4dbfa69e0b11 ? Does this fix this issue?

**Comment by pllim** [comment]
Yes, it did. Thanks!
