### ISSUE TITLE
First cut levels not applied when typed in Info plugin, first time only

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#79]
Affects: reference viewer

When Ginga is first started and an image is loaded, typing a value for one of the cut levels in the Info plugin box and pressing enter does not apply the value.  Pressing a second time applies the value, and it appears that any subsequent values entered or pressed are applied correctly.

From looking at the log, it appears that for this initial case, the value is applied, but then reset.

**Comment by pllim** [comment]
Maybe this is related: When I have `autocuts='off'` set in `channel_Image.cfg` and I display a bunch of images at once using `ginga *.fits`, the "Cut Low" and "Cut High" values are both 0. I was expecting that the initial cut levels will be based on one of the images (first or last; doesn't matter to me), but then are fixed at those values until user explicitly change them. Having default 0/0 limits is not very useful.

**Comment by ejeschke** [comment]
Fixed.
