### ISSUE TITLE
Segmentation fault with Numpy 1.17.0

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#793]
Same problem as https://github.com/ejeschke/ginga/pull/764#issuecomment-523639951 but it appears to be a problem with `master` and not the pull request itself. 

A run with `gdb` wasn't too helpful either.
```
(gdb) where
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address ...: 
```

**Comment by ejeschke** [comment]
@pllim, does it give the same traceback as you showed in #764 conversation?  If so, I think the fix may be simple.

**Comment by pllim** [comment]
Yes, traceback is the same.

**Comment by ejeschke** [comment]
@pllim, could you do a `git pull` on master and give it another try in the `numpy` 1.17.0 environment?

**Comment by pllim** [comment]
Fixed now. Thanks!

**Comment by ejeschke** [comment]
Hmm, something must have changed that now returns a float rather than an int.  Could you try the following?
```python
import numpy as np
a = np.arange(1, 3, dtype=np.uint)
type(a[0].clip(0, 34))
```

**Comment by ejeschke** [comment]
I'd like to know in case there are some other potential calculations that might be affected.

**Comment by pllim** [comment]
```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np 
   ...: a = np.arange(1, 3, dtype=np.uint) 
   ...: type(a[0].clip(0, 34))                                                  
Out[1]: numpy.float64
```

**Comment by ejeschke** [comment]
*a-HA!*  I figured it was `clip`.  That's interesting. Thanks for the test.

**Comment by ejeschke** [comment]
Wonder if that is a bug in `numpy` 1.17.0?  Seems like `clip` of an `int` array should be an int.

**Comment by pllim** [comment]
Good question, @ejechke. I have reported it upstream at numpy/numpy#14334 and will see what they say.

**Comment by pllim** [comment]
p.s. If it is indeed a bug of Numpy, does that mean we have to revert c30ef770e204c63c2f4fbfafad85f4 when Numpy 1.17.1 is out, or just apply the `int` casting for 1.17.0? :thinking:

**Comment by ejeschke** [comment]
Looks like they added `ufunc` kwargs to `clip` in 1.17.0, and maybe this changed the default.  Could you run the tests under `ginga/tests`?  I'm wondering specifically how the `test_colordist` does.

Putting together a quick PR that should quash any bugs for other uses of `clip` in Ginga.

**Comment by pllim** [comment]
No failures for the existing tests with Numpy 1.17.0.
```
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0

Running tests with ginga version 3.0.dev2221.
Running tests in ginga doc.

Date: 2019-08-22T16:40:05

Platform: Linux-3.10.0-1062.el7.x86_64-x86_64-with-redhat-7.7-Maipo

Executable: .../miniconda/envs/py37/bin/python

Full Python Version: 
3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.17.0
Scipy: 1.3.0
Matplotlib: 3.1.1
Pandas: 0.24.2
Astropy: 4.0.dev25566
scikit-image: not available
astropy_helpers: 3.2rc1
Using Astropy options: remote_data: none.

rootdir: ..., inifile: setup.cfg
plugins: doctestplus-0.3.0, remotedata-0.3.1, openfiles-0.3.2, arraydiff-0.3, ci-watson-0.0.0.dev76+g4b73d3b5
collected 148 items                                                            

ginga/misc/tests/test_Callback.py .........................              [ 16%]
ginga/misc/tests/test_Future.py ......................                   [ 31%]
ginga/misc/tests/test_Task.py ........                                   [ 37%]
ginga/tests/test_ImageView.py ..                                         [ 38%]
ginga/tests/test_aimg.py ....                                            [ 41%]
ginga/tests/test_cmap.py ........                                        [ 46%]
ginga/tests/test_colordist.py ........                                   [ 52%]
ginga/tests/test_colors.py ..................                            [ 64%]
ginga/tests/test_imap.py ........                                        [ 69%]
ginga/tests/test_iohelper.py ..                                          [ 70%]
ginga/tests/test_iqcalc.py ....                                          [ 73%]
ginga/tests/test_wcs.py sss..sss..sss..sss.....................          [100%]

=================== 136 passed, 12 skipped in 14.67 seconds ====================
```

**Comment by ejeschke** [comment]
> p.s. If it is indeed a bug of Numpy, does that mean we have to revert c30ef77 when Numpy 1.17.1 is out, or just apply the int casting for 1.17.0?

I think it will be fine to keep the casting. It won't hurt in case that changes in the future sometime (again).
