### ISSUE TITLE
TST: Enable ReadTheDocs PR build

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#797]
As per https://blog.readthedocs.com/building-docs-for-pull-requests/ , we can take doc build job off Travis CI and let ReadTheDocs (RTD) do it instead. The advantages are that the documentation would be built exactly as it would after merge (no surprises caused by infrastructure difference) and you get a HTML preview *before* merge.

I already have this beta feature enabled for this repository. However, I cannot access the admin settings here, so @ejeschke would have to go in and make sure the RTD webhook is listening to "pull requests".

p.s. You can see it in action at spacetelescope/synphot_refactor#214 .

**Comment by ejeschke** [comment]
@pllim, I updated the setting to trigger on "Pull Requests".
