### ISSUE TITLE
Design an icon for ginga?

### ISSUE THREAD

**Issue by olebole** [ejeschke/ginga#804]
Hi,

thanks for the new version; I am just preparing its upload as a Debian package.
One request for perfection: it would be nice if ginga would have an icon that can be displayed f.e. in task bars. [`ginga-512x512.png`](https://github.com/ejeschke/ginga/blob/b33e09fff87921d10dc85fd1b0735a90ab102bca/ginga/icons/ginga-512x512.png) is too big for this.

Cheers
Ole

**Comment by pllim** [comment]
What about https://github.com/ejeschke/ginga/blob/master/doc/_static/ginga-128x128.png ?

**Comment by olebole** [comment]
Hmm, at the end this is your decision. To me, this does not look very beautiful: unreadable text in the icon, the bright center makes it difficult to read the japan letters (not that I knew what they mean…), too many small details. IMO it would be nice to have an easily recognizable schematic icon. It is not urgent at all however, and also probably not that important.

**Comment by pllim** [comment]
I will have to defer to @ejeschke for that decision. Maybe Subaru has a graphics artist.

**Comment by ejeschke** [comment]
Good suggestion, it is time we got a good icon.  Ginga (_geeng-gah_) means "galaxy" in Japanese, although I don't think the icon needs to represent a galaxy. We need something that can render well at small pixel sizes, and is somewhat original.  Now that we have an issue open, maybe we can brainstorm some ideas here!

**Comment by ejeschke** [comment]
@olebole, what is the preferred icon size and format? Are SVG icons accepted? As a vector format they scale nicely.

**Comment by olebole** [comment]
SVG is perfect for us, but I can live with everything (and would just convert during build).

**Comment by ejeschke** [comment]
Proposal!

![ginga_icon](https://user-images.githubusercontent.com/1305473/186071216-f178b5d2-b2f2-447b-9def-1d3ef82f14b0.png)

**Comment by ejeschke** [comment]
I have an SVG version that I could add to the repo.
