### ISSUE TITLE
File not openable just because of extension '.fit' ?

### ISSUE THREAD

**Issue by michaelaye** [ejeschke/ginga#808]
According to [Wikipedia](https://en.wikipedia.org/wiki/FITS), `.fit` is an allowed extension for FITS files and all Akatsuki mission camera data are stored as .fit files: https://atmos.nmsu.edu/PDS/data/vcoir2_0001/data/r0009/

I noticed that ginga cannot open a .fit file from that server, apparently just because of the extension `.fit` because after renaming it to *.fits it worked just fine?

Using Ginga 3.0.1

**Comment by ejeschke** [comment]
@michaelaye , what happens if you have `python-magic` installed via `pip` (and retry the open with `ginga`)?

**Comment by michaelaye** [comment]
Then it works. and it's admittedly a safer approach on opening supported files. However, how to balance another requirement vs a simple addition of an extension to allow? I struggle that balance as well all the time with my packages...

**Comment by ejeschke** [comment]
We can still add a check for ".fit".  However, it might be good to add `python-magic` as a requirement if there are a lot of variations that we are not aware of.

**Comment by michaelaye** [comment]
well, if peeps follow the standard as portrayed by Wikipedia, it's only .fits, .fit, and .fts.

**Comment by ejeschke** [comment]
It may not be an unreasonable claim that Wikipedia is the authority on such matters! :smile:  However, I wonder if the [IAU FITS working group](https://fits.gsfc.nasa.gov/iaufwg/) has some specification on file extensions...

**Comment by michaelaye** [comment]
Their page links to Wikipedia and the library of congress, with the latter only allowing .fits it seems. https://www.loc.gov/preservation/digital/formats/fdd/fdd000317.shtml#sign

**Comment by pllim** [comment]
@michaelaye , if you install dev version of Ginga, this should no longer be a problem.
