### ISSUE TITLE
Add "setuptools_scm" to the setup_requires option in setup.py?

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#819]
@pllim, it seems that I had a little bit of trouble installing ginga with #814 merged.  Don't we need to add "setuptools_scm" to the `setup_requires` option in `setup.py`?  I think I had to manually install `setuptools_scm` via `pip` before things installed correctly.

(I realize there is another fix in #818 that is a different issue.)

**Comment by ejeschke** [comment]
pllim wrote:
> Otherwise, if adding something like this (you need to check the syntax) in setup.cfg works for you, feel free to add it in:
```python
setup_requires = setuptools_scm
```

**Comment by ejeschke** [comment]
(@pllim, sorry, moved this from email to an issue to better discuss)

> Are you installing with "pip install -e ."? setuptools_scm is defined in pyproject.toml

Yes, but because I didn't have `setuptools_scm` defined it just went ahead and installed but gave me a version number of `0.0.0`.

**Comment by ejeschke** [comment]
I'll try adding that to `setup.cfg` and see if it makes a difference.

**Comment by pllim** [comment]
Did you fetch the tags from "upstream"? `setuptools_scm` relies on `git` tags to create the version.

**Comment by ejeschke** [comment]
If I add it to the "[options]" are in `setup.cfg` then `python setup.py install ` works fine to get the correct version.

**Comment by pllim** [comment]
Ah, but we're not supposed to be using `python setup.py install` anymore. The new command should be `pip install -e .` to install the developer version.

**Comment by ejeschke** [comment]
I understand, but I think a lot of people will not read the install instructions and expect the old way to work.

**Comment by ejeschke** [comment]
What is being planned for `astropy` core? Will it raise a nag message if someone tries to do `python setup.py install`, telling them the correct command invocation?

**Comment by pllim** [comment]
Good question... If @astrofrog don't answer I'm time, I'll try it on his PR.

**Comment by pllim** [comment]
@ejeschke , trying to install astropy/astropy#9726 , when I do `python setup.py install`, I first get this error:

```
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from extension_helpers import get_extensions
ModuleNotFoundError: No module named 'extension_helpers'
```

After I manually `pip install extension-helpers` though, it does install as usual. Does this answer your question?

**Comment by ejeschke** [comment]
Hmm, doesn't sound very helpful to the user. I hope something better is planned, otherwise there will be a lot of issues reported for those that didn't read the release notes.

**Comment by pllim** [comment]
@ejeschke , feel free to comment on the Astropy pull request linked above. As for this issue, looks like you added setup_requires on master, so I'm closing it. Thanks!
