### ISSUE TITLE
How to change NAXIS1 view of 4D cube?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#824]
I have a big data cube from TESS with the following layout:
```
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      31   ()      
  1                1 ImageHDU         9   (2, 1282, 2136, 2078)   float32
  2  ...        ...  BinTableHDU    553   1282R x 184C   [...] 
```

When I load it in Ginga, I think it defaults to displaying `image[2, 1282, :, :]` (not a Python notation). But what I really want is `image[1, :, :, :]`, which would give me a `1282 x 2136 x 2078` 3D cube. I cannot seem to find a way to change the values of NAXIS1 and NAXIS2 in `MultiDim` (see below).

![Screenshot from 2020-02-05 18-01-57](https://user-images.githubusercontent.com/2090236/73891227-ca294d80-4841-11ea-82aa-064c6aae8b55.png)

The extension 1 FITS header:
```
XTENSION= 'IMAGE   '           / Image extension                                
BITPIX  =                  -32 / array data type                                
NAXIS   =                    4 / number of array dimensions                     
NAXIS1  =                    2                                                  
NAXIS2  =                 1282                                                  
NAXIS3  =                 2136                                                  
NAXIS4  =                 2078                                                  
PCOUNT  =                    0 / number of parameters                           
GCOUNT  =                    1 / number of groups
```

**Comment by ejeschke** [comment]
I think you hit upon a PR enhancement, @pllim.  `MultiDim` I think simply skips the first two dimensions as far as providing NAXIS controls.  Then, I think you *may* also need to modify `AstroImage` and probably `ginga.util.io_fits` to navigate through the first two dimensions of the `naxispath` argument.

But all in all, not a big deal (I *think*).

**Comment by pllim** [comment]
Coming back to this issue, I think I had stumbled upon a transposed cube especially made for `TESSCut`. See https://github.com/ejeschke/ginga/pull/805#issuecomment-583495735 and astropy/astrowidgets#110. Probably not worth pursuing.

**Comment by ejeschke** [comment]
I think I'm missing something here, looking at this again. Shouldn't NAXIS3, NAXIS4 ... NAXISN provide all the controls needed to navigate down to any 2D slice?

The fact that NAXIS1 == 2, NAXIS2 == 1282 means that you have a 2x1282 slice at the end of the day (would be a a line, basically).  But you can navigate through all the upper dimensions to get to those slices.

**Comment by ejeschke** [comment]
Now if you want to roll the axes, or do a higher-order transpose (not just swap X and Y) before loading a slice, that we do not have controls for, presently.  But as those are standard `numpy` operations, it wouldn't be hard to add them.

**Comment by pllim** [comment]
Transpose is very slow for this particular cube. What I ended up doing is transpose it outside of Ginga and save it in the "correct" dimension.
