### ISSUE TITLE
How do I make a mosaic from different extensions of the same FITS file?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#825]
I have a FITS file with 4 extensions. I cannot seem to drag the different extensions loaded into the Image channel into the `Mosaic` plugin. Is there a way to do this? Thanks!

**Comment by ejeschke** [comment]
@pllim, the interface is a bit limiting at the moment. I'd try checking the "Mosaic HDUs" box and then dragging the file in`to the window from `FBrowser`.

I'd like to eventually enable dragging of images from `Contents` or `Thumbs` for that kind of purpose. Or maybe some general way to operate a plugin on a selection from `Contents` or `Thumbs`. Future PR...

**Comment by pllim** [comment]
Ah yes, checking the HDU box worked. Thanks!

Although that means it only has the option to mosaic all the HDUs in the file, which is not always what I want to do, especially if I only want to mosaic the SCI extensions and ignore the ERR or DQ extensions.
