### ISSUE TITLE
"pip install -e .[docs]" does not install all dependencies

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#829]
In particular, `sphinx_rtd_theme` is not installed and must be installed manually afterward:
```bash
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v2.4.4
making output directory... done

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 2
```

**Comment by ejeschke** [comment]
I think this may just be a matter of adding "sphinx_rtd_theme" to the list in `setup.cfg` for "docs". Currently:
```python
docs = sphinx-astropy
```
Suggested:
```python
docs = sphinx-astropy, sphinx_rtd_theme
```
@pllim, do you concur? If so, I will submit a PR.

**Comment by pllim** [comment]
Hmm. RTD could build it with no problem, but doesn't hurt to add it anyway if you need it. 👍

**Comment by ejeschke** [comment]
On my box I could not build it. I got the following error:
```bash
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v2.4.4
making output directory... done

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 2
```
After manually installing `sphinx_rtd_theme` via `pip`, it built fine.

**Comment by pllim** [comment]
>  do you concur? If so, I will submit a PR.

@ejeschke , sorry for the confusion, I do concur.

**Comment by ejeschke** [comment]
AFAIK, this was fixed with the commits noted above. Closing.
