### ISSUE TITLE
PixValue not reporting correct value when used with Zoom

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#836]
First reported in https://github.com/ejeschke/ginga/pull/812#issuecomment-618754188 but then I realized it is already that way on `master` even without #812 patch. Release 3.0.1 worked fine. I tried rolling back the OpenGL PR #830 but that didn't help either.

UPDATE: Caused by  #806 . With current `master`, if you set the zoom amount in `Zoom` to, say `1/18x`, `PixTable` reports correct values!

**Comment by ejeschke** [comment]
Hmm..I just tested this over ssh with branch `master`. It works fine for me.  Platform is Linux.

**Comment by pllim** [comment]
There is no way to check if it is also a problem when I am physically at that machine, unfortunately. The SSH is handled by NoMachine, but as I mentioned above, `PixValue` works fine when I downgraded to 3.0.1.

**Comment by ejeschke** [comment]
![Screenshot from 2020-04-24 09-18-07](https://user-images.githubusercontent.com/1305473/80249085-e9e43c80-860c-11ea-85c8-17898cf0c2a4.png)

**Comment by ejeschke** [comment]
I am just using standard ssh-tunneled display back.

**Comment by pllim** [comment]
Did you try SSH from Windows to Linux? 😅

**Comment by ejeschke** [comment]
Just out of curiosity, could you try (on the affected machine) to remove all `__pycache__` and `build` dir and do a `pip install .` (without the `-e`).  Just want to make sure we don't have a stale file in there anywhere...

**Comment by ejeschke** [comment]
`git clean -xdf` would be even better...

**Comment by pllim** [comment]
I don't think that's going to change anything. This was how I install.

```
git clean -xdf
pip install -e .
```

But I'll try anyway and report back.

**Comment by ejeschke** [comment]
Oh, you are already being thorough.  This is going to be an interesting bug hunt. Are you able to do a regular `ssh -X` type login through your VPN and test that way (without NoMachine)?

**Comment by pllim** [comment]
Unfortunately, no. For pop-up graphics, I need the NoMachine client to work. Long story.

**Comment by pllim** [comment]
So, in testing `master` to see if a release is viable, I am reminded of this bug again. I need to ping @Skyhawk172 and @obi-wan76 to see if this is a deal breaker for them, especially given the work-from-home situation. If it is a deal breaker, STScI will just have to pin Ginga to 3.0 (where this is not a problem) for now.

**Comment by pllim** [comment]
I also tried the following and encountered the same problem (with more lag too but that is a separate story):

`Windows -> WSL 2 (Debian) -> SSH -> Ginga`

**Comment by ejeschke** [comment]
@pllim, does `Cursor` report the correct cursor position?  All the plugins are pretty much feeding off the same mouse reporting call, so I'd be surprised if only `PixTable` was affected.  Maybe zoom in a lot and compare a local viewer loading the same file with an NX display of same file?

**Comment by pllim** [comment]
@ejeschke , I think I tracked it down to #806. Something you did in `Zoom` somehow changes some global state that affects `PixTable`. With current `master`, if I adjust "zoom amount" in `Zoom` to very small (say, `1 / 8x`), `PixTable` reports the correct values again! If I increase the "zoom amount" from there on, I see `PixTable` reporting change for the same area of image. Does this behavior make sense to you?

**Comment by pllim** [comment]
I have a feeling maybe this line but I don't know enough of the internals to understand why:

https://github.com/ejeschke/ginga/blob/1c30ad4b8ac608a6c813ac0e07a53986f5ab3f4c/ginga/rv/plugins/Zoom.py#L235

**Comment by pllim** [comment]
Cursor seems normal as far as I can tell.

p.s. The key to getting `PixTable` value to match cursor value is set "zoom amount" to very small. I think the magic zoom amount also depends on the input image size but I am not 100% sure.

**Comment by ejeschke** [comment]
> Windows -> WSL 2 (Debian) -> SSH -> Ginga

@pllim, was this also with NX?  I am just wanting to rule out any possible mouse/cursor registration issue with the remote display technology (i.e. unrelated to Ginga, or maybe in Qt, etc). As I mentioned above, I did not see this issue with vanilla ssh/X display back.

**Comment by ejeschke** [comment]
I'll take a closer look at `Zoom`.

**Comment by ejeschke** [comment]
@pllim, if you run with `--disable-plugins=Zoom` does it work as expected without any special adjustments?

**Comment by ejeschke** [comment]
> Does this behavior make sense to you?

No.  Especially if you only see it in ssh display back.  Can't understand how that could change the plugin's behavior.  Can you definitively say that when you run the current master locally (on Windows or WSL) that you don't see the problem?

**Comment by ejeschke** [comment]
@pllim, I am able to reproduce it if I start Zoom! :smiley: Yay, and it happens locally too! 

Good work tracking it to that plugin. Think I may know where this is happening. I'll be posting a PR.

**Comment by ejeschke** [comment]
Please see #847.
