### ISSUE TITLE
Help button segfaults

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#837]
I think this is a side effect of #830 even though I started Ginga *without* `--opengl` option. I see this on Linux:

1. Start Ginga: `ginga --loglevel=30 --stderr`
2. Start any plugin
3. Click "Help"

Ginga crashed with segfault:
```
QOpenGLShader::compile(Vertex): failed
QOpenGLShader::compile(Fragment): failed
Could not link shader program:
 ""
Segmentation fault
[14890:14890:0100/000000.705366:ERROR:broker_posix.cc(41)] Invalid node channel message
```

**Comment by ejeschke** [comment]
@pllim, I think I may have fixed this issue in commit 882653935bac2395ca7131e16fa3a074abc36aeb. Could you try to recreate the error using master on the platform that you got this error?

**Comment by pllim** [comment]
Unfortunately, it still segfaults with latest `master` with that commit you mentioned:
```
2020-05-04 15:15:03,925 | W | rgb_cms.py:64 (profile_to_working_pil) | No working profile defined; leaving image unprofiled.
QOpenGLShader::compile(Vertex): failed
QOpenGLShader::compile(Fragment): failed
Could not link shader program:
 ""
Segmentation fault
[28479:28479:0100/000000.119132:ERROR:broker_posix.cc(41)] Invalid node channel message
```

I did a clean install.

**Comment by ejeschke** [comment]
@pllim, I will need your help because I cannot reproduce this issue on any machine so far.  Could you comment out the following lines in `ginga.qtw.ImageViewQt.py`:
```python
## try:
     from ginga.opengl.CanvasRenderGL import CanvasRenderer as OpenGLRenderer
     from ginga.opengl.GlHelp import get_transforms
     from ginga.opengl.glsl import req

     have_opengl = True
 except ImportError:
     pass
```
so that it looks like:
```python
## try:
##     from ginga.opengl.CanvasRenderGL import CanvasRenderer as OpenGLRenderer
##     from ginga.opengl.GlHelp import get_transforms
##     from ginga.opengl.glsl import req

##     have_opengl = True
## except ImportError:
##     pass
```
Ginga only tries to build an opengl program if the `--opengl` switch is passed, so I think this error message must be coming from the Qt web widget or somewhere else in Qt. These lines (above) are the only thing that I can imagine would be affecting things and all they do is cause `pyopengl` to be imported--no opengl programs are compiled just importing them.

**Comment by pllim** [comment]
That didn't fix it. I think it is related to `from qtpy.QtWidgets import QOpenGLWidget` in `QtHelp.py`. I think you said that my OpenGL is too old but maybe Ginga is trying to use it anyway? Is there a way to not use it if it is too old?

**Comment by ejeschke** [comment]
Except Ginga doesn't build anything or allocate any widgets or set any global OpenGL settings, unless you pass `--opengl`.  Following up your idea, could you comment out the import of `QOpenGLWidget` in `QtHelp.py` and in `ImageViewQt` remove it from the import list and comment out the entire `RenderGLWidget` class definition. That way it should not be imported at all.

**Comment by ejeschke** [comment]
Ooh, I have an idea.  If the above still doesn't work, we could try changing the order of import statements in `QtHelp.py` so that `QWebEngineView` is imported *before* `QOpenGLWidget`. I'm guessing that the Qt web widget uses or initializes OpenGL somehow..

**Comment by pllim** [comment]
So... I think this is actually unrelated to the OpenGL PR. Internet suggests that the error message might be a Linux bug dealing with browser and "Help" uses `WBrowser`. I downgraded Ginga to 3.0.1 and the problem still exists. Maybe it is the way I am SSH-ing into the machine that is causing this. Sorry for the noise!

**Comment by ejeschke** [comment]
Hmmm, there seem to be quite a few results when I search up "QWebEngineView linux segmentation fault".  I guess we can reopen if the problem resurfaces again in other settings.  Thanks for your investigation!

**Comment by pllim** [comment]
I had my colleague, @rendinam, tried it out on his local Linux installation. He also reported a segfault but it does not appear until he quits Ginga. And it only appears if he clicks the Help button:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffbd16bdcc in ?? () from .../venvs/ginga/lib/python3.7/site-packages/PySide2/Qt/lib/libQt5WebEngineCore.so.5
```

He was using the latest dev version of Ginga and Qt backend.

**Comment by pllim** [comment]
FWIW, no segfault on Windows 10.

**Comment by ejeschke** [comment]
> And it only appears if he clicks the Help button

Meaning when the Help button is pressed, or when the program exits?  I notice from the error message he is using `PySide2`, which is a platform we don't test very often (usually `conda` installs `PyQt5`...).

**Comment by pllim** [comment]
> Meaning when the Help button is pressed, or when the program exits?

When he clicks the Help, the segfault happens on exit.

**Comment by ejeschke** [comment]
> When he clicks the Help, the segfault happens on exit.

I was able to reproduce this with a `PySide2` environment on Linux. It doesn't seem to happen with `PyQt5`.  I'll file an issue.
