### ISSUE TITLE
MultiDim layout is wrong

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#849]
![multidim_horizontal](https://user-images.githubusercontent.com/2090236/86835811-a6756800-c06a-11ea-8e6f-47a1a4ce1ddd.jpg)

The second box should have been stacked horizontally below the first box.

**Comment by pllim** [comment]
Happens on older releases too like 3.0.1 and 2.7.2, so maybe this is caused by Qt?

**Comment by ejeschke** [comment]
@pllim, it looks like the space for the `MultiDim` window is wider than it is tall?  Is it correct? If so, it is the normal behavior because `MultiDim` is using `Widgets.get_oriented_box()`.

**Comment by pllim** [comment]
@ejeschke , perhaps. It is a wide screen monitor. But even if I force `orientation = 'vertical'` in the plugin code, nothing seems to change.

**Comment by ejeschke** [comment]
You will find that if you close `MultiDim` and resize Ginga so that the space where the plugin will go is now taller than it is wide, and reopen `MultiDim`--it will now stack the boxes vertically.

**Comment by ejeschke** [comment]
> But even if I force orientation = 'vertical' in the plugin code, nothing seems to change.

Except that the orientation that it "discovers" is used multiple places in the `build_gui()`.

**Comment by pllim** [comment]
I tried it like this:
```diff
--- a/ginga/rv/plugins/MultiDim.py
+++ b/ginga/rv/plugins/MultiDim.py
@@ -101,8 +101,9 @@ class MultiDim(GingaPlugin.LocalPlugin):
         top = Widgets.VBox()
         top.set_border_width(4)
 
-        vbox, sw, orientation = Widgets.get_oriented_box(container,
-                                                         scrolled=True)
+        vbox, sw, _ = Widgets.get_oriented_box(container,
+                                               scrolled=True)
+        orientation = 'vertical'
         self.orientation = orientation
         vbox.set_border_width(4)
         vbox.set_spacing(2)
```

**Comment by ejeschke** [comment]
If you feel strongly that this plugin should never have the horizontal orientation it can be fixed to a vertical.  Or, it can be fixed to better layout when it detects a horizontal orientation.  I'm trying to keep in mind various possible layouts that people might want to use rather than being fixated on the tri-pane default.

**Comment by pllim** [comment]
I see no reason why the boxes in `MultiDim` should ever be stacked horizontally like that. 🤷‍♀️

**Comment by ejeschke** [comment]
No, you would need to do something like:
```python
vbox = Widgets.VBox()
sw = Widgets.ScrollArea()
sw.set_widget(vbox)
orientation = 'vertical'
```

**Comment by pllim** [comment]
Thanks, @ejeschke !

**Comment by ejeschke** [comment]
> I see no reason why the boxes in MultiDim should ever be stacked horizontally like that.

![ginga_alt_layout](https://user-images.githubusercontent.com/1305473/86842976-a7de6a80-c041-11ea-844d-3c2f8e437a57.png)

**Comment by pllim** [comment]
Re: https://github.com/ejeschke/ginga/issues/849#issuecomment-655133949 -- Hah, okay. Though even in that layout, I think vertical might still work... 😅

**Comment by ejeschke** [comment]
Above shows a layout where user has hi-res monitor with lots of horizontal and vertical space. They are always interested in the FITS headers, so `Header` gets a nice big vertical box. They've added a workspace to the lower central area where the `MultiDim` works quite nicely in horizontal mode, alongside `Pan` and `Info` and maybe `Zoom`.

**Comment by pllim** [comment]
But that penalizes normal user with a screen just wide enough that it becomes horizontal when vertical is desired... Hmm...

**Comment by ejeschke** [comment]
@pllim, see #851
