### ISSUE TITLE
BUG: WCSAxes plugin is broken

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#855]
Using the latest `master`, it no longer works. Maybe related to the recent refactoring associated with shapes/canvas. I used HST/ACS calibrated fullframe image but I don't think the image matters as long as it has a valid WCS.

![broken_wcsaxes](https://user-images.githubusercontent.com/2090236/86971894-feca6980-c13f-11ea-9127-9c7fc815467f.jpg)

To reproduce:

1. Open image with WCS in Ginga.
2. Start WCSAxes plugin.

**Comment by ejeschke** [comment]
@pllim, I don't have access to that file, but I tried another HST one that I have:
![Screenshot from 2020-07-08 11-40-00](https://user-images.githubusercontent.com/1305473/86973193-e5a9c480-c10f-11ea-89d4-aa0ae23d163d.png)

**Comment by ejeschke** [comment]
Some Subaru ones look fine.  I do notice two problems:
- there seems to be a print statement that prints "diff <some set>" that should be removed or changed to a logger debug statement
- the plugin does not seem to respond correctly on `redo()` when I switch between thumbs. It seems like it does not recognize that the image has changed
