### ISSUE TITLE
Release checklist for 3.1

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#858]
- [x] Need #856 
- [x] Decision on whether to punt #763 to 3.2 or not
- [x] Merge #861
- [x] Make sure there are no outstanding open items in https://github.com/ejeschke/ginga/milestones/3.1

**Comment by ejeschke** [comment]
So, @pllim, ready for 3.1 release after merge #860 ?

**Comment by ejeschke** [comment]
Also need to fix #841

**Comment by pllim** [comment]
I'll follow up on Monday. Thanks for your patience!

**Comment by pllim** [comment]
I think 3.1 is GTG unless you have other things you want to fit in it.

**Comment by ejeschke** [comment]
No, I think it's baked. Let's pull it out of the oven!

Thanks for your thorough help, as always!

**Comment by pllim** [comment]
🥧 ❤️ 

You are welcome!
