### ISSUE TITLE
Is there a way to have multi-line config value for plugin?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#859]
In [DQInspect](https://stginga.readthedocs.io/en/stable/stginga/plugins_manual/dqinspect.html), I found myself writing a very long config item in `~/.ginga/plugin_DQInspect.cfg`:
```python
dqdict = {'NIRCAM': 'data/dqflags_jwst.txt', 'NIRSPEC': 'data/dqflags_jwst.txt', ..., 'WFPC2': 'data/dqflags_hstgen.txt'}
```

I wonder if there is a way to add in line breaks so it is more human-readable in a way that won't break Ginga.
```python
dqdict = {'NIRCAM': 'data/dqflags_jwst.txt',
          'NIRSPEC': 'data/dqflags_jwst.txt',
          ...,
          'WFPC2': 'data/dqflags_hstgen.txt'}
```

It is okay if that is not possible. I am just wondering. Thanks!

**Comment by ejeschke** [comment]
See #862
