### ISSUE TITLE
Ginga window position

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#86]
Is it possible to configure Ginga such that it does not start at `(0,0)` of the screen? What if I want it to start centered on my screen? If not, that's fine; I am just wondering. I am unable to find this info in http://ginga.readthedocs.org/en/latest/manual/customizing.html

**Comment by ejeschke** [comment]
@pllim, could you try setting the autocenter feature to 'on' or 'override'.  Bring up preferences for the Image channel.  You'll find the setting near the bottom.  Save your preferences.

Does this do what you want?

**Comment by pllim** [comment]
@ejeschke , I am not talking about panning the image. I am talking about the positioning of the Ginga application itself (the widget) on the monitor screen.

**Comment by ejeschke** [comment]
Could you try the --geometry command line option?  Does that do what you want?

**Comment by pllim** [comment]
That might work, what is the proper syntax for that option?

**Comment by ejeschke** [comment]
Try +nnn+mmm.  I believe it is the same as for any X application, i.e. WxH+X+Y.  You can omit the size and just specify the offset.

**Comment by pllim** [comment]
Ah, okay. That works for me. Thanks!
