### ISSUE TITLE
Doc: Ginga color palette

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#87]
Would be nice for developer to have access to a color palette in the documentation as defined by `colors.py`.

**Comment by ejeschke** [comment]
Do you mean to be able to define your own colormaps?

**Comment by pllim** [comment]
No, I just want to see a table of supported color names and what the color looks like. I spent 15 minutes today going through the names in `colors.py` trying to find one that looks nice for my plugin. Something like http://matplotlib.org/examples/color/colormaps_reference.html

**Comment by ejeschke** [comment]
I see.  I actually have some code that shows a small preview of the color map, along with the name.  Was planning to use this, but it seems there is a problem with it and recent versions of Qt.  Need to work on it.

Do you want to use a matplotlib colormap with ginga?  You can.

**Comment by pllim** [comment]
I wasn't really looking for an entire colormap. I was just looking for one specific color that would go nicely with the image I am using (for a shape I am trying to superimpose on the image). The small preview you mentioned sounds useful when you get the chance to fix it.

**Comment by ejeschke** [comment]
Just FYI, if you have matplotlib installed, and want to add their selection of colormaps to ginga, add the following line to `$HOME/.ginga/general.cfg`:
```python
useMatplotlibColormaps=True
```

**Comment by pllim** [comment]
I think this has been solved by `ColorMapPicker` plugin.
