### ISSUE TITLE
Drop Python 3.5

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#879]
Should we drop support Python 3.5, @ejeschke ? `conda` doesn't even ship things with it anymore and Python org is dropping it next month, see https://devguide.python.org/#status-of-python-branches .

https://github.com/ejeschke/ginga/blob/7e7ed3a1dba908d0d41607055f7df11d563c8195/setup.cfg#L43

Bonus: We can use f-string once we drop Python 3.5.

**Comment by ejeschke** [comment]
I'm in favor. Further, I'd say minimum version of 3.7, unless you think there is a good reason not to.

**Comment by pllim** [comment]
I am using 3.8 myself, so if you want to drop 3.6, I won't object. 😸
