### ISSUE TITLE
Pick plugin: Not obvious when FWHM fitting failed

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#884]
In the `Pick` plugin, currently user can switch between Gaussian and Moffat (and with #880, Lorentz too). When I switch "FWHM fitting" algorithm choice in Settings and click Redo Pick, it is hard to tell if the fit was actually successful or not without looking at the terminal output.

On the terminal, I would see things like `RuntimeWarning` or (with #880 and using `astropy.modeling`) `The fit may be unsuccessful`. However, there is no indication of any problem back at the GUI. At worst, the numbers don't update and one might mistake result from a previous selection as result for the new algorithm.

Given the already crowded GUI, perhaps the simplest solution is to clear the plot before attempting a re-fit. Then user will know something is wrong if a new plot does not appear. What do you think, @ejeschke ?

**Comment by pllim** [comment]
It seems like `Pick` has logic to do `self.fwhm_plot.clear()` but I cannot seem to trigger it even when I purposely pick an empty part of the sky and `Pick` cannot find any source. With all the `try ... except ...` in `Pick`, it is hard to debug and the log traceback isn't particular informational for me.

**Comment by ejeschke** [comment]
When it fails to find any objects the display looks like this:
![failed_pick](https://user-images.githubusercontent.com/1305473/91520907-3927cb80-e892-11ea-890f-4f474973b823.png)

with a bright red "X" on both the display and the cutout. In the lower right "status message" for `Pick`, the message "Cannot find bright peaks" appears.  This is what I would expect to happen if the fit fails. 

Is there a way to tell easily if the `astropy.modeling` fit fails? If so, we should be able to recreate this same effect.

**Comment by ejeschke** [comment]
For the `FWHM` and `Radial` plots, see #889.  I think this does what you are expecting.
