### ISSUE TITLE
MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#890]
This deprecation warning appears from [this line](https://github.com/ejeschke/ginga/blob/master/ginga/cmap.py#L13317) in `ginga.cmap`.  It looks like `matplotlib` is trying to [deprecate accessing the global colormaps dictionary](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cm.py#L75-L118).  

So far I have not found a replacement API for getting the same information using a public API.

**Comment by pllim** [comment]
Hmm. I haven't seen it. Maybe I am not using a new enough Matplotlib.

**Comment by ejeschke** [comment]
Seems to be a bleeding-edge version...

**Comment by ejeschke** [comment]
Looks like we might be able to replace
```python
for name in _cm.cmap_d:
```
with
```python
for name in _cm._gen_cmap_registry():
```
But of course that also looks like an internal API, and we'd need to check `matplotlib` version before trying to access it.

**Comment by pllim** [comment]
xref matplotlib/matplotlib#16991
