### ISSUE TITLE
evaluate_peaks takes bright_radius but does not use it

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#898]
https://github.com/ejeschke/ginga/blob/965d1ec23fdf02b7a48c86b428153346c6ce5cad/ginga/util/iqcalc.py#L466

`ginga.util.iqcalc.evaluate_peaks()` takes an optional keyword called `bright_radius`. Calling function even passes it in, but it is not used anywhere inside `evaluate_peaks`. Did I miss something, @ejeschke ?

xref #896

**Comment by ejeschke** [comment]
:man_shrugging: Not 100% sure about this one, @pllim.  It looks like the idea was to allow the option to pass in a separate radius parameter for one of the functions that would be used in evaluating the peaks.  It's possible (likely?) that `evaluate_peaks` evolved and the parameter was kept just to preserve the API even though it wasn't used anymore.  I spent a little bit of time grepping through our various codes that use Ginga, but I can't find any uses of the parameter.

My best guess is that maybe it used to be a way to pass a separate radius to the centroid call in the middle of the loop (which now appears to use the `fwhm_radius`, but perhaps didn't at first).  There could be other explanations; I didn't look through the history of the changes to this function yet.   I'll poke around a bit more and see what I can dig up.

**Comment by ejeschke** [comment]
@pllim, I've removed this unused parameter in #996.  I added a note in the docstring for all the methods that took ``bright_radius`` as a parameter.
