### ISSUE TITLE
Doc: Mosaic plugin

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#90]
Hi. I have difficulty figuring how to use `Mosaic` local plugin properly. There does not seem to be much documentation about this. For example, what if I have several images loaded, and I want to mosaic together two of them that I see in `Thumbs`?

**Comment by ejeschke** [comment]
Hi @pllim, Mosaic is not documented at all I think, and not completely polished, although we subclass it and are using a customized version regularly with certain instruments here.

Start the plugin, and set a compatible field of view (in degrees) in the plugin (say, large enough to hold the mosaiced result).  Now drag your two images onto the main channel window where the plugin is active.  They should be mosaiced into a single image.  I don't think Thumbs or Contents can be the source of this drag (at least presently), but you can drag from the FBrowser plugin or from the Mac finder, or a Linux Nautilus window.

Caveat: the quality of the mosaicing is really only quicklook-level.  So don't expect sub-pixel alignment or support for odd distortions.  This is pretty much a simple rotate and drop in kind of plugin.

I'd like eventually to create a version that would figure out a reasonable field width from the dropped images, but I haven't gotten that far yet with this plugin.

**Comment by pllim** [comment]
STScI has AstroDrizzle (http://www.stsci.edu/hst/HST_overview/drizzlepac/photometry/astrodrizzle), but unfortunately I don't think it is suitable as a plugin here.

**Comment by pllim** [comment]
Anyway, it looks like `Mosaic` is not what I need. You may close this issue if you want to.
