### ISSUE TITLE
Pick reports two different sets of FWHM values

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#900]
I saw this in https://github.com/ejeschke/ginga/pull/896#issuecomment-692832388 but I don't think it is related to my changes in that PR, so I am reporting this as a separate issue. Image can be obtained from https://stsci.box.com/s/c1rs5hqbv4mc6qlmw6fa9qedcina9p07 (special permission required for access).

**Problem**

Readout reports different FWHM X and FWHM Y from FWHM plot.

| | Readout | FWHM plot |
| --- | --- | --- |
| FWHM X | 4.883 | 3.74 |
| FWHM Y | 8.248 | 5.09 |

**Expected behavior**

Readout FWHM values should be consistent with FWHM plot.

**Screenshots**

![Screenshot 2020-09-15 124149](https://user-images.githubusercontent.com/2090236/93239680-20a02800-f751-11ea-9178-050ea374be02.jpg)

![Screenshot 2020-09-15 124209](https://user-images.githubusercontent.com/2090236/93239689-239b1880-f751-11ea-9ed8-628b64448811.jpg)

**Comment by ejeschke** [comment]
@pllim, found the issue: the plot redoes the fwhm calculation, but was not including the sky background calculation, so the background was using a smaller data set to get the mean. 

If you rebase #896 you will pick up the fix.

**Comment by pllim** [comment]
Yes, the values agree now and the plot makes more sense too. Thanks!
