### ISSUE TITLE
Adding total brightness inside the box in PixTable 

### ISSUE THREAD

**Issue by obi-wan76** [ejeschke/ginga#904]
Hi all, 
This is a request to add the total sum of the pixel values as one of the outputs in PixTable. This would be in addition to the existing output, Min, Max, Avg and Rms. I think the total surface brightness within the NxN box would be a very useful feature for a quick assessment of a PSF brightens when trying to identify best observing strategies. 

There may be other ways to obtain the total brightness inside a NxN box inside Ginga. For example, I am wondering if the total flux of a 3x3 box can be obtained via Pick by changing the Box size, however, currently the lowest setting allowed seems to be 5. 

However, having this total brightens functionality - within a NxN box - seems to be appropriate for the PixTable plugging. 

Thanks!

**Comment by ejeschke** [comment]
@obi-wan76, seems straightforward and sensible.  Want to give it a go with a PR?  :smile_cat: 

Otherwise I'm sure we can get to it before release 3.2 (hopefully this month).  

Maybe the label should be something like "box sum"?

**Comment by pllim** [comment]
@ejeschke , maybe somewhat related... When the box is 3x3, some stats get cut off like this:

![Screenshot 2020-10-06 172559](https://user-images.githubusercontent.com/2090236/95261837-14136a80-07f9-11eb-9ec3-ec0da3e05c30.jpg)

I am wondering if the stats need to be broken into 2 lines.

**Comment by obi-wan76** [comment]
@pllim good point. If I change the Font Size it will fit but then it is too small to read comfortably.

**Comment by obi-wan76** [comment]
@ejeschke "Box Sum" sounds reasonable.

**Comment by pllim** [comment]
@obi-wan76 , do you want to take a stab at this or you want me to implement it with TEL money? 😸

**Comment by ejeschke** [comment]
Breaking it into two summary lines sounds like the easiest thing for now...

**Comment by obi-wan76** [comment]
@pllim Let me see if this is something that I can do (time permitted), ot

**Comment by pllim** [comment]
No need to close so soon. We can close when the PR is resolved. 😄

**Comment by obi-wan76** [comment]
@pllim Sorry! I pressed the wrong button! (why is Comment next to Close?? 😄 )

**Comment by pllim** [comment]
@obi-wan76 , if you want this in the next release but don't have time to implement in the next week or two, please let me know. I'll  be glad to help.

**Comment by obi-wan76** [comment]
@pllim Yes, I don'y think I'll have the time but I would like this to be implemented before the next release. If you can help it would be great, Thanks!

**Comment by pllim** [comment]
@obi-wan76 , if you use the dev version of Ginga now, you should be able to see the total brightness under "Sum". Thanks for your help, @ejeschke !

**Comment by ejeschke** [comment]
> Thanks for your help, @ejeschke !

My pleasure. Good update to this plugin.

**Comment by obi-wan76** [comment]
@pllim @ejeschke I'll give it a try, this will be a very useful update for us, thanks for all your help.
