### ISSUE TITLE
How to close an image?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#91]
How to close an open image without deleting the whole channel? This might sound silly but I cannot find the close button!

**Comment by ejeschke** [comment]
@pllim, there is no way currently to delete only a single image from a channel.  In the original design, the images would simply get bumped of the `Datasrc` for a channel as more images get examined.  Then they get reloaded from disk if they got bumped out (e.g. clicking on an "old" thumbnail).

It would be pretty straightforward to add this feature, however.  A `Datasrc` has a mapping interface, so something a `del` on the Datasrc for the channel with the image name as key will do it.  If you want to remove the thumbnail and contents entries, etc. that might entail a little more work, like adding an `image-removed` event that can be subscribed to.

BTW, there is not necessarily anything wrong with treating channels as single image "frames" either.  We could also make it easier to create and delete channels with a button click or keypress.  I've thought about doing that for the grid type workspaces, which would then act very similar to ds9 frames.

**Comment by pllim** [comment]
In situations where user accidentally opens an unwanted image and wishes to de-clutter thumbnails by getting rid of it, a close image button would be nice. Intuitively, I was trying to right click on its thumbnail or `Contents` listing for a "Close" menu. I also looked under `File` menu on top left of Ginga main window. I would expect `Thumbs` and `Contents` to update themselves when an image is closed, so `image-removed` event will be very useful as well.

**Comment by ejeschke** [comment]
Hi @pllim, could you try commit 8c8497adb2c2cc06c487b0d0e7ea7d03681c7d63?  You can choose File->Remove Image to remove the current image, or right click on a thumbnail in the Thumbs tab to get a context menu that allows you to remove the image.

**Comment by pllim** [comment]
@ejeschke , that works. Thank you! However, I don't see the point of `"Load"` option that I see when I right-click on a thumbnail.

**Comment by ejeschke** [comment]
Load is the same as left-clicking the thumb.  Try right-clicking and selecting load for an image that is not currently showing in the channel.  Does it work?

**Comment by pllim** [comment]
Yes, it does. In fact, it preserves the modified buffer, which is nice. I was afraid it was going to reload the data from file. Therefore, `Load` is a little misleading in this context. Maybe another wording like `Focus`, `Display`, `Set Active`, or something that isn't `Load`?

**Comment by pllim** [comment]
Also, somewhat related, when I click `delete channel`, `Contents` is updated but not `Thumbs`.

**Comment by ejeschke** [comment]
@pllim, can you confirm that this happens only when there is one channel created?  If there is more than one channel created I cannot reproduce the issue.

**Comment by ejeschke** [comment]
@pllim, could you check commit 907aec86d8ad05f59a2a008600aee9472d1a4602?  I believe this fixes the issue where the thumbs are not removed if the channel is deleted.  Tnx.

**Comment by ejeschke** [comment]
Regarding the changing of the command in the pop up menu from "Load".  I'm open to other suggestions.  If the image has fallen out of the `Datasrc` then it will indeed reload it from disk.  Maybe "Display" is representative of what is happening.

**Comment by pllim** [comment]
For the menu verbiage, I would prefer "Display" over "Load".

Yes, I only have one channel opened. Now thumbnails are removed if I delete the channel. However, other plugins like `Info`, `Header`, `Zoom`, and `Dialogs` are not cleared.

**Comment by ejeschke** [comment]
@pllim, could you test commit 06255c890d973b1082e9c64bd401d77bf4c02c06?  This should properly handle things in the Pan, Info and Header plugins when a channel is deleted.  Zoom will be updated when the mouse is moved over any other image.

Still thinking about what to do about Dialogs.  I suppose all local plugins related to the channel should be stopped and closed.

**Comment by ejeschke** [comment]
Changed "Load" to "Display" this will be in the next commit.

**Comment by pllim** [comment]
Thanks for the commits!

Yes, `Info` and `Header` clears up when channel is deleted now. As for `Zoom`, when I deleted my one and only `Image` channel, there is no other image to mouse over to update it.

In addition, here is another peculiar behavior: I loaded a single image into my one and only channel (`Image`). Then, I deleted the channel. Then I selected `File -> Load Image`, and deleted the channel; and repeated load-delete cycle one more time. Now I see two `Image` tabs on the top of the main display, which are not responsive to delete channel command anymore. All the global plugins are cleared, except for `Zoom`. I did not test `Dialogs` as you are already aware of its issue. From here on, when I select `File -> Load Image` again, a new `Image` tab pops up on top of the main display.

**Comment by pllim** [comment]
One more thing: When I deleted my last channel (so no more channels left) and I select "delete channel" again, I get error traceback below. I propose for Ginga to either disable "delete channel" when there is no more, or just ignore it silently (or with warning to log file) when user selects it.
```
Traceback (most recent call last):
  File ".../ginga-2.2.20150303042350-py2.7.egg/ginga/qtw/QtHelp.py", line 381, in cb
    callback(self, val)
  File ".../ginga-2.2.20150303042350-py2.7.egg/ginga/qtw/GingaQt.py", line 542, in <lambda>
    lambda w, rsp: self.delete_channel_cb(w, rsp, chname))
  File ".../ginga-2.2.20150303042350-py2.7.egg/ginga/qtw/GingaQt.py", line 781, in delete_channel_cb
    self.delete_channel(chname)
  File ".../ginga-2.2.20150303042350-py2.7.egg/ginga/Control.py", line 1108, in delete_channel
    chinfo = self.channel[name]
KeyError: 'image'
```

**Comment by pllim** [comment]
I think this is moot now.

**Comment by ejeschke** [comment]
> One more thing: When I deleted my last channel (so no more channels left) and I select "delete channel" again, I get error traceback below.

Do you still get this traceback, @pllim?  When I repeatedly use the delete channel it offers to delete "Image", but there is no traceback.  Seems like the effect is rather benign now.  But I would welcome a PR to disable/enable the menu item if you think it is important.

**Comment by pllim** [comment]
No traceback for me as well. I did issue PR #243 to prevent deletion of the last channel. Do you think that makes sense? I mean, Ginga always needs at least a channel to work anyway, right?
