### ISSUE TITLE
Problems with update_widget method in ImageViewTk

### ISSUE THREAD

**Issue by Alex-J-Brown** [ejeschke/ginga#911]
Not having PIL.ImageTK seems to cause an error in the update_widget method of ImageViewTk. I think it's due to line 121 missing the 'renderer' from 'self.renderer.get_surface_as_rgb_format_bytes(...)' but I could be wrong.

**Comment by ejeschke** [comment]
@Alex-J-Brown, the Tk version of the widget does require `PIL.ImageTk`.  It should possibly throw a better error message if it is not available.

**Comment by ejeschke** [comment]
More specifically, it requires `PhotoImage` from that package.

**Comment by Alex-J-Brown** [comment]
Sorry I thought it used PhotoImage imported straight from tkinter when PIL.ImageTK is not installed

**Comment by ejeschke** [comment]
It does try to do that.  Has that import path changed?

**Comment by ejeschke** [comment]
Seems to work for me with Python 3.7:
```python
 ipython
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from tkinter import PhotoImage                                          

In [2]: quit                                                                    
```

**Comment by ejeschke** [comment]
Are you getting the error running one of the examples in `ginga/examples/tk` ?

**Comment by ejeschke** [comment]
I see what you are referring to on line 121 of `ImageViewTk` and I think you are right, it should be `self.renderer.get_surface_as_rgb_format_bytes`.

Thanks for catching that!

**Comment by Alex-J-Brown** [comment]
Ah ok great, no worries!

**Comment by ejeschke** [comment]
Does changing that line to `self.renderer.get_surface_as_rgb_format_bytes` fix the problem for you?

**Comment by Alex-J-Brown** [comment]
When I had the issue I just solved it by installing PIL.ImageTK, but it was pointed out to me that I should raise it as an issue anyway. Unfortunately I wouldn't know how to test it now I've bypassed the issue.

**Comment by ejeschke** [comment]
> When I had the issue I just solved it by installing PIL.ImageTK, but it was pointed out to me that I should raise it as an issue anyway. 

Indeed, fix is in master.  Thanks for stopping by!
