### ISSUE TITLE
TST: Basic security audit failed

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#912]
There are a few things that tripped the security audit job. Can you please advise, @ejeschke ? Is the path hardcoding on purpose?

https://github.com/ejeschke/ginga/runs/1508897912?check_suite_focus=true

**Comment by ejeschke** [comment]
I've pushed up a commit that should address any issues of using /tmp directory in favor of Python `tempfile` module.

**Comment by pllim** [comment]
Looks good now. Thanks for the quick fix!

**Comment by ejeschke** [comment]
:relieved:
