### ISSUE TITLE
Ginga plugins as a namespace package?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#92]
In my experience so far in developing custom plugins for my users, I found 3 ways I could distribute them, all of which have their own pitfalls:

1. Have my program always copy the plugins over to the user's `$HOME/.ginga/plugins` directory every time it runs.
2. Keep reminding my users to manually run a special script that does the copying as needed before starting my program.
3. Forcefully copy my plugins into `ginga/misc/plugins` installation directory via my `setup.py`.

I asked my colleagues for a more elegant solution. @embray mentioned the following, which I thought you might be interested to consider:

> What Eric might consider doing is making the "ginga" package into a namespace package.
> Or in particular he might consider making a "ginga.plugins" namespace package.
> This is basically the Official Pythonic way of installing multiple optional subpackages into the
> same namespace.
>
> If for whatever reason he doesn't want to make the "ginga" package itself into a
> namespace package, he could still establish an official "ginga_plugins"
> namespace which *would* be a namespace package, and that all Ginga plugins could
> be required to belong to.
>
> Another option which is used by a few projects and isn't *too* bad would be to
> use setuptools entry points
> (https://pythonhosted.org/setuptools/setuptools.html#dynamic-discovery-of-services-and-plugins)
> to discover installed plugins.

What do you think on this matter? Thank you.

**Comment by ejeschke** [comment]
I understand the issue.  I'll take a look at the namespace feature.

**Comment by ejeschke** [comment]
I think the namespace approach sounds feasible.  I suppose ginga.misc.plugins, ginga.qtw.plugins and ginga.gtkw.plugins all should be exported as namespaces.  Any quick pointers on how to implement that?

**Comment by pllim** [comment]
@embray, perhaps you are the best person to answer this?

**Comment by pllim** [comment]
@embray wrote this on an internal webpage, so I copy-and-pasted it here for reference. What do you think, @ejeschke ? Is this feasible?

**Python Namespace Packages**

Namespace packages are one of those kind of weird things in Python that get talked about from time to time but nobody really uses them or understands what they do.  Except people ''do'' use them.  ''We'' use them as of recently for many of the packages that are part of `stsci_python`.  It is a useful concept.  But until recently it was something that was just sort of hacked on to Python without much foresight.  A new implementation of namespace packages was finally standardized after a long series of discussions incorporating many lessons learned, all culminating in [PEP-420](http://www.python.org/dev/peps/pep-0420/).  But unfortunately the results of that labor are only available in Python 3.3 and up, so we still need an understanding of the "old" way too.

**Normal packages**
Brief review -- probably not new to anybody.  Normal packages in Python are just directories that are importable.  Rather than importing a single file `mymodule.py` as a module named `mymodule`, one can import a directory called `mypackage/` as a module called `mypackage`.  Note that in both cases the term "module" was used.  That is because internally Python makes little distinction between package and module:

```
#!python
>>> import this
The Zen of Python, by Tim Peter

...
Namespaces are one honking great idea -- let's do more of those!
>>> this
<module 'this' from '/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/this.pyc'>
>>> import numpy
<module 'numpy' from '/usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/numpy/__init__.pyc'>
```

Both `this` and `numpy` are `module` objects.  But while `this` was a single-file module (imported from `this.pyc`), `numpy` is a package -- it did not come from any `numpy.pyc`, but rather from `numpy/__init__.py`.  The only thing ''currently'' that makes a directory into a Python package is the presence of an `__init__.py` file in that directory.  The actual package/module name comes from the name of the directory.  But `__init__.py` *may* contain arbitrary Python code -- this is the code that is executed by the Python interpreter when one runs `import numpy`, just ''as if'' there had been a single-file module called `numpy.py`.

There are two things that commonly appear in the `__init__.py` for a package:
 * A variable called `__version__` which, just convention, holds the package's version string.
 * One or more `from <submodule> import <objects>` import statements that fill out the top-level `mypackage` namespace with objects that are implemented in some of the package's submodules.  For example when you `import numpy; dir(numpy)` there are many functions, classes, and methods in Numpy's top-level namespace.  Very few of these are implemented directly in its `__init__.py`.  Most of them were imported from submodules within the `numpy` package.  In other words, packages do not add any of its submodules to their namespaces by default.

(It *is* possible to explicitly `import numpy.__init__`.  This will return a module called `numpy.__init__` and not just `numpy`, but there is no good reason to do this.)


**Submodules**

A submodule is a Python module that lives within the namespace of a package.  A submodule can be implemented as a `.py` file directly within a directory that defines a package.  It may also be implemented as another package in which case it is also a subpackage.  All of the behavior of subpackages is the same as top-level packages, except their name inherits the namespace of the top-level package.  That is, the *fully qualified* name of a subpackage called "mysubpackage" that is a subdirectory of "mypackage" is `mypackage.mysubpackage`.  Likewise for single-file submodules.  *In general*, a submodule/subpackage must be installed on the file system directly within the top-level package's directory.  A submodule generally cannot be installed by itself without the entire top-level package that it belongs to and all its other submodules.


**Namespace packages**

A namespace package is a special kind of package that merely serves as a top-level namespace for one or more submodules, and *nothing* more.  It may not contain a `__version__`, nor may it import from any of its submodules.  It cannot even be guaranteed which submodules of a namespace package are installed.  In fact, submodules of a namespace package must be subpackages, specifically.  If `moonunit` is a namespace package, one may not have a single-file `moonunit.submod` module.  It must be refactored into a subpackage like `moonunit.subpkg`, with a directory structure like:

```
+- moonunit/
   +- subpkg/
   |  +- __init__.py
   +- __init__.py
```

The reason for these restrictions is this:  Each subpackage of a namespace package can be distributed and installed separately from any other subpackages in that namespace.  They may also be installed to different places on the file system -- each subpackage must still be under a directory with the name of the namespace package, and that directory must still contain an `__init__.py`.  But they may otherwise be in other parts of the file system.  Just as long as each top-level `moonunit` directory is in location that gets added to `sys.path`, as soon as you `import moonunit` the Python import system will find ''all'' packages on `sys.path` called `moonunit` and *compose* their subpackages into a single namespace.  For example, I could have two different subpackages of a namespace package installed in two different locations:

```
+- /usr/stsci/pyssgdev/Python-2.7.3/lib/python2.7/site-packages/
   +- moonunit/
   |  +- subpackage1/
   |     +- __init__.py
   +- __init__.py
+- /home/myhome/.local/lib/python2.7/site-packages/
   +- moonunit/
   |  +- subpackage2/
   |     +- __init__.py
   +- __init__.py
```

As long as both my `.local` site-packages, and the `pyssgdev` site-packages are on `sys.path`, I can import both of these subpackages by doing `import moonunit.subpackage1` and `import moonunit.subpackage2`.  This is not possible with normal packages.  For example with normal packages, if I have my `.local` site-packages first on `sys.path`, as soon as I import `moonunit` or any submodule of that package, Python will recognize that as the ''only'' top-level `moonunit` on the system and not search the rest of `sys.path` for any other packages of that name.

There is some confusion of terminology when it comes to discussions of "namespace packages".  Sometimes a "namespace package" is used to refer to a top-level namespace package like our `moonunit` example.  Other times the same term is used to refer to a specific subpackage of a namespace package.  For example, "let's make `moonunit.foo` a namespace package".  This is due in part to the fact that one does not need to install an empty package called `moonunit` in order to declare a namespace package.  Once can instead ship a subpackage like `moonunit.foo`, and it can simply declare that `moonunit` is a namespace package and that other packages may add themselves to that namespace.  For example, we do not distribute a single package called `stsci`.  But we ''do'' distribute `stsci.tools`, `stsci.image`, `stsci.convolve`, etc. each of which independently declares that `stsci` is a namespace package.

Subpackages of a namespace package are technically unaware of each others' existence.  If I'm `stsci.tools` I can't automatically assume that every other subpackage of `stsci` is installed on the user's system.  I could declare other `stsci` subpackages as a dependency, but then it is the job of the installer/package manager to make sure that those dependencies are resolved just like dependencies between any two normal packages.  No subpackage "owns" the namespace package more than any other, and new subpackages may be added at any time without affecting existing subpackages.

**How do I make a namespace package?**

The previous introduction already explained essentially how to lay out your package to be part of a namespace package:  Just create it like any other Python package, but place it within a directory that is named after the namespace package, and include an `__init__.py` directly under that directory as well.  For example `moonunit/__init__.py`.  `moonunit` is then declared a namespace package by what goes into that `__init__.py`.  Every single package that wants to belong to the `moonunit` namespace package must declare the following incantation in that file:

```
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```

The `__init__.py` should not contain anything else (besides maybe comments) and should not contain any code specifically related to your subpackage.

**Why the limitation on what can go into `__init__.py`?**

There are a few reasons for this.  The first time one imports a namespace package after starting the Python interpreter, whether they are importing ''just'' the top-level package (i.e. `import moonunit`) or a subpackage (`import moonunit.subpackage`), Python first imports the ''first'' `moonunit/__init__.py` it finds on `sys.path` and runs the above code.  What that code does, essentially, is search the rest of `sys.path` for other packages called `moonunit` and adds their path to the list of paths that make up the different pieces of the `moonunit` package.  Once the first `moonunit` subpackage has been found, the `moonunit.__init__` in the other subpackages is never executed.  So if they contain code with any purpose other than declaring the namespace package it is not guaranteed to run depending on whether there are other `moonunit` subpackges on `sys.path` before it.

Another, perhaps more immediately obvious reason is that different subpackages of a namespace package are not ''required'' to live under different `sys.path` entries.  In fact, if one installs multiple subpackages of a namespace package, say, with pip, the default is for them all to be installed under site-packages.  They are composed together in the same filesystem hierarchy, under a single `moonunit` directory with a single `moonunit/__init__.py`.  Only the `moonunit/__init__.py` from the subpackage that was installed first is used (or the subpackage that was installed last, depending on the policy of the installer).  So you better not put anything special in that file as it is likely to be clobbered.

(And yes, this creates the potential for "malicious" packages that use the same namespace but that do not follow this policy, thus breaking every other package that belongs to that namespace.  This is one of the problems addressed in [PEP-420](http://www.python.org/dev/peps/pep-0420/) which reworked how namespace packages are handled, but it is only available as of Python 3.3.)

**Comment by ejeschke** [comment]
@pllim, since `ginga.qtw.plugins` has an empty `__init__.py` can you simply declare it as a namespace package in your plugin install script, similarly to what @embray describes here?  After rereading this description it doesn't seem like there is anything required on the ginga side except an auto-discovery bit of code.  If you install and do `ginga --plugins=FOO` does it pick it up?  I think it will if it is in your python path(s).  

If this works we can simply write a bit of auto-discovery code to locate the plugins by searching known namespaces.

**Comment by embray** [comment]
As for auto-discovery, pkg_resources / setuptools provides a mechanism for this by way of entry-points.  Not sure if that's the way you'd want to go though since it depends in part on how the plugin package is installed.  But this has been used successfully for other projects, such as Trac, for plugin discovery.

**Comment by pllim** [comment]
I started a prototype at #169. When it is ready for review, I will remove the "DO NOT MERGE" tag.

**Comment by pllim** [comment]
Okay, it's done. Tested fine on my end. If you are okay with #169, you can merge it and close this issue. Thanks!

**Comment by ejeschke** [comment]
Merged.

@pllim, do you have some custom startup code or are you just using the `--plugins=` and `--modules=` options to force loading of your plugins?  

Thinking of leaving this issue open until we get some sort of auto discovery code added.

**Comment by pllim** [comment]
@ejeschke , thanks! Sure, we can leave this open, as auto discovery would be convenient. But then, we also need to consider the discovery behavior in cases where same plugin name exists at several different locations at once.

The `--` commands in my example are just for simplicity. I actually use something like this in my startup script, as we discussed some time ago:
```python
from ginga import main as gmain
from ginga.main import reference_viewer
...
gmain.global_plugins += [
    Bunch(module='MyGlobalPlugin2', tab='MyGlobalPlugin2', ws='right', pfx='ginga.qtw.plugins')]
gmain.local_plugins += [
    Bunch(module='MyLocalPlugin2', tab='MyLocalPlugin2', ws='dialogs', pfx='ginga.qtw.plugins')]
reference_viewer(...)
```

**Comment by pllim** [comment]
So right now, I have Qt plugins in two different namespaces and I notice that `ginga.qtw.plugins.__path__` lists both of them:
```python
>>> ginga.qtw.plugins.__path__
['.../ginga-2.5.20151022033143-py2.7.egg/ginga/qtw/plugins',
 '.../mygingastuff.egg/ginga/qtw/plugins']
```
So, we could use this for auto-discovery.

c/c @eteq

**Comment by ejeschke** [comment]
That could work.  If we traverse the known plugin directories' `__path__`s, then we could find all the module names.

**Comment by pllim** [comment]
I added a function that is able to find these custom plugins in #176 (see `nstools.py`). But I cannot figure out how to determine whether the plugin is global or local. So right now, there is a way to find them, but it is not possible to auto-load them.

**Comment by pllim** [comment]
No go.
