### ISSUE TITLE
Adding encircled and ensquared energy to Pick plugin

### ISSUE THREAD

**Issue by shanosborne** [ejeschke/ginga#933]
Hi, 

@obi-wan76 and I have been discussing a possible addition to Ginga’s Pick plugin that we’d find helpful. We’d like to add a calculation of the encircled energy fraction and ensquared energy fraction of the PSF that would get displayed on the Readout page and written out in the FITS table. We were thinking that the user could define the radius and box size at which to measure the encircled and ensquared energy fraction respectively on the Parameters page, and then the box the user draws around the PSF would be used to find the total energy. 

The one other subtly we thought of is how to subtract the background from the PSF before doing the EE calculations. We thought we could handle this by adding one more parameter to the Parameters page, which would be for the size of an annulus around the PSF that the background would be calculated from. The user could enter the number of pixels beyond the drawn box around the PSF, and that’s how the annulus would be set. Then the background would be the mean/median of that area. This could also be turned off by something like setting the size to 0.

Let us know if you think that this would be an appropriate addition to Ginga. If so, we can talk more about the specifics and we would be happy to do the implementation work ourselves. Thanks!

**Comment by pllim** [comment]
If this is for STScI TEL work, there is already a [background subtraction plugin](https://stginga.readthedocs.io/en/latest/stginga/plugins_manual/backgroundsub.html) in `stginga` for background subtraction.

Your use case seems very specific, so I would recommend moving this request over to [stginga issues](https://github.com/spacetelescope/stginga/issues) and maybe we can see how to extend [SNRCalc plugin](https://stginga.readthedocs.io/en/stable/stginga/plugins_manual/snrcalc.html) to address your needs. A specific example use case with made up but realistic numbers (and relevant equations) will also be very helpful.

Thanks!

**Comment by pllim** [comment]
> written out in the FITS table

Also please provide the format of the table desired over at `stginga`.

I am closing this over here now and awaiting your issue on the other side.

**Comment by obi-wan76** [comment]
Hi @pllim!  We thought about expanding the SNRCalc plugin but what it seems more convenient is to get the EE as an additional parameter in the Pick plugin which already have lots of different properties of the PSF.  So, in a single table (Report) we can get everything that Pick provides + EEs, specially as we use the Pick functionality of moving and record Picks automatically. The only thing missing to calculate EE is the background subtraction, which could be a simple local background. Nothing to complicated as in EE results in very small difference anyways.

**Comment by pllim** [comment]
I am not sure about complicating the GUI with extra parameters to just calculate this one more element that is very specific to your use case. This calculation might not make sense to others, depending on the formula you are using. 

We can also think about extending Pick over at `stginga`, just like how `MosaicAuto` over there extends `Mosaic` here.

**Comment by obi-wan76** [comment]
Ok, if you think it will complicate the Pick GUI we can think of a transfer to stginga, similar to Mosaic. However, the EE is a pretty standard metric of PSF characterization that is not specific to our case because a user can select their target radius/size. EEs is widely used when estimating aperture corrections or overall light profiles, therefore, we thought it could be a good addition to the larger scientific community that use Ginga.

**Comment by pllim** [comment]
Okay, I'll re-open here and see what @ejeschke think then. In the meantime, if you can provide more details like formulae, example use case, and desired FITS format, that would be great. Even better if you can mock up the desired UI (like screenshot what we have now and annotate where you want new things to be). Thanks!

**Comment by ejeschke** [comment]
This seems like it would be good useful addition to Ginga's `Pick`, especially if it is generally useful for PSF analysis. My only concern is that we should consider the additional controls carefully, as it is already a fairly complex plugin.  Since the `Settings` tab consists of a scrollable box, it shouldn't add too much visual complexity to the overall plugin, I think.  Informative tool tips will be important.

> We were thinking that the user could define the radius and box size at which to measure the encircled and ensquared energy fraction respectively on the Parameters page, and then the box the user draws around the PSF would be used to find the total energy.

Would this radius be applied from the peak found in the object?

One consideration will be whether the EE calculations are done for each candidate found, or only the final "preferred" candidate--this determines where in the code the calculations are done.  For example, a little known feature is that if you check the box "Show candidates" in the Settings, and then draw a shape large enough to enclose several objects, the measurements for each object found are added to the report table. If unchecked, only the "preferred" candidate found is reported.

> The one other subtly we thought of is how to subtract the background from the PSF before doing the EE calculations. We thought we could handle this by adding one more parameter to the Parameters page, which would be for the size of an annulus around the PSF that the background would be calculated from. The user could enter the number of pixels beyond the drawn box around the PSF, and that’s how the annulus would be set. Then the background would be the mean/median of that area. This could also be turned off by something like setting the size to 0.

Would it be desirable to be able to set the subtraction value manually (override the median)?

**Comment by pllim** [comment]
@shanosborne or @obi-wan76 , I am not sure how to proceed with this. You would need to help us refine the requirements. If this is time sensitive for TEL work, please contact me directly. Thanks!

**Comment by shanosborne** [comment]
Here’s a few answers to both @pllim's and @ejeschke’s questions. @obi-wan76 will add more answers hopefully today.

The example use case would be very similar to that of a normal Pick plugin use case. The user would set the parameters, only now including the radius, box size, and background annulus size. Then they’d draw/move boxes to multiple PSFs, examining the readout and adding the picks to the table. And then they would save the FITS table.

The desired FITS format would be a FITS table, the same as what the Pick plugin outputs right now. Except with 2 new columns, named something like encircled_energy and ensquared_energy (at the radius and box size the user chose).

I’ve attached some example screenshots of the changes to the UI.

The question of if the calculations should be done for each candidate found or just the final “preferred” candidate is an interesting subtly. I think the best thing to do would be to treat the EE calculations the same way the FWHM calculations are treated. I think that would help make the code more self-consistent and less confusing to the users.

<img width="200" alt="readout" src="https://user-images.githubusercontent.com/31218961/109317431-b40a7880-781a-11eb-8c57-c98ec1e295b9.png">
<img width="200" alt="settings" src="https://user-images.githubusercontent.com/31218961/109317427-b371e200-781a-11eb-9220-58911614da1c.png">
<img width="200" alt="report" src="https://user-images.githubusercontent.com/31218961/109317417-b10f8800-781a-11eb-8b9f-a89ab23d70bf.png">

**Comment by obi-wan76** [comment]
For the EE(r) = Sum_r f(x,y)/ Sum f(x,y) where f(x,y) is the background corrected flux. The denominator is just the total flux, up to the size of the selection region around the PSF, and the numerator is the cumulative sum up to a radius r (specified by the user).  This radius is defined from the center of mass of the image (centroid) or from the max. pixel value which is required when calculating the ensquared energy fraction. For the  ensquared energy fraction, the radius is the size of a box, centered at the Max. pixel value. For example, a r=3 for ensquared energy fraction would create a 3x3 square aperture (pixel size) centered at the max. pixel. 
There could be a tab, similar to the radial profile, showing the EE function for the entire selection region. In a way, EE is very similar to the radial profile where at each radius we do a cumulative sum up to that point. 
As an addition benefit of an EE curve display tab, the user can verify that background has been subtracted correctly as this curve should flatted toward lard radii.

**Comment by pllim** [comment]
I still think background subtraction should be done separate in [BackgroundSub](https://stginga.readthedocs.io/en/stable/stginga/plugins_manual/backgroundsub.html) plugin. You can then measure this stuff in the background subtracted buffer that the plugin creates. That way, you get all the proper options for background subtraction without complicating `Pick`.

**Comment by pllim** [comment]
p.s. The screenshots are super helpful. Thanks, @shanosborne ! And thanks for the additional info, @obi-wan76 !

**Comment by pllim** [comment]
> r=3 for ensquared energy fraction would create a 3x3 square aperture (pixel size)

This is confusing to me. `r` is radius, which translates more to half-width of a box, so `r=3` would make a 6x6 box, no?

**Comment by ejeschke** [comment]
> The question of if the calculations should be done for each candidate found or just the final “preferred” candidate is an interesting subtly. I think the best thing to do would be to treat the EE calculations the same way the FWHM calculations are treated. I think that would help make the code more self-consistent and less confusing to the users.

That actually simplifies things somewhat--it just means that `iqcalc` is enhanced to do EE calculations for every candidate object, similar to the way it does all the other calculations.

**Comment by pllim** [comment]
Re: Background subtraction -- So, it turns out that `IQCalc` already calculates its own "background" and "sky level," so we can use one of those for EE calc, but which one?

**Comment by pllim** [comment]
Re: Encircled energy -- Unlike ensquared energy (which seems like a straight-forward sum of sliced array unless you want to cut through the center of the pixel), this seems like it needs `photutils`, which currently `iqcalc` isn't using. There is `iqcalc_astropy.py` that does uses it but I am not sure if that is the correct approach to only implement it for the latter.

Why do you need both encircled and ensquared? Is just ensquared enough?

**Comment by pllim** [comment]
Let's discuss implementation details at #936 . I have some questions that need further clarifications there.

**Comment by obi-wan76** [comment]
Yes, I think it is important to have both as there may be subtle differences close to the core of the PSF because of pixel physical size, under/oversampled PSFs at different wavelengths etc. As for the implementation, I like the approach in Poppy for the measure_ee function https://github.com/mperrin/poppy/blob/master/poppy/utils.py 
It is faster than using photutils. However, Ginga already has radial profile so it should be just an accumulative sum up to that radius. 
Re: radius ensquared. For ensquared I think is more intuitive to think of a box size instead of radius. So a box with size x, center in the max pixel.

**Comment by pllim** [comment]
The radial profile is a simple cut across X and Y. It doesn't do aperture photometry. Maybe I'm misunderstanding something here.

**Comment by obi-wan76** [comment]
Oh Ok, I thought the radial profile was measure at a distance r in circular bin sizes, not a cut across the PSF. I wonder if we could improve that as well, i.e., a radial profile as it is in the link above, the radial_profile function.

**Comment by ejeschke** [comment]
The radial profile is a fit to the data, moving away from the detected peak.

**Comment by pllim** [comment]
Refactoring radial profile algorithm is out of scope of this request, but I'll look into the `poppy` code for EE calculations. Thanks!
