### ISSUE TITLE
How to keep free-panning active?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#94]
This is a feedback from my colleague, who does not have a GitHub account, using Ginga: He pressed the "hand" icon to do free panning, but the free-pan mode is inactive as soon as he releases the left mouse button on main display, so to pan to different regions in his zoomed in image, he had to keep pressing the "hand" icon, which he finds inconvenient. He is wondering if there is a way to keep the free-pan mode active until he explicitly clicks the "hand" icon again.

I realize that he can also pan using the smaller display in `Info` tab, but sometimes that's not the most ideal way to do free panning, especially if the image is really big and very zoomed in.

**Comment by ejeschke** [comment]
Hi @pllim, he can press the Lock button immediately after pressing the Hand button to lock the free panning mode on.  Then press the Lock button again when finished with Free panning.  This lock feature works for all of the modes.

Alternatively, if using a three-button scroll-wheel mouse, I believe by default the scroll wheel is bound to the free panning function when depressed.

**Comment by ejeschke** [comment]
Forgot to mention the default key bindings: 'w' for free pan and 'l' for lock/unlock.  Escape always cancels the current mode (but doesn't toggle the lock, so if you have the mode lock on, and press escape to get out of a mode, the next mode you enter will also be locked).

**Comment by pllim** [comment]
Great. Thanks!

**Comment by ejeschke** [comment]
One final comment for your colleague: if heavily zoomed in the Panning box can be sometimes a very quick way to navigate the image.  Two little known features: 1) you don't have to drag the pan box, you can simply click anywhere in the pan image to set the pan position (at the same zoom level), and 2) the right mouse button can be used to draw a rectangle in the pan window and ginga will try to make the main image match as closely as possible the region drawn--this only works to a certain degree depending on the aspect ratio of the main window and the aspect ratio of the drawn rectangle, but I find it works pretty well in practice.

**Comment by ejeschke** [comment]
Oh, and you can also scroll in in the pan window to zoom the main image as well.
