### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#948]
Ref: [this issue](https://github.com/pypeit/PypeIt/issues/1178)

Summary: Ginga reference viewer may have a memory leak.  The basic widget does not exhibit the leak.

* The Ginga reference viewer's memory limiting option, the `numImages` channel setting, does not seem to be limiting memory use as it used to.  When opening multiple files with one channel open and the `numImages` set to a small fixed number, the memory use seems to be rising proportionally to the image array sizes. Instead, the memory size should plateau some short period after the limit has been reached and then only gradually increase by the size of a thumbnail image and a few bits of accounting data.
* The problem seems to happen regardless of whether the Qt or Gtk toolkit has been used
* The problem is not exhibited with the basic ginga viewer widget.  You can start the `example2_qt.py` and load image after image, the size plateaus after a bit and then just rises and falls within the plateau range.

**Comment by ejeschke** [comment]
Ginga release 2.7.2 behaves as expected.

**Comment by pllim** [comment]
Might be able to `git bisect` since you know the last good commit and how to detect the leak. 💭

**Comment by ejeschke** [comment]
It's a good plan.  I suspect either a plugin or some change in the renderer, so am starting by disabling most plugins and then slowly adding them back.

**Comment by pllim** [comment]
What about I/O backend (like `astropy.io.fits` vs `cfitsio`)? I hope it wasn't my adding support for ASDF that caused this. 😱

**Comment by ejeschke** [comment]
> What about I/O backend (like astropy.io.fits vs cfitsio)? I hope it wasn't my adding support for ASDF that caused this.

No, I tried both `fitsio` and `astropy` as FITS loaders, and the problem isn't there, I don't think.  But I think it _is_ related to changes I made to the load process in order to work in the ASDF loader, amongst other things.

Right now I'm testing by dragging and dropping files. The good news is that by a small change to route around the extra functions that were inserted, even the main branch shows stabilized memory.  I'm not sure, but I think I am capturing some memory in those functions making Python closures that is not being returned to the heap.

**Comment by ejeschke** [comment]
Hmmm..I'm beginning to wonder about whether or where there actually is a leak.  I employed `muppy` to check the memory usage.  Here's a set of outputs of the memory summary:
```python
                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         354 |     74.75 MB
                   str |      129158 |     20.64 MB
                  dict |       59215 |     20.42 MB
                  type |        6879 |      6.86 MB
                  code |       33908 |      4.68 MB
                  list |       47514 |      4.66 MB
                 tuple |       44675 |      3.79 MB
                   set |        1645 |      1.22 MB
               weakref |        9948 |    854.91 KB
       sip.wrappertype |         752 |    780.20 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                  cell |       11969 |    654.55 KB
                   int |       21659 |    650.96 KB
    wrapper_descriptor |        6722 |    577.67 KB





                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         364 |    109.43 MB
                   str |      132492 |     20.92 MB
                  dict |       61044 |     20.83 MB
                  type |        6881 |      6.86 MB
                  list |       48205 |      4.75 MB
                  code |       33910 |      4.68 MB
                 tuple |       44835 |      3.80 MB
                   set |        1655 |      1.22 MB
               weakref |       10067 |    865.13 KB
       sip.wrappertype |         752 |    780.20 KB
  sip.methoddescriptor |       10767 |    672.94 KB
                  cell |       12145 |    664.18 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21679 |    651.52 KB
    wrapper_descriptor |        6726 |    578.02 KB



                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         398 |    213.50 MB
                  dict |       65086 |     21.65 MB
                   str |      133907 |     21.00 MB
                  type |        6881 |      6.86 MB
                  list |       49132 |      4.85 MB
                  code |       33912 |      4.68 MB
                 tuple |       45654 |      3.85 MB
                   set |        1655 |      1.22 MB
               weakref |       10075 |    865.82 KB
       sip.wrappertype |         752 |    780.20 KB
                  cell |       12313 |    673.37 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21704 |    652.20 KB
    wrapper_descriptor |        6726 |    578.02 KB



                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         437 |    334.90 MB
                  dict |       69175 |     22.50 MB
                   str |      136067 |     21.22 MB
                  type |        6881 |      6.86 MB
                  list |       51593 |      5.10 MB
                  code |       33911 |      4.68 MB
                 tuple |       45809 |      3.86 MB
                   set |        1654 |      1.22 MB
               weakref |       10089 |    867.02 KB
       sip.wrappertype |         752 |    780.20 KB
                  cell |       12460 |    681.41 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21724 |    652.75 KB
    wrapper_descriptor |        6726 |    578.02 KB



                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         442 |    265.53 MB
                  dict |       68173 |     22.32 MB
                   str |      134918 |     21.11 MB
                  type |        6881 |      6.86 MB
                  list |       51424 |      5.07 MB
                  code |       33911 |      4.68 MB
                 tuple |       45415 |      3.84 MB
                   set |        1654 |      1.22 MB
               weakref |       10103 |    868.23 KB
       sip.wrappertype |         752 |    780.20 KB
                  cell |       12592 |    688.62 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21706 |    652.25 KB
    wrapper_descriptor |        6726 |    578.02 KB



                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         457 |    282.88 MB
                  dict |       69839 |     22.68 MB
                   str |      135664 |     21.17 MB
                  type |        6881 |      6.86 MB
                  list |       52183 |      5.14 MB
                  code |       33912 |      4.68 MB
                 tuple |       45360 |      3.83 MB
                   set |        1655 |      1.22 MB
               weakref |       10117 |    869.43 KB
       sip.wrappertype |         752 |    780.20 KB
                  cell |       12702 |    694.64 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21710 |    652.36 KB
    wrapper_descriptor |        6726 |    578.02 KB



                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         550 |    178.83 MB
                  dict |       69848 |     22.91 MB
                   str |      134543 |     21.04 MB
                  type |        6881 |      6.86 MB
                  list |       52621 |      5.10 MB
                  code |       33911 |      4.68 MB
                 tuple |       46053 |      3.88 MB
                   set |        1654 |      1.22 MB
               weakref |       10131 |    870.63 KB
       sip.wrappertype |         752 |    780.20 KB
                  cell |       13014 |    711.70 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21713 |    652.45 KB
    wrapper_descriptor |        6726 |    578.02 KB


                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         595 |    213.52 MB
                  dict |       71226 |     23.22 MB
                   str |      134869 |     21.06 MB
                  type |        6881 |      6.86 MB
                  list |       53573 |      5.17 MB
                  code |       33911 |      4.68 MB
                 tuple |       46716 |      3.93 MB
                   set |        1654 |      1.22 MB
               weakref |       10145 |    871.84 KB
       sip.wrappertype |         752 |    780.20 KB
                  cell |       13171 |    720.29 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21721 |    652.66 KB
    wrapper_descriptor |        6726 |    578.02 KB



                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         620 |    317.58 MB
                  dict |       74991 |     23.96 MB
                   str |      136405 |     21.23 MB
                  type |        6881 |      6.86 MB
                  list |       56069 |      5.43 MB
                  code |       33911 |      4.68 MB
                 tuple |       46356 |      3.91 MB
                   set |        1654 |      1.22 MB
               weakref |       10159 |    873.04 KB
       sip.wrappertype |         752 |    780.20 KB
                  cell |       13298 |    727.23 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21722 |    652.69 KB
    wrapper_descriptor |        6726 |    578.02 KB



                 types |   # objects |   total size
====================== | =========== | ============
         numpy.ndarray |         619 |    248.21 MB
                  dict |       73898 |     23.76 MB
                   str |      135245 |     21.13 MB
                  type |        6881 |      6.86 MB
                  list |       55951 |      5.40 MB
                  code |       33911 |      4.68 MB
                 tuple |       46130 |      3.89 MB
                   set |        1654 |      1.22 MB
               weakref |       10173 |    874.24 KB
       sip.wrappertype |         752 |    780.20 KB
                  cell |       13431 |    734.51 KB
  sip.methoddescriptor |       10767 |    672.94 KB
          sip.enumtype |         636 |    660.84 KB
                   int |       21707 |    652.28 KB
    wrapper_descriptor |        6726 |    578.02 KB
```
The loads were: 2 files, then 7 files, then 13 files, 13 files, 13 files, ...  until 112 4Kx8K (18MB) images were loaded. `numImages` was set to 2.

We can see that the number of `ndarray` objects keeps growing as expected, but most of these are thumbnails.  And the size of the total `ndarray` objects is not out of control, nor are any of the other numbers.  The mystery deepens...

**Comment by ejeschke** [comment]
Here's a `mprof` profile of loading the same 112 files:
![mprof-ginga](https://user-images.githubusercontent.com/1305473/116337853-812b2500-a776-11eb-8c16-87104ea2e72d.png)

The time is not meaningful because it is me manually dragging files to the window, which introduces some variation. The near-plateau can be seen for the last few loads.  The total value is much higher than reported by `muppy`, but not growing linearly at all.

**Comment by pllim** [comment]
So, is this plateau value consistent with Ginga 2.7 performance?

Also, if I understood correctly, you said the thumbnails can bypass this limit. So theoretically, if a downstream package generates *a lot* of thumbnails, they could use up memory anyway? Also, does the memory consumption lessen if you disable `Thumbs` plugin?

**Comment by pllim** [comment]
@ejeschke , please let me know if there is anything I can help with to smoke this one out. 🙏

**Comment by ejeschke** [comment]
Here is a profile of the viewer widget loading the same 112 files:
![mprof_ginga_widget](https://user-images.githubusercontent.com/1305473/116462900-be8ac380-a805-11eb-8468-c995864010a3.png)

Judging by profiling the loading of those 112 files in `astropy.fits.io` (by itself) the loading takes about 160MB, even if each file is immediately discarded afterward.

**Comment by pllim** [comment]
Interesting... So, RV version loads 3x more memory.

**Comment by ejeschke** [comment]
Here is a test program just loading the 112 files using `astropy.io.fits`:
```python
#! /usr/bin/env python3
import sys
import time
import os
import glob
import numpy as np

from astropy.io import fits

for i, path in enumerate(glob.glob(os.path.join(sys.argv[1], '*.fits'))):
    print('loading {} ...'.format(i+1))
    fits_f = fits.open(path, 'readonly')
    data = fits_f[0].data
    total = np.nanmax(data)
    data = None
    del fits_f[0].data

time.sleep(100000)
```
And here is the profile:
![mprof_astropy_io_fits](https://user-images.githubusercontent.com/1305473/116466177-dfedae80-a809-11eb-8c7b-15cfc2bf2654.png)

So there seems to be some memory that is not returned from loading FITS files, no matter what.

**Comment by pllim** [comment]
Is it memory mapping? I think it is on by default.

**Comment by ejeschke** [comment]
Judging from this, the basic viewer adds about 300MB "load".  This includes the Qt UI plus the optimizations Ginga does for rendering and display (will depend on the window size).

> Interesting... So, RV version loads 3x more memory.

That could make sense, depending on the number of widgets used in various places.

**Comment by ejeschke** [comment]
> Is it memory mapping? I think it is on by default.

Does it do that even if you specify 'readonly'?  I'll try turning it off.

**Comment by ejeschke** [comment]
Ok, here's the modified program:
```python
#! /usr/bin/env python3
import sys
import time
import os
import glob
import numpy as np

from astropy.io import fits

for i, path in enumerate(glob.glob(os.path.join(sys.argv[1], '*.fits'))):
    print('loading {} ...'.format(i+1))
    fits_f = fits.open(path, 'readonly', memmap=False)
    data = fits_f[0].data
    total = np.nanmax(data)
    data = None
    del fits_f[0].data

time.sleep(100000)
```
Saves a little memory, but there is still some not returned:
![mprof_astropy_io_fits_memmap_false](https://user-images.githubusercontent.com/1305473/116467504-75d60900-a80b-11eb-9f4b-3826df27a509.png)

**Comment by ejeschke** [comment]
Profiling the program where it doesn't load any images, but still iterates over the files, it looks like the resident size is about 67MB. So `astropy.io.fits`, in the case where `memmap=False` is returning the memory.

**Comment by pllim** [comment]
Okay, it is good news that `memmap=False` frees memory as expected. `memmap=True` and problem with freeing memory is a known issue.

**Comment by ejeschke** [comment]
> Also, if I understood correctly, you said the thumbnails can bypass this limit. So theoretically, if a downstream package generates a lot of thumbnails, they could use up memory anyway? Also, does the memory consumption lessen if you disable Thumbs plugin?

Here's the profile with `Thumbs` disabled using `--disable-plugins=Thumbs`:

![mprof-ginga_thumbs_disabled](https://user-images.githubusercontent.com/1305473/116468666-dc0f5b80-a80c-11eb-90c5-7bbdc4e078a1.png)

Doesn't look like it saves much.  Each thumb is a compressed RGB image as an ndarray.  Now this run I only loaded 112 files, so probably not much extra is generated for those.  But we run Ginga all night and it fills up with hundreds (sometimes thousands) of thumbnails.  I just checked last night's observation GUIs.  Ginga is still up and there are probably a few thousand thumbnails (8 channels, 3 instruments). Total resident memory usage is sitting at 1.7GB (2.7% of memory).  Not much on a server with 32 or 64GB.

**Comment by ejeschke** [comment]
Based on this I am not convinced there is a memory leak in Ginga at all.  It is memory-hungry, no doubt. But I think that with the `memmap` behavior as discussed, it should reach a plateau-like state and then grow only minimally as thumbs are generated.

**Comment by ejeschke** [comment]
@pllim, do you think we should make `memmap=False` the default?  I cannot tell from the various discussions what the best choice is.  It seems like for data cubes it would probably be best to leave it as the default (`None`, which would then default to `True` inside `astropy`, I guess).

**Comment by pllim** [comment]
No, I don't think `memmap=False` is a good default, especially as astronomy is heading towards the big-data era. And it is less confusing if we follow `astropy` default. What we can do is write up some doc to advise people when they should use `memmap=True` or just default with Ginga... 💭

**Comment by ejeschke** [comment]
So, then, is there a general idea for how much memory is not returned if `memmap` is enabled in `astropy.io.fits`?  I think using `fitsio` I basically saw a similar memory profile.

**Comment by pllim** [comment]
As far as I understand, which isn't much, `memmap=True` should only give you the data you ask for, so the memory usage depends on the data you grab from the file. Once the memory is used, freeing it isn't as simple as simply closing the file pointer. But the benefit is it doesn't try to load the whole file on open.

**Comment by ejeschke** [comment]
But is it the case that it has a slow memory leak? Just wondering if with the default setting we need to add a destructor to `io_fits` objects or something to make sure the memory is fully reclaimed when the image is unreferenced?

**Comment by pllim** [comment]
The official recommendation is here: https://docs.astropy.org/en/latest/io/fits/index.html#working-with-large-files

**Comment by ejeschke** [comment]
I just compared two profiles, one with `memmap=None` and one with `memmap=False`.  In the case of the latter, there is a significant increased memory usage compared to the default.  So we will leave it as is.

**Comment by ejeschke** [comment]
I added destructors for `AstroImage` and `PyFitsFileHandler` and then also added a `gc.collect()` that runs after each set of drag drops.  `gc.collect()` tells you how many objects it recovered (that apparently were not reclaimed by reference counting).  Here's what it said when using the `astropy` loader:
```python
objects collected 308
objects collected 0
objects collected 30
objects collected 0
objects collected 0
objects collected 75
objects collected 90
objects collected 15
objects collected 0

```
And here's the profile:
![mprof-ginga_dest_gc_astropy](https://user-images.githubusercontent.com/1305473/116477754-bf792080-a818-11eb-9714-535c81c3ca3b.png)

Here's the exact same run but using the `fitsio` loader:
```python
objects collected 308
objects collected 0
objects collected 0
objects collected 0
objects collected 0
objects collected 0
objects collected 0
objects collected 0
objects collected 0
```

Profile:
![mprof-ginga_dest_gc_fitsio](https://user-images.githubusercontent.com/1305473/116477814-d455b400-a818-11eb-971d-054a70db30e8.png)

**Comment by pllim** [comment]
Wut... How can adding destructors add another 200 MB ? The bumps look dramatic, but plateau still comparable with https://github.com/ejeschke/ginga/issues/948#issuecomment-828097562 .

**Comment by ejeschke** [comment]
If I leave out the `gc.collect()` between drops, this is what the `astropy` loader one looks like:
![mprof-ginga_dest_astropy](https://user-images.githubusercontent.com/1305473/116478258-81303100-a819-11eb-8060-8218df1fd1e3.png)

Not significantly different from with GCs.  But I find it curious that when using the `astropy` loader it finds things that weren't collected by reference counting.

**Comment by ejeschke** [comment]
> Wut... How can adding destructors add another 200 MB ? The bumps look dramatic, but plateau still comparable with #948 (comment) .

Yeah, not sure that the destructors add anything to help, particularly. Just wanted to see if they make any difference. But it seems that, yes, the result is still basically a smooth rise to a plateau of sorts, with small increments afterwards, probably accounting for just maintaining info about the files that have been loaded in the channel without the data (thumbs, etc).

**Comment by ejeschke** [comment]
> Ginga release 2.7.2 behaves as expected.

I have to walk back this comment.  This was just from watching the system monitor app in early part of testing, and not very reliable.  I tested several versions with `memory-profiler`.  Here are the results.

v2.6.4:
![mprof-ginga_2_6_4](https://user-images.githubusercontent.com/1305473/116483378-af663e80-a822-11eb-8d41-8d4e46ec5214.png)

v2.6.6 (versions 2.7.x are similar to this profile):
![mprof-ginga_2_6_6](https://user-images.githubusercontent.com/1305473/116483379-b1c89880-a822-11eb-8180-dda52b3bb4a5.png)

current main:
![mprof-ginga_3_0_0](https://user-images.githubusercontent.com/1305473/116483386-b4c38900-a822-11eb-8965-9dfe981139e9.png)


It looks like there could have been a memory leak from 2.6.6 on, but I didn't test with enough images to see if it leveled out more later.

From the v3.0.x series on the

**Comment by ejeschke** [comment]
_Now for something completely surprising_. Here is loading the same 144 files using the Ginga `RC` plugin (command was "ggrc ginga load_file /path/to/file.fits" successively for 144 files):
![mprof-ginga_latest_rc](https://user-images.githubusercontent.com/1305473/116486146-a0828a80-a828-11eb-8046-59bff4b88440.png)

The big long flat part is just the viewer being idle while I fiddled with an ipython session getting ready to send the commands. All the loads happen in the end.  But look at the memory use--it's only 130-140 MB above an idle, empty Ginga session!  This is with the `numImages` set at 2.

**Comment by ejeschke** [comment]
Finally, I measure memory profile doing the same method that appears to be shown [in this issue](https://github.com/pypeit/PypeIt/issues/1178)--using the `load_np()` command with the programmatic interface from `ginga.util.grc`:
![mprof-ginga_latest_rc_np](https://user-images.githubusercontent.com/1305473/116487415-9a41dd80-a82b-11eb-921d-271b0919a702.png)
A little bit more memory use due to buffers being received and converted, but overall, still pretty good.  This is 144 18MB buffers.

**Comment by ejeschke** [comment]
Looks like the base reference viewer usage is about 400MB, balloons to just under 700 loading and cycling through all those buffers, and finally drops below 600.

**Comment by pllim** [comment]
I am not sure what to conclude from all this. Like you said, it uses more memory now but the usage does plateau, so does that qualify as a "leak"?

I remember at some point, you did add a feature to cache more stuff so the cursor is more responsive, right? I don't remember which version that was introduce though, or if it has any effect on this. But I don't think we can conclude anything without investing a lot of time profiling every merge commit since 2.7.0. 🤯

**Comment by ejeschke** [comment]
Closing this issue. If we get more claims of memory leaks we can reopen it if necessary.

**Comment by ejeschke** [comment]
> I am not sure what to conclude from all this. Like you said, it uses more memory now but the usage does plateau, so does that qualify as a "leak"?

Well, it is a "feature" and not a "bug" that Ginga keeps track of every image that you load into it _and don't remove_.  I think it would qualify as a leak if Ginga does not recover memory for images that you remove.  It does remove the pixel and header data for "loaded" images from memory in a user configurable fashion (i.e. `numImages`), but keeps enough information to reload the image if possible and to show what is still "remembered" by the viewer. It's hardly surprising that this bookkeeping for each image does take some space.
