### ISSUE TITLE
MultiDim play buttons do nothing

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#96]
I was under the impression that `Play` in `MultiDim` cycles through all the loaded extensions for the particular image. But it does not seem to be working.

**Comment by ejeschke** [comment]
That section is for data cubes.  If you load a data cube you will be able to step through it with those controls.  It does nothing for HDUs.

**Comment by pllim** [comment]
Okay. Perhaps the buttons can be disabled (or not displayed at all) if data cube is not present. Or at least clarify their usage in the instructions.

**Comment by ejeschke** [comment]
I've made some changes for this issue in commit 8a344e36051b20d9dd981db15a12b7a9402f5eb7.  It should enable or disable the NAXIS animation controls based on the number of dimensions found.

**Comment by ejeschke** [comment]
There is still a possible usability issue in that the NAXIS controls are not rebuilt until you select an HDU in the HDU controls.

**Comment by pllim** [comment]
I don't have data cubes, so this works good enough for me. Thanks!
