### ISSUE TITLE
Pan "hack" causing compass failure for HST/ACS FLC image

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#960]
I am not sure why it is forcing an error here for a big (1 degree) offset.

https://github.com/ejeschke/ginga/blob/833517ab092a525b2eac63b736515a21951dacd2/ginga/rv/plugins/Pan.py#L310-L311

This causes the following failure for HST/ACS FLC image, [jbt7a3k7q_flc.fits](https://stsci.box.com/s/gitjnk0xxb0q0g5hbygy7wtu7td5yhvd). The detector has 202x202 arcsec^2 FOV and the image WCS is not corrected for distortion at this stage.

```
WCSError: 'WCS.all_world2pix' failed to converge to the requested accuracy.
After 2 iterations, the solution is diverging at least for one input point.
```

**Comment by ejeschke** [comment]
Hmm, well, I think the hack worked as advertised--if the WCS fails it is not going to be able to calculate a compass.  Was this `astropy` or `astropy_ape14` WCS that failed?

**Comment by pllim** [comment]
astropy_ape14

**Comment by ejeschke** [comment]
@pllim, I have that file.  I can confirm it loads fine and displays a compass with `astropy` WCS.  Compass looks like the one displayed by `ds9`.

**Comment by ejeschke** [comment]
Given that `astropy` is the default WCS, and we won't merge anything till after this release...probably not a blocker for 3.2?

**Comment by pllim** [comment]
Not a blocker. Thanks!

**Comment by pllim** [comment]
I don't understand why the hack is there and why it needs such a big offset (1 degree in the sky). When there is distortion, such a big offset outside of the detector is not going to give you anything good.

**Comment by ejeschke** [comment]
I'm totally ok with trying a smaller offset. I can't remember exactly how the offsets (lengths) for the arms is calculated, but I think this particular call is just to make sure that a WCS calculation can be performed.

**Comment by ejeschke** [comment]
But I'd still be curious why `astropy_ape14` doesn't handle the calculation, whereas `astropy` does. Does that signal anything significant?

**Comment by pllim** [comment]
I don't remember the details, but APE 14 is the canonical way now. Perhaps the old way ignored distortion, like DS9, but I am just guessing.

APE 14: https://github.com/astropy/astropy-APEs/blob/main/APE14.rst

**Comment by ejeschke** [comment]
Hmm, I'd be curious about the time difference between them as well.  Sounds like the new one does some sort of iteration to a solution.

**Comment by ejeschke** [comment]
Is the old way going to be deprecated (in astropy itself, I mean)?  Is there a timeline for when we have to merge astropy_ape14 and astropy?

**Comment by pllim** [comment]
AFAIK, there is no plan to remove any WCS stuff from `astropy`. However, APE 14 implementation is necessary for GWCS support.
