### ISSUE TITLE
ci_workflows: update ubuntu version

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/ginga#961]
We are getting a warning in ci_workflows:
```bash
The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details
```
Any reason not to update to "ubuntu-latest"?

**Comment by pllim** [comment]
Not really. I just wanted to cross test the "oldest deps" job with an older version of Ubuntu, just in case. I think latest is now 20.x, so we could bump the "oldest deps" to use 18.x or if you don't care, we can just use latest for all the Linux jobs.

Do you have a preference?
