### ISSUE TITLE
Entry points: Replace pkg_resources with importlib

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#963]
See https://github.com/conda-forge/ginga-feedstock/pull/12#issuecomment-856332510 onwards.

https://packaging.python.org/specifications/entry-points/

**Comment by ejeschke** [comment]
```bash
$ grep -R -l pkg_resources ginga
ginga/misc/__init__.py
ginga/qtw/__init__.py
ginga/rv/plugins/__init__.py
ginga/rv/main.py
ginga/__init__.py
```

**Comment by ejeschke** [comment]
@pllim, I don't know about the ones in the `__init__.py`'s. I think I was responsible for the one in `main.py`, because that one is used to load externally defined plugins, via entry points.

**Comment by pllim** [comment]
Go ahead. Will be happy to help if you need it. I don't remember why I needed special entry point code either. As long as it doesn't break existing downstream stuff on my side, it's fine by me. Thanks!
